BattleFrontier_Lounge8_MapScripts::
	.byte 0

BattleFrontier_Lounge8_EventScript_Man::
	msgbox BattleFrontier_Lounge8_Text_WhatATrainerNeeds, MSGBOX_NPC
	end

BattleFrontier_Lounge8_EventScript_Woman::
	msgbox BattleFrontier_Lounge8_Text_KnowAboutFrontierBrains, MSGBOX_NPC
	end

BattleFrontier_Lounge8_EventScript_NinjaBoy::
	msgbox BattleFrontier_Lounge8_Text_ToldMeIHaveTalentForBattling, MSGBOX_NPC
	end

BattleFrontier_Lounge8_Text_WhatATrainerNeeds:
	.string "What a warrior needs…\p"
	.string "Knowledge…\n"
	.string "Strategy…\l"
	.string "Luck…\l"
	.string "Guts…\l"
	.string "Spirit…\l"
	.string "Courage…\l"
	.string "And a sky-high power level…\p"
	.string "I have all of it!\n"
	.string "No building can stop me!\p"
	.string "Huh? POKéMON?\n"
	.string "What's that?$"

BattleFrontier_Lounge8_Text_KnowAboutFrontierBrains:
	.string "Have you heard of the FRONTIER\n"
	.string "BRAINS?\p"
	.string "That's what ANNOUNCER calls the seven\n"
	.string "elite fighters who each rule one of\l"
	.string "the seven facilities in the BATTLE\l"
	.string "FRONTIER.$"

BattleFrontier_Lounge8_Text_ToldMeIHaveTalentForBattling:
	.string "At the BATTLE TOWER, an older girl\n"
	.string "told me I've got a ton of talent\l"
	.string "for battling!\p"
	.string "But I like POKéMON CONTESTS more!\p"
	.string "And I'm no good at CONTESTS!\p"
	.string "I guess having talent and loving\n"
	.string "something are two different things.$"

