#!/usr/bin/env python3
"""Generate the runtime season tables from graphics/seasons/<season>/ (see import_seasons.py).

Writes
  src/data/dbz_battle_views.h  - location battle views, one table per season (shared arrays reused)
  src/data/seasons_gen.h       - every other INCGFX/INCBIN resource whose output changes with the season:
                                 seasonal copies plus a {base, size, variants[4]} lookup table
  src/data/dbz_hud_seasons.h   - HUD palette + panel per season
"""
import os, re, sys, hashlib
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import seasons_scan as S

R = S.ROOT
CAP = {s: s.capitalize() for s in S.SEASONS}

def read(p):
    return open(os.path.join(R, p)).read()

# ---------------------------------------------------------------- battle views
def gen_battle_views():
    heads = {s: read(f'{S.SEASON_DIR}/{s}/src/data/dbz_battle_views.h') for s in S.SEASONS
             if os.path.exists(os.path.join(R, S.SEASON_DIR, s, 'src/data/dbz_battle_views.h'))}
    base = heads['summer']
    names = re.findall(r'\{&gTileset_General, &gTileset_(\w+),', base)
    decl = re.compile(r'^static const (\w+) (sBV_(\w+?)_(\w+))\[\] = (.*);$', re.M)
    out = ['// generated by tools/pbo/gen_seasons.py from the seasonal art pack - do not edit',
           '// one location-view table per season; arrays that match summer are shared', '']
    sym = {}   # (season, kind, name) -> symbol
    for s in ['summer'] + [t for t in S.SEASONS if t != 'summer']:
        h = heads.get(s, base)
        found = {(m.group(3), m.group(4)): m for m in decl.finditer(h)}
        for name in names:
            for kind in ('Tiles', 'Pal', 'Meta', 'Dark', 'Light'):
                m = found[(kind, name)]
                typ, body = m.group(1), m.group(5)
                inc = re.match(r'INCBIN_U(\d+)\("([^"]+)"\)', body)
                if inc:
                    path = inc.group(2)
                    vpath = S.variant_path(s, path)
                    same = s == 'summer' or open(os.path.join(R, vpath), 'rb').read() == open(os.path.join(R, path), 'rb').read()
                    body = f'INCBIN_U{inc.group(1)}("{vpath}")'
                else:
                    sb = {(mm.group(3), mm.group(4)): mm for mm in decl.finditer(base)}[(kind, name)].group(5)
                    same = s == 'summer' or body == sb
                if same and s != 'summer':
                    sym[(s, kind, name)] = sym[('summer', kind, name)]
                    continue
                sname = f'sBV_{kind}_{name}' + ('' if s == 'summer' else '_' + CAP[s])
                sym[(s, kind, name)] = sname
                out.append(f'static const {typ} {sname}[] = {body};')
    out.append('')
    out.append('extern const struct Tileset ' + ', '.join(f'gTileset_{n}' for n in names) + ';')
    for s in S.SEASONS:
        out.append(f'static const struct DbzBattleView sBattleViews_{CAP[s]}[] = {{')
        for n in names:
            out.append(f'    {{&gTileset_General, &gTileset_{n}, ' + ', '.join(sym[(s, k, n)] for k in ('Tiles', 'Pal', 'Meta', 'Dark', 'Light')) + '},')
        out.append('};')
    out.append('static const struct DbzBattleView *const sBattleViewsBySeason[] = {' + ', '.join(f'sBattleViews_{CAP[s]}' for s in S.SEASONS) + '};')
    out.append(f'#define NUM_BATTLE_VIEWS {len(names)}')
    open(os.path.join(R, 'src/data/dbz_battle_views.h'), 'w').write('\n'.join(out) + '\n')
    print('battle views:', len(names), 'per season,', len(out), 'lines')

# ---------------------------------------------------------------- HUD
def gen_hud():
    out = ['// generated by tools/pbo/gen_seasons.py - seasonal HUD palette and panel', '']
    pals, panels = {}, {}
    for s in S.SEASONS:
        p = 'src/data/dbz_hud.h' if s == 'summer' else S.variant_path(s, 'src/data/dbz_hud.h')
        h = read(p)
        pals[s] = re.search(r'gDBZHudPalette\[16\] = (\{[^}]*\});', h).group(1)
        panels[s] = re.search(r'sHudPanel\[32\]\[64\] = (\{.*?\}\});', h, re.S).group(1)
    for s in S.SEASONS:
        out.append(f'static const u16 sHudPalette_{CAP[s]}[16] = {pals[s]};')
    panel_sym = {}
    for s in S.SEASONS:
        prev = [t for t in S.SEASONS[:S.SEASONS.index(s)] if panels[t] == panels[s]]
        if prev:
            panel_sym[s] = panel_sym[prev[0]]
        else:
            panel_sym[s] = f'sHudPanel_{CAP[s]}'
            out.append(f'static const u8 sHudPanel_{CAP[s]}[32][64] = {panels[s]};')
    out.append('static const u16 *const sHudPaletteBySeason[] = {' + ', '.join(f'sHudPalette_{CAP[s]}' for s in S.SEASONS) + '};')
    out.append('static const u8 (*const sHudPanelBySeason[])[64] = {' + ', '.join(panel_sym[s] for s in S.SEASONS) + '};')
    open(os.path.join(R, 'src/data/dbz_hud_seasons.h'), 'w').write('\n'.join(out) + '\n')
    print('hud: panels', len(set(panel_sym.values())))

# ---------------------------------------------------------------- everything else
UNSTATIC_SKIP = {'sUnused_Pal'}
SKIP_FILES = {'src/data/dbz_battle_views.h', 'src/data/dbz_hud.h', 'src/data/dbz_hud_seasons.h', 'src/data/seasons_gen.h'}

def gen_generic():
    entries, statics, out = [], [], []
    out += ['// generated by tools/pbo/gen_seasons.py - seasonal copies of shared graphics resources.',
            '// Season_Resolve() swaps a base pointer (or a pointer into it) for the current season\'s copy.', '']
    externs = []
    for f, static, typ, name, dims, incs, full, body in S.scan_decls():
        if f in SKIP_FILES:
            continue
        paths = {p for _, p, _, _ in incs}
        if not any(os.path.exists(os.path.join(R, S.SEASON_DIR, s, p)) for s in S.SEASONS if s != S.BASE for p in paths):
            continue
        diff = {s: any(S.output_differs(p, ext, s) for _, p, ext, _ in incs) for s in S.SEASONS if s != S.BASE}
        if not any(diff.values()):
            continue
        if static:
            if name in UNSTATIC_SKIP:
                continue
            # make it visible to the season table (names were checked to be unique across src/)
            src = read(f)
            fixed = full.replace('static const', 'const', 1)
            src = src.replace(full, fixed, 1)
            src = re.sub(r'static const (\w+) ' + name + r'\[\];', r'const \1 ' + name + '[];', src)
            open(os.path.join(R, f), 'w').write(src)
            statics.append(f'{f}: {name}')
        externs.append(f'extern const {typ} {name}{re.sub(r"\[[^\]]*\]", "[]", dims, count=1)};')
        vs = {}
        for s in S.SEASONS:
            if s == S.BASE or not diff[s]:
                vs[s] = name
                continue
            vbody = body
            for _, p, _, _ in incs:
                vbody = vbody.replace(f'"{p}"', f'"{S.variant_path(s, p)}"')
            vname = f'sSzn_{name}_{CAP[s]}'
            out.append(f'static const {typ} {vname}{dims} ALIGNED(4) = {vbody};')
            vs[s] = vname
        sizer = next(vs[s] for s in S.SEASONS if vs[s] != name)
        # compressed data differs in length per season, so only an exact pointer to its start may be
        # swapped; uncompressed copies have identical sizes and pointers into them resolve too
        compressed = any(re.search(r'smol|lz|rl|fastSmol|smolTM', ext) for _, _, ext, _ in incs)
        entries.append((name, '0' if compressed else f'sizeof({sizer})', vs))
    head = out[:3] + sorted(set(externs)) + [''] + out[3:]
    head.append('')
    head.append('const struct SeasonResource gSeasonResources[] = {')
    for name, sizer, vs in entries:
        head.append(f'    {{{name}, {sizer}, {{' + ', '.join(vs[s] for s in S.SEASONS) + '}},')
    head.append('};')
    head.append('const u16 gSeasonResourceCount = ARRAY_COUNT(gSeasonResources);')
    open(os.path.join(R, 'src/data/seasons_gen.h'), 'w').write('\n'.join(head) + '\n')
    print('generic seasonal resources:', len(entries))
    if statics:
        print('made non-static for the season table:'); [print('   ', x) for x in statics]

gen_battle_views()
gen_hud()
gen_generic()
