gText_ApprenticeChallenge0::
	.string "Um, I'm {STR_VAR_1}'s no. {STR_VAR_2} disciple.\n"
	.string "Sniff… My knees won't stop shaking…$"

gText_ApprenticeChallenge1::
	.string "I'm {STR_VAR_1}'s no. {STR_VAR_2} disciple!\n"
	.string "Here I come!$"

gText_ApprenticeChallenge2::
	.string "I'm the no. {STR_VAR_2} disciple of {STR_VAR_1}!\n"
	.string "I accept the challenge!$"

gText_ApprenticeChallenge3::
	.string "Um… I'm {STR_VAR_1}'s no. {STR_VAR_2} disciple…\n"
	.string "My power level is pretty low, you know…$"

gText_ApprenticeChallenge4::
	.string "I'm {STR_VAR_1}'s no. {STR_VAR_2} disciple!\n"
	.string "I'll graciously let you fight me!$"

gText_ApprenticeChallenge5::
	.string "I'm swamped with work, but I'm also\n"
	.string "{STR_VAR_1}'s no. {STR_VAR_2} disciple.$"

gText_ApprenticeChallenge6::
	.string "I'm {STR_VAR_1}'s no. {STR_VAR_2} disciple.\n"
	.string "Nice to meet you!$"

gText_ApprenticeChallenge7::
	.string "I have the honor of being {STR_VAR_1}'s\n"
	.string "no. {STR_VAR_2} disciple. May I begin?$"

gText_ApprenticeChallenge8::
	.string "Eek! I'm {STR_VAR_1}'s no. {STR_VAR_2} disciple!\n"
	.string "I'll give it everything I've got!$"

gText_ApprenticeChallenge9::
	.string "Dude! I'm {STR_VAR_1}'s no. {STR_VAR_2}\n"
	.string "disciple! Let's rumble!$"

gText_ApprenticeChallenge10::
	.string "I'm {STR_VAR_1}'s 1,000th disciple!\n"
	.string "Okay, really I'm no. {STR_VAR_2}! Here goes!$"

gText_ApprenticeChallenge11::
	.string "Yeah, I'm {STR_VAR_1}'s no. {STR_VAR_2}\n"
	.string "disciple! Time to rock the ring and roll!$"

gText_ApprenticeChallenge12::
	.string "Woo-hoo! I'm what they call\n"
	.string "{STR_VAR_1}'s no. {STR_VAR_2} disciple!$"

gText_ApprenticeChallenge13::
	.string "Cough! I'm {STR_VAR_1}'s no. {STR_VAR_2}\n"
	.string "disciple. Pleased to meet you! Cough!$"

gText_ApprenticeChallenge14::
	.string "My nerves are shot…\n"
	.string "I'm the no. {STR_VAR_2} disciple of {STR_VAR_1}.$"

gText_ApprenticeChallenge15::
	.string "I am {STR_VAR_1}'s no. {STR_VAR_2} disciple,\n"
	.string "and I swear it on my honor.$"

gText_ApprenticePleaseTeach0::
	.string "Are you… {PLAYER}?\n"
	.string "Oh! Sniff…sob…\p"
	.string "Oh! S-sorry…\n"
	.string "I'm so nervous, the tears just come…\p"
	.string "I'm {STR_VAR_1}, and I've admired you ever\n"
	.string "since I heard you took on the\l"
	.string "strongest fighters in the universe,\l"
	.string "{PLAYER}.\p"
	.string "I… I always dreamed of meeting you and\n"
	.string "asking you about POKéMON and training.\p"
	.string "Please, please, {PLAYER}! Please take me\n"
	.string "as your disciple and teach me!$"

gText_ApprenticeRejectTeaching0::
	.string "Oh… B-but…\n"
	.string "Sniff… Waaaaaaah!\p"
	.string "Please!\n"
	.string "I'm begging you, please!$"

gText_ApprenticeWhichLevelMode0::
	.string "Really? You will?\n"
	.string "This is the best day of my life! Awoooh!\p"
	.string "Oh… Sorry…\n"
	.string "I'm so happy, I'm crying again…\p"
	.string "Um… Then please tell me!\n"
	.string "It's about the BATTLE TOWER.\p"
	.string "Which is better for someone like me:\n"
	.string "Level 50 or Open Level?$"

gText_ApprenticeLevelModeThanks0::
	.string "{STR_VAR_1}?\n"
	.string "Waaaaah!\p"
	.string "Oh! I'm so sorry! You chose a level for\n"
	.string "me, and I'm so happy I'm crying…\p"
	.string "Sniff…\n"
	.string "Thank you so much!\l"
	.string "Please come talk to me again!$"

gText_ApprenticePleaseTeach1::
	.string "Wowee! You're {PLAYER}, aren't you?\n"
	.string "You're ridiculously strong, right?\p"
	.string "I'm {STR_VAR_1}!\n"
	.string "I just started training as a TRAINER!\p"
	.string "Please, {PLAYER}! Be my master and teach\n"
	.string "me everything about being a TRAINER!$"

gText_ApprenticeRejectTeaching1::
	.string "Aww, why not?\n"
	.string "Please? Pretty please?\l"
	.string "Please be my master!$"

gText_ApprenticeWhichLevelMode1::
	.string "Yay! Awesome!\p"
	.string "The first thing I wanted to ask is\n"
	.string "about the BATTLE TOWER!\p"
	.string "The Level 50 and Open Level Rooms…\n"
	.string "Which one fits me best?$"

gText_ApprenticeLevelModeThanks1::
	.string "{STR_VAR_1}, huh? Makes sense!\n"
	.string "I'll train hard for it!\p"
	.string "If we meet here again, teach me\n"
	.string "something new, master!$"

gText_ApprenticePleaseTeach2::
	.string "Um… Are you {PLAYER}?\n"
	.string "My name is {STR_VAR_1}.\p"
	.string "I want to become a POKéMON TRAINER,\n"
	.string "but I have no idea where to start…\p"
	.string "Since you're so famous, I thought maybe\n"
	.string "you could give me some advice.\p"
	.string "{PLAYER}, would you give me advice?$"

gText_ApprenticeRejectTeaching2::
	.string "Oh, but…\p"
	.string "I really, truly want to become a POKéMON\n"
	.string "TRAINER!\p"
	.string "Please, will you answer my questions?$"

gText_ApprenticeWhichLevelMode2::
	.string "Thank you!\n"
	.string "I have my first question right away!\p"
	.string "The BATTLE TOWER has two levels, Level\n"
	.string "50 and Open Level, right?\p"
	.string "Which one do you think suits me?$"

gText_ApprenticeLevelModeThanks2::
	.string "Oh, the {STR_VAR_1} challenge?\n"
	.string "Got it!\p"
	.string "If I have another question, I'll come\n"
	.string "back and ask you!$"

gText_ApprenticePleaseTeach3::
	.string "Oh? Huh? You're…\n"
	.string "No, that can't be right.\p"
	.string "There's no way someone like me could\n"
	.string "meet {PLAYER}.\p"
	.string "…You really are {PLAYER}?\n"
	.string "I can't believe I'm talking to you!\p"
	.string "When something this good happens,\n"
	.string "something awful is bound to follow. I\l"
	.string "just know it…\p"
	.string "…Sorry…\n"
	.string "I'm… {STR_VAR_1}…\p"
	.string "I don't have a single thing to be proud\n"
	.string "of…\p"
	.string "I shouldn't even talk about myself.\n"
	.string "You'll forget me anyway…\p"
	.string "I dreamed that if I ever met you,\n"
	.string "{PLAYER}, maybe I could ask for advice\l"
	.string "as a TRAINER.\p"
	.string "But I don't think you'd say yes.\p"
	.string "…Or would you be kind enough to advise\n"
	.string "me?$"

gText_ApprenticeRejectTeaching3::
	.string "I knew it…\p"
	.string "Of course. I'm just a boring nobody…\p"
	.string "But I thought, just maybe…\n"
	.string "You won't reconsider, will you?\p"
	.string "But I can't give up that easily.\n"
	.string "I'll ask while my luck holds!\p"
	.string "Please, will you be kind enough to\n"
	.string "advise me?$"

gText_ApprenticeWhichLevelMode3::
	.string "Really? I can't believe it!\n"
	.string "You'll actually advise me!\l"
	.string "I… I'm so happy…\p"
	.string "My question is really silly, but I can't\n"
	.string "decide…\p"
	.string "At the BATTLE TOWER, you can pick Level\n"
	.string "50 or Open Level.\p"
	.string "Which one do you think even I might\n"
	.string "survive?$"

gText_ApprenticeLevelModeThanks3::
	.string "{STR_VAR_1}? Okay! But do you really think\n"
	.string "someone like me has a chance?\p"
	.string "I'll do my best, even if it probably won't\n"
	.string "work.\p"
	.string "Thank you for spending time on someone\n"
	.string "like me.$"

gText_ApprenticePleaseTeach4::
	.string "Oh! You're {PLAYER}{KUN}, aren't you?\p"
	.string "I hear you're tough with POKéMON!\p"
	.string "I'm {STR_VAR_1}!\n"
	.string "I'll be your rival… I mean friend!\p"
	.string "You know what?\p"
	.string "You can't win at the BATTLE FRONTIER on\n"
	.string "what they teach at the TRAINER'S\l"
	.string "SCHOOL alone.\p"
	.string "I'll hear your advice.\n"
	.string "You'll give it, of course?$"

gText_ApprenticeRejectTeaching4::
	.string "Huh? Why are you refusing?\n"
	.string "I'm the one asking you here!\l"
	.string "You have to reconsider!$"

gText_ApprenticeWhichLevelMode4::
	.string "Okay, here's the thing.\n"
	.string "I want you to decide something for me.\p"
	.string "The BATTLE TOWER has Level 50 and Open\n"
	.string "Level Rooms, right?\p"
	.string "Which one's right for me, {PLAYER}{KUN}?$"

gText_ApprenticeLevelModeThanks4::
	.string "Okay, {STR_VAR_1} is right for me?\n"
	.string "Thanks!\p"
	.string "Since you picked it, {PLAYER}{KUN}, I won't be\n"
	.string "so mad if I lose.\p"
	.string "Okay, I'll come to you for advice again.\n"
	.string "Later!$"

gText_ApprenticePleaseTeach5::
	.string "Oh, hi there, {PLAYER}{KUN}!\n"
	.string "I know you, you're famous!\l"
	.string "Call me {STR_VAR_1}! Nice to meet you!\p"
	.string "I do weighted-shell training every day,\n"
	.string "so I stay in shape even while I raise\l"
	.string "POKéMON.\p"
	.string "I've also got work, napping, fishing…\p"
	.string "Being this busy, it's hard to become a\n"
	.string "decent TRAINER.\p"
	.string "So, I have a proposal!\p"
	.string "There's a reason we met. So, {PLAYER}{KUN},\n"
	.string "how about sharing some of your wisdom\l"
	.string "with me now and then?$"

gText_ApprenticeRejectTeaching5::
	.string "Aw, come on, please? A guy like me needs\n"
	.string "someone like you, {PLAYER}{KUN}!\p"
	.string "Honestly, I need your advice!$"

gText_ApprenticeWhichLevelMode5::
	.string "Thanks! That's the spirit!\n"
	.string "Let's start with an easy one!\p"
	.string "You know the BATTLE TOWER has two\n"
	.string "courses, right? Level 50 and Open Level.\p"
	.string "As a busy guy, which one should I\n"
	.string "prepare for?$"

gText_ApprenticeLevelModeThanks5::
	.string "{STR_VAR_1}, huh? Okay, got it. I'll find the\n"
	.string "time somehow and give it a shot!\p"
	.string "…Whoops, I'd better get to work!\n"
	.string "Thanks! See you around!$"

gText_ApprenticePleaseTeach6::
	.string "No way! Seriously?\n"
	.string "Are you the real {PLAYER}?\p"
	.string "Yes! Awesome! I'm {STR_VAR_1}, so happy to\n"
	.string "meet you!\p"
	.string "{PLAYER}, you're really strong, right?\p"
	.string "Everyone's talking about you!\p"
	.string "Oh! I just had a great idea!\n"
	.string "I'll get advice from you, {PLAYER}!\l"
	.string "I bet it'll make me tougher!\p"
	.string "Isn't that a great idea?\n"
	.string "Please, I want your advice!$"

gText_ApprenticeRejectTeaching6::
	.string "Ahahaha, you can act tough, but you\n"
	.string "can't fool me! You really mean yes, don't\l"
	.string "you?$"

gText_ApprenticeWhichLevelMode6::
	.string "Yay! I knew you had a big heart,\n"
	.string "{PLAYER}!\p"
	.string "What should I ask first?\n"
	.string "…Oh, I know!\p"
	.string "Drum roll, please!\n"
	.string "My question is…\p"
	.string "If I took on the BATTLE TOWER, which\n"
	.string "way should I go?\p"
	.string "Level 50 or Open Level?\n"
	.string "Which suits me better?$"

gText_ApprenticeLevelModeThanks6::
	.string "Oh-oh-oh!\n"
	.string "{STR_VAR_1}, you say!\l"
	.string "Thanks for the totally awesome answer!\p"
	.string "I think that's all I wanted to ask\n"
	.string "today.\p"
	.string "Let's meet here again, okay?\n"
	.string "Thanks!$"

gText_ApprenticePleaseTeach7::
	.string "Forgive me, but…\n"
	.string "Are you {PLAYER}?\p"
	.string "I am {STR_VAR_1}, and it is an honor to meet\n"
	.string "you.\p"
	.string "I have long admired you…\p"
	.string "… … … … … …\p"
	.string "Um… I hope this isn't too much of an\n"
	.string "imposition, but…\p"
	.string "May I become your disciple, {PLAYER}?$"

gText_ApprenticeRejectTeaching7::
	.string "Oh…!\p"
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "…I must have fainted from shock.\n"
	.string "Forgive me, I must have misheard you.\p"
	.string "Please! Please say you'll accept me as\n"
	.string "your disciple!$"

gText_ApprenticeWhichLevelMode7::
	.string "Oh… I'm overjoyed!\p"
	.string "I don't want to waste your time, so\n"
	.string "please advise me on this.\p"
	.string "I plan to take a BATTLE TOWER challenge\n"
	.string "soon.\p"
	.string "However, there are two levels…\p"
	.string "Which would suit me best?\n"
	.string "Level 50 or Open Level?$"

gText_ApprenticeLevelModeThanks7::
	.string "{STR_VAR_1} is your choice!\n"
	.string "I see. I will do my best!\p"
	.string "Thank you, {PLAYER}.\n"
	.string "I hope I may count on you again.\l"
	.string "Please take care!$"

gText_ApprenticePleaseTeach8::
	.string "Eek! Eek! {PLAYER}!\n"
	.string "You spoke to me!\l"
	.string "I… I'm overjoyed!\p"
	.string "My name is {STR_VAR_1}!\n"
	.string "I just started training as a TRAINER!\p"
	.string "I'm so lucky I met you, {PLAYER}, the\n"
	.string "greatest name in POKéMON!\p"
	.string "Oh-oh-oh, I know!\n"
	.string "May I ask a huge favor, {PLAYER}?\p"
	.string "Please take me in as your disciple!\n"
	.string "I want to learn from you!$"

gText_ApprenticeRejectTeaching8::
	.string "Waaaah!\n"
	.string "{PLAYER} turned me down…\l"
	.string "I… I'll treasure this experience!\p"
	.string "{PLAYER}, please! This time I want to\n"
	.string "hear a yes!\p"
	.string "I beg you for your guidance!$"

gText_ApprenticeWhichLevelMode8::
	.string "Hieeeeh! {PLAYER} said yes!\n"
	.string "{PLAYER} said yes!\p"
	.string "I won't be able to sleep tonight…\n"
	.string "Thank you so much!\p"
	.string "Then, here's my question!\p"
	.string "At the BATTLE TOWER, what's right for\n"
	.string "me, Level 50 or Open Level?$"

gText_ApprenticeLevelModeThanks8::
	.string "{STR_VAR_1}! Understood!\n"
	.string "I understand perfectly!\l"
	.string "I'm so happy I could burst!\p"
	.string "Please teach me more some other time.$"

gText_ApprenticePleaseTeach9::
	.string "Whoa! Could you be… Might you be…\n"
	.string "{PLAYER}{KUN}?! That strong, famous fighter?\l"
	.string "Well, hello, aren't I the luckiest dude\l"
	.string "ever!\p"
	.string "Name's {STR_VAR_1}, dude!\p"
	.string "I've been hunting for a POKéMON master.\p"
	.string "And with perfect timing,\n"
	.string "along comes you, {PLAYER}{KUN}!\p"
	.string "So here's the deal, {PLAYER}{KUN}!\n"
	.string "Let me be your disciple!$"

gText_ApprenticeRejectTeaching9::
	.string "Gwaaaah!\n"
	.string "You're cool and tough, huh…\p"
	.string "Don't be like that, please.\n"
	.string "I'm asking you here!$"

gText_ApprenticeWhichLevelMode9::
	.string "Oh, yeah! That's the answer I wanted!\n"
	.string "Totally radical, I might add!\p"
	.string "So how about a first lesson on the\n"
	.string "BATTLE TOWER?\p"
	.string "If I went, what would be better?\n"
	.string "Level 50 or Open Level?$"

gText_ApprenticeLevelModeThanks9::
	.string "Uh-huh, {STR_VAR_1} it is!\n"
	.string "Totally A-OK!\l"
	.string "I'll go show them my moves, like, bam!\p"
	.string "All right, I'll look to you as my master!\n"
	.string "Later, dude!$"

gText_ApprenticePleaseTeach10::
	.string "Oh, hey, {PLAYER}{KUN}, right? The Red Ribbon\n"
	.string "Army was looking for you!\p"
	.string "… … …\n"
	.string "Of course I'm lying!\p"
	.string "Me, I'm {STR_VAR_1}. Don't let the way I look\n"
	.string "fool you, I'm the WORLD CHAMPION!\l"
	.string "…That's a lie too!\p"
	.string "This part's no lie, though.\n"
	.string "I'm not very good at battling.\p"
	.string "So how about you become my master in\n"
	.string "all things POKéMON?$"

gText_ApprenticeRejectTeaching10::
	.string "If you're going to be cold like that,\n"
	.string "watch what I do!\p"
	.string "Waaah! Waaah! Waaah!\n"
	.string "Hiccup!\p"
	.string "Hahaha, those were FAKE TEARS!\p"
	.string "Come on, will you please be my POKéMON\n"
	.string "master?$"

gText_ApprenticeWhichLevelMode10::
	.string "Yippee!\n"
	.string "I'll buy you a whole island for that!\p"
	.string "Of course I'm lying again!\n"
	.string "But… Thank you, master!\p"
	.string "You know how the BATTLE TOWER has\n"
	.string "Level 50 and Open Level?\p"
	.string "I can't decide which one to take on…\p"
	.string "Can you decide for me, master?$"

gText_ApprenticeLevelModeThanks10::
	.string "Okay, so {STR_VAR_1} is better!\n"
	.string "I'll go for the other one, then!\p"
	.string "Just kidding!\n"
	.string "I'll follow your teaching, master!\p"
	.string "Thanks, master!\n"
	.string "Please keep teaching me!$"

gText_ApprenticePleaseTeach11::
	.string "A-H-O-Y!\n"
	.string "And that spells ahoy, and it means hi!\p"
	.string "I'm {STR_VAR_1}, the rappin' SAILOR am I!\p"
	.string "Now it's your turn, tell me about\n"
	.string "yourself, give it a try!\p"
	.string "Uh-huh, uh-huh!\n"
	.string "{PLAYER}{KUN}'s your name,\l"
	.string "and POKéMON's your game!\p"
	.string "And you're strong and in your prime,\n"
	.string "this is your time to shine!\p"
	.string "Anyway, here's the deal, I tell you true,\n"
	.string "that you're the tenth fighter I've\l"
	.string "spoken to!\p"
	.string "Let's make it a celebration!\n"
	.string "Be my master for the occasion!$"

gText_ApprenticeRejectTeaching11::
	.string "But!\n"
	.string "You've got to work with me!\p"
	.string "Don't be such a tease!\n"
	.string "Be my master, please!$"

gText_ApprenticeWhichLevelMode11::
	.string "That's it!\n"
	.string "{PLAYER}, you've got the spirit!\p"
	.string "Here's my first question,\n"
	.string "I need your suggestion!\p"
	.string "It's about the BATTLE TOWER,\n"
	.string "and how to match my power!\p"
	.string "Level 50 and Open Level there be,\n"
	.string "which is the one that's right for me?$"

gText_ApprenticeLevelModeThanks11::
	.string "Okay, {STR_VAR_1} it is, you say!\n"
	.string "I'll take it on my way!\p"
	.string "If it's advice I ever need,\n"
	.string "{PLAYER}, your word I'll always heed!$"

gText_ApprenticePleaseTeach12::
	.string "Say, hey, aren't you {PLAYER}?\n"
	.string "What should I do? Talk to you?\l"
	.string "Why not? I'm already talking to you!\p"
	.string "{PLAYER}, are you surprised at me?\n"
	.string "I'd better tell you who I happen to be!\p"
	.string "{STR_VAR_1} is what you can call me. The\n"
	.string "brightest guitar star there'll ever be!\p"
	.string "Are you receiving me?\n"
	.string "You are receiving me!\p"
	.string "My luck's at its best,\n"
	.string "so I'll hit you with a request!\p"
	.string "{PLAYER}, let me be your disciple!\n"
	.string "I want you to teach me everything!$"

gText_ApprenticeRejectTeaching12::
	.string "You're turning me down, then?\n"
	.string "I'll just have to ask again!\p"
	.string "{PLAYER}, I beg to be your disciple!\n"
	.string "I need you to teach me everything!$"

gText_ApprenticeWhichLevelMode12::
	.string "Lucky, yeah, woo-hoo!\n"
	.string "Should I pop a question to you?\p"
	.string "Since we're near the BATTLE TOWER,\n"
	.string "how about a question on its power?\p"
	.string "Of the choices you see,\n"
	.string "which is the right one for me?$"

gText_ApprenticeLevelModeThanks12::
	.string "If {STR_VAR_1} is what you suggest,\n"
	.string "it must be the very best!\p"
	.string "Well, {PLAYER}, I've got to roam free,\n"
	.string "but don't you forget about me.\p"
	.string "See you again, my smart friend!$"

gText_ApprenticePleaseTeach13::
	.string "Oh, hi! You there!\n"
	.string "Could you rub my shoulder for me?\p"
	.string "…Yes, there! That's the spot!\n"
	.string "Ouch, ouch! Oooh, that feels great!\p"
	.string "My name's {STR_VAR_1}. I train in martial\n"
	.string "arts, but my body can't take the\l"
	.string "strain…\p"
	.string "So I decided to battle with POKéMON and\n"
	.string "toughen myself up.\p"
	.string "You're {PLAYER}{KUN}, aren't you? The one who\n"
	.string "became POKéMON LEAGUE CHAMP?\p"
	.string "Listen, would you give me some advice?$"

gText_ApprenticeRejectTeaching13::
	.string "Oh, why not?\p"
	.string "I promise I won't be a bother!\n"
	.string "Please?$"

gText_ApprenticeWhichLevelMode13::
	.string "Thank you. That's very kind of you!\n"
	.string "…Cough! Cough!\p"
	.string "Oogh, I've got to toughen up fast…\p"
	.string "I'm heading to the BATTLE TOWER right\n"
	.string "away, but which is better for me? Level\l"
	.string "50 or Open Level?$"

gText_ApprenticeLevelModeThanks13::
	.string "Hm, all right. {STR_VAR_1} it is.\n"
	.string "I'll head there right away.\p"
	.string "I hope I can keep coming to you for\n"
	.string "help--after all, you're my master!$"

gText_ApprenticePleaseTeach14::
	.string "Er… Um…\n"
	.string "{PLAYER}{KUN}…?\p"
	.string "Please, don't look at me like that.\n"
	.string "It makes me so self-conscious.\p"
	.string "I… I'm {STR_VAR_1}.\p"
	.string "It's embarrassing to admit, but I\n"
	.string "explore ancient ruins and such.\p"
	.string "It's even more embarrassing to say I'm\n"
	.string "interested in the BATTLE FRONTIER.\p"
	.string "{PLAYER}{KUN}, you have a reputation as a\n"
	.string "tough TRAINER…\p"
	.string "It's hard for me to say this, but I want\n"
	.string "to ask something.\p"
	.string "Could you be my master and give me\n"
	.string "advice?$"

gText_ApprenticeRejectTeaching14::
	.string "Please don't brush me off like this!\n"
	.string "I couldn't bear the embarrassment.\p"
	.string "Please be my master!\n"
	.string "I need your advice!$"

gText_ApprenticeWhichLevelMode14::
	.string "Th-thank you…\p"
	.string "But please don't stare at me like that.\n"
	.string "It makes me nervous.\p"
	.string "Please, answer without looking at my\n"
	.string "eyes.\p"
	.string "At the BATTLE TOWER…\n"
	.string "Which level should I try?$"

gText_ApprenticeLevelModeThanks14::
	.string "Oh… Okay!\n"
	.string "I'll give that a try.\p"
	.string "I hope I can take on the challenge\n"
	.string "without getting too flustered…\p"
	.string "Thank you, {PLAYER}{KUN}. If we meet again, I\n"
	.string "hope you'll be just as helpful.$"

gText_ApprenticePleaseTeach15::
	.string "Hm? You look like {PLAYER}{KUN}…\n"
	.string "But are you truly the real thing?\p"
	.string "You may call me {STR_VAR_1}.\p"
	.string "I've been considering becoming the\n"
	.string "disciple of a strong TRAINER.\p"
	.string "So it is my good fortune that you came\n"
	.string "along! …You really are {PLAYER}{KUN}, yes?\p"
	.string "No, no, if you are the real one, that's\n"
	.string "fine. I only wish for you to acknowledge\l"
	.string "me as your disciple.$"

gText_ApprenticeRejectTeaching15::
	.string "Oh?\n"
	.string "But what would make you refuse?\p"
	.string "I apologize for doubting your identity.\p"
	.string "Please accept my apology, and accept\n"
	.string "me as your disciple.$"

gText_ApprenticeWhichLevelMode15::
	.string "You really are accepting me?\n"
	.string "I don't wish to celebrate too early.\p"
	.string "If so, I apologize.\n"
	.string "But now, I need your advice.\p"
	.string "If I were to enter the BATTLE TOWER,\n"
	.string "which would be worthy of me? Level 50 or\l"
	.string "Open Level?$"

gText_ApprenticeLevelModeThanks15::
	.string "{STR_VAR_1}?\n"
	.string "Are you certain?\p"
	.string "I see. If so, that's fine.\n"
	.string "Thank you for your time.\p"
	.string "I know I can be a nuisance, but it\n"
	.string "delights me that you accepted me.\p"
	.string "Let us meet again!$"

gText_ApprenticeWhatHeldItem0::
	.string "Sniff… Sob…\n"
	.string "Oh, {PLAYER}!\p"
	.string "I'm stuck on a problem and I can't\n"
	.string "decide.\p"
	.string "I can't decide what to give my {STR_VAR_1}\n"
	.string "to hold.\p"
	.string "Please tell me, {PLAYER}.\n"
	.string "What item should it hold?$"

gText_ApprenticeHoldNothing0::
	.string "Oh, really? My {STR_VAR_1} shouldn't hold\n"
	.string "anything at all?$"

gText_ApprenticeThanksNoHeldItem0::
	.string "Oh, okay! I'm so glad that's settled!\n"
	.string "This is the best! Awoooh!\p"
	.string "Thank you so much!$"

gText_ApprenticeThanksHeldItem0::
	.string "Oh, I'm so glad…\n"
	.string "I think I have that {STR_VAR_1}, too.\p"
	.string "I'm so happy that's settled!\n"
	.string "Awoooh!\p"
	.string "Thank you so much!$"

gText_ApprenticeItemAlreadyRecommended0::
	.string "Waaaah! Please don't be mean!\p"
	.string "You already told me about that {STR_VAR_1}\n"
	.string "before, sniff…\p"
	.string "Or do you mean my {STR_VAR_2} shouldn't\n"
	.string "hold anything?$"

gText_ApprenticeWhatHeldItem1::
	.string "Yay! It's {PLAYER}! Awesome! I wanted to\n"
	.string "ask you something!\p"
	.string "Do you give your POKéMON items to hold?\n"
	.string "I want mine to hold something, but…\p"
	.string "What item would be good for {STR_VAR_1} to\n"
	.string "hold?\p"
	.string "What do you think?$"

gText_ApprenticeHoldNothing1::
	.string "Huh? You mean my {STR_VAR_1} doesn't need\n"
	.string "to hold anything?$"

gText_ApprenticeThanksNoHeldItem1::
	.string "Oh, I get it! I'll do that!\n"
	.string "Thanks for teaching me!$"

gText_ApprenticeThanksHeldItem1::
	.string "Oh, wow! One {STR_VAR_1}, huh?\n"
	.string "Okay, I'll do that!\p"
	.string "Thanks for teaching me!$"

gText_ApprenticeItemAlreadyRecommended1::
	.string "Oh, uh, no, that's not what I meant. I\n"
	.string "want to hear about an item other than\l"
	.string "the ones I already know.\p"
	.string "Or do you mean my POKéMON doesn't need\n"
	.string "to hold anything this time?$"

gText_ApprenticeWhatHeldItem2::
	.string "{PLAYER}, hello!\n"
	.string "It's about my {STR_VAR_1}…\p"
	.string "I want it to hold something good.\n"
	.string "What would suit it?$"

gText_ApprenticeHoldNothing2::
	.string "Oh, so my {STR_VAR_1} doesn't need to hold\n"
	.string "anything?$"

gText_ApprenticeThanksNoHeldItem2::
	.string "Okay, got it!\n"
	.string "See you again!$"

gText_ApprenticeThanksHeldItem2::
	.string "Oh, the item {STR_VAR_1}?\n"
	.string "Got it!\p"
	.string "I'll do my best to find one!\n"
	.string "See you again!$"

gText_ApprenticeItemAlreadyRecommended2::
	.string "Somebody already told me about the\n"
	.string "{STR_VAR_1}.\p"
	.string "I want my POKéMON to hold a different\n"
	.string "kind of item.\p"
	.string "Or do you think {STR_VAR_2} doesn't need to\n"
	.string "hold anything?$"

gText_ApprenticeWhatHeldItem3::
	.string "Hello, {PLAYER}… Sorry to bother you,\n"
	.string "but I have another thing to ask.\p"
	.string "I don't think I'm strong enough to win\n"
	.string "on my own, so I want my {STR_VAR_1} to hold\l"
	.string "an item.\p"
	.string "But I don't know what would be good.\p"
	.string "{PLAYER}, please, could you decide for\n"
	.string "me?$"

gText_ApprenticeHoldNothing3::
	.string "Someone like me would be better off\n"
	.string "without an item for my POKéMON?$"

gText_ApprenticeThanksNoHeldItem3::
	.string "I understand…\n"
	.string "You're saying I shouldn't lean on items.\l"
	.string "I'll try my best!\p"
	.string "Thank you very much!$"

gText_ApprenticeThanksHeldItem3::
	.string "The item {STR_VAR_1}, okay.\n"
	.string "I'm not sure I can get one…\l"
	.string "No! I'll do my best to get it.\p"
	.string "Thank you very much!$"

gText_ApprenticeItemAlreadyRecommended3::
	.string "Oh, but…\n"
	.string "I think I've heard about that before…\p"
	.string "Is it because I haven't used the\n"
	.string "{STR_VAR_1} well enough?\p"
	.string "Or do you mean my {STR_VAR_2} shouldn't\n"
	.string "hold anything?$"

gText_ApprenticeWhatHeldItem4::
	.string "Oh, {PLAYER}{KUN}.\n"
	.string "There's something I wanted to ask you.\p"
	.string "You already chose which POKéMON I\n"
	.string "should use.\p"
	.string "But I never asked what it should hold.\p"
	.string "Since you've already helped me this far,\n"
	.string "how about seeing it through?\p"
	.string "What would be good? I want my {STR_VAR_1}\n"
	.string "to hold something.$"

gText_ApprenticeHoldNothing4::
	.string "Oh! So my {STR_VAR_1} should fight with its\n"
	.string "bare power?$"

gText_ApprenticeThanksNoHeldItem4::
	.string "If you say that's best, I'll do it.\p"
	.string "Since you picked it, {PLAYER}{KUN}, I won't be\n"
	.string "so mad if I lose.\p"
	.string "Okay, I'll come to you for advice again.\n"
	.string "Later!$"

gText_ApprenticeThanksHeldItem4::
	.string "The item {STR_VAR_1}, huh?\n"
	.string "Not bad. I'll use it!\p"
	.string "Since you picked it, {PLAYER}{KUN}, I won't be\n"
	.string "so mad if I lose.\p"
	.string "Okay, I'll come to you for advice again.\n"
	.string "Later!$"

gText_ApprenticeItemAlreadyRecommended4::
	.string "Huh? What are you saying?\n"
	.string "You already told me about the {STR_VAR_1}.\p"
	.string "Or do you mean my {STR_VAR_2} should fight\n"
	.string "with its bare power?$"

gText_ApprenticeWhatHeldItem5::
	.string "Yo, {PLAYER}{KUN}!\p"
	.string "We're both busy, but we keep running\n"
	.string "into each other!\p"
	.string "Today I have walking, cleaning, and\n"
	.string "shell-polishing to do.\p"
	.string "I haven't even found time to buy my\n"
	.string "precious {STR_VAR_1} anything.\p"
	.string "I'm short on time, so how about telling\n"
	.string "me what my {STR_VAR_1} should hold?$"

gText_ApprenticeHoldNothing5::
	.string "Oh, so since I'm so busy, you're saying\n"
	.string "my {STR_VAR_1} needs nothing?$"

gText_ApprenticeThanksNoHeldItem5::
	.string "Okay, got it.\n"
	.string "That won't take me any time at all.\p"
	.string "Thanks for today!\n"
	.string "See you around!$"

gText_ApprenticeThanksHeldItem5::
	.string "Okay, got it. I'll find the time somehow\n"
	.string "and track down that {STR_VAR_1} you\l"
	.string "recommended.\p"
	.string "I'm glad I found a good master in you.\n"
	.string "Thanks! See you around!$"

gText_ApprenticeItemAlreadyRecommended5::
	.string "Huh? I already know about that\n"
	.string "{STR_VAR_1}.\p"
	.string "Oh, right, I get it. Since I'm so busy,\n"
	.string "you're saying my {STR_VAR_2} needs\l"
	.string "nothing?$"

gText_ApprenticeWhatHeldItem6::
	.string "Hiya, {PLAYER}! It's me!\n"
	.string "I need to pick your brain again today.\l"
	.string "Please, I need your advice!\p"
	.string "Drum roll, please!\n"
	.string "My question is…\p"
	.string "If I want my {STR_VAR_1} to hold an item,\n"
	.string "what should it be?$"

gText_ApprenticeHoldNothing6::
	.string "Is that right? My {STR_VAR_1} doesn't need\n"
	.string "an item, you're saying.$"

gText_ApprenticeThanksNoHeldItem6::
	.string "Okay, that's what I'll do!\p"
	.string "I think that's all I wanted to ask\n"
	.string "today.\p"
	.string "Let's meet here again, okay?\n"
	.string "Thanks!$"

gText_ApprenticeThanksHeldItem6::
	.string "Uh-huh! One {STR_VAR_1}.\n"
	.string "What a cool choice!\l"
	.string "I'll definitely try it!\p"
	.string "I think that's all I wanted to ask\n"
	.string "today.\p"
	.string "Let's meet here again, okay?\n"
	.string "Thanks!$"

gText_ApprenticeItemAlreadyRecommended6::
	.string "Ahahah! That's funny! You already told\n"
	.string "me about that {STR_VAR_1}!\p"
	.string "Are you feeling okay, {PLAYER}?\p"
	.string "Oh, wait! My {STR_VAR_2} doesn't need an\n"
	.string "item, you're saying.$"

gText_ApprenticeWhatHeldItem7::
	.string "Hello, {PLAYER}. I hope you've been well.\p"
	.string "May I ask you for advice?\p"
	.string "In a recent battle, my opponent gave\n"
	.string "his POKéMON an item to hold.\p"
	.string "As a result, I was defeated…\p"
	.string "I don't wish to fall behind. I would like\n"
	.string "my {STR_VAR_1} to hold an item, too.\p"
	.string "I would be grateful if you could decide\n"
	.string "what is right for my POKéMON…$"

gText_ApprenticeHoldNothing7::
	.string "In other words… My POKéMON has no need\n"
	.string "to hold an item?$"

gText_ApprenticeThanksNoHeldItem7::
	.string "I understand clearly now!\n"
	.string "I will keep going as I am.\p"
	.string "Thank you, {PLAYER}.\n"
	.string "I hope I may count on you again.\l"
	.string "Please take care!$"

gText_ApprenticeThanksHeldItem7::
	.string "One {STR_VAR_1} it is!\n"
	.string "I will order it right away.\p"
	.string "Thank you, {PLAYER}.\n"
	.string "I hope I may count on you again.\l"
	.string "Please take care!$"

gText_ApprenticeItemAlreadyRecommended7::
	.string "You have already told me about that,\n"
	.string "and I already have it.\p"
	.string "Or are you saying… My POKéMON has no\n"
	.string "need to hold an item?$"

gText_ApprenticeWhatHeldItem8::
	.string "Eek! {PLAYER}!\n"
	.string "I… I'm overjoyed to see you again!\p"
	.string "Oh-oh-oh! There's something I just had\n"
	.string "to ask, {PLAYER}!\p"
	.string "Please decide what my {STR_VAR_1} should\n"
	.string "be holding!$"

gText_ApprenticeHoldNothing8::
	.string "Oh, wow! I didn't expect that answer!\n"
	.string "So it doesn't need to hold an item?$"

gText_ApprenticeThanksNoHeldItem8::
	.string "Understood perfectly!\n"
	.string "I'll keep training without an item!\p"
	.string "Please teach me more some other time.$"

gText_ApprenticeThanksHeldItem8::
	.string "{STR_VAR_1}! I'll use that!\p"
	.string "Um… Could it be, {PLAYER}, that you give\n"
	.string "your POKéMON that item, too?\p"
	.string "I'll be sure to get it!\n"
	.string "Please teach me more some other time.$"

gText_ApprenticeItemAlreadyRecommended8::
	.string "Oh? You recommended that {STR_VAR_1}\n"
	.string "before, too.\p"
	.string "Or is it simply the best thing to hold?\n"
	.string "Or do you mean my {STR_VAR_2} doesn't need\l"
	.string "anything?$"

gText_ApprenticeWhatHeldItem9::
	.string "Yo!\n"
	.string "My master, {PLAYER}{KUN}!\p"
	.string "I want to pick your brain about POKéMON\n"
	.string "gear.\p"
	.string "What do you think my {STR_VAR_1} should\n"
	.string "hold?\p"
	.string "Don't be shy, dude.\n"
	.string "Just say it!$"

gText_ApprenticeHoldNothing9::
	.string "Oh? So you're saying my {STR_VAR_1} can win\n"
	.string "without holding anything?$"

gText_ApprenticeThanksNoHeldItem9::
	.string "Totally righteous!\n"
	.string "I'll give it my best shot, like, slam!\p"
	.string "All right, thanks as always!\n"
	.string "Later, dude!$"

gText_ApprenticeThanksHeldItem9::
	.string "Uh-huh, that's one {STR_VAR_1}?\n"
	.string "Totally righteous!\l"
	.string "I'll go find one, like, bam!\p"
	.string "All right, thanks as always!\n"
	.string "Later, dude!$"

gText_ApprenticeItemAlreadyRecommended9::
	.string "No, no! You already told me about that\n"
	.string "{STR_VAR_1} thing.\p"
	.string "Oh, hold on a sec… So you're saying my\n"
	.string "{STR_VAR_2} can win without holding\l"
	.string "anything?$"

gText_ApprenticeWhatHeldItem10::
	.string "{PLAYER}{KUN}, you won't believe what\n"
	.string "happened!\p"
	.string "I woke up this morning and my POKéMON\n"
	.string "was holding 10 DRAGON BALLS!\p"
	.string "Of course I'm lying!\n"
	.string "Wahahaha!\p"
	.string "This part's no lie, though. I'm not good\n"
	.string "at figuring out what POKéMON should\l"
	.string "hold.\p"
	.string "So how about deciding what my {STR_VAR_1}\n"
	.string "should hold, master?$"

gText_ApprenticeHoldNothing10::
	.string "What's that mean?\n"
	.string "Don't give it anything?$"

gText_ApprenticeThanksNoHeldItem10::
	.string "Okay, so it holds nothing.\n"
	.string "Then I'd better go buy it something!\p"
	.string "Just kidding!\n"
	.string "I'll follow your teaching, master!\p"
	.string "Thanks, master!\n"
	.string "Please keep teaching me!$"

gText_ApprenticeThanksHeldItem10::
	.string "Okay, so it's one {STR_VAR_1}!\n"
	.string "I'll give it anything but that!\p"
	.string "Just kidding!\n"
	.string "I'll follow your teaching, master!\p"
	.string "Thanks, master!\n"
	.string "Please keep teaching me!$"

gText_ApprenticeItemAlreadyRecommended10::
	.string "Um, you told me about that before,\n"
	.string "didn't you?\p"
	.string "Is there anything else?\p"
	.string "Or do you mean my {STR_VAR_2} shouldn't\n"
	.string "hold anything?$"

gText_ApprenticeWhatHeldItem11::
	.string "A-H-O-Y!\n"
	.string "And that spells ahoy!\p"
	.string "The rappin' SAILOR am I! I've got an\n"
	.string "item question, and I need your\l"
	.string "suggestion!\p"
	.string "My {STR_VAR_1} needs something to hold,\n"
	.string "what should it be, if I may be bold?$"

gText_ApprenticeHoldNothing11::
	.string "Is that right? My {STR_VAR_1} doesn't need\n"
	.string "to hold a thing, not even a ring?$"

gText_ApprenticeThanksNoHeldItem11::
	.string "Okay, I hear you, sure I do!\n"
	.string "My POKéMON goes empty-handed, too!\p"
	.string "If it's advice I ever need,\n"
	.string "{PLAYER}, your word I'll always heed!$"

gText_ApprenticeThanksHeldItem11::
	.string "Okay, one {STR_VAR_1},\n"
	.string "that's what I'll use.\l"
	.string "I was right to make you choose!\p"
	.string "If it's advice I ever need,\n"
	.string "{PLAYER}, your word I'll always heed!$"

gText_ApprenticeItemAlreadyRecommended11::
	.string "Okay, one {STR_VAR_1}, you say?\n"
	.string "You told me that the other day.\l"
	.string "I need a new idea, a brand new way.\p"
	.string "Or is it that my POKéMON doesn't need to\n"
	.string "hold a thing?$"

gText_ApprenticeWhatHeldItem12::
	.string "Say, hey, {PLAYER}!\n"
	.string "I found you again today!\p"
	.string "What should I do? Ask for your advice?\n"
	.string "Why not? I'm already talking to you!\p"
	.string "{PLAYER}, are you sick of me?\n"
	.string "Nah, no way, that can't be.\p"
	.string "Will you hear me out? I'm looking for\n"
	.string "advice, that's what it's about.\p"
	.string "It's about a hold item for my {STR_VAR_1}\n"
	.string "that'd be good. I can't decide, and it's\l"
	.string "got me in a mood.$"

gText_ApprenticeHoldNothing12::
	.string "My {STR_VAR_1} needs nothing?\n"
	.string "Doesn't have to hold anything?$"

gText_ApprenticeThanksNoHeldItem12::
	.string "If holding nothing is the best,\n"
	.string "I'll do as you suggest!\p"
	.string "Well, {PLAYER}, I've got to roam free,\n"
	.string "but don't you forget about me.\p"
	.string "See you again, my smart friend!$"

gText_ApprenticeThanksHeldItem12::
	.string "If holding that {STR_VAR_1} is\n"
	.string "the best, I'll do as you suggest!\p"
	.string "Well, {PLAYER}, I've got to roam free,\n"
	.string "but don't you forget about me.\p"
	.string "See you again, my smart friend!$"

gText_ApprenticeItemAlreadyRecommended12::
	.string "Haven't I heard about that {STR_VAR_1}\n"
	.string "before? I'm certain I have, that's for\l"
	.string "sure!\p"
	.string "I need something new!\n"
	.string "Or does my {STR_VAR_2} need nothing?\l"
	.string "Doesn't have to hold anything?$"

gText_ApprenticeWhatHeldItem13::
	.string "Gwah! Ouch! {PLAYER}{KUN}, my arm's broken!\n"
	.string "Don't touch it, please!\p"
	.string "I must have hurt it while trying out\n"
	.string "hold items on my gang of POKéMON.\p"
	.string "So, things being this way, I need you to\n"
	.string "decide for me.\p"
	.string "{PLAYER}{KUN}, what would be good for my\n"
	.string "{STR_VAR_1} to hold?$"

gText_ApprenticeHoldNothing13::
	.string "Ouch…\p"
	.string "So you're suggesting my {STR_VAR_1}\n"
	.string "doesn't have to hold anything?$"

gText_ApprenticeThanksNoHeldItem13::
	.string "Hm, all right. That would be easier for\n"
	.string "me, the way things are now.\p"
	.string "I hope I can keep coming to you for help\n"
	.string "like this.$"

gText_ApprenticeThanksHeldItem13::
	.string "Hm, all right. That's one {STR_VAR_1}. My\n"
	.string "POKéMON's arm is fine, so I'll have it\l"
	.string "hold that right away.\p"
	.string "I hope I can keep coming to you for help\n"
	.string "like this.$"

gText_ApprenticeItemAlreadyRecommended13::
	.string "No, no, you told me about that {STR_VAR_1}\n"
	.string "before, remember?\p"
	.string "How about telling me something even\n"
	.string "better?\p"
	.string "Oh, wait a second. So you're suggesting\n"
	.string "my {STR_VAR_2} doesn't have to hold\l"
	.string "anything?$"

gText_ApprenticeWhatHeldItem14::
	.string "Er… Um…\n"
	.string "{PLAYER}{KUN}…\p"
	.string "Please, don't look at me like that.\n"
	.string "My POKéMON don't hold anything yet.\p"
	.string "I… I'm really embarrassed about this,\n"
	.string "but I need your advice.\p"
	.string "I can't decide what item would make my\n"
	.string "{STR_VAR_1} strong.\p"
	.string "{PLAYER}{KUN}, what do you think would be\n"
	.string "good?$"

gText_ApprenticeHoldNothing14::
	.string "Oh… Then you think my {STR_VAR_1} would be\n"
	.string "better off without an item?$"

gText_ApprenticeThanksNoHeldItem14::
	.string "Oh… Okay!\n"
	.string "I'll go without an item.\p"
	.string "This is nerve-racking, though.\n"
	.string "It'll be fine, right?\p"
	.string "Thank you, {PLAYER}{KUN}. If we meet again, I\n"
	.string "hope you'll be just as helpful.$"

gText_ApprenticeThanksHeldItem14::
	.string "Oh… Okay!\n"
	.string "I'll go with that {STR_VAR_1}.\p"
	.string "This is nerve-racking, though.\n"
	.string "It'll be fine, right?\p"
	.string "Thank you, {PLAYER}{KUN}. If we meet again, I\n"
	.string "hope you'll be just as helpful.$"

gText_ApprenticeItemAlreadyRecommended14::
	.string "B-but I already heard about that.\p"
	.string "Please don't brush me off like this!\n"
	.string "I couldn't bear the embarrassment.\p"
	.string "Oh… Am I jumping to conclusions? Do you\n"
	.string "think my {STR_VAR_2} would be better off\l"
	.string "without an item?$"

gText_ApprenticeWhatHeldItem15::
	.string "Hm? You look like {PLAYER}{KUN}…\n"
	.string "But are you truly the real thing?\l"
	.string "Perhaps you have a twin?\p"
	.string "Oh, no, no, no, don't worry! If you really\n"
	.string "are {PLAYER}, please forgive my\l"
	.string "rudeness.\p"
	.string "What I would like is more of your fine\n"
	.string "advice.\p"
	.string "I have my {STR_VAR_1} here, and I wish to\n"
	.string "give it a useful item to hold.\p"
	.string "What would be worthy of it?$"

gText_ApprenticeHoldNothing15::
	.string "It would be better if it held nothing?\n"
	.string "Are you certain?$"

gText_ApprenticeThanksNoHeldItem15::
	.string "I see. If so, that's fine.\n"
	.string "Thank you for your time.\p"
	.string "Let us meet again!$"

gText_ApprenticeThanksHeldItem15::
	.string "One {STR_VAR_1}?\n"
	.string "Are you certain?\p"
	.string "I see. If so, that's fine.\n"
	.string "Thank you for your time.\p"
	.string "I do hope my POKéMON puts it to good\n"
	.string "use.\p"
	.string "Let us meet again!$"

gText_ApprenticeItemAlreadyRecommended15::
	.string "No, no, wait a moment.\n"
	.string "I believe you taught me that before.\p"
	.string "I would like you to recommend something\n"
	.string "different this time.\p"
	.string "Perhaps you are suggesting that my\n"
	.string "{STR_VAR_2} should hold nothing? Are you\l"
	.string "certain?$"

gText_ApprenticeWhichMonFirst0::
	.string "Waah, {PLAYER}!\n"
	.string "I have a problem, sob…\p"
	.string "I want to start fighting other people,\n"
	.string "but I don't know what to do.\p"
	.string "How should I line up my POKéMON so\n"
	.string "they're at their strongest?\p"
	.string "Please tell me, {PLAYER}. If you were me,\n"
	.string "which of these POKéMON would you send\l"
	.string "out first?$"

gText_ApprenticeMonFirstThanks0::
	.string "My {STR_VAR_1} should go first?\n"
	.string "Waaaaah!\p"
	.string "Oh! I'm so sorry! You picked my lead\n"
	.string "POKéMON for me, and I'm so happy I'm\l"
	.string "crying…\p"
	.string "Thank you so much!$"

gText_ApprenticeWhichMonFirst1::
	.string "Yay! It's {PLAYER}! Awesome! I wanted to\n"
	.string "ask you something!\p"
	.string "Um, of my POKéMON, which one do you\n"
	.string "think should go out first?$"

gText_ApprenticeMonFirstThanks1::
	.string "My {STR_VAR_1}? Makes sense.\n"
	.string "Okay, I'll do that!\p"
	.string "Thanks for teaching me!$"

gText_ApprenticeWhichMonFirst2::
	.string "{PLAYER}, hello!\p"
	.string "I think it matters a lot which POKéMON\n"
	.string "comes out first in a battle.\p"
	.string "Out of the POKéMON I have, which would\n"
	.string "be good to send out first?$"

gText_ApprenticeMonFirstThanks2::
	.string "My {STR_VAR_1} goes first?\n"
	.string "Okay, got it!\p"
	.string "See you again!$"

gText_ApprenticeWhichMonFirst3::
	.string "Hello, {PLAYER}… Sorry to bother you\n"
	.string "again with another question.\p"
	.string "I have so little confidence, I don't\n"
	.string "know what I'd do without you, {PLAYER}.\p"
	.string "It may be a waste of time to worry\n"
	.string "about it, but I just can't decide\l"
	.string "something…\p"
	.string "Which of my POKéMON should I send out\n"
	.string "first in a battle?$"

gText_ApprenticeMonFirstThanks3::
	.string "My {STR_VAR_1}?\n"
	.string "Understood!\p"
	.string "I can't believe you'd bother to answer\n"
	.string "my questions so often!\p"
	.string "I'm so grateful you'd even talk to me…\n"
	.string "Thank you!$"

gText_ApprenticeWhichMonFirst4::
	.string "Oh, {PLAYER}{KUN}! It's me! I'm glad to see\n"
	.string "you, because I have a little problem.\p"
	.string "I can't decide how to line up my\n"
	.string "POKéMON. Can you decide for me?\p"
	.string "Oh, you don't need to decide the whole\n"
	.string "team right now.\p"
	.string "How about picking just the first\n"
	.string "POKéMON?$"

gText_ApprenticeMonFirstThanks4::
	.string "My {STR_VAR_1}? Great!\p"
	.string "Since you picked it, {PLAYER}{KUN}, I won't be\n"
	.string "so mad if I lose.\p"
	.string "Okay, I'll come to you for advice again.\n"
	.string "Later!$"

gText_ApprenticeWhichMonFirst5::
	.string "Hi, master {PLAYER}{KUN}!\n"
	.string "I'm busy again today!\p"
	.string "I have to go cycling, shopping, and\n"
	.string "meditating.\p"
	.string "I haven't even had time to decide how\n"
	.string "to line up my POKéMON team.\p"
	.string "So how about checking out my team?\n"
	.string "Which one should go first?$"

gText_ApprenticeMonFirstThanks5::
	.string "Okay, got it. I at least have time to put\n"
	.string "my {STR_VAR_1} at the head of the line!\p"
	.string "Whoops, my girlfriend's waiting!\n"
	.string "Thanks! See you around!$"

gText_ApprenticeWhichMonFirst6::
	.string "Yoo-hoo! Hiya, {PLAYER}! You always walk\n"
	.string "around looking so tough!\p"
	.string "Listen, I need something from you\n"
	.string "again! The usual!\p"
	.string "Drum roll, please!\n"
	.string "My question is about my team.\p"
	.string "Which of my POKéMON should be the first\n"
	.string "to go out in a battle?$"

gText_ApprenticeMonFirstThanks6::
	.string "Hmhm!\n"
	.string "My {STR_VAR_1}, you say!\l"
	.string "Thanks for the super cool answer!\p"
	.string "I think that's all I wanted to ask\n"
	.string "today.\p"
	.string "Let's meet here again, okay?\n"
	.string "Thanks!$"

gText_ApprenticeWhichMonFirst7::
	.string "Thank you so much for stopping to talk\n"
	.string "with me, {PLAYER}.\p"
	.string "I know I'm taking advantage of your\n"
	.string "kindness, but may I ask for advice?\p"
	.string "I would like you to decide the order of\n"
	.string "my POKéMON team.\p"
	.string "I would be grateful if you could decide\n"
	.string "which POKéMON should come first.$"

gText_ApprenticeMonFirstThanks7::
	.string "My {STR_VAR_1} it is!\n"
	.string "I will put it first right away!\p"
	.string "Thank you, {PLAYER}.\n"
	.string "I hope I may count on you again.\l"
	.string "Please take care!$"

gText_ApprenticeWhichMonFirst8::
	.string "Eek! {PLAYER}!\n"
	.string "I… I'm overjoyed to see you again!\p"
	.string "My POKéMON have gotten so much\n"
	.string "stronger!\p"
	.string "But I don't always win. It seems to\n"
	.string "depend on which POKéMON goes first.\p"
	.string "{PLAYER}, please, I need your help!\p"
	.string "Please decide which of my POKéMON\n"
	.string "should go out first!$"

gText_ApprenticeMonFirstThanks8::
	.string "Sigh… I'm overwhelmed with happiness…\p"
	.string "It's like a dream to have you decide for\n"
	.string "me, {PLAYER}.\p"
	.string "But understood perfectly!\n"
	.string "I'll lead with my {STR_VAR_1}!\p"
	.string "Please teach me more some other time.$"

gText_ApprenticeWhichMonFirst9::
	.string "Hey, hey, dude!\n"
	.string "My master, {PLAYER}{KUN}!\l"
	.string "Hit me with your wisdom today!\p"
	.string "So I put together a team of three\n"
	.string "POKéMON. So far so good.\p"
	.string "But the battle order isn't settled yet.\p"
	.string "That's where you come in, {PLAYER}{KUN}!\n"
	.string "You decide who leads off!\p"
	.string "Don't be shy, dude.\n"
	.string "Just say it!$"

gText_ApprenticeMonFirstThanks9::
	.string "Uh-huh, my {STR_VAR_1} leads off!\n"
	.string "Totally A-OK!\l"
	.string "I'll switch up the lineup, like, wham!\p"
	.string "All right, thanks as always!\n"
	.string "Later, dude!$"

gText_ApprenticeWhichMonFirst10::
	.string "{PLAYER}{KUN}, listen!\n"
	.string "It's a crisis!\p"
	.string "My POKéMON, all three of them, jump into\n"
	.string "battle at once!\p"
	.string "Of course that's impossible!\n"
	.string "Wahahaha!\p"
	.string "This part's no lie, though. I'm bad at\n"
	.string "deciding how to line up my POKéMON.\p"
	.string "So how about deciding which POKéMON\n"
	.string "should go first, master?$"

gText_ApprenticeMonFirstThanks10::
	.string "Okay, so it's my {STR_VAR_1} you chose? I'll\n"
	.string "send out anything but that one first!\p"
	.string "Just kidding!\n"
	.string "I'll follow your teaching, master!\p"
	.string "Thanks, master!\n"
	.string "Please keep teaching me!$"

gText_ApprenticeWhichMonFirst11::
	.string "A-H-O-Y!\n"
	.string "And that spells ahoy!\p"
	.string "The rappin' SAILOR am I!\n"
	.string "Here's a question that's pretty fly!\p"
	.string "It's a team lineup question,\n"
	.string "I need your suggestion!\p"
	.string "Out of this lot, which should go first,\n"
	.string "ready to burst?$"

gText_ApprenticeMonFirstThanks11::
	.string "Okay, I hear you, sure I do!\n"
	.string "I'll switch them up, that I'll do!\p"
	.string "If it's advice I ever need,\n"
	.string "{PLAYER}, your word I'll always heed!$"

gText_ApprenticeWhichMonFirst12::
	.string "Yahoo, {PLAYER}!\n"
	.string "How do you do?\p"
	.string "What should I do? Go ahead and ask?\n"
	.string "Uh-huh, I have something to ask!\l"
	.string "Are you receiving me?\l"
	.string "You are receiving me!\p"
	.string "You've got to decide which of my\n"
	.string "POKéMON is the first to ride into\l"
	.string "battle, I mean to say.$"

gText_ApprenticeMonFirstThanks12::
	.string "My {STR_VAR_1}? Yes!\n"
	.string "That'll do, there's no distress!\p"
	.string "Well, {PLAYER}, I've got to roam free,\n"
	.string "but don't you forget about me.\p"
	.string "See you again, my smart friend!$"

gText_ApprenticeWhichMonFirst13::
	.string "…Oof…ooch… {PLAYER}{KUN}…\n"
	.string "My stomach suddenly hurts…\p"
	.string "…It's getting better now…\p"
	.string "I must have worried myself sick racking\n"
	.string "my brain over how to line up my gang of\l"
	.string "POKéMON.\p"
	.string "So, things being this way, I need you to\n"
	.string "decide for me.\p"
	.string "{PLAYER}{KUN}, which of my POKéMON should go\n"
	.string "first? So I'd win, I mean.$"

gText_ApprenticeMonFirstThanks13::
	.string "Hm, all right.\n"
	.string "My {STR_VAR_1} goes first.\p"
	.string "I'll fix the lineup after supper.\p"
	.string "I hope I can keep coming to you for help\n"
	.string "like this.$"

gText_ApprenticeWhichMonFirst14::
	.string "Er… Um…\n"
	.string "{PLAYER}{KUN}?\p"
	.string "Please, don't look at me like that.\n"
	.string "It's making me flustered.\p"
	.string "Um…\n"
	.string "I really need your advice.\p"
	.string "It's embarrassing to say, but I picked\n"
	.string "my team of 3 POKéMON. I can't decide on\l"
	.string "the order, though.\p"
	.string "Which POKéMON should I send out first\n"
	.string "so I at least look capable?$"

gText_ApprenticeMonFirstThanks14::
	.string "Oh… Okay!\n"
	.string "I'll lead with my {STR_VAR_1}.\p"
	.string "I hope I can do my best without getting\n"
	.string "flustered.\p"
	.string "Thank you, {PLAYER}{KUN}. If we meet again, I\n"
	.string "hope you'll be just as helpful.$"

gText_ApprenticeWhichMonFirst15::
	.string "Hm? You look like {PLAYER}{KUN}…\n"
	.string "But are you truly the real thing?\l"
	.string "Perhaps a clever look-alike?\p"
	.string "Oh, no, no, no, don't worry! If you really\n"
	.string "are {PLAYER}, please forgive my\l"
	.string "rudeness.\p"
	.string "What I would like is your fine advice.\p"
	.string "I have my POKéMON team here. Please\n"
	.string "tell me which one should go first in a\l"
	.string "battle.$"

gText_ApprenticeMonFirstThanks15::
	.string "My {STR_VAR_1}…\n"
	.string "You aren't pulling my leg?\p"
	.string "I see. If so, that's fine.\n"
	.string "Thank you for your time.\p"
	.string "I am what I am, but I shall do my best.\p"
	.string "Let us meet again!$"

gText_ApprenticeWhichMon0::
	.string "Sniff…\n"
	.string "Oh, {PLAYER}!\p"
	.string "What perfect timing!\n"
	.string "There's something I just can't decide…\p"
	.string "I can't decide which POKéMON I should\n"
	.string "use.\p"
	.string "I can't choose between the POKéMON\n"
	.string "{STR_VAR_1} and {STR_VAR_2}…\p"
	.string "{PLAYER}, which do you think would give\n"
	.string "even me a chance at winning?$"

gText_ApprenticeMonThanks0::
	.string "Sniff… I… I understand!\n"
	.string "Oh! I'm so sorry!\l"
	.string "You've made me so happy, I'm crying…\p"
	.string "I'll do my best to catch one {STR_VAR_1}!\p"
	.string "Thank you so much!$"

gText_ApprenticeWhichMon1::
	.string "Yay! It's {PLAYER}! Yay, you showed up\n"
	.string "at just the right time! I need your\l"
	.string "advice again!\p"
	.string "Um, I'm all mixed up--should I use my\n"
	.string "{STR_VAR_1} or {STR_VAR_2}…\p"
	.string "Which one do you think I should raise,\n"
	.string "{PLAYER}?$"

gText_ApprenticeMonThanks1::
	.string "Oh, so my {STR_VAR_1} is better!\n"
	.string "Okay, I'll do that!\p"
	.string "Thanks for teaching me!$"

gText_ApprenticeWhichMon2::
	.string "{PLAYER}, hello!\n"
	.string "I have a question I wanted to ask.\p"
	.string "I can't decide whether to raise a\n"
	.string "{STR_VAR_1} or a {STR_VAR_2}.\p"
	.string "Which POKéMON do you think will be\n"
	.string "stronger?$"

gText_ApprenticeMonThanks2::
	.string "{STR_VAR_1} is your choice?\n"
	.string "Okay, got it!\p"
	.string "I'll go catch a strong {STR_VAR_1} right\n"
	.string "away!\p"
	.string "See you again!$"

gText_ApprenticeWhichMon3::
	.string "Hello, {PLAYER}…\p"
	.string "Um, you've probably forgotten someone\n"
	.string "like me already…\p"
	.string "…But that doesn't matter if you could\n"
	.string "give me advice…\p"
	.string "I can't decide which kind of POKéMON to\n"
	.string "raise…\p"
	.string "I've narrowed it down to the POKéMON\n"
	.string "{STR_VAR_1} and {STR_VAR_2}, but that's where\l"
	.string "I got stuck…\p"
	.string "{PLAYER}, I know it's a bother, but\n"
	.string "please decide for me.$"

gText_ApprenticeMonThanks3::
	.string "But will a wild {STR_VAR_1} even pay\n"
	.string "attention to me?\p"
	.string "I'll try!\p"
	.string "But will I even be able to catch one…\n"
	.string "No! I'll do my best!\p"
	.string "Thank you!$"

gText_ApprenticeWhichMon4::
	.string "Oh, {PLAYER}{KUN}! I'm so glad to see you!\n"
	.string "I was just about to go look for you!\p"
	.string "Can you decide which kind of POKéMON I\n"
	.string "should use?\p"
	.string "For instance… How about the POKéMON\n"
	.string "{STR_VAR_1} and {STR_VAR_2}?\p"
	.string "Which one do you think would be better?$"

gText_ApprenticeMonThanks4::
	.string "{STR_VAR_1}? Great!\p"
	.string "Since you picked it, {PLAYER}{KUN}, I won't be\n"
	.string "so mad if I lose.\p"
	.string "Okay, I'll come to you for advice again.\n"
	.string "Later!$"

gText_ApprenticeWhichMon5::
	.string "If it isn't {PLAYER}{KUN}! How's it going?\n"
	.string "I'm busy again, as always!\p"
	.string "I want to do well with POKéMON, too, but\n"
	.string "I can't decide which POKéMON to use.\p"
	.string "See, {STR_VAR_1} look strong, right?\n"
	.string "But {STR_VAR_2} are hard to ignore.\p"
	.string "{PLAYER}{KUN}, give me some of your good\n"
	.string "advice! Which one would be good for me?$"

gText_ApprenticeMonThanks5::
	.string "Okay, got it. I'll find the time somehow\n"
	.string "and catch that {STR_VAR_1} you\l"
	.string "recommended.\p"
	.string "I'm glad I found a good master in you.\n"
	.string "Thanks! See you around!$"

gText_ApprenticeWhichMon6::
	.string "Oh!\n"
	.string "Yay, it's {PLAYER}!\p"
	.string "I wasted no time bragging to my friends\n"
	.string "about meeting you!\p"
	.string "I need to pick your brain again today.\n"
	.string "It's an easy one for you!\p"
	.string "Drum roll, please!\n"
	.string "My question is…\p"
	.string "If I were going to raise a POKéMON, and\n"
	.string "the choices were a {STR_VAR_1} or a\l"
	.string "{STR_VAR_2}, which should it be?$"

gText_ApprenticeMonThanks6::
	.string "Ahhh!\n"
	.string "{STR_VAR_1}, you say!\l"
	.string "Thanks for the super cool answer!\p"
	.string "I think that's all I wanted to ask\n"
	.string "today.\p"
	.string "Let's meet here again, okay?\n"
	.string "Thanks!$"

gText_ApprenticeWhichMon7::
	.string "Oh, is that you, {PLAYER}?\n"
	.string "I'm delighted to see you again!\p"
	.string "Since becoming your disciple, my\n"
	.string "confidence has been blooming.\p"
	.string "I think I'm ready to raise a POKéMON of\n"
	.string "my own!\p"
	.string "{PLAYER}, may I impose on you to choose\n"
	.string "which POKéMON I should raise?\p"
	.string "The choices are the POKéMON {STR_VAR_1} or\n"
	.string "{STR_VAR_2}… Which is right for me?$"

gText_ApprenticeMonThanks7::
	.string "One {STR_VAR_1} it is!\n"
	.string "I will find one right away!\p"
	.string "Thank you, {PLAYER}.\n"
	.string "I hope I may count on you again.\l"
	.string "Please take care!$"

gText_ApprenticeWhichMon8::
	.string "Eek! {PLAYER}! I met you again!\n"
	.string "I… I'm overjoyed!\p"
	.string "Oh-oh-oh, I know!\n"
	.string "I can't pass up this chance!\p"
	.string "May I ask a huge favor, {PLAYER}?\n"
	.string "Please choose a POKéMON for me!\p"
	.string "Please decide which would be better,\n"
	.string "{STR_VAR_1} or {STR_VAR_2}!$"

gText_ApprenticeMonThanks8::
	.string "Wow! You decided for me! I'll raise one\n"
	.string "{STR_VAR_1} to the best of my ability.\p"
	.string "Please teach me more some other time.$"

gText_ApprenticeWhichMon9::
	.string "Hey, hey, dude!\n"
	.string "My master, {PLAYER}{KUN}!\p"
	.string "Hey, I've been looking all over for you\n"
	.string "for more of your wisdom!\p"
	.string "Which kind of POKéMON would be right\n"
	.string "for me, a {STR_VAR_1} or a {STR_VAR_2}?\p"
	.string "Don't be shy, dude.\n"
	.string "Just say it!$"

gText_ApprenticeMonThanks9::
	.string "Uh-huh, one {STR_VAR_1} it is!\n"
	.string "Totally A-OK!\l"
	.string "I'll get one into a BALL, like, cram!\p"
	.string "All right, thanks as always!\n"
	.string "Later, dude!$"

gText_ApprenticeWhichMon10::
	.string "{PLAYER}{KUN}, listen! Big news!\n"
	.string "I caught a legendary POKéMON!\p"
	.string "Of course I'm lying!\n"
	.string "Wahahaha!\p"
	.string "This part's no lie, though.\n"
	.string "I'm bad at catching POKéMON.\p"
	.string "So how about deciding which kind of\n"
	.string "POKéMON I should catch, master?\p"
	.string "Which would be better?\n"
	.string "{STR_VAR_1} or {STR_VAR_2}?$"

gText_ApprenticeMonThanks10::
	.string "Okay, so it's {STR_VAR_1} you chose?\n"
	.string "I'll catch the other kind, then!\p"
	.string "Just kidding!\n"
	.string "I'll follow your teaching, master!\p"
	.string "Thanks, master!\n"
	.string "Please keep teaching me!$"

gText_ApprenticeWhichMon11::
	.string "A-H-O-Y!\n"
	.string "And that spells ahoy!\p"
	.string "The rappin' SAILOR am I!\n"
	.string "Surely you remember me, why?\p"
	.string "Today I've got a POKéMON question,\n"
	.string "and I need your suggestion!\p"
	.string "I have the choice between a {STR_VAR_1}\n"
	.string "and a {STR_VAR_2}, you see. Which is the one\l"
	.string "to catch for me?$"

gText_ApprenticeMonThanks11::
	.string "{STR_VAR_1}, you say, hey, hey!\n"
	.string "I'll go get me one right away!\p"
	.string "If it's advice I ever need,\n"
	.string "{PLAYER}, your word I'll always heed!$"

gText_ApprenticeWhichMon12::
	.string "Oh, wow, if it isn't {PLAYER}!\p"
	.string "What should I do? Ask your advice?\n"
	.string "Why not? I'm already talking to you!\p"
	.string "It's been a while. Let me break the ice,\n"
	.string "I'm looking for advice! Are you\l"
	.string "receiving me? You are receiving me!\p"
	.string "My POKéMON--which should I use?\n"
	.string "It's either {STR_VAR_1} or {STR_VAR_2}.\l"
	.string "Which do you choose?$"

gText_ApprenticeMonThanks12::
	.string "If that {STR_VAR_1} is the best,\n"
	.string "I'll do as you suggest!\p"
	.string "Well, {PLAYER}, I've got to roam free,\n"
	.string "but don't you forget about me.\p"
	.string "See you again, my smart friend!$"

gText_ApprenticeWhichMon13::
	.string "Oh, hi, {PLAYER}{KUN}…\n"
	.string "I've got a terrible headache…\p"
	.string "I must have worried too much about\n"
	.string "which POKéMON to raise.\p"
	.string "So, things being this way, I need you to\n"
	.string "decide for me.\p"
	.string "{PLAYER}{KUN}, if I had to choose between the\n"
	.string "POKéMON {STR_VAR_1} and {STR_VAR_2}, which\l"
	.string "should it be?$"

gText_ApprenticeMonThanks13::
	.string "Hm, one {STR_VAR_1}, all right.\n"
	.string "I'll go look for one when I feel better.\p"
	.string "I hope I can keep coming to you for help\n"
	.string "like this.$"

gText_ApprenticeWhichMon14::
	.string "Er… Um…\n"
	.string "{PLAYER}{KUN}…?\p"
	.string "Please, don't look at me like that.\n"
	.string "I'm getting flustered…\l"
	.string "I… I need your advice.\p"
	.string "I… I'm really embarrassed, but I can't\n"
	.string "decide which POKéMON to use.\p"
	.string "If the choices were {STR_VAR_1} or\n"
	.string "{STR_VAR_2}, which would be better?$"

gText_ApprenticeMonThanks14::
	.string "Oh… Okay!\n"
	.string "I'll do my best with one {STR_VAR_1}.\p"
	.string "I hope I can do my best without getting\n"
	.string "flustered.\p"
	.string "Thank you, {PLAYER}{KUN}. If we meet again, I\n"
	.string "hope you'll be just as helpful.$"

gText_ApprenticeWhichMon15::
	.string "Hm? You look like {PLAYER}{KUN}…\n"
	.string "But are you truly the real thing?\p"
	.string "No, no, if you are the real one, that's\n"
	.string "fine. Incidentally, I would like your\l"
	.string "advice.\p"
	.string "It concerns which POKéMON I should use.\p"
	.string "If the choices are the POKéMON {STR_VAR_1}\n"
	.string "and {STR_VAR_2}, which is more worthy of\l"
	.string "me?$"

gText_ApprenticeMonThanks15::
	.string "{STR_VAR_1}?\n"
	.string "Are you certain?\p"
	.string "I see. If so, that's fine.\n"
	.string "Thank you for your time.\p"
	.string "I do hope it's something even I can\n"
	.string "handle with aplomb.\p"
	.string "Let us meet again!$"

gText_ApprenticeWhichMove0::
	.string "Waaah! Oh, {PLAYER}!\n"
	.string "Sniff… Hiccup…\p"
	.string "I have a problem! I can't decide on a\n"
	.string "move for my {STR_VAR_1}…\p"
	.string "Please, please, {PLAYER}.\n"
	.string "Can you decide for me?\p"
	.string "For my {STR_VAR_1}, which move is the\n"
	.string "better choice: {STR_VAR_2} or {STR_VAR_3}?$"

gText_ApprenticeMoveThanks0::
	.string "{STR_VAR_1}?\n"
	.string "Waaaaah!\p"
	.string "Oh! I'm so sorry, {PLAYER}! You picked\n"
	.string "the move for me, and I'm so happy I'm\l"
	.string "crying…\p"
	.string "Sniff…\n"
	.string "Thank you so much!$"

gText_ApprenticeWhichMove1::
	.string "Yay! Hi, {PLAYER}!\n"
	.string "I need your advice again!\p"
	.string "I want to teach my {STR_VAR_1} a cool move.\p"
	.string "I like both {STR_VAR_2} and {STR_VAR_3}.\n"
	.string "Which do you recommend?$"

gText_ApprenticeMoveThanks1::
	.string "{STR_VAR_1} is better? I guess so!\n"
	.string "Okay, I'll go with that!\p"
	.string "If we meet here again, teach me\n"
	.string "something new, master!$"

gText_ApprenticeWhichMove2::
	.string "{PLAYER}, hello! It's about my {STR_VAR_1},\n"
	.string "and I'm worried about its moves.\p"
	.string "You see, it's {STR_VAR_2} and {STR_VAR_3}.\p"
	.string "Which is stronger and better for my\n"
	.string "{STR_VAR_1}?$"

gText_ApprenticeMoveThanks2::
	.string "{STR_VAR_1} is your choice?\n"
	.string "Okay, got it!\p"
	.string "I'll go teach {STR_VAR_1} to my POKéMON\n"
	.string "right away!\p"
	.string "See you again!$"

gText_ApprenticeWhichMove3::
	.string "Ohhh, {PLAYER}…\n"
	.string "I'm hopeless, really!\p"
	.string "I decided to raise a POKéMON, but now I\n"
	.string "can't even decide which move it should\l"
	.string "learn…\p"
	.string "I know it means nothing to you,\n"
	.string "{PLAYER}.\p"
	.string "But it means a lot to me…\p"
	.string "Please, {PLAYER}, could you choose a\n"
	.string "move for my {STR_VAR_1}?\p"
	.string "Even if you just chose between {STR_VAR_2}\n"
	.string "and {STR_VAR_3}…$"

gText_ApprenticeMoveThanks3::
	.string "I understand!\p"
	.string "But will it even be willing to learn\n"
	.string "{STR_VAR_1} for me… No! I'll do my best!\p"
	.string "Thank you!$"

gText_ApprenticeWhichMove4::
	.string "Oh, {PLAYER}{KUN}!\n"
	.string "I was hoping to see you, too!\p"
	.string "I've been wondering which move suits my\n"
	.string "{STR_VAR_1}.\p"
	.string "I can't decide, so can you decide for\n"
	.string "me?\p"
	.string "For instance… How about {STR_VAR_2} and\n"
	.string "{STR_VAR_3}? Which would be better?$"

gText_ApprenticeMoveThanks4::
	.string "{STR_VAR_1}? Great!\p"
	.string "Since you picked it, {PLAYER}{KUN}, I won't be\n"
	.string "so mad if I lose.\p"
	.string "Okay, I'll come to you for advice again.\n"
	.string "Later!$"

gText_ApprenticeWhichMove5::
	.string "How can things be this busy?\n"
	.string "Hey, if it isn't {PLAYER}{KUN}!\l"
	.string "How's it going?\p"
	.string "Since I got up this morning, I've done\n"
	.string "my jogging, swimming, and cooking!\p"
	.string "You wouldn't believe how busy I am!\p"
	.string "I can't even decide what move my\n"
	.string "{STR_VAR_1} should learn!\p"
	.string "{STR_VAR_2} looks good, huh?\n"
	.string "But {STR_VAR_3} is also decent.\p"
	.string "{PLAYER}{KUN}, give me some of your good\n"
	.string "advice! Which move would be good for\l"
	.string "me?$"

gText_ApprenticeMoveThanks5::
	.string "Okay, got it. I'll make room in my\n"
	.string "schedule and teach that move.\p"
	.string "I'm glad I found a good master in you.\n"
	.string "Thanks! See you around!$"

gText_ApprenticeWhichMove6::
	.string "Oh! Lucky!\n"
	.string "I met you again, {PLAYER}!\l"
	.string "I need to pick your brain again today.\p"
	.string "Drum roll, please!\n"
	.string "My question is…\p"
	.string "For my {STR_VAR_1}, which move is best\n"
	.string "suited, {STR_VAR_2} or {STR_VAR_3}?$"

gText_ApprenticeMoveThanks6::
	.string "Ahhh!\n"
	.string "{STR_VAR_1}, you say!\l"
	.string "Thanks for the super cool answer!\p"
	.string "I think that's all I wanted to ask\n"
	.string "today.\p"
	.string "Let's meet here again, okay?\n"
	.string "Thanks!$"

gText_ApprenticeWhichMove7::
	.string "Oh, hello, {PLAYER}.\n"
	.string "I trust you've been well?\p"
	.string "I must seek your advice again.\n"
	.string "It's about my dearest {STR_VAR_1}.\p"
	.string "What would be the ideal move for my\n"
	.string "lovable {STR_VAR_1}? {STR_VAR_2} or {STR_VAR_3}?$"

gText_ApprenticeMoveThanks7::
	.string "{STR_VAR_1} it is!\n"
	.string "I will teach it right away!\p"
	.string "Thank you, {PLAYER}.\n"
	.string "I hope I may count on you again.\l"
	.string "Please take care!$"

gText_ApprenticeWhichMove8::
	.string "Eek! {PLAYER}! I met you again!\n"
	.string "I… I'm overjoyed!\p"
	.string "Whenever I'm in need, you're always\n"
	.string "there for me, {PLAYER}!\p"
	.string "Today I want you to recommend a move\n"
	.string "for me!\p"
	.string "Please choose a move for my {STR_VAR_1}!\p"
	.string "Which move would be better, {STR_VAR_2} or\n"
	.string "{STR_VAR_3}?$"

gText_ApprenticeMoveThanks8::
	.string "Oh-oh-oh! Thank you!\n"
	.string "{STR_VAR_1} it is!\l"
	.string "Understood perfectly!\p"
	.string "Please teach me more some other time.$"

gText_ApprenticeWhichMove9::
	.string "Yo, {PLAYER}{KUN}, dude! I'm hoping for more\n"
	.string "of your wisdom today!\p"
	.string "What's the best move for my {STR_VAR_1}?\p"
	.string "Something that'll let me win, just like\n"
	.string "that!\p"
	.string "Would it be {STR_VAR_2}?\n"
	.string "Or {STR_VAR_3}?$"

gText_ApprenticeMoveThanks9::
	.string "Uh-huh, {STR_VAR_1} it is!\n"
	.string "Totally righteous!\l"
	.string "I'll get it taught, like, ka-blam!\p"
	.string "All right, thanks as always!\n"
	.string "Later, dude!$"

gText_ApprenticeWhichMove10::
	.string "{PLAYER}{KUN}, it's totally wild!\p"
	.string "My POKéMON!\n"
	.string "It learned six moves!\p"
	.string "Of course I'm lying!\n"
	.string "Wahahaha!\p"
	.string "This part's no lie, though. I'm bad at\n"
	.string "choosing moves for my POKéMON.\p"
	.string "So how about deciding which move I\n"
	.string "should teach?\p"
	.string "{STR_VAR_2} or {STR_VAR_3}--which would go\n"
	.string "best with my {STR_VAR_1}?$"

gText_ApprenticeMoveThanks10::
	.string "Okay, so it's {STR_VAR_1} you chose?\n"
	.string "I'll pick another move, then!\p"
	.string "Just kidding!\n"
	.string "I'll follow your teaching, master!\p"
	.string "Thanks, master!\n"
	.string "Please keep teaching me!$"

gText_ApprenticeWhichMove11::
	.string "A-H-O-Y!\n"
	.string "And that spells ahoy!\p"
	.string "The rappin' SAILOR am I! I'm always in\n"
	.string "the groove, so I'll ask you to approve!\p"
	.string "Today I've got a move question,\n"
	.string "I need your suggestion!\p"
	.string "{STR_VAR_2} and {STR_VAR_3} are the moves.\n"
	.string "What's best for my {STR_VAR_1} to groove?$"

gText_ApprenticeMoveThanks11::
	.string "{STR_VAR_1}, you say, hey, hey!\n"
	.string "I'll go teach it right away!\p"
	.string "If it's advice I ever need,\n"
	.string "{PLAYER}, your word I'll always heed!$"

gText_ApprenticeWhichMove12::
	.string "Oh, yeah, if it isn't {PLAYER}!\p"
	.string "What should I do? Ask your advice?\n"
	.string "Why not? I'm already talking to you!\p"
	.string "{PLAYER}, are you surprised by me?\n"
	.string "I want your advice, can't you see?\p"
	.string "Are you receiving me?\n"
	.string "You are receiving me!\p"
	.string "My {STR_VAR_1}--what should it use?\n"
	.string "It's {STR_VAR_2} or {STR_VAR_3},\l"
	.string "what do you choose?$"

gText_ApprenticeMoveThanks12::
	.string "If that {STR_VAR_1} is the best,\n"
	.string "I'll do as you suggest!\p"
	.string "Well, {PLAYER}, I've got to roam free,\n"
	.string "but don't you forget about me.\p"
	.string "See you again, my smart friend!$"

gText_ApprenticeWhichMove13::
	.string "Gahack! Gaah! Oh, {PLAYER}{KUN}…\n"
	.string "I've got this lousy cold…\p"
	.string "I want to pick a move for my POKéMON,\n"
	.string "but I'm not up to it…\p"
	.string "So, things being this way, I need you to\n"
	.string "decide for me.\p"
	.string "{PLAYER}{KUN}, if I had to choose between\n"
	.string "{STR_VAR_2} and {STR_VAR_3} for my {STR_VAR_1},\l"
	.string "which would it be?$"

gText_ApprenticeMoveThanks13::
	.string "Hm, {STR_VAR_1}, all right. Cough!\n"
	.string "I'll teach it when I feel better.\p"
	.string "I hope I can keep coming to you for help\n"
	.string "like this.$"

gText_ApprenticeWhichMove14::
	.string "Er… Um…\n"
	.string "{PLAYER}{KUN}…?\p"
	.string "Please, don't look at me like that.\n"
	.string "I'm getting flustered…\l"
	.string "I… I need your advice.\p"
	.string "I… I'm really embarrassed, but I can't\n"
	.string "decide which move I should teach my\l"
	.string "POKéMON.\p"
	.string "It's for my {STR_VAR_1}. If the choices\n"
	.string "were {STR_VAR_2} or {STR_VAR_3}, which would be\l"
	.string "better?$"

gText_ApprenticeMoveThanks14::
	.string "Oh… Okay!\n"
	.string "I'll try that {STR_VAR_1}.\p"
	.string "I hope I can teach it that move…\n"
	.string "This is so nerve-racking…\p"
	.string "Thank you, {PLAYER}{KUN}. If we meet again, I\n"
	.string "hope you'll be just as helpful.$"

gText_ApprenticeWhichMove15::
	.string "Hm? You look like {PLAYER}{KUN}…\n"
	.string "But are you truly the real thing?\p"
	.string "Perhaps you're one of those talented\n"
	.string "impersonators?\p"
	.string "No, no, if you are the real one, that's\n"
	.string "fine. No need to be upset, I assure you!\p"
	.string "Incidentally, I would like your advice.\p"
	.string "It's about my {STR_VAR_1}.\p"
	.string "Which move would be better for it to\n"
	.string "use, {STR_VAR_2} or {STR_VAR_3}?$"

gText_ApprenticeMoveThanks15::
	.string "{STR_VAR_1}?\n"
	.string "There's no doubt about it?\p"
	.string "I see. If so, that's fine.\n"
	.string "Thank you for your time.\p"
	.string "I do hope it's something even my\n"
	.string "POKéMON can learn.\p"
	.string "Let us meet again!$"

gText_ApprenticePickWinSpeech0::
	.string "Oh… {PLAYER}?\n"
	.string "It is {PLAYER}!\l"
	.string "Oh! Sniff…sob… Please, listen!\p"
	.string "I… When I battle, I get so nervous that\n"
	.string "I cry even when I win…\p"
	.string "I wish I could say something cool when I\n"
	.string "win…\p"
	.string "Please, please, {PLAYER}! Could you\n"
	.string "teach me something cool to say when I\l"
	.string "win, so I don't cry?$"

gText_ApprenticeWinSpeechThanks0::
	.string "{STR_VAR_1}\p"
	.string "Awesome! Amazing! Awoooh!\n"
	.string "It's so cool!\p"
	.string "Oh… I'm sorry…\n"
	.string "I'm so happy, I'm crying…\p"
	.string "Sniff… {PLAYER}!\n"
	.string "Thank you so much for everything!\p"
	.string "I'll fight my hardest for your sake,\n"
	.string "{PLAYER}!\p"
	.string "{PLAYER}…\n"
	.string "Next time… Let's battle!$"

gText_ApprenticePickWinSpeech1::
	.string "Yay! It's {PLAYER}! Hello!\n"
	.string "I wanted to ask you something!\p"
	.string "I want to say something cool when I win\n"
	.string "a match.\p"
	.string "Do you have a cool saying you could\n"
	.string "recommend?$"

gText_ApprenticeWinSpeechThanks1::
	.string "{STR_VAR_1}\p"
	.string "Oh, wow! That is so cool!\n"
	.string "Okay, I'll say that!\p"
	.string "Thanks for teaching me all this time!\n"
	.string "I'll do my very best wherever I go from\l"
	.string "now on!\p"
	.string "When we meet again, it'll be for a\n"
	.string "battle!$"

gText_ApprenticePickWinSpeech2::
	.string "{PLAYER}, hello!\p"
	.string "My POKéMON and I are ready for\n"
	.string "anything, except one thing.\p"
	.string "I think it'd be good to have something\n"
	.string "to shout when I win.\p"
	.string "Could you think of something good to\n"
	.string "say?$"

gText_ApprenticeWinSpeechThanks2::
	.string "{STR_VAR_1}\p"
	.string "…Cool!\n"
	.string "I'll use that!\p"
	.string "I'm going out to battle all over the\n"
	.string "place.\p"
	.string "Who knows, I might even get to battle\n"
	.string "you one day, {PLAYER}.\p"
	.string "Next time, let's meet at a place of\n"
	.string "battle!$"

gText_ApprenticePickWinSpeech3::
	.string "Hello, {PLAYER}…\n"
	.string "Sorry to bug you, but I'm hopeless…\p"
	.string "Even when… Even when I win, I have\n"
	.string "nothing special to say…\p"
	.string "I know it means nothing to you,\n"
	.string "{PLAYER}.\p"
	.string "But it means a lot to me…\p"
	.string "Please, {PLAYER}, what should I say if I\n"
	.string "win a battle?$"

gText_ApprenticeWinSpeechThanks3::
	.string "{STR_VAR_1}\p"
	.string "That's inspired…\p"
	.string "Uh… Is it okay for someone like me to\n"
	.string "even say that?\p"
	.string "No! I'll do my best!\p"
	.string "{PLAYER}, thank you so much for putting\n"
	.string "up with me for so long…\p"
	.string "I promise I'll do my best from now on.\p"
	.string "I'm sure you'll forget someone like me\n"
	.string "quickly, but let's meet somewhere again!$"

gText_ApprenticePickWinSpeech4::
	.string "Oh, {PLAYER}{KUN}.\n"
	.string "There's something I want you to hear.\p"
	.string "I know I don't always sound nice or\n"
	.string "polite…\p"
	.string "When I win a battle, I think I come\n"
	.string "across as arrogant.\p"
	.string "I don't want people to dislike me, so I\n"
	.string "want to say something nice to the one I\l"
	.string "beat.\p"
	.string "But I can't think of anything good!\n"
	.string "Could you think something up for me?$"

gText_ApprenticeWinSpeechThanks4::
	.string "{STR_VAR_1}\p"
	.string "Not bad!\n"
	.string "Yup, that's what I'll go with!\p"
	.string "I'm hitting the road to do what I can\n"
	.string "with what you taught me, in my head and\l"
	.string "in my heart.\p"
	.string "Sorry I've been so pushy with you!\p"
	.string "Next time, we battle, okay?\n"
	.string "See you!$"

gText_ApprenticePickWinSpeech5::
	.string "Oh, I can't get over how busy I am!\n"
	.string "Oh, hey, I was looking for you, {PLAYER}{KUN}.\p"
	.string "Are you well, as usual?\n"
	.string "Nothing has changed for me at all.\p"
	.string "I've got running, sparring, and mapping\n"
	.string "to do. Why am I so busy?\p"
	.string "But even when I'm busy, it'd be rude to\n"
	.string "just walk away from a win without a\l"
	.string "word.\p"
	.string "So what would be a cool saying to\n"
	.string "underline my coolness as I walk away?\l"
	.string "{PLAYER}{KUN}, help me!$"

gText_ApprenticeWinSpeechThanks5::
	.string "{STR_VAR_1}\p"
	.string "Okay, got it.\n"
	.string "I can find the time to say that!\p"
	.string "Honestly, I'm glad I met a good master\n"
	.string "like you.\p"
	.string "I'll make time somehow so I can get into\n"
	.string "battling.\p"
	.string "Thanks for everything, {PLAYER}{KUN}!\n"
	.string "We have to battle, you and me, one day!$"

gText_ApprenticePickWinSpeech6::
	.string "I lucked out again!\n"
	.string "{PLAYER}! Am I glad to see you!\l"
	.string "Like always, I need your advice!\p"
	.string "Drum roll, please!\n"
	.string "My last question is…\p"
	.string "If I win a battle and want to end it with\n"
	.string "a cool flourish, what should I say?$"

gText_ApprenticeWinSpeechThanks6::
	.string "{STR_VAR_1}\p"
	.string "That… That's fabulous!\n"
	.string "It's dignified and cool! I claim it!\p"
	.string "…Listen, I think I'm getting pretty\n"
	.string "good at this, huh?\p"
	.string "So I'm thinking of challenging other\n"
	.string "TRAINERS from now on.\p"
	.string "{PLAYER}, your advice really helped me.\p"
	.string "Maybe one day we'll battle!\p"
	.string "Thank you for everything!$"

gText_ApprenticePickWinSpeech7::
	.string "Oh, {PLAYER}.\n"
	.string "I'm so glad I met you!\p"
	.string "I no longer have any worries about my\n"
	.string "POKéMON.\p"
	.string "It's myself that worries me…\p"
	.string "You know how a TRAINER says a few\n"
	.string "words after winning a battle?\p"
	.string "I wish I could do that, too!\p"
	.string "Please, what should I say when I win a\n"
	.string "battle?$"

gText_ApprenticeWinSpeechThanks7::
	.string "{STR_VAR_1}\p"
	.string "Ah! That saying! It refreshes me and\n"
	.string "makes me feel reborn!\p"
	.string "I must use it right away!\p"
	.string "And now I must take my leave, {PLAYER}…\p"
	.string "I will go out and battle many others,\n"
	.string "but I'll never forget your teachings.\p"
	.string "Perhaps one day…\n"
	.string "Farewell!$"

gText_ApprenticePickWinSpeech8::
	.string "Eek! I spotted {PLAYER}!\n"
	.string "I… I'm overjoyed to see you!\p"
	.string "Oh-oh-oh! There's something I just had\n"
	.string "to ask you!\p"
	.string "A little while ago, I won a battle.\n"
	.string "That part was thrilling!\p"
	.string "But I was so overjoyed that I choked up\n"
	.string "and couldn't say a thing!\p"
	.string "So now, {PLAYER}, please, think up an\n"
	.string "exit line for me for when I win!$"

gText_ApprenticeWinSpeechThanks8::
	.string "{STR_VAR_1}\p"
	.string "Waaaaah!\n"
	.string "I'm going to say that?!\l"
	.string "I… I'm delirious with joy!\p"
	.string "Th-th-thank you!\n"
	.string "I have nothing left to regret now!\p"
	.string "I'm going to travel and battle all sorts\n"
	.string "of people.\p"
	.string "I owe everything to you, {PLAYER}.\n"
	.string "Really, really, thank you!\p"
	.string "I've got to go now, but let's meet in\n"
	.string "battle one day!$"

gText_ApprenticePickWinSpeech9::
	.string "Yo, dude!\n"
	.string "{PLAYER}{KUN}!\p"
	.string "You know, I'm itching to roam and battle\n"
	.string "wherever I can.\p"
	.string "But before I do, I want your advice one\n"
	.string "more time, please!\p"
	.string "If I win a battle, what would be a good\n"
	.string "boast to say to my fallen opponent?$"

gText_ApprenticeWinSpeechThanks9::
	.string "{STR_VAR_1}\p"
	.string "Uh-huh, that's sweet!\n"
	.string "Totally righteous!\l"
	.string "I'll try saying that, like, ham!\p"
	.string "And now it's time to say good-bye!\n"
	.string "Thanks for everything!\p"
	.string "Give me a battle one day, okay?\n"
	.string "Later, dude!$"

gText_ApprenticePickWinSpeech10::
	.string "{PLAYER}{KUN}, there's big trouble!\p"
	.string "When I win a battle, I brag about it for\n"
	.string "an hour at least!\p"
	.string "Of course I'm lying!\n"
	.string "Wahahaha!\p"
	.string "This part's no lie, though.\n"
	.string "I'm bad at chatting.\p"
	.string "So how about deciding what I should say\n"
	.string "after winning a battle, master?$"

gText_ApprenticeWinSpeechThanks10::
	.string "{STR_VAR_1}\p"
	.string "That's what I should say, huh?\n"
	.string "Then I'll stay away from that!\p"
	.string "Just kidding!\n"
	.string "I'll follow your teaching, master!\p"
	.string "Thanks for teaching me all this time,\n"
	.string "master!\p"
	.string "I'm finally starting to understand what\n"
	.string "being a TRAINER is about.\p"
	.string "I'm going to go out and win battles\n"
	.string "against any TRAINER.\p"
	.string "Maybe it'll be you one day, master!\p"
	.string "That's all!\n"
	.string "Farewell, my master!$"

gText_ApprenticePickWinSpeech11::
	.string "A-H-O-Y!\n"
	.string "And that spells ahoy!\p"
	.string "The rappin' SAILOR am I!\n"
	.string "This is my last question, don't cry!\p"
	.string "It's a saying question,\n"
	.string "I need your suggestion!\p"
	.string "If I win a match, what can I say\n"
	.string "in a real cool way?$"

gText_ApprenticeWinSpeechThanks11::
	.string "{STR_VAR_1}\p"
	.string "Perfect! That's what I'll use.\n"
	.string "I was right to make you choose!\p"
	.string "And now I think it's best\n"
	.string "if I fly the nest!\p"
	.string "Thanks for all you taught me.\n"
	.string "I'm off on a battle spree!\p"
	.string "B-O-N-V-O-Y-A-G-E!\n"
	.string "And that spells bon voyage,\l"
	.string "to you this is my homage!$"

gText_ApprenticePickWinSpeech12::
	.string "Oh, yeah, {PLAYER}!\n"
	.string "I found you again today!\p"
	.string "What should I do? Ask again?\n"
	.string "Why not? I'm already asking you!\p"
	.string "Anyways, {PLAYER}…\n"
	.string "Are you receiving me?\l"
	.string "You are receiving me!\l"
	.string "I need more advice from you!\p"
	.string "It's about what I should yell. Something\n"
	.string "cool to holler when a battle ends well.\p"
	.string "Come on, I wanna hear you say it!$"

gText_ApprenticeWinSpeechThanks12::
	.string "{STR_VAR_1}\p"
	.string "All right, all right!\n"
	.string "I'll use that because it's so tight!\p"
	.string "I'm out of things to ask you.\n"
	.string "Waving bye is all that's left to do.\p"
	.string "But maybe one day we'll meet, with one\n"
	.string "of us destined for defeat.\p"
	.string "But it really is time to say farewell.\p"
	.string "Well, {PLAYER}, I've got to roam free,\n"
	.string "but don't you forget about me!\p"
	.string "Take care, {PLAYER}!\n"
	.string "Love ya!$"

gText_ApprenticePickWinSpeech13::
	.string "{PLAYER}{KUN}, I'm finished…\n"
	.string "My nose won't stop dripping…\p"
	.string "I was trying to think of something cool\n"
	.string "to say when I win a battle.\p"
	.string "I got so inspired that I cried, and now\n"
	.string "my nose won't stop running…\p"
	.string "So, things being this way, I need you to\n"
	.string "decide for me, {PLAYER}{KUN}.\p"
	.string "When I win a battle,\n"
	.string "what should I say?$"

gText_ApprenticeWinSpeechThanks13::
	.string "{STR_VAR_1}\p"
	.string "… … …That's good.\n"
	.string "No, it's awe-inspiring!\l"
	.string "It's bringing fresh tears to my eyes!\p"
	.string "But in spite of my tears and runny nose,\n"
	.string "I'll use that saying!\p"
	.string "I'm plumb out of things to ask you,\n"
	.string "{PLAYER}{KUN}.\p"
	.string "From now on, we're rivals!\n"
	.string "Thanks for everything!$"

gText_ApprenticePickWinSpeech14::
	.string "Er… Um…\n"
	.string "{PLAYER}{KUN}…\p"
	.string "Please, don't look at me like that.\n"
	.string "It's making me nervous.\p"
	.string "I… I need your advice again.\n"
	.string "This will be my last, though…\p"
	.string "It's really embarrassing to ask, but\n"
	.string "what if I win a battle? What should I\l"
	.string "say?$"

gText_ApprenticeWinSpeechThanks14::
	.string "{STR_VAR_1}\p"
	.string "Oh… Okay!\n"
	.string "I'll try to say that!\l"
	.string "I might be too nervous to say it…\p"
	.string "Thank you, {PLAYER}{KUN}.\n"
	.string "I have to say good-bye now.\p"
	.string "I'll follow everything you taught me,\n"
	.string "{PLAYER}{KUN}, and do the best I can.$"

gText_ApprenticePickWinSpeech15::
	.string "Hm? You look like {PLAYER}{KUN}…\n"
	.string "But are you truly the real thing?\l"
	.string "Perhaps a clever {PLAYER} impersonator?\p"
	.string "Oh, no, no, no, don't worry! If you really\n"
	.string "are the real one, please forgive my\l"
	.string "rudeness.\p"
	.string "No need to be angry. All I wish for is\n"
	.string "more of your fine advice.\p"
	.string "It concerns a saying.\p"
	.string "More precisely, what should I say if I\n"
	.string "win a battle?$"

gText_ApprenticeWinSpeechThanks15::
	.string "{STR_VAR_1}\p"
	.string "… … … … … …\n"
	.string "When I win a match…\p"
	.string "{STR_VAR_1}\p"
	.string "…Are you serious?\p"
	.string "I see. If you are serious, that's fine.\n"
	.string "Thank you for your time.\p"
	.string "I do hope even I will be able to put that\n"
	.string "saying to good use.\p"
	.string "I seem to have run dry of questions.\p"
	.string "I believe it's high time I bid you\n"
	.string "farewell and strike out on my own.\p"
	.string "Thank you, my master!\n"
	.string "I apologize for my skepticism!$"
