BattleDome_Text_Potential1::
	.string "The top pick to take the title!$"

BattleDome_Text_Potential2::
	.string "A sure bet for the finals.$"

BattleDome_Text_Potential3::
	.string "Likely to reach the top three.$"

BattleDome_Text_Potential4::
	.string "A strong contender for first place.$"

BattleDome_Text_Potential5::
	.string "A team with true top-class power.$"

BattleDome_Text_Potential6::
	.string "This tournament's surprise fighters.$"

BattleDome_Text_Potential7::
	.string "A team with above-average power.$"

BattleDome_Text_Potential8::
	.string "The average team of this tournament.$"

BattleDome_Text_Potential9::
	.string "A team with ordinary power.$"

BattleDome_Text_Potential10::
	.string "A team a little below average.$"

BattleDome_Text_Potential11::
	.string "A team still hunting for its first win.$"

BattleDome_Text_Potential12::
	.string "One win would make this team proud.$"

BattleDome_Text_Potential13::
	.string "All in all, a weak team.$"

BattleDome_Text_Potential14::
	.string "A team with very little power.$"

BattleDome_Text_Potential15::
	.string "A team that is unlikely to win.$"

BattleDome_Text_Potential16::
	.string "The team least likely to win it all.$"

BattleDome_Text_PotentialDomeAceTucker::
	.string "The flawless, unbeatable superstar!$"

BattleDome_Text_StyleRiskDisaster::
	.string "Sometimes gambles on total disaster.$"

BattleDome_Text_StyleEndureLongBattles::
	.string "Has the stamina for long battles.$"

BattleDome_Text_StyleVariesTactics::
	.string "Changes tactics to suit the foe.$"

BattleDome_Text_StyleToughWinningPattern::
	.string "Has a hard-to-break winning pattern.$"

BattleDome_Text_StyleUsesVeryRareMove::
	.string "Now and then pulls out a very rare move.$"

BattleDome_Text_StyleUsesStartlingMoves::
	.string "Likes startling, disruptive moves.$"

BattleDome_Text_StyleConstantlyWatchesHP::
	.string "Never takes its eyes off its HP.$"

BattleDome_Text_StyleStoresAndLoosesPower::
	.string "Charges up power, then lets it all go.$"

BattleDome_Text_StyleEnfeeblesFoes::
	.string "Good at weakening its foes.$"

BattleDome_Text_StylePrefersLuckTactics::
	.string "Likes tactics that lean on luck.$"

BattleDome_Text_StyleRegalAtmosphere::
	.string "Fights with a royal air about it.$"

BattleDome_Text_StylePowerfulLowPPMoves::
	.string "Bets on powerful, low-PP moves.$"

BattleDome_Text_StyleEnfeebleThenAttack::
	.string "Weakens the foe first, then strikes.$"

BattleDome_Text_StyleBattlesWhileEnduring::
	.string "Takes every hit and keeps on fighting.$"

BattleDome_Text_StyleUpsetsFoesEmotionally::
	.string "Gets under the foe's skin.$"

BattleDome_Text_StyleStrongAndStraightforward::
	.string "Fights with strong, honest moves.$"

BattleDome_Text_StyleAggressivelyStrongMoves::
	.string "Charges in with strong moves.$"

BattleDome_Text_StyleCleverlyDodgesAttacks::
	.string "Fights by slipping past attacks.$"

BattleDome_Text_StyleUsesUpsettingMoves::
	.string "Good at rattling foes with attacks.$"

BattleDome_Text_StyleUsesPopularMoves::
	.string "Relies on many well-known moves.$"

BattleDome_Text_StyleHasPowerfulComboMoves::
	.string "Knows moves that chain into combos.$"

BattleDome_Text_StyleUsesHighProbabilityMoves::
	.string "Prefers attacks that rarely miss.$"

BattleDome_Text_StyleAggressivelySpectacularMoves::
	.string "Charges in with showy, flashy moves.$"

BattleDome_Text_StyleEmphasizesOffenseOverDefense::
	.string "Puts offense ahead of defense.$"

BattleDome_Text_StyleEmphasizesDefenseOverOffense::
	.string "Puts defense ahead of offense.$"

BattleDome_Text_StyleAttacksQuicklyStrongMoves::
	.string "Strikes fast with strong moves.$"

BattleDome_Text_StyleUsesAddedEffectMoves::
	.string "Often uses moves with extra effects.$"

BattleDome_Text_StyleUsesBalancedMixOfMoves::
	.string "Uses a nicely balanced mix of moves.$"

BattleDome_Text_StyleSampleMessage1::
	.string "This is sample message 1.$"

BattleDome_Text_StyleSampleMessage2::
	.string "This is sample message 2.$"

BattleDome_Text_StyleSampleMessage3::
	.string "This is sample message 3.$"

BattleDome_Text_StyleSampleMessage4::
	.string "This is sample message 4.$"

BattleDome_Text_EmphasizesHPAndAtk::
	.string "Trains hard in HP and ATTACK.$"

BattleDome_Text_EmphasizesHPAndDef::
	.string "Trains hard in HP and DEFENSE.$"

BattleDome_Text_EmphasizesHPAndSpeed::
	.string "Trains hard in HP and SPEED.$"

BattleDome_Text_EmphasizesHPAndSpAtk::
	.string "Trains hard in HP and SP. ATTACK.$"

BattleDome_Text_EmphasizesHPAndSpDef::
	.string "Trains hard in HP and SP. DEFENSE.$"

BattleDome_Text_EmphasizesAtkAndDef::
	.string "Trains hard in ATTACK and DEFENSE.$"

BattleDome_Text_EmphasizesAtkAndSpeed::
	.string "Trains hard in ATTACK and SPEED.$"

BattleDome_Text_EmphasizesAtkAndSpAtk::
	.string "Trains hard in ATTACK and SP. ATTACK.$"

BattleDome_Text_EmphasizesAtkAndSpDef::
	.string "Trains hard in ATTACK and SP. DEFENSE.$"

BattleDome_Text_EmphasizesDefAndSpeed::
	.string "Trains hard in DEFENSE and SPEED.$"

BattleDome_Text_EmphasizesDefAndSpAtk::
	.string "Trains hard in DEFENSE and SP. ATTACK.$"

BattleDome_Text_EmphasizesDefAndSpDef::
	.string "Trains hard in DEFENSE and SP. DEFENSE.$"

BattleDome_Text_EmphasizesSpeedAndSpAtk::
	.string "Trains hard in SPEED and SP. ATTACK.$"

BattleDome_Text_EmphasizesSpeedAndSpDef::
	.string "Trains hard in SPEED and SP. DEFENSE.$"

BattleDome_Text_EmphasizesSpAtkAndSpDef::
	.string "Trains SP. ATTACK and SP. DEFENSE.$"

BattleDome_Text_EmphasizesHP::
	.string "Trains hard in HP.$"

BattleDome_Text_EmphasizesAtk::
	.string "Trains hard in ATTACK.$"

BattleDome_Text_EmphasizesDef::
	.string "Trains hard in DEFENSE.$"

BattleDome_Text_EmphasizesSpeed::
	.string "Trains hard in SPEED.$"

BattleDome_Text_EmphasizesSpAtk::
	.string "Trains hard in SP. ATTACK.$"

BattleDome_Text_EmphasizesSpDef::
	.string "Trains hard in SP. DEFENSE.$"

BattleDome_Text_NeglectsHPAndAtk::
	.string "Skips training in HP and ATTACK.$"

BattleDome_Text_NeglectsHPAndDef::
	.string "Skips training in HP and DEFENSE.$"

BattleDome_Text_NeglectsHPAndSpeed::
	.string "Skips training in HP and SPEED.$"

BattleDome_Text_NeglectsHPAndSpAtk::
	.string "Skips training in HP and SP. ATTACK.$"

BattleDome_Text_NeglectsHPAndSpDef::
	.string "Skips training in HP and SP. DEFENSE.$"

BattleDome_Text_NeglectsAtkAndDef::
	.string "Skips training in ATTACK and DEFENSE.$"

BattleDome_Text_NeglectsAtkAndSpeed::
	.string "Skips training in ATTACK and SPEED.$"

BattleDome_Text_NeglectsAtkAndSpAtk::
	.string "Skips training in ATTACK and SP. ATTACK.$"

BattleDome_Text_NeglectsAtkAndSpDef::
	.string "Skips ATTACK and SP. DEFENSE.$"

BattleDome_Text_NeglectsDefAndSpeed::
	.string "Skips training in DEFENSE and SPEED.$"

BattleDome_Text_NeglectsDefAndSpAtk::
	.string "Skips DEFENSE and SP. ATTACK.$"

BattleDome_Text_NeglectsDefAndSpDef::
	.string "Skips DEFENSE and SP. DEFENSE.$"

BattleDome_Text_NeglectsSpeedAndSpAtk::
	.string "Skips training in SPEED and SP. ATTACK.$"

BattleDome_Text_NeglectsSpeedAndSpDef::
	.string "Skips training in SPEED and SP. DEFENSE.$"

BattleDome_Text_NeglectsSpAtkAndSpDef::
	.string "Skips SP. ATTACK and SP. DEFENSE.$"

BattleDome_Text_NeglectsHP::
	.string "Skips training in HP.$"

BattleDome_Text_NeglectsAtk::
	.string "Skips training in ATTACK.$"

BattleDome_Text_NeglectsDef::
	.string "Skips training in DEFENSE.$"

BattleDome_Text_NeglectsSpeed::
	.string "Skips training in SPEED.$"

BattleDome_Text_NeglectsSpAtk::
	.string "Skips training in SP. ATTACK.$"

BattleDome_Text_NeglectsSpDef::
	.string "Skips training in SP. DEFENSE.$"

BattleDome_Text_RaisesMonsWellBalanced::
	.string "Trains POKéMON in a balanced way.$"

BattleDome_Text_LetTheBattleBegin::
	.string "Let the battle begin!$"

BattleDome_Text_TrainerWonUsingMove::
	.string "{STR_VAR_1} wins with {STR_VAR_2}!$"

BattleDome_Text_TrainerBecameChamp::
	.string "{STR_VAR_1} is the new champ!$"

BattleDome_Text_TrainerWonByDefault::
	.string "{STR_VAR_1} wins by default!$"

BattleDome_Text_TrainerWonOutrightByDefault::
	.string "{STR_VAR_1} wins outright by default!$"

BattleDome_Text_TrainerWonNoMoves::
	.string "{STR_VAR_1} wins without using a move!$"

BattleDome_Text_TrainerWonOutrightNoMoves::
	.string "{STR_VAR_1} wins outright with no moves!$"

BattleDome_Text_Round1Match1::
	.string "Round 1, Match 1$"

BattleDome_Text_Round1Match2::
	.string "Round 1, Match 2$"

BattleDome_Text_Round1Match3::
	.string "Round 1, Match 3$"

BattleDome_Text_Round1Match4::
	.string "Round 1, Match 4$"

BattleDome_Text_Round1Match5::
	.string "Round 1, Match 5$"

BattleDome_Text_Round1Match6::
	.string "Round 1, Match 6$"

BattleDome_Text_Round1Match7::
	.string "Round 1, Match 7$"

BattleDome_Text_Round1Match8::
	.string "Round 1, Match 8$"

BattleDome_Text_Round2Match1::
	.string "Round 2, Match 1$"

BattleDome_Text_Round2Match2::
	.string "Round 2, Match 2$"

BattleDome_Text_Round2Match3::
	.string "Round 2, Match 3$"

BattleDome_Text_Round2Match4::
	.string "Round 2, Match 4$"

BattleDome_Text_SemifinalMatch1::
	.string "Semifinal, Match 1$"

BattleDome_Text_SemifinalMatch2::
	.string "Semifinal, Match 2$"

BattleDome_Text_FinalMatch::
	.string "The Final Match$"
