PetalburgCity_Gym_Text_GiveEnigmaBerry:
	.string "KRILLIN: Hey, {PLAYER}!\p"
	.string "A friend just sent me a really rare\n"
	.string "BERRY. I thought of you right away.\l"
	.string "Take it!$"

Route104_Text_PlantBerriesInSoilTakeThis:
	.string "If you see BERRIES growing in loamy\n"
	.string "soil, feel free to take them.\p"
	.string "But make sure you plant a BERRY in the\n"
	.string "same spot. That's common courtesy.\p"
	.string "Here, I'll share this with you.$"

Route104_Text_TrainersOftenMakeMonHoldBerries:
	.string "The way you carry yourself, you must be\n"
	.string "a TRAINER, no?\p"
	.string "TRAINERS often make POKéMON hold\n"
	.string "BERRIES.\p"
	.string "It's up to you whether to grow BERRIES\n"
	.string "or use them.$"

Route111_Text_WateredPlantsEveryDayTakeBerry:
	.string "I watered the plants every day. They\n"
	.string "grew lots of flowers.\p"
	.string "And they gave me lots of BERRIES, too.\p"
	.string "Here you go! You can have it!$"

Route111_Text_GoingToTryToMakeDifferentColorBerries:
	.string "I'm going to try really hard to make\n"
	.string "BERRIES in different colors.\p"
	.string "I hope you train hard, too!$"

Route111_Text_WhatColorBerriesToLookForToday:
	.string "I wonder what color BERRIES I'll find\n"
	.string "today?$"

Route114_Text_LoveUsingBerryCrushShareBerry:
	.string "I love using the BERRY CRUSH machine,\n"
	.string "so I'm collecting BERRIES.\p"
	.string "I'll share one with you, if you'd like.$"

Route114_Text_TryBerryCrushWithFriends:
	.string "You should try the BERRY CRUSH machine\n"
	.string "with your friends.$"

Route114_Text_FunToThinkAboutBerries:
	.string "Which BERRY should be planted? Should\n"
	.string "you use them or hoard them?\p"
	.string "It's fun to think about.$"

Route120_Text_BerriesExpressionOfLoveIsntIt:
	.string "BERRIES grow by soaking up sunlight.\p"
	.string "We help them grow by watering them\n"
	.string "regularly.\p"
	.string "It's an expression of love, isn't it?$"

Route120_Text_YesYouUnderstand:
	.string "Yes, yes.\p"
	.string "You understand what I mean.\p"
	.string "You should take this.$"

Route120_Text_MakeYourOwnImpressions:
	.string "Oh… But it is important to form your own\n"
	.string "impressions, I suppose…\p"
	.string "You can have this.$"

Route120_Text_BerryIsRareRaiseItWithCare:
	.string "I think that BERRY is rare.\p"
	.string "I hope you raise it with loving care.$"

Route120_Text_IllGetMoreBerriesFromBerryMaster:
	.string "I'll get more BERRIES from the BERRY\n"
	.string "MASTER.$"

LilycoveCity_Text_BerrySuitsYou:
	.string "When it gets right down to it…\p"
	.string "The same way a gi suits a fighter, a\n"
	.string "crisp breeze suits the sea.\p"
	.string "And you, a BERRY suits you to a “T”…\p"
	.string "Why should that be so?$"

LilycoveCity_Text_BecauseYoureTrainer:
	.string "When it gets right down to it…\p"
	.string "It's because you're a TRAINER!$"

LilycoveCity_Text_PokeblocksSuitPokemon:
	.string "When it gets right down to it…\p"
	.string "The way dignified simplicity suits me,\n"
	.string "{POKEBLOCK}S perfectly suit POKéMON.$"

Route123_BerryMastersHouse_Text_YoureDeservingOfBerry:
	.string "You may call me the BERRY MASTER.\p"
	.string "I dream of filling the world with\n"
	.string "beautiful flowers, so I raise BERRIES\l"
	.string "and hand them out to everyone.\p"
	.string "You're deserving of one!$"

Route123_BerryMastersHouse_Text_WhyBeStingyTakeAnother:
	.string "Why be stingy?\p"
	.string "Take another!$"

Route123_BerryMastersHouse_Text_VisitPrettyPetalFlowerShop:
	.string "Be sure to visit the PRETTY PETAL\n"
	.string "flower shop near RUSTBORO.\p"
	.string "Let flowers fill the world!$"

Route123_BerryMastersHouse_Text_DoneForToday:
	.string "I'm done for today.\p"
	.string "Come again another day.\p"
	.string "Let flowers fill the world!$"

Route123_BerryMastersHouse_Text_HeardAGoodSayingLately:
	.string "The way my husband grows BERRIES, oh,\n"
	.string "he's the best in the world.\p"
	.string "He makes me proud, that he does.\p"
	.string "Incidentally, child, have you heard a\n"
	.string "good saying lately?$"

Route123_BerryMastersHouse_Text_InspirationalTakeThis:
	.string "Ah! What a remarkable saying!\p"
	.string "Inspirational, it is!\p"
	.string "I want you to have this.$"

Route123_BerryMastersHouse_Text_GoodSayingTakeThis:
	.string "Oh! A good saying it is.\p"
	.string "You're quite remarkable.\p"
	.string "I want you to have this.$"

Route123_BerryMastersHouse_Text_JoyNeverGoesOutOfMyLife:
	.string "Our four grandchildren will surely grow\n"
	.string "stronger than my husband.\p"
	.string "Joy never goes out of my life!$"

Route123_BerryMastersHouse_Text_Ah:
	.string "Ah…$"

Route104_PrettyPetalFlowerShop_Text_ThisIsPrettyPetalFlowerShop:
	.string "Hello!\p"
	.string "This is the PRETTY PETAL flower shop.\p"
	.string "Spreading flowers all over the world!$"

Route104_PrettyPetalFlowerShop_Text_LearnAboutBerries:
	.string "{PLAYER}{KUN}, would you like to learn about\n"
	.string "BERRIES?$"

Route104_PrettyPetalFlowerShop_Text_IntroLearnAboutBerries:
	.string "Your name is?\p"
	.string "{PLAYER}{KUN}.\p"
	.string "What a strong, friendly name.\p"
	.string "{PLAYER}{KUN}, would you like to learn about\n"
	.string "BERRIES?$"

Route104_PrettyPetalFlowerShop_Text_BerriesExplanation:
	.string "BERRIES grow on trees that thrive only\n"
	.string "in soft, loamy soil.\p"
	.string "If you take some BERRIES, be sure to\n"
	.string "plant one in the loamy soil again.\p"
	.string "A planted BERRY will soon sprout, grow\n"
	.string "into a plant, flower beautifully, then\l"
	.string "grow BERRIES again.\p"
	.string "I want to see the whole wide world\n"
	.string "filled with beautiful flowers. That's my\l"
	.string "dream.\p"
	.string "Please help me, {PLAYER}{KUN}. Plant BERRIES\n"
	.string "and bring more flowers into the world.$"

Route104_PrettyPetalFlowerShop_Text_FlowersBringHappiness:
	.string "Flowers bring so much happiness to\n"
	.string "people, don't they?$"

Route104_PrettyPetalFlowerShop_Text_YouCanHaveThis:
	.string "Hello!\p"
	.string "The more attention you give to flowers,\n"
	.string "the more beautifully they bloom.\p"
	.string "You'll like tending flowers. I'm sure of\n"
	.string "it. You can have this.$"

Route104_PrettyPetalFlowerShop_Text_WailmerPailExplanation:
	.string "While BERRY plants are growing, water\n"
	.string "them with the WAILMER PAIL.\p"
	.string "Oh, another thing.\p"
	.string "If you don't pick BERRIES for a while,\n"
	.string "they'll drop off onto the ground. But\l"
	.string "they'll sprout again.\p"
	.string "Isn't that amazing?\p"
	.string "It's like they have a fighting spirit\n"
	.string "and a will to live.$"

Route104_PrettyPetalFlowerShop_Text_ImGrowingFlowers:
	.string "I'm trying to be like my big sisters. I'm\n"
	.string "growing flowers, too!\p"
	.string "Here you go!\p"
	.string "It's for you!$"

Route104_PrettyPetalFlowerShop_Text_MachineMixesBerries:
	.string "You can plant a BERRY and grow it big, or\n"
	.string "you can make a POKéMON hold it.\p"
	.string "But now they have a machine that mixes\n"
	.string "different BERRIES and makes candies\l"
	.string "for POKéMON.\p"
	.string "I want some candy, too.$"

SootopolisCity_Text_NameIsKiriHaveOneOfThese:
	.string "Hi, what's your name?\p"
	.string "… … …  … … …  … … …\n"
	.string "Okay. That's nice!\p"
	.string "My name is KIRI.\p"
	.string "My mommy and daddy named me that so I\n"
	.string "would grow up healthy and warmhearted.\l"
	.string "That's what they wished.\p"
	.string "You can have one of these.$"

SootopolisCity_Text_GiveYouThisBerryToo:
	.string "KIRI will give you this BERRY, too!\p"
	.string "I really like it lots!$"

SootopolisCity_Text_WhatKindOfWishInYourName:
	.string "I wonder what kind of wish is in your\n"
	.string "name.$"

SootopolisCity_Text_LikeSeasonBornIn:
	.string "Spring, summer, autumn, and winter.\p"
	.string "If you're born in springtime, do you like\n"
	.string "the spring, and if you're born in the\l"
	.string "summer, do you like the summer?$"

SootopolisCity_Text_ThenILoveAutumn:
	.string "Then KIRI was born in the autumn, so I\n"
	.string "love the autumn!\p"
	.string "Which season do you like?$"

SootopolisCity_Text_OhDoesntMatter:
	.string "Oh…\p"
	.string "It doesn't matter…\p"
	.string "There's so much I want to know…$"
