gText_Birch_Welcome::
	.string "Hohoho! Sorry to keep you waiting!\p"
	.string "Welcome to the world of POKéMON!\p"
	.string "My name is ROSHI.\p"
	.string "You may know me as the TURTLE HERMIT.\p"
	.string "These days, though, everyone calls me\n"
	.string "the POKéMON PROFESSOR.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "Behold! This is what we call a\n"
	.string "“POKéMON.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "This world is home to countless\n"
	.string "creatures called POKéMON.\p"
	.string "We humans live beside them, sometimes\n"
	.string "as close friends and training partners,\l"
	.string "and sometimes as faithful work mates.\p"
	.string "And sometimes, we test our strength\n"
	.string "against each other in battle.\p"
	.string "But for all our time together, we still\n"
	.string "don't understand POKéMON fully.\p"
	.string "There are many, many secrets still\n"
	.string "hidden inside them, just like the\l"
	.string "secrets of ki itself.\p"
	.string "To unravel those mysteries, I've been\n"
	.string "doing research in my old age.\l"
	.string "That's my life's work now.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "Now then, who might you be?$"

gText_Birch_BoyOrGirl::
	.string "Tell me, are you a boy?\n"
	.string "Or are you a girl?\p"
	.string "(Not that I'm hoping, ho ho!)$"

gText_Birch_WhatsYourName::
	.string "Good, good.\n"
	.string "So what's your name?$"

gText_Birch_SoItsPlayer::
	.string "Ah, so your name is {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ohoho, so you're {PLAYER}{KUN}, the one who\n"
	.string "moved into town next door!\l"
	.string "Now it all makes sense!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "Well then, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to begin.\p"
	.string "Summon your courage and leap into\n"
	.string "the world of POKéMON, where battles,\l"
	.string "training and true friends await!\p"
	.string "I'll be waiting for you.\n"
	.string "Come see me at my POKéMON LAB.\p"
	.string "$"
