BerryBlender_Text_BlendWithTheBlendMaster:
	.string "BLEND MASTER: Indeed I am!\n"
	.string "The BLEND MASTER am I!\p"
	.string "Blend with me, and witness the\n"
	.string "mastery I honed beneath mountain\l"
	.string "waterfalls!$"

BerryBlender_Text_SeeMyMasteryInAction:
	.string "BLEND MASTER: Hmmm! So, you wish to\n"
	.string "see my mastery in action?$"

BerryBlender_Text_TooBusyNowIsee:
	.string "Hmmm!\p"
	.string "So, you are too busy now, I see!\p"
	.string "But fear not!\n"
	.string "I shall be here all day!\l"
	.string "Hurry back from your errand!$"

BerryBlender_Text_BlendMasterNoBerries:
	.string "Hmmm!\p"
	.string "You haven't got a single BERRY!\p"
	.string "I shall be here all day!\n"
	.string "Hurry back with some BERRIES!$"

BerryBlender_Text_BlendMasterKnowHowToMakePokeblocks:
	.string "Of course!\n"
	.string "Of course!\p"
	.string "Incidentally…\n"
	.string "You do know how to blend {POKEBLOCK}S\l"
	.string "from BERRIES?$"

BerryBlender_Text_BlendMasterExplainBerryBlending:
	.string "Hmmm!\p"
	.string "Ah, but it is a simple process!\p"
	.string "When the BLENDER's arrow comes to\n"
	.string "your marker, press the A Button.\p"
	.string "That is all you must do.\p"
	.string "When you see how precisely I press\n"
	.string "the A Button, you will understand.\p"
	.string "Timing is everything, as any\n"
	.string "martial artist knows!$"

BerryBlender_Text_BlendMasterLetsBerryBlender:
	.string "Fine!\p"
	.string "Let's get started, then!\p"
	.string "All together with the BLEND MASTER,\n"
	.string "let's BERRY BLENDER!$"

BerryBlender_Text_BlendMasterNoPokeblockCase:
	.string "Hmmm!\p"
	.string "You do not appear to have the\n"
	.string "{POKEBLOCK} CASE!\p"
	.string "I shall be here all day! Obtain the\n"
	.string "{POKEBLOCK} CASE and hurry back!$"

BerryBlender_Text_BlendMasterPokeblockCaseFull:
	.string "Hmmm!\p"
	.string "Your {POKEBLOCK} CASE appears to be full!\p"
	.string "I shall be here all day!\n"
	.string "Use some {POKEBLOCK}S and hurry back!$"

BerryBlender_Text_WhoaAwesome:
	.string "Whoa!\n"
	.string "His power level is off the charts!$"

BerryBlender_Text_WickedlyFast:
	.string "Faster than the eye can see!$"

BerryBlender_Text_WhatAnExpert:
	.string "What a true master!$"

BerryBlender_Text_MadeAmazingPokeblocksWithMaster:
	.string "When I blended with the MASTER,\n"
	.string "we made amazing {POKEBLOCK}S!$"

BerryBlender_Text_QualitiesOfBlendMaster:
	.string "Eyes that track the arrow with\n"
	.string "the focus of a trained fighter…\p"
	.string "A hand that taps the A Button\n"
	.string "with clockwork precision…\p"
	.string "Those are the qualities that make\n"
	.string "the BLEND MASTER truly great.$"

BerryBlender_Text_MasterWorksOnSkillsInMountains:
	.string "The BLEND MASTER is said to train\n"
	.string "his skills deep in the mountains,\l"
	.string "the way a true martial artist would.\p"
	.string "Sometimes he comes to LILYCOVE\n"
	.string "to blend BERRIES all day long.$"
