CableClub_Text_WelcomeWhichCableClubService:
	.string "Welcome to the POKéMON CABLE\n"
	.string "CLUB!\p"
	.string "Which of our services would you\n"
	.string "like to use?$"

CableClub_Text_WhichService:
	.string "Which of our services would you\n"
	.string "like to use?$"

CableClub_Text_TradeUsingLinkCable::
	.string "Trade POKéMON with another player\n"
	.string "over a GBA Game Link cable.$"

CableClub_Text_BattleUsingLinkCable::
	.string "Throw down with another TRAINER\n"
	.string "over a GBA Game Link cable.$"

CableClub_Text_RecordCornerUsingLinkCable::
	.string "Use the RECORD CORNER with others\n"
	.string "over a GBA Game Link cable.$"

@ Unused
CableClub_Text_CloseThisMenu:
	.string "Close this menu.$"

CableClub_Text_NeedTwoMonsForDoubleBattle:
	.string "For a DOUBLE BATTLE, you need at\n"
	.string "least two POKéMON.$"

CableClub_Text_NeedTwoMonsToTrade:
	.string "To trade, you need at least two\n"
	.string "POKéMON with you.$"

CableClub_Text_CantTradeEnigmaBerry:
	.string "A POKéMON holding the {STR_VAR_1}\n"
	.string "BERRY can't be traded.$"

gText_PleaseWaitForLink::
	.string "Please wait.\n"
	.string "… … B Button: Cancel$"

gText_ConfirmLinkWhenPlayersReady::
	.string "When all players are ready…\n"
	.string "A Button: Confirm\l"
	.string "B Button: Cancel$"

gText_ConfirmStartLinkWithXPlayers::
	.string "Start link with {STR_VAR_1} players.\n"
	.string "A Button: Confirm\l"
	.string "B Button: Cancel$"

gText_AwaitingLinkup::
	.string "Awaiting linkup…\n"
	.string "… … B Button: Cancel$"

@ Unused
CableClub_Text_OkayToSaveProgress::
	.string "Your progress has to be saved\n"
	.string "before linking. Okay to save?$"

CableClub_Text_PleaseEnter:
	.string "Please go on in.$"

CableClub_Text_DirectYouToYourRoom:
	.string "I'll show you to your room now.$"

Text_SomeoneIsNotReadyToLink:
	.string "Someone isn't ready to link.\p"
	.string "Please come back once everyone\n"
	.string "has gotten ready.$"

Text_LinkErrorPleaseReset:
	.string "Sorry, there's a link error…\n"
	.string "Please reset and try again.$"

Text_PlayersMadeDifferentSelections:
	.string "Your link partners seem to have\n"
	.string "made different selections.$"

CableClub_Text_PleaseVisitAgain:
	.string "Please come visit again.$"

CableClub_Text_IncorrectNumberOfParticipants:
	.string "The number of participants isn't\n"
	.string "correct.$"

CableClub_Text_CantSingleBattleWithXPlayers:
	.string "SINGLE BATTLE Mode can't be\n"
	.string "played by {STR_VAR_1} players.$"

CableClub_Text_CantDoubleBattleWithXPlayers:
	.string "DOUBLE BATTLE Mode can't be\n"
	.string "played by {STR_VAR_1} players.$"

CableClub_Text_NeedFourPlayers:
	.string "You need four players to play\n"
	.string "this Battle Mode.$"

CableClub_Text_PleaseConfirmNumberAndRestart:
	.string "Please check the number of\n"
	.string "players and start again.$"

Text_TerminateLinkConfirmation:
	.string "The link will end if you leave\n"
	.string "the room. Is that okay?$"

Text_TerminateLinkPleaseWait:
	.string "Ending the link…\n"
	.string "You will be escorted out of\l"
	.string "the room. Please wait.$"

CableClub_Text_TooBusyToNotice:
	.string "This TRAINER is too busy to\n"
	.string "notice you…$"

CableClub_Text_GotToLookAtTrainerCard:
	.string "Score! You got a look at\n"
	.string "{STR_VAR_1}'s TRAINER CARD!$"

CableClub_Text_GotToLookAtColoredTrainerCard:
	.string "Score! You got a look at\n"
	.string "{STR_VAR_1}'s TRAINER CARD!\p"
	.string "It's a {STR_VAR_2} card!$"

BattleColosseum_2P_Text_TakePlaceStartBattle:
	.string "Please take your place and start\n"
	.string "your battle.$"

TradeCenter_Text_TakeSeatStartTrade:
	.string "Please take your seat and start\n"
	.string "your trade.$"

RecordCorner_Text_ThanksForComing:
	.string "Thanks for coming.$"

CableClub_Text_TrainerCardDataOverwritten:
	.string "The TRAINER CARD data will\n"
	.string "be overwritten.$"

CableClub_Text_HopeToSeeYouAgain:
	.string "Hope to see you again!$"

CableClub_Text_NotSetUpForFarAwayRegion:
	.string "I'm awfully sorry.\p"
	.string "We aren't set up to trade with\n"
	.string "TRAINERS in far-off regions yet…$"

CableClub_Text_OtherTrainerNotReady:
	.string "The other TRAINER isn't ready.$"

CableClub_Text_YouHaveAMonThatCantBeTaken:
	.string "You have at least one POKéMON\n"
	.string "that can't be taken along.$"

RecordCorner_Text_TakeSeatAndWait:
	.string "Please take your seat and wait.$"

RecordCorner_Text_PlayerSentOverOneX:
	.string "{STR_VAR_1} sent over one\n"
	.string "{STR_VAR_2}.$"

CableClub_Text_CantMixWithJapaneseGame:
	.string "Sorry, there's a transmission error.\p"
	.string "You can't mix records with  \n"
	.string "Japanese Ruby or Sapphire games.\p"
	.string "Also, you can't mix records with\n"
	.string "Japanese Emerald and overseas Ruby\l"
	.string "or Sapphire games at the same time.$"

CableClub_Text_AdapterNotConnected:
	.string "The Wireless Adapter isn't\n"
	.string "connected properly.$"

CableClub_Text_ParticipantsStepUpToCounter:
	.string "Participants, please step up\n"
	.string "to the reception counter.$"

@ Unused
CableClub_Text_Hello:
	.string "Hello!$"

@ Unused
CableClub_Text_PleaseWait:
	.string "Please wait.$"

CableClub_Text_YouMayTradeHere::
	.string "Trade your POKéMON here with\n"
	.string "another TRAINER.$"

CableClub_Text_YouMayBattleHere::
	.string "Battle your friends here.\n"
	.string "Show them your power!$"

CableClub_Text_CanMakeBerryPowder::
	.string "Two to five TRAINERS can make\n"
	.string "BERRY POWDER together.$"

CableClub_Text_CanMixRecords::
	.string "The records of two to four players\n"
	.string "can be mixed together.$"

@ Unused
CableClub_Text_GuideToVariousServices:
	.string "A guide to the WIRELESS CLUB's\n"
	.string "many services.$"

CableClub_Text_CancelSelectedItem::
	.string "Cancels the selected MENU item.$"

@ Unused
CableClub_Text_WhichBattleMode:
	.string "Which battle mode do you want?$"

@ Unused
CableClub_Text_ReturnsToPreviousStep:
	.string "Goes back to the previous step.$"

CableClub_Text_NeedBerryForBerryCrush:
	.string "To use the BERRY CRUSH service,\n"
	.string "you need at least one BERRY.$"

CableClub_Text_NeedTwoMonsForUnionRoom:
	.string "To enter the UNION ROOM, you need\n"
	.string "at least two POKéMON.$"

CableClub_Text_NoEnigmaBerryInUnionRoom:
	.string "No POKéMON holding the {STR_VAR_1}\n"
	.string "BERRY may enter the UNION ROOM.$"

CableClub_Text_UnionRoomAdapterNotConnected:
	.string "This is the POKéMON WIRELESS CLUB\n"
	.string "UNION ROOM.\p"
	.string "Unfortunately, your Wireless\n"
	.string "Adapter isn't connected properly.\p"
	.string "Please come again.$"

@ Unused
CableClub_Text_OhExcuseMe:
	.string "Oh…\n"
	.string "Excuse me!$"

CableClub_Text_PlayerIsWaiting:
	.string "Looks like {STR_VAR_1} is playing\n"
	.string "right now.\l"
	.string "Go for it!$"

MossdeepCity_GameCorner_1F_Text_DescribeWhichGame:
	.string "I can explain the game rules\n"
	.string "to you, if you like.\p"
	.string "Which game should I describe?$"

MossdeepCity_GameCorner_1F_Text_PokemonJumpInfo:
	.string "“POKéMON JUMP”\p"
	.string "Make your POKéMON skip the VINE WHIP\n"
	.string "rope with the A Button.\p"
	.string "Only mini POKéMON around 28 inches\n"
	.string "or less may take part.\p"
	.string "POKéMON that only swim, burrow,\n"
	.string "or fly aren't good at jumping.\p"
	.string "So those POKéMON can't\n"
	.string "take part.\p"
	.string "Good things happen if everyone\n"
	.string "jumps in time.$"

MossdeepCity_GameCorner_1F_Text_DodrioBerryPickingInfo:
	.string "“DODRIO BERRY-PICKING”\p"
	.string "Command DODRIO's three heads to\n"
	.string "catch the falling BERRIES.\p"
	.string "Press right, up, or left on the\n"
	.string "{PLUS} Control Pad to move the heads.\p"
	.string "To play this game, you need\n"
	.string "a DODRIO.$"

MossdeepCity_GameCorner_1F_Text_TalkToOldManToPlay:
	.string "If you want to play a game,\n"
	.string "talk to the old man next to me.$"

MossdeepCity_GameCorner_1F_Text_WelcomeCanYouWait:
	.string "Hi, welcome!\n"
	.string "Are you here to play games over\l"
	.string "Wireless Communication?\p"
	.string "Can you wait just a little bit?$"

MossdeepCity_GameCorner_1F_Text_ComeAgain:
	.string "All right, come again!$"

MossdeepCity_GameCorner_1F_Text_AdapterNotConnected:
	.string "The Wireless Adapter isn't connected.\n"
	.string "Come back when it's hooked up!$"

MossdeepCity_GameCorner_1F_Text_PlayWhichGame:
	.string "All right, which game do you want\n"
	.string "to play?$"

MossdeepCity_GameCorner_1F_Text_EnterWhichPokemon:
	.string "Which POKéMON do you want to\n"
	.string "enter?$"

MossdeepCity_GameCorner_1F_Text_AllGoodToGo:
	.string "Okay, you're all set.\n"
	.string "Don't let the others beat you!$"

@ Unused
MossdeepCity_GameCorner_1F_Text_LeavingDoComeAgain:
	.string "Are you leaving already?\n"
	.string "Do come again!$"

MossdeepCity_GameCorner_1F_Text_ExplainRequiredMon:
	.string "Looks like you don't have any\n"
	.string "POKéMON that can enter…\p"
	.string "Want me to explain which kinds\n"
	.string "of POKéMON can enter?$"

MossdeepCity_GameCorner_1F_Text_ShortJumpingPokemonAllowed:
	.string "“POKéMON JUMP” is open to POKéMON\n"
	.string "around 28 inches or less.\p"
	.string "The ones that can't enter are the\n"
	.string "POKéMON that can't jump.\p"
	.string "You know, POKéMON that only\n"
	.string "swim, burrow, or fly.\p"
	.string "That's all you need to know.$"

MossdeepCity_GameCorner_1F_Text_OnlyDodrioAllowed:
	.string "DODRIO BERRY-PICKING is a game that \n"
	.string "only a DODRIO may enter.$"

@ Unused
MossdeepCity_GameCorner_1F_Text_RetryPlease:
	.string "Could you start over from the\n"
	.string "beginning, please?$"

CableClub_Text_WelcomeWhichDirectCornerRoom:
	.string "Welcome to the POKéMON WIRELESS\n"
	.string "CLUB DIRECT CORNER.\p"
	.string "You can interact directly with\n"
	.string "your friends here.\p"
	.string "Which room would you like to\n"
	.string "enter?$"

CableClub_Text_TradePokemon:
	.string "Want to trade POKéMON?$"

CableClub_Text_PlayWhichBattleMode:
	.string "Which Battle Mode do you want\n"
	.string "to play?$"

CableClub_Text_AccessRecordCorner:
	.string "Want to access\n"
	.string "the RECORD CORNER?$"

CableClub_Text_UseBerryCrush:
	.string "Want to use the\n"
	.string "BERRY CRUSH System?$"

CableClub_Text_ExplainBattleModes:
	.string "There are three Battle Modes.\p"
	.string "SINGLE BATTLE is for two TRAINERS\n"
	.string "with one or more POKéMON each.\p"
	.string "Each TRAINER fights with one POKéMON\n"
	.string "at a time.\p"
	.string "DOUBLE BATTLE is for two TRAINERS\n"
	.string "with two or more POKéMON each.\p"
	.string "Each TRAINER sends out two\n"
	.string "POKéMON at a time.\p"
	.string "MULTI BATTLE is for four TRAINERS\n"
	.string "with one or more POKéMON each.\p"
	.string "Each TRAINER fights with one POKéMON\n"
	.string "at a time.$"

CableClub_Text_ChooseGroupLeaderOfTwo:
	.string "Please decide which of you two\n"
	.string "will be the LEADER.\p"
	.string "The other player must then choose\n"
	.string "“JOIN GROUP.”$"

CableClub_Text_ChooseGroupLeaderOfFour:
	.string "Please decide which of you four\n"
	.string "will be the GROUP LEADER.\p"
	.string "The other players must then choose\n"
	.string "“JOIN GROUP.”$"

CableClub_Text_ChooseGroupLeader:
	.string "Please decide which of you will\n"
	.string "be the GROUP LEADER.\p"
	.string "The other players must then choose\n"
	.string "“JOIN GROUP.”$"

CableClub_Text_WelcomeUnionRoomEnter:
	.string "Welcome to the POKéMON WIRELESS\n"
	.string "CLUB UNION ROOM.\p"
	.string "You can interact directly with\n"
	.string "other TRAINERS here, even some\l"
	.string "you've never met.\p"
	.string "Would you like to enter the ROOM?$"

CableClub_Text_UnionRoomInfo:
	.string "The TRAINERS in the UNION ROOM\n"
	.string "are the players around you who\l"
	.string "have also entered the ROOM.\p"
	.string "You can do all sorts of things\n"
	.string "here, like trading greetings.\p"
	.string "You can enter two POKéMON up to\n"
	.string "Lv. 30 in a one-on-one battle.\p"
	.string "You can join a chat with\n"
	.string "two to five people.\p"
	.string "Or you can register a POKéMON for\n"
	.string "trade.\p"
	.string "Would you like to enter the ROOM?$"

CableClub_Text_EnjoyUnionRoom:
	.string "I hope you enjoy your time in\n"
	.string "the UNION ROOM.$"

CableClub_Text_FirstTimeRightThisWay:
	.string "Hello!\n"
	.string "My name is TEALA.\p"
	.string "This must be your first time\n"
	.string "up here.\p"
	.string "I'll show you how the Wireless\n"
	.string "Communication System works.\p"
	.string "First, let me show you around this\n"
	.string "floor of our POKéMON CENTER.\p"
	.string "Right this way, please.$"

CableClub_Text_ExplainWirelessClubFirstTime:
	.string "The top floor has two rooms.\p"
	.string "First, the room on the left.\n"
	.string "That's the UNION ROOM.\p"
	.string "You can link up with TRAINERS\n"
	.string "around you who have also entered\l"
	.string "the UNION ROOM.\p"
	.string "With them, you can chat, battle,\n"
	.string "and trade.\p"
	.string "Second, the room on the right is\n"
	.string "the DIRECT CORNER.\p"
	.string "You can trade or battle POKéMON\n"
	.string "with your friends in that room.\p"
	.string "If the Wireless Adapter isn't\n"
	.string "connected, you can still link up\l"
	.string "with a GBA Game Link cable.\p"
	.string "If so, you have to go\n"
	.string "to the DIRECT CORNER.\p"
	.string "I hope you enjoy the Wireless \n"
	.string "Communication System.$"

CableClub_Text_AskAboutLinking:
	.string "Hello, {PLAYER}!\p"
	.string "It's me, TEALA, the POKéMON\n"
	.string "CENTER 2F attendant.\p"
	.string "Is there something you wanted to\n"
	.string "ask me about linking?$"

CableClub_Text_ExplainWirelessClub:
	.string "Let me explain how the POKéMON\n"
	.string "WIRELESS CLUB works.\p"
	.string "The top floor has two rooms.\p"
	.string "First, the room on the left.\n"
	.string "That's the UNION ROOM.\p"
	.string "You can link up with TRAINERS\n"
	.string "around you who have also entered\l"
	.string "the UNION ROOM.\p"
	.string "With them, you can chat, battle,\n"
	.string "and trade.\p"
	.string "Second, the room on the right is\n"
	.string "the DIRECT CORNER.\p"
	.string "You can trade or battle POKéMON\n"
	.string "with your friends in that room.\p"
	.string "Sometimes you might not be able to\n"
	.string "find your friends in the UNION ROOM\l"
	.string "or the DIRECT CORNER.\p"
	.string "If that happens, try moving closer\n"
	.string "to your friends.\p"
	.string "If the Wireless Adapter isn't\n"
	.string "connected, you can still link up\l"
	.string "with a GBA Game Link cable.\p"
	.string "If so, you have to go\n"
	.string "to the DIRECT CORNER.\p"
	.string "I hope you enjoy the Wireless \n"
	.string "Communication System.$"

CableClub_Text_HopeYouEnjoyWirelessSystem:
	.string "I hope you enjoy the Wireless\n"
	.string "Communication System.$"
