Text_PictureBookShelf:
	.string "A set of POKéMON picture books.\n"
	.string "Looks like a kids' collection.$"

Text_BookShelf:
	.string "The shelf is packed with all kinds\n"
	.string "of books.$"

Text_PokemonCenterBookShelf:
	.string "POKéMON magazines!\n"
	.string "POKéMON PAL…\p"
	.string "POKéMON HANDBOOK…\n"
	.string "ADORABLE POKéMON…$"

Text_Vase:
	.string "This vase looks expensive…\n"
	.string "You peeked inside…\p"
	.string "But it was empty.$"

Text_EmptyTrashCan:
	.string "It's empty.$"

Text_ShopShelf:
	.string "The shelves are stacked with all\n"
	.string "kinds of POKéMON merchandise.$"

Text_Blueprint:
	.string "Is this a blueprint? It's way too\n"
	.string "complicated, even for BULMA!$"
