@ Contest move effect descriptions

gText_HighlyAppealingMove::
	.string "A move with huge appeal.$"

gText_UserMoreEasilyStartled::
	.string "Afterward, the user gets\n"
	.string "spooked more easily.$"

gText_GreatAppealButNoMoreToEnd::
	.string "A great appeal, but the user\n"
	.string "can't appeal again after it.$"

gText_UsedRepeatedlyWithoutBoringJudge::
	.string "Can be used over and over\n"
	.string "without boring the JUDGE.$"

gText_AvoidStartledByOthersOnce::
	.string "Dodges being startled by\n"
	.string "others one time.$"

gText_AvoidStartledByOthers::
	.string "Dodges being startled\n"
	.string "by others.$"

gText_AvoidStartledByOthersLittle::
	.string "Dodges being startled by\n"
	.string "others a little.$"

gText_UserLessLikelyStartled::
	.string "Afterward, the user is less\n"
	.string "likely to get startled.$"

gText_SlightlyStartleFrontMon::
	.string "Gives the POKéMON in front\n"
	.string "a slight scare.$"

gText_SlightlyStartleAppealed::
	.string "Gives those that already\n"
	.string "appealed a slight scare.$"

gText_StartleAppealedBeforeUser::
	.string "Scares the POKéMON that\n"
	.string "appealed just before the user.$"

gText_StartleAllAppealed::
	.string "Scares every POKéMON that\n"
	.string "has already appealed.$"

gText_BadlyStartleFrontMon::
	.string "Gives the POKéMON in front\n"
	.string "a bad scare.$"

gText_BadlyStartleAppealed::
	.string "Gives those that already\n"
	.string "appealed a bad scare.$"

gText_StartleAppealedBeforeUser2::
	.string "Scares the POKéMON that\n"
	.string "appealed just before the user.$"

gText_StartleAllAppealed2::
	.string "Scares every POKéMON that\n"
	.string "has already appealed.$"

gText_ShiftJudgesAttentionFromOthers::
	.string "Pulls the JUDGE's eyes\n"
	.string "away from the others.$"

gText_StartleMonHasJudgesAttention::
	.string "Scares the POKéMON that\n"
	.string "has the JUDGE's attention.$"

gText_JamOthersMissesTurn::
	.string "Jams the others, but the user\n"
	.string "sits out one round of appeals.$"

gText_StartleMonsMadeSameTypeAppeal::
	.string "Scares POKéMON that made\n"
	.string "an appeal of the same type.$"

gText_BadlyStartleCoolAppeals::
	.string "Badly scares POKéMON\n"
	.string "that made COOL appeals.$"

gText_BadlyStartleBeautyAppeals::
	.string "Badly scares POKéMON\n"
	.string "that made BEAUTY appeals.$"

gText_BadlyStartleCuteAppeals::
	.string "Badly scares POKéMON\n"
	.string "that made CUTE appeals.$"

gText_BadlyStartleSmartAppeals::
	.string "Badly scares POKéMON\n"
	.string "that made SMART appeals.$"

gText_BadlyStartleToughAppeals::
	.string "Badly scares POKéMON\n"
	.string "that made TOUGH appeals.$"

gText_MakeMonAfterUserNervous::
	.string "Rattles one POKéMON that\n"
	.string "appeals after the user.$"

gText_MakeAllMonsAfterUserNervous::
	.string "Rattles all POKéMON that\n"
	.string "appeal after the user.$"

gText_WorsenConditionOfThoseMadeAppeals::
	.string "Worsens the condition of\n"
	.string "those that already appealed.$"

gText_BadlyStartleMonsGoodCondition::
	.string "Badly scares POKéMON that\n"
	.string "are in good condition.$"

gText_AppealGreatIfPerformedFirst::
	.string "A great appeal if the user\n"
	.string "goes first.$"

gText_AppealGreatIfPerformedLast::
	.string "A great appeal if the user\n"
	.string "goes last.$"

gText_AppealAsGoodAsThoseBeforeIt::
	.string "Appeals just as well as\n"
	.string "those before it.$"

gText_AppealAsGoodAsOneBeforeIt::
	.string "Appeals just as well as\n"
	.string "the one before it.$"

gText_AppealBetterLaterItsPerformed::
	.string "The later it goes in the\n"
	.string "order, the better it appeals.$"

gText_AppealVariesDependingOnTiming::
	.string "The appeal's quality changes\n"
	.string "with its timing.$"

gText_WorksWellIfSameTypeAsBefore::
	.string "Works well if it matches the\n"
	.string "type of the one before.$"

gText_WorksWellIfDifferentTypeAsBefore::
	.string "Works well if its type differs\n"
	.string "from the one before.$"

gText_AffectedByAppealInFront::
	.string "Depends on how well the\n"
	.string "appeal in front went.$"

gText_UpsConditionHelpsPreventNervousness::
	.string "Raises the user's condition.\n"
	.string "Helps fend off nerves.$"

gText_AppealWorksWellIfConditionGood::
	.string "Appeals well if the user's\n"
	.string "condition is good.$"

gText_NextAppealMadeEarlier::
	.string "The next appeal can come\n"
	.string "earlier next turn.$"

gText_NextAppealMadeLater::
	.string "The next appeal can come\n"
	.string "later next turn.$"

gText_TurnOrderMoreEasilyScrambled::
	.string "Makes the order of the next\n"
	.string "turn easier to scramble.$"

gText_ScrambleOrderOfNextAppeals::
	.string "Scrambles the order of\n"
	.string "appeals on the next turn.$"

gText_AppealExcitesAudienceInAnyContest::
	.string "An appeal that fires up the\n"
	.string "crowd in any CONTEST.$"

gText_BadlyStartlesMonsGoodAppeals::
	.string "Badly scares all POKéMON\n"
	.string "that made good appeals.$"

gText_AppealBestMoreCrowdExcited::
	.string "The more fired up the crowd,\n"
	.string "the better this appeals.$"

gText_TemporarilyStopCrowdExcited::
	.string "Temporarily keeps the crowd\n"
	.string "from getting fired up.$"

@ Unused move names

gText_RainDance::
	.string "RAIN DANCE$"

gText_Rage::
	.string "RAGE$"

gText_FocusEnergy::
	.string "FOCUS ENERGY$"

gText_Hypnosis::
	.string "HYPNOSIS$"

gText_Softboiled::
	.string "SOFTBOILED$"

gText_HornAttack::
	.string "HORN ATTACK$"

gText_SwordsDance::
	.string "SWORDS DANCE$"

gText_Conversion::
	.string "CONVERSION$"

gText_SunnyDay::
	.string "SUNNY DAY$"

gText_Rest2::
	.string "REST$"

gText_Vicegrip::
	.string "VICEGRIP$"

gText_DefenseCurl::
	.string "DEFENSE CURL$"

gText_LockOn::
	.string "LOCK-ON$"

@ Contest type names

gContestMoveTypeCoolText::
	.string "COOL$"

gContestMoveTypeBeautyText::
	.string "BEAUTY$"

gContestMoveTypeCuteText::
	.string "CUTE$"

gContestMoveTypeSmartText::
	.string "SMART$"

gContestMoveTypeToughText::
	.string "TOUGH$"

gText_AppealNumWhichMoveWillBePlayed::
	.string "Appeal no. {STR_VAR_1}!\n"
	.string "Which move will you play?$"

gText_AppealNumButItCantParticipate::
	.string "Appeal no. {STR_VAR_1}!\n"
	.string "But it can't take part!$"

gText_MonAppealedWithMove::
	.string "{STR_VAR_1} appealed with\n"
	.string "{STR_VAR_2}!$"

gText_MonWasWatchingOthers::
	.string "{STR_VAR_1} sized up\n"
	.string "the others.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_AllOutOfAppealTime::
	.string "Time's up! We're all out of\n"
	.string "Appeal Time!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

@ Unused appeal result texts

gText_ButAppealWasJammed::
	.string "But the appeal got\n"
	.string "jammed.$"

gText_FollowedAnotherMonsLead::
	.string "It followed another\n"
	.string "POKéMON's lead.$"

gText_ButItMessedUp::
	.string "But it messed up.$"

gText_WentBetterThanUsual::
	.string "It went better than\n"
	.string "usual.$"

gText_JudgeLookedAwayForSomeReason::
	.string "The JUDGE glanced away\n"
	.string "for some reason.$"

gText_WorkedHardToBuildOnPastMistakes::
	.string "It fought hard to make up\n"
	.string "for past mistakes.$"

gText_CantMakeAnyMoreMoves::
	.string "It can't make any more\n"
	.string "moves.$"

gText_WorkedFrighteninglyWell::
	.string "It performed frighteningly\n"
	.string "well.$"

gText_WorkedHardAsStandoutMon::
	.string "It pushed as hard as the\n"
	.string "standout POKéMON.$"

gText_JudgedLookedOnExpectantly::
	.string "The JUDGE watched with\n"
	.string "high expectations.$"

gText_WorkedRatherWell::
	.string "It did rather well.$"

gText_WorkedLittleBetterThanUsual::
	.string "It did a little better\n"
	.string "than usual.$"

@ Round result texts

gText_MonFailedToStandOutAtAll::
	.string "{STR_VAR_1} failed to\n"
	.string "stand out at all…{PAUSE_UNTIL_PRESS}$"

gText_MonDidntStandOutVeryMuch::
	.string "{STR_VAR_1} didn't stand\n"
	.string "out very much…{PAUSE_UNTIL_PRESS}$"

gText_MonCaughtALittleAttention::
	.string "{STR_VAR_1} caught a\n"
	.string "little attention.{PAUSE_UNTIL_PRESS}$"

gText_MonAttractedALotOfAttention::
	.string "{STR_VAR_1} drew a\n"
	.string "lot of attention.{PAUSE_UNTIL_PRESS}$"

gText_MonCommandedTotalAttention::
	.string "{STR_VAR_1} commanded\n"
	.string "the whole room's attention.{PAUSE_UNTIL_PRESS}$"

gText_MonHasntMadeItsAppeal::
	.string "{STR_VAR_1} hasn't made\n"
	.string "its appeal yet.{PAUSE_UNTIL_PRESS}$"

@ Unused
gText_AnticipationSwelledForMonsAppealNext2::
	.string "Excitement swelled for\n"
	.string "{STR_VAR_1}'s appeal next.$"

gText_EmptyContestString::
	.string "$"

gText_JudgesViewsOnMonHeldFirm::
	.string "The JUDGE 's views on\n"
	.string "{STR_VAR_1} held firm.$"

gText_MonsXChangedPerceptions::
	.string "{STR_VAR_1}'s {STR_VAR_3}\n"
	.string "changed perceptions.$"

gText_MonsAppealEffectWoreOff::
	.string "{STR_VAR_1}'s appeal\n"
	.string "effect wore off.$"

gText_SpecialAppealsEffectWoreOff::
	.string "The special appeal's\n"
	.string "effect wore off.$"

gText_EveryonesAppealsMadeToLookSame::
	.string "Everyone's appeals were\n"
	.string "made to look the same.$"

gText_CheapenedMonsAppeal::
	.string "It cheapened\n"
	.string "{STR_VAR_2}'s appeal.$"

gText_CheapenedAppealOfThoseAhead::
	.string "It cheapened the appeal\n"
	.string "of those ahead.$"

gText_StoleAttentionAwayFromMon::
	.string "It stole the spotlight\n"
	.string "from {STR_VAR_2}.$"

gText_CheapenedMonsAppeal2::
	.string "It cheapened\n"
	.string "{STR_VAR_2}'s appeal.$"

gText_SeverelyCheapenedOtherAppeals::
	.string "It severely cheapened\n"
	.string "the other appeals.$"

gText_AnticipationSwelledForMonsAppealNext::
	.string "Excitement swelled for\n"
	.string "{STR_VAR_1}'s appeal next.$"

gText_CheapenedAppealOfThoseAhead2::
	.string "It cheapened the appeal\n"
	.string "of those ahead.$"

gText_CheapenedJudgesFavoriteAppeal::
	.string "It cheapened the JUDGE's\n"
	.string "favorite appeal.$"

gText_AppealsOfOthersCheapenedByHalf::
	.string "Everyone else's appeals\n"
	.string "were cut in half.$"

gText_StoodOutToMakeUpForBeingJammed::
	.string "It stood out to make up\n"
	.string "for being jammed.$"

gText_CantParticipateInAppealsAnyMore::
	.string "It can't take part in\n"
	.string "appeals any more.$"

gText_TouchedJudgeForFantasticAppeal::
	.string "It moved the JUDGE with\n"
	.string "a fantastic appeal.$"

gText_AnticipationRoseForUpcomingAppeals::
	.string "Excitement rose for the\n"
	.string "upcoming appeals.$"

gText_StoodOutAsMuchAsSpecialAppeals::
	.string "It stood out as much as\n"
	.string "the special appeals.$"

gText_StoodOutAsMuchAsMon::
	.string "It stood out as much as\n"
	.string "{STR_VAR_1}.$"

gText_JammedAppealsMadeEvenLessNoticeable::
	.string "Jammed appeals faded into\n"
	.string "the background even more.$"

gText_EveryonesAppealsMadeSame::
	.string "Everyone's appeals were\n"
	.string "made the same.$"

@ Appeal result texts

gText_BecameMoreConsciousOfOtherMons::
	.string "It grew more wary\n"
	.string "of the other POKéMON.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonCantMakeAnAppealAfterThis::
	.string "{STR_VAR_1} can't make an\n"
	.string "appeal after this.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_SettledDownJustLittleBit::
	.string "It calmed down just a\n"
	.string "little bit.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_BecameObliviousToOtherMons::
	.string "It tuned out all the\n"
	.string "other POKéMON.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_BecameLessAwareOfOtherMons::
	.string "It grew less aware of\n"
	.string "the other POKéMON.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_StoppedCaringAboutOtherMons::
	.string "It stopped worrying about\n"
	.string "other POKéMON much.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToStartleOtherMons::
	.string "It tried to spook the\n"
	.string "other POKéMON.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToDazzleOthers::
	.string "It tried to dazzle the\n"
	.string "others.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_JudgeLookedAwayFromMon::
	.string "The JUDGE looked away\n"
	.string "from {STR_VAR_1}.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToUnnerveNextMon::
	.string "It tried to rattle the\n"
	.string "next POKéMON.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonBecameNervous::
	.string "{STR_VAR_1} got\n"
	.string "nervous.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_AppealTriedToUnnerveWaitingMons::
	.string "The appeal tried to\n"
	.string "unnerve waiting POKéMON.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TauntedMonsDoingWell::
	.string "It taunted POKéMON\n"
	.string "doing well.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonRegainedItsForm::
	.string "{STR_VAR_1} regained its\n"
	.string "form.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToJamMonDoingWell::
	.string "It tried to jam POKéMON\n"
	.string "doing well.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_StandoutMonHustledEvenMore::
	.string "The standout {STR_VAR_1}\n"
	.string "hustled even more.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_LargelyUnnoticedMonWorkedHard::
	.string "The overlooked wallflower\n"
	.string "{STR_VAR_1} worked hard.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_WorkedAsMuchAsMonBefore::
	.string "It pushed as hard as the\n"
	.string "POKéMON before it.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotGoWell::
	.string "{STR_VAR_1}'s appeal did\n"
	.string "not go well.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_WorkedAsMuchAsPrecedingMon::
	.string "It pushed as hard as the\n"
	.string "preceding POKéMON.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotGoWell2::
	.string "{STR_VAR_1}'s appeal did\n"
	.string "not go well.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotGoWell3::
	.string "{STR_VAR_1}'s appeal did\n"
	.string "not go well.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentSlightlyWell::
	.string "{STR_VAR_1}'s appeal\n"
	.string "went slightly well.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentPrettyWell::
	.string "{STR_VAR_1}'s appeal\n"
	.string "went pretty well.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentExcellently::
	.string "{STR_VAR_1}'s appeal\n"
	.string "went excellently.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWasDud::
	.string "{STR_VAR_1}'s appeal was\n"
	.string "a dud.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotWorkVeryWell::
	.string "{STR_VAR_1}'s appeal did\n"
	.string "not work very well.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentSlightlyWell2::
	.string "{STR_VAR_1}'s appeal\n"
	.string "went slightly well.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentPrettyWell2::
	.string "{STR_VAR_1}'s appeal\n"
	.string "went pretty well.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentVeryWell::
	.string "{STR_VAR_1}'s appeal\n"
	.string "went very well.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentExcellently2::
	.string "{STR_VAR_1}'s appeal\n"
	.string "went excellently.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_SameTypeAsOneBeforeGood::
	.string "Same type as the\n"
	.string "POKéMON before--good!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_NotSameTypeAsOneBeforeGood::
	.string "Different type from\n"
	.string "the one before--good!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_StoodOutMuchMoreThanMonBefore::
	.string "It stood out far more\n"
	.string "than the POKéMON before.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_DidntDoAsWellAsMonBefore::
	.string "It didn't do as well as the\n"
	.string "POKéMON before it.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsConditionRoseAboveUsual::
	.string "{STR_VAR_1}'s condition\n"
	.string "rose above usual.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsHotStatusMadeGreatAppeal::
	.string "{STR_VAR_1}'s hot streak\n"
	.string "made it a great appeal!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MovedUpInLineForNextAppeal::
	.string "It moved up in line for\n"
	.string "the next appeal.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MovedBackInLineForNextAppeal::
	.string "It moved back in line for\n"
	.string "the next appeal.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_ScrambledUpOrderForNextTurn::
	.string "It shook up the\n"
	.string "order for the next turn.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_JudgeLookedAtMonExpectantly::
	.string "The JUDGE looked at\n"
	.string "{STR_VAR_1} expectantly.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_AppealComboWentOverWell::
	.string "The appeal combo went\n"
	.string "over well.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_AppealComboWentOverVeryWell::
	.string "The appeal combo went\n"
	.string "over very well.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_AppealComboWentOverExcellently::
	.string "The appeal combo went\n"
	.string "over excellently.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonManagedToAvertGaze::
	.string "{STR_VAR_1} managed to\n"
	.string "avert its gaze.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonManagedToAvoidSeeingIt::
	.string "{STR_VAR_1} managed to\n"
	.string "avoid seeing it.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonIsntFazedByThatSortOfThing::
	.string "{STR_VAR_1} isn't fazed\n"
	.string "by that sort of thing.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonBecameALittleDistracted::
	.string "{STR_VAR_1} got a\n"
	.string "little distracted.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToStartleOtherPokemon::
	.string "It tried to spook the\n"
	.string "other POKéMON.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonLookedDownOutOfDistraction::
	.string "{STR_VAR_1} looked down\n"
	.string "out of distraction.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonTurnedBackOutOfDistraction::
	.string "{STR_VAR_1} turned away\n"
	.string "out of distraction.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonCouldntHelpUtteringCry::
	.string "{STR_VAR_1} couldn't help\n"
	.string "uttering a cry.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonCouldntHelpLeapingUp::
	.string "{STR_VAR_1} couldn't help\n"
	.string "leaping up.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonTrippedOutOfDistraction::
	.string "{STR_VAR_1} tripped over\n"
	.string "out of distraction.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonWasTooNervousToMove::
	.string "{STR_VAR_1} was too\n"
	.string "nervous to move.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_ButItMessedUp2::
	.string "But it messed up.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_ButItFailedToMakeTargetNervous::
	.string "But it couldn't make\n"
	.string "the target nervous.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_ButItFailedToMakeAnyoneNervous::
	.string "But it failed to rattle\n"
	.string "anyone.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_ButItWasIgnored::
	.string "But it was ignored…{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_CouldntImproveItsCondition::
	.string "But it couldn't improve\n"
	.string "its condition…{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_BadConditionResultedInWeakAppeal::
	.string "Its poor condition\n"
	.string "resulted in a weak appeal.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonWasUnaffected::
	.string "{STR_VAR_1} was\n"
	.string "unaffected.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_RepeatedAppeal::
	.string "{STR_VAR_1} let the crowd down\n"
	.string "by repeating an appeal.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsXWentOverGreat::
	.string "{STR_VAR_1}'s {STR_VAR_3}\n"
	.string "went over great.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsXDidntGoOverWell::
	.string "{STR_VAR_1}'s {STR_VAR_3}\n"
	.string "didn't go over well here…{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsXGotTheCrowdGoing::
	.string "{STR_VAR_1}'s {STR_VAR_3}\n"
	.string "got the crowd going.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonCantAppealNextTurn::
	.string "{STR_VAR_1} can't appeal\n"
	.string "next turn…{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_AttractedCrowdsAttention::
	.string "It caught the crowd's\n"
	.string "attention.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_CrowdContinuesToWatchMon::
	.string "The crowd continues to\n"
	.string "watch {STR_VAR_3}.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsMoveIsIgnored::
	.string "{STR_VAR_1}'s\n"
	.string "{STR_VAR_2} is ignored.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_Contest_Shyness::
	.string "shyness$"

gText_Contest_Anxiety::
	.string "anxiety$"

gText_Contest_Laziness::
	.string "laziness$"

gText_Contest_Hesitancy::
	.string "hesitancy$"

gText_Contest_Fear::
	.string "fear$"

gText_Contest_Coolness::
	.string "coolness$"

gText_Contest_Beauty::
	.string "beauty$"

gText_Contest_Cuteness::
	.string "cuteness$"

gText_Contest_Smartness::
	.string "smartness$"

gText_Contest_Toughness::
	.string "toughness$"

@ Unused
gText_Tension::
	.string "TENSION$"

gText_CoolMove::
	.string "COOL Move$"

gText_BeautyMove::
	.string "BEAUTY Move$"

gText_CuteMove::
	.string "CUTE Move$"

gText_SmartMove::
	.string "SMART Move$"

gText_ToughMove::
	.string "TOUGH Move$"

gText_3QuestionMarks::
	.string "???$"
