EventTicket_Text_ShowOldSeaMap:
	.string "The ferry to SLATEPORT is…\p"
	.string "Eh? You want us to sail to a place\n"
	.string "on this map?\p"
	.string "I know someone who can help you\n"
	.string "better. Wait here.$"

EventTicket_Text_ThatPass:
	.string "The ferry to SLATEPORT is…\p"
	.string "Oh?\n"
	.string "That PASS…$"

EventTicket_Text_ShowEonTicket:
	.string "Aye, mate, are you the one who\n"
	.string "brought that mighty odd PASS?\p"
	.string "You're after a tiny spit of an\n"
	.string "island, way out in the far south.\p"
	.string "There's no telling what we'll run\n"
	.string "into once we get there, aye.\l"
	.string "My ki's tingling just thinking of it!\p"
	.string "All aboard!$"

EventTicket_Text_SouthernIslandSailBack:
	.string "Aye, mate, there's nothing to see\n"
	.string "or do on this forgettable island.\p"
	.string "What say we sail back to LILYCOVE?$"

EventTicket_Text_SailHome:
	.string "Aye, right, then!\n"
	.string "Home we sail!$"

EventTicket_Text_AsYouLike:
	.string "Aye, right, as you like, then.$"

SouthernIsland_Interior_Text_Sign:
	.string "“All dreams are but another reality.\n"
	.string "Never forget…”$"

SouthernIsland_Exterior_Text_Sign:
	.string "“Those whose memories fade seek to\n"
	.string "carve them in their hearts…”$"
