EventTicket_Text_OldSeaMapTooFar:
	.string "What's up, youngster?\p"
	.string "What, you're the one with a tattered\n"
	.string "old map?\p"
	.string "Let's have a look.\n"
	.string "… … … … … …\p"
	.string "Boy, that's a long way off.\n"
	.string "I'm afraid I can't help you…$"

EventTicket_Text_BrineyHoldOnASecond:
	.string "BRINEY: Hold on a second!\p"
	.string "What's the idea of turning away\n"
	.string "someone I owe so much to?$"

EventTicket_Text_BrineyLetsSail:
	.string "{PLAYER}{KUN}, I'm terribly sorry.\p"
	.string "You came to me for help, and we\n"
	.string "almost sent you away.\p"
	.string "Well, let me make it right.\p"
	.string "We sail right now, of course!\p"
	.string "Let's find this island on this\n"
	.string "OLD SEA MAP!$"

EventTicket_Text_OddTicketGetOnBoard:
	.string "Are you the one who brought that\n"
	.string "odd ticket?\p"
	.string "Where you want to go is an island\n"
	.string "far, far away.\p"
	.string "No one knows what's waiting there…\p"
	.string "The thought alone fires up my\n"
	.string "blood, like a real sailing man!\p"
	.string "Get on board, youngster!$"

FarawayIsland_Entrance_Text_SailorReturn:
	.string "CAPT. BRINEY can be so maddeningly\n"
	.string "fickle…\p"
	.string "Do you want to go back to LILYCOVE?$"

BirthIsland_Harbor_Text_SailorReturn:
	.string "Strange-looking island, eh?\n"
	.string "Do you want to go back to LILYCOVE?$"

EventTicket_Text_OddTicketsWhereTo:
	.string "Are you the one who brought those\n"
	.string "odd tickets?\p"
	.string "… … …Hm.\p"
	.string "These tickets will take you to\n"
	.string "islands far, far away.\p"
	.string "No one knows what's waiting there,\n"
	.string "or what might happen.\p"
	.string "The thought alone fires up my\n"
	.string "blood, like a real sailing man!\p"
	.string "Get on board, youngster!\n"
	.string "Where shall we sail first?$"

NavelRock_Harbor_Text_SailorReturn:
	.string "Did… Did you hear that?\n"
	.string "That low growl from deep inside.\p"
	.string "It's a huge power, I can feel it!\n"
	.string "Should we get out of here?$"

FarawayIsland_Entrance_Text_Sign:
	.string "The writing is fading as if it was\n"
	.string "written a long time ago…\p"
	.string "“…ber, 6th day\n"
	.string "If any human…sets foot here…\l"
	.string "again…et it be a kindhearted pers…\l"
	.string "…ith that hope, I depar…”$"

FarawayIsland_Interior_Text_Mew:
	.string "Myuu…$"
