@ Only contains the text for the Mauville Man named Giddy. The rest is in scripts/mauville_man.inc
GiddyText_SoPretty::
	.string " so pretty!$"

GiddyText_SoDarling::
	.string " so darling!$"

GiddyText_SoRelaxed::
	.string " so relaxing!$"

GiddyText_SoSunny::
	.string " so sunny!$"

GiddyText_SoDesirable::
	.string " so tempting!$"

GiddyText_SoExciting::
	.string " so thrilling!$"

GiddyText_SoAmusing::
	.string " so hilarious!$"

GiddyText_SoMagical::
	.string " so magical!$"

GiddyText_Is::
	.string " is$"

GiddyText_DontYouAgree::
	.string "\n"
	.string "Don't you agree?$"

GiddyText_ISoWantToGoOnAVacation::
	.string "I so want to go on a vacation.\n"
	.string "Know any nice islands? Like Kame\l"
	.string "House, but with more sunshine?$"

GiddyText_IBoughtCrayonsWith120Colors::
	.string "I bought a capsule that pops out\n"
	.string "120 colors of crayons!\l"
	.string "Don't you think that's neat?$"

GiddyText_WouldntItBeNiceIfWeCouldFloat::
	.string "Wouldn't it be nice to float away\n"
	.string "on a Flying Nimbus, just drifting?$"

GiddyText_WhenYouWriteOnASandyBeach::
	.string "When you write on a sandy beach,\n"
	.string "the waves wash it all away.\l"
	.string "That makes me so sad.$"

GiddyText_WhatsTheBottomOfTheSeaLike::
	.string "What's the bottom of the sea like?\n"
	.string "Just once I would so love to go!$"

GiddyText_WhenYouSeeTheSettingSunDoesIt::
	.string "When you watch the setting sun,\n"
	.string "doesn't it make you want to go home\l"
	.string "for dinner?$"

GiddyText_LyingBackInTheGreenGrass::
	.string "Lying back in the green grass…\n"
	.string "Oh, it's so, so nice!$"

GiddyText_SecretBasesAreSoWonderful::
	.string "SECRET BASES are so wonderful!\n"
	.string "Can't you feel the excitement?$"
