MoveTutor_Text_ThisMoveCanOnlyBeLearnedOnce:
	.string "This move can be learned only once.\p"
	.string "Is that okay?$"

MoveTutor_Text_SwaggerTeach:
	.string "Heh! My POKéMON totally rules!\p"
	.string "It's tougher than any POKéMON out\n"
	.string "there!\p"
	.string "I was strutting around with a swagger\n"
	.string "like a certain Saiyan prince when the\l"
	.string "CHAIRMAN chewed me out.\p"
	.string "That took all the swagger out of my\n"
	.string "step.\p"
	.string "If you'd like, I'll teach the move\n"
	.string "SWAGGER to a POKéMON of yours.$"

MoveTutor_Text_SwaggerDeclined:
	.string "What, no? Can't you get into the spirit\n"
	.string "of things?$"

MoveTutor_Text_SwaggerWhichMon:
	.string "All right, which POKéMON wants to learn\n"
	.string "how to SWAGGER?$"

MoveTutor_Text_SwaggerTaught:
	.string "I'll just praise my POKéMON from now on,\n"
	.string "without the swagger.$"

MoveTutor_Text_RolloutTeach:
	.string "Did you know you can go a long way in\n"
	.string "that direction from here without ever\l"
	.string "changing course?\p"
	.string "I bet I could roll all the way down it.\p"
	.string "Do you think your POKéMON would want to\n"
	.string "roll, too?\p"
	.string "I can teach one the move ROLLOUT, if\n"
	.string "you'd like.$"

MoveTutor_Text_RolloutDeclined:
	.string "No need to be shy about it.\p"
	.string "Let's roll!$"

MoveTutor_Text_RolloutWhichMon:
	.string "Ehehe, sure thing! It'd be great if the\n"
	.string "POKéMON looked like me.$"

MoveTutor_Text_RolloutTaught:
	.string "Rolling around in the grass makes me\n"
	.string "happy. Come on, let's roll!$"

MoveTutor_Text_FuryCutterTeach:
	.string "There's a move that gets stronger when\n"
	.string "you keep using it in a row.\p"
	.string "It's a BUG-type move, and it is wickedly\n"
	.string "cool.\p"
	.string "It's called FURY CUTTER.\p"
	.string "Want me to teach it to a POKéMON?$"

MoveTutor_Text_FuryCutterDeclined:
	.string "We're not on the same wavelength.$"

MoveTutor_Text_FuryCutterWhichMon:
	.string "Yay!\p"
	.string "Show me which POKéMON I should teach.$"

MoveTutor_Text_FuryCutterTaught:
	.string "I get a thrill watching to see if the\n"
	.string "move keeps hitting in a combo!$"

MoveTutor_MimicTeach:
	.string "Ah, young one!\p"
	.string "I am also a young one, but I mimic the\n"
	.string "styles and speech of the elderly folks\l"
	.string "of this town.\p"
	.string "What say you, young one?\p"
	.string "Would you agree if I offered to teach\n"
	.string "the move MIMIC?$"

MoveTutor_MimicDeclined:
	.string "Oh, boo! I wanted to teach MIMIC to\n"
	.string "your POKéMON!$"

MoveTutor_Text_MimicWhichMon:
	.string "Fwofwo! And so I shall!\p"
	.string "Let me see the POKéMON you wish me to\n"
	.string "teach.$"

MoveTutor_Text_MimicTaught:
	.string "MIMIC is a move of great depth.\p"
	.string "Could you copy it as perfectly as I\n"
	.string "do…?$"

MoveTutor_Text_MetronomeTeach:
	.string "I want all sorts of things!\p"
	.string "But I've spent all my allowance…\p"
	.string "Wouldn't it be nice if there were a\n"
	.string "technique that made ZENI appear when\l"
	.string "you waggle a finger?\p"
	.string "If you want, I can teach your POKéMON\n"
	.string "the move METRONOME.\p"
	.string "ZENI won't appear, but your POKéMON will\n"
	.string "waggle a finger. Yes?$"

MoveTutor_Text_MetronomeDeclined:
	.string "Okay. I'll be here if you change your\n"
	.string "mind.$"

MoveTutor_Text_MetronomeWhichMon:
	.string "Okay! I'll teach it!\p"
	.string "Which POKéMON should I teach?$"

MoveTutor_Text_MetronomeTaught:
	.string "When a POKéMON waggles its finger like a\n"
	.string "METRONOME, all sorts of nice things\l"
	.string "happen.\p"
	.string "Wouldn't it be nice if we could use it,\n"
	.string "too?$"

MoveTutor_Text_SleepTalkTeach:
	.string "Humph! My wife relies on HIDDEN POWER\n"
	.string "to stay awake.\p"
	.string "She should just take a nap like I do,\n"
	.string "and SLEEP TALK.\p"
	.string "I can teach your POKéMON how to SLEEP\n"
	.string "TALK instead. Interested?$"

MoveTutor_Text_SleepTalkDeclined:
	.string "Oh, fine, fine. You want to stay awake\n"
	.string "with HIDDEN POWER, too…$"

MoveTutor_Text_SleepTalkWhichMon:
	.string "Ah, an appreciative child!\p"
	.string "Which POKéMON should I teach?$"

MoveTutor_Text_SleepTalkTaught:
	.string "I've never once gotten my wife's coin\n"
	.string "trick right.\p"
	.string "I'd be happy to get it right even while I\n"
	.string "SLEEP TALK…$"

MoveTutor_Text_SubstituteTeach:
	.string "When I look out over the wide world from\n"
	.string "up here on the roof…\p"
	.string "I think about how nice it would be to\n"
	.string "have more than one of me, like TIEN's\l"
	.string "multi-form technique, so I could enjoy\l"
	.string "all sorts of lives.\p"
	.string "Of course it's not possible.\n"
	.string "Giggle…\p"
	.string "I know! Would you be interested in\n"
	.string "having a POKéMON learn SUBSTITUTE?$"

MoveTutor_Text_SubstituteDeclined:
	.string "Oh, no?\p"
	.string "A POKéMON can make a copy of itself\n"
	.string "with it, you know.$"

MoveTutor_Text_SubstituteWhichMon:
	.string "Giggle…\p"
	.string "Which POKéMON do you want me to teach\n"
	.string "SUBSTITUTE?$"

MoveTutor_Text_SubstituteTaught:
	.string "We humans should enjoy our own lives to\n"
	.string "the fullest!\p"
	.string "I hope you'll do the same!$"

MoveTutor_Text_DynamicPunchTeach:
	.string "I can't do this anymore!\p"
	.string "It's utterly hopeless!\p"
	.string "I'm a FIGHTING-type TRAINER, so I can't\n"
	.string "beat GOTEN and TRUNKS at the MOSSDEEP\l"
	.string "GYM no matter how hard I try!\p"
	.string "Argh! Punch! Punch! Punch! Punch!\n"
	.string "Punch! Punch!\p"
	.string "What, don't look at me like that! I'm\n"
	.string "only hitting the ground!\p"
	.string "Or do you want me to teach your POKéMON\n"
	.string "DYNAMICPUNCH?$"

MoveTutor_Text_DynamicPunchDeclined:
	.string "Darn! You're making fun of me, too?\p"
	.string "Punch! Punch! Punch!$"

MoveTutor_Text_DynamicPunchWhichMon:
	.string "What? You do? You're a good person!\p"
	.string "Which POKéMON should I teach?$"

MoveTutor_Text_DynamicPunchTaught:
	.string "I want you to win at the MOSSDEEP GYM\n"
	.string "with that DYNAMICPUNCH!$"

MoveTutor_Text_DoubleEdgeTeach:
	.string "Sigh…\p"
	.string "PICCOLO, the SOOTOPOLIS GYM LEADER, is\n"
	.string "really so stoic and admirable.\p"
	.string "But that means I have lots of rivals for\n"
	.string "his attention.\p"
	.string "He's got a charm that cuts like a\n"
	.string "DOUBLE-EDGE. I couldn't even catch his\l"
	.string "eye.\p"
	.string "Please, let me teach your POKéMON the\n"
	.string "move DOUBLE-EDGE!$"

MoveTutor_Text_DoubleEdgeDeclined:
	.string "Oh…\p"
	.string "Even you rejected me…$"

MoveTutor_Text_DoubleEdgeWhichMon:
	.string "Okay, which POKéMON should I teach\n"
	.string "DOUBLE-EDGE?$"

MoveTutor_Text_DoubleEdgeTaught:
	.string "I won't live for love anymore!\p"
	.string "I'll become tough!$"

MoveTutor_Text_ExplosionTeach:
	.string "I don't intend to be stuck going\n"
	.string "nowhere fast in the sticks like this\l"
	.string "forever.\p"
	.string "You watch me, I'll get out to the city\n"
	.string "and become a huge hit.\p"
	.string "Seriously, I'm going to cause a huge\n"
	.string "EXPLOSION of popularity!\p"
	.string "If you overheard that, I'll happily\n"
	.string "teach EXPLOSION to your POKéMON!$"

MoveTutor_Text_ExplosionDeclined:
	.string "Gaah! You're turning me down because I\n"
	.string "live in the country?$"

MoveTutor_Text_ExplosionWhichMon:
	.string "Fine! An EXPLOSION it is!\p"
	.string "Which POKéMON wants to blow up?$"

MoveTutor_Text_ExplosionTaught:
	.string "For a long time, I've taught POKéMON how\n"
	.string "to use EXPLOSION, but I've yet to set\l"
	.string "off my own…\p"
	.string "Maybe it's because deep down, I'd\n"
	.string "rather stay here…$"
