gText_WouldYouLikeToRestYourPkmn::
	.string "Hello, and welcome to the POKéMON\n"
	.string "CENTER.\p"
	.string "We restore your tired POKéMON to full\n"
	.string "health, as good as a SENZU BEAN.\p"
	.string "Would you like to rest your POKéMON?$"

gText_IllTakeYourPkmn::
	.string "Okay, I'll take your POKéMON for a few\n"
	.string "moments.$"

gText_RestoredPkmnToFullHealth::
	.string "Thank you for waiting.\p"
	.string "Your POKéMON are fully restored and\n"
	.string "ready to fight!$"

gText_WeHopeToSeeYouAgain::
	.string "We hope to see you again!$"

gText_WelcomeCutShort::
	.string "Hello, and welcome to the POKéMON\n"
	.string "CENTER.\p"
	.string "We restore your tired POKéMON to full\n"
	.string "health, as good as a SENZU BEAN.\p"
	.string "Would you like to…$"

gText_NoticesGoldCard::
	.string "Th-that card…\n"
	.string "Could it be… The GOLD CARD?!\p"
	.string "Oh, the gold is so brilliant!\n"
	.string "The four stars seem to sparkle!\p"
	.string "I've seen several TRAINERS with a\n"
	.string "SILVER CARD before, but, {PLAYER},\l"
	.string "you're the first TRAINER I've ever seen\l"
	.string "with a GOLD CARD!\p"
	.string "Okay, {PLAYER}, please allow me the\n"
	.string "honor of resting your POKéMON!$"

gText_YouWantTheUsual::
	.string "I'm delighted to see you, {PLAYER}!\p"
	.string "You'll be wanting the usual, am I right?$"

gText_IllTakeYourPkmn2::
	.string "Okay, I'll take your POKéMON for a few\n"
	.string "moments.$"

gText_ThankYouForWaiting::
	.string "Thank you for waiting. They're at full\n"
	.string "power!$"

gText_WeHopeToSeeYouAgain2::
	.string "We hope to see you again!$"
