gBirchDexRatingText_AreYouCurious::
	.string "MASTER ROSHI: Ah, {PLAYER}{KUN}!\p"
	.string "Are you curious how your POKéDEX is\n"
	.string "coming along?$"

gBirchDexRatingText_Cancel::
	.string "Hm? Oh, you haven't caught enough\n"
	.string "POKéMON to make it worthwhile.$"

gBirchDexRatingText_SoYouveSeenAndCaught::
	.string "Hmhm…\p"
	.string "So, you've seen {STR_VAR_1} POKéMON, and\n"
	.string "you've caught {STR_VAR_2} POKéMON…$"

gBirchDexRatingText_LessThan10::
	.string "Get out into the grassy areas more and\n"
	.string "look for POKéMON more carefully. A true\l"
	.string "martial artist is observant!$"

gBirchDexRatingText_LessThan20::
	.string "I guess you're getting the hang of it.\n"
	.string "But it gets harder from here.$"

gBirchDexRatingText_LessThan30::
	.string "Some POKéMON only appear in certain\n"
	.string "areas.\p"
	.string "You must be persistent.$"

gBirchDexRatingText_LessThan40::
	.string "Well, it could use more quantity, but\n"
	.string "this is starting to look like a POKéDEX.$"

gBirchDexRatingText_LessThan50::
	.string "This is coming along pretty well. Keep\n"
	.string "up the training!$"

gBirchDexRatingText_LessThan60::
	.string "Are you using any RODS?\p"
	.string "There are many POKéMON in the sea. Even\n"
	.string "I fished a lot at KAME HOUSE.$"

gBirchDexRatingText_LessThan70::
	.string "Instead of just catching POKéMON, how\n"
	.string "about making them evolve, too?$"

gBirchDexRatingText_LessThan80::
	.string "This is going to be a fantastic POKéDEX.\p"
	.string "That's the feeling I'm getting.$"

gBirchDexRatingText_LessThan90::
	.string "You've collected this many…\p"
	.string "Your talent is remarkable!$"

gBirchDexRatingText_LessThan100::
	.string "Have you visited the SAFARI ZONE?\p"
	.string "I hear there are some POKéMON that can\n"
	.string "only be caught there.$"

gBirchDexRatingText_LessThan110::
	.string "You've finally reached the 100-kind\n"
	.string "mark.\p"
	.string "This is an impressive POKéDEX!$"

gBirchDexRatingText_LessThan120::
	.string "There might be POKéMON that can be\n"
	.string "found using ROCK SMASH.$"

gBirchDexRatingText_LessThan130::
	.string "You should get some more POKéMON by\n"
	.string "trading with others.$"

gBirchDexRatingText_LessThan140::
	.string "I've heard of POKéMON that evolve when\n"
	.string "they come to fully love their TRAINERS.$"

gBirchDexRatingText_LessThan150::
	.string "I had no idea there were so many\n"
	.string "POKéMON species in the HOENN region.$"

gBirchDexRatingText_LessThan160::
	.string "On occasion, some POKéMON appear in\n"
	.string "large numbers, like outbreaks.\p"
	.string "Don't miss opportunities like those.$"

gBirchDexRatingText_LessThan170::
	.string "One can get a very good idea of the\n"
	.string "POKéMON of the HOENN region by looking\l"
	.string "through your POKéDEX.$"

gBirchDexRatingText_LessThan180::
	.string "I'd say you already qualify as a\n"
	.string "POKéMON PROFESSOR, and a good one, too!\p"
	.string "Hohoho!$"

gBirchDexRatingText_LessThan190::
	.string "With a POKéDEX this complete, you're a\n"
	.string "real professional at this!$"

gBirchDexRatingText_LessThan200::
	.string "You're very close to completing this\n"
	.string "POKéDEX.\p"
	.string "I can feel it in my old bones!$"

gBirchDexRatingText_DexCompleted::
	.string "Congratulations!\p"
	.string "Your POKéDEX is complete!$"

gBirchDexRatingText_OnANationwideBasis::
	.string "Hmhm…\p"
	.string "On a nationwide basis…\p"
	.string "You've seen {STR_VAR_1} POKéMON, and\n"
	.string "you've caught {STR_VAR_2} POKéMON…$"
