gBirchDexRatingText_AreYouCurious::
	.string "MASTER ROSHI: Ah, {PLAYER}{KUN}!\p"
	.string "Are you curious how your POKéDEX is\n"
	.string "coming along?$"

gBirchDexRatingText_Cancel::
	.string "Hm? Oh, you haven't caught enough\n"
	.string "POKéMON to make it worthwhile.$"

gBirchDexRatingText_SoYouveSeenAndCaught::
	.string "Hmhm…\p"
	.string "So, you've seen {STR_VAR_1} POKéMON, and\n"
	.string "you've caught {STR_VAR_2} POKéMON…$"

gBirchDexRatingText_LessThan10::
	.string "Get out into the grassy areas more and\n"
	.string "look for POKéMON more carefully. A true\l"
	.string "martial artist is observant!$"

gBirchDexRatingText_LessThan20::
	.string "I guess you're getting the hang of it.\n"
	.string "But it gets harder from here.$"

gBirchDexRatingText_LessThan30::
	.string "Some POKéMON only appear in certain\n"
	.string "areas.\p"
	.string "You must be persistent.$"

gBirchDexRatingText_LessThan40::
	.string "Well, it could use more quantity, but\n"
	.string "this is starting to look like a POKéDEX.$"

gBirchDexRatingText_LessThan50::
	.string "This is coming along pretty well. Keep\n"
	.string "up the training!$"

gBirchDexRatingText_LessThan60::
	.string "Are you using any RODS?\p"
	.string "There are many POKéMON in the sea. Even\n"
	.string "I fished a lot at KAME HOUSE.$"

gBirchDexRatingText_LessThan70::
	.string "Instead of just catching POKéMON, how\n"
	.string "about making them evolve, too?$"

gBirchDexRatingText_LessThan80::
	.string "This is going to be a fantastic POKéDEX.\p"
	.string "That's the feeling I'm getting.$"

gBirchDexRatingText_LessThan90::
	.string "You've collected this many…\p"
	.string "Your talent is remarkable!$"

gBirchDexRatingText_LessThan100::
	.string "Have you visited the SAFARI ZONE?\p"
	.string "I hear there are some POKéMON that can\n"
	.string "only be caught there.$"

gBirchDexRatingText_LessThan110::
	.string "You've finally reached the 100-kind\n"
	.string "mark.\p"
	.string "This is an impressive POKéDEX!$"

gBirchDexRatingText_LessThan120::
	.string "There might be POKéMON that can be\n"
	.string "found using ROCK SMASH.$"

gBirchDexRatingText_LessThan130::
	.string "You should get some more POKéMON by\n"
	.string "trading with others.$"

gBirchDexRatingText_LessThan140::
	.string "I've heard of POKéMON that evolve when\n"
	.string "they come to fully love their TRAINERS.$"

gBirchDexRatingText_LessThan150::
	.string "I had no idea there were so many\n"
	.string "POKéMON species in the HOENN region.$"

gBirchDexRatingText_LessThan160::
	.string "On occasion, some POKéMON appear in\n"
	.string "large numbers, like outbreaks.\p"
	.string "Don't miss opportunities like those.$"

gBirchDexRatingText_LessThan170::
	.string "One can get a very good idea of the\n"
	.string "POKéMON of the HOENN region by looking\l"
	.string "through your POKéDEX.$"

gBirchDexRatingText_LessThan180::
	.string "I'd say you already qualify as a\n"
	.string "POKéMON PROFESSOR, and a good one, too!\p"
	.string "Hohoho!$"

gBirchDexRatingText_LessThan190::
	.string "With a POKéDEX this complete, you're a\n"
	.string "real professional at this!$"

gBirchDexRatingText_LessThan200::
	.string "You're very close to completing this\n"
	.string "POKéDEX.\p"
	.string "I can feel it in my old bones!$"

gBirchDexRatingText_DexCompleted::
	.string "Congratulations!\p"
	.string "Your POKéDEX is complete!$"

gBirchDexRatingText_OnANationwideBasis::
	.string "Hmhm…\p"
	.string "On a nationwide basis…\p"
	.string "You've seen {STR_VAR_1} POKéMON,\n"
	.string "and you've caught {STR_VAR_2} POKéMON…$"

@ FRLG

PokedexRating_Text_HowIsPokedexComingAlong::
	.string "OAK: Good to see you!\n"
	.string "How is your POKéDEX coming along?\p"
	.string "Here, let me take a look.$"

PokedexRating_Text_SeenXOwnedY::
	.string "The amount of progress you've made\n"
	.string "on your POKéDEX is:\p"
	.string "{STR_VAR_1} POKéMON seen and\n"
	.string "{STR_VAR_2} POKéMON owned.\p"
	.string "{FONT_NORMAL}PROF. OAK's rating:$"

PokedexRating_Text_LessThan10::
	.string "You still have lots to do.\p"
	.string "Go into every patch of grass you\n"
	.string "see and look for POKéMON!$"

PokedexRating_Text_LessThan20::
	.string "It looks as if you're getting on\n"
	.string "the right track!\p"
	.string "I've given one of my AIDES a FLASH\n"
	.string "HM. Make sure you go get it!$"

PokedexRating_Text_LessThan30::
	.string "Your POKéDEX could use a bit more\n"
	.string "volume still!\p"
	.string "Try to catch other species of\n"
	.string "POKéMON!$"

PokedexRating_Text_LessThan40::
	.string "Good, it's apparent that you're\n"
	.string "trying hard!\p"
	.string "I've given one of my AIDES an\n"
	.string "ITEMFINDER. Be sure to collect it!$"

PokedexRating_Text_LessThan50::
	.string "Your POKéDEX is coming along quite\n"
	.string "well!\p"
	.string "I've given one of my AIDES an\n"
	.string "AMULET COIN. Be sure to get it!$"

PokedexRating_Text_LessThan60::
	.string "Ah, you've finally topped 50\n"
	.string "species!\p"
	.string "I've given one of my AIDES an EXP.\n"
	.string "SHARE. Be sure to go get it!$"

PokedexRating_Text_LessThan70::
	.string "Hoho! This is turning into quite the\n"
	.string "respectable POKéDEX!$"

PokedexRating_Text_LessThan80::
	.string "Very good!\p"
	.string "I think you'll collect even more\n"
	.string "POKéMON by going fishing!$"

PokedexRating_Text_LessThan90::
	.string "Wonderful! Let me guess… You\n"
	.string "like to collect things, don't you?$"

PokedexRating_Text_LessThan100::
	.string "I'm impressed!\n"
	.string "It must have been difficult to do!$"

PokedexRating_Text_LessThan110::
	.string "You've finally hit 100 species!\n"
	.string "I can't believe how good you are!$"

PokedexRating_Text_LessThan120::
	.string "You even have the evolved forms\n"
	.string "of POKéMON! Super!$"

PokedexRating_Text_LessThan130::
	.string "Excellent! Trade with friends to\n"
	.string "get some more!$"

PokedexRating_Text_LessThan140::
	.string "Outstanding!\n"
	.string "You've become a real pro at this!$"

PokedexRating_Text_LessThan150::
	.string "I have nothing left to say!\n"
	.string "You're the POKéMON PROFESSOR now!$"

PokedexRating_Text_Complete::
	.string "Your POKéDEX is entirely complete!\n"
	.string "Congratulations!!$"

PokedexRating_Text_NationalDexSeenXOwnedY::
	.string "And your NATIONAL POKéDEX is:\p"
	.string "{STR_VAR_1} POKéMON seen and\n"
	.string "{STR_VAR_2} POKéMON owned.$"

PokedexRating_Text_LookForwardToFilledNationalDex::
	.string "I'll be looking forward to seeing\n"
	.string "you fill the NATIONAL POKéDEX!$"

PokedexRating_Text_YouveCompletedDex::
	.string "Finally…\p"
	.string "You've finally completed the\n"
	.string "POKéDEX!\p"
	.string "It's magnificent!\n"
	.string "Truly, this is a fantastic feat!$"

PokedexRating_Text_Wroooaaarrr::
	.string "Wroooooooaaaaaarrrr!$"

PokedexRating_Text_ThankYouMadeDreamReality::
	.string "Thank you, {PLAYER}!\n"
	.string "Sincerely, thank you!\l"
	.string "You've made my dream a reality!$"

PokedexRating_Text_LoveSeeingYourPokedex::
	.string "OAK: Ah, welcome!\p"
	.string "Tell me, how is your POKéDEX\n"
	.string "coming along?\p"
	.string "Wahaha!\p"
	.string "Actually, I know how it is, but I\n"
	.string "love seeing it anyway!\p"
	.string "Let's see…$"
