Questionnaire_Text_FillOut::
	.string "There's a questionnaire here.\n"
	.string "Want to fill it out?$"

Questionnaire_Text_ThankYou::
	.string "Thanks for taking the time to\n"
	.string "fill out our questionnaire.\p"
	.string "Your answers will help us make\n"
	.string "things better down the road.$"

Questionnaire_Text_YouKnowThoseWordsGift::
	.string "Oh, hey there!\n"
	.string "You know those words?\p"
	.string "Then you must know about the\n"
	.string "MYSTERY GIFT.\p"
	.string "From now on, MYSTERY GIFTS are\n"
	.string "going to find their way to you!$"

Questionnaire_Text_YouCanAccessMysteryGift::
	.string "Save your game and you can\n"
	.string "access the MYSTERY GIFT.$"

Questionnaire_Text_YouKnowThoseWordsEvent::
	.string "Oh, hey there!\n"
	.string "You know those words?\p"
	.string "Then you must know about the\n"
	.string "MYSTERY EVENT.$"

Questionnaire_Text_YouCanAccessMysteryEvent::
	.string "Save your game and you can\n"
	.string "access the MYSTERY EVENT.$"

MysteryGift_Text_TheresATicketForYou::
	.string "Thanks for using the MYSTERY\n"
	.string "EVENT System.\p"
	.string "You must be {PLAYER}.\n"
	.string "A ticket came in for you.$"

MysteryGift_Text_TryUsingItAtLilycovePort::
	.string "It looks like it's meant for the\n"
	.string "LILYCOVE CITY port.\p"
	.string "Why not go and find out what\n"
	.string "it's all about?$"
