	.align 2
gText_ConfirmSave::
	.string "Would you like to save your progress?$"

gText_AlreadySavedFile::
	.string "There is already a saved file.\p"
	.string "Is it okay to overwrite it?$"

gText_SavingDontTurnOff::
	.string "SAVING…\n"
	.string "DON'T TURN OFF THE POWER.$"

gText_PlayerSavedGame::
	.string "{PLAYER} saved the game.$"

gText_DifferentSaveFile::
	.string "WARNING!\p"
	.string "There is a different game file that is\n"
	.string "already saved.\p"
	.string "If you save now, the other file's\n"
	.string "adventure, including items and POKéMON,\l"
	.string "will be entirely lost.\p"
	.string "Are you sure you want to save now and\n"
	.string "overwrite the other save file?$"

gText_SaveError::
	.string "Save error.\p"
	.string "Please exchange the backup memory.$"

gText_SavingDontTurnOffPower::
	.string "SAVING…\n"
	.string "DON'T TURN OFF THE POWER.$"
