SecretBase_Text_Trainer0Intro:
	.string "Got a SECRET BASE of your own yet?\p"
	.string "I wandered all over the place before\n"
	.string "settling on this spot.\p"
	.string "Since you've dropped in, how about\n"
	.string "a battle?$"

SecretBase_Text_Trainer0AcceptBattle:
	.string "All right!\n"
	.string "Here I come!$"

SecretBase_Text_Trainer0DeclineBattle:
	.string "Huh?\n"
	.string "Oh, you can't right now…$"

SecretBase_Text_Trainer0Defeated::
	.string "Waaargh! You're too strong!\n"
	.string "Please keep my loss a secret!$"

SecretBase_Text_Trainer0PostBattle:
	.string "So, what do you think of my\n"
	.string "SECRET BASE? Drop by again tomorrow.$"

SecretBase_Text_Trainer0PreChampion:
	.string "Got a SECRET BASE of your own yet?\p"
	.string "I wandered all over the place before\n"
	.string "settling on this spot.\p"
	.string "Feel free to hang out!$"

SecretBase_Text_Trainer5Intro:
	.string "There are plenty of places to build\n"
	.string "a SECRET BASE.\p"
	.string "But this spot is my favorite.\n"
	.string "Isn't it nice?\p"
	.string "Oh, want to have a battle?$"

SecretBase_Text_Trainer5AcceptBattle:
	.string "All right, here goes!$"

SecretBase_Text_Trainer5DeclineBattle:
	.string "Oh…\n"
	.string "Not now? Okay.$"

SecretBase_Text_Trainer5Defeated::
	.string "Hmmm… We lost this one…\n"
	.string "But don't tell anyone!\l"
	.string "It's top secret!$"

SecretBase_Text_Trainer5PostBattle:
	.string "If you're in this area again,\n"
	.string "I hope you'll come visit.$"

SecretBase_Text_Trainer5PreChampion:
	.string "There are plenty of places to build\n"
	.string "a SECRET BASE.\p"
	.string "But this spot is my favorite.\n"
	.string "Isn't it nice?$"

SecretBase_Text_Trainer1Intro:
	.string "This is a popular spot.\n"
	.string "It's always taken.\p"
	.string "Oh! Were you thinking of claiming\n"
	.string "this spot too?\p"
	.string "Tell you what, it's yours if you\n"
	.string "can beat me.$"

SecretBase_Text_Trainer1AcceptBattle:
	.string "All right!\n"
	.string "I'll defend my SECRET BASE!$"

SecretBase_Text_Trainer1DeclineBattle:
	.string "Huh? Really?\n"
	.string "You're not interested in this spot?$"

SecretBase_Text_Trainer1Defeated::
	.string "I can't keep going!\n"
	.string "I give up!$"

SecretBase_Text_Trainer1PostBattle:
	.string "All right, when I move out one day,\n"
	.string "this place is yours!$"

SecretBase_Text_Trainer1PreChampion:
	.string "This is a popular spot.\n"
	.string "It's always taken.\p"
	.string "I waited a long time for it to open\n"
	.string "up. Now it's finally mine!$"

SecretBase_Text_Trainer6Intro:
	.string "Welcome to my POKéMON LAB.\p"
	.string "I carry out secret research on\n"
	.string "battling, like a CAPSULE CORP. genius.\p"
	.string "Want to see how strong I am?$"

SecretBase_Text_Trainer6AcceptBattle:
	.string "I'm going all out!$"

SecretBase_Text_Trainer6DeclineBattle:
	.string "Oh.\n"
	.string "Some other time, then!$"

SecretBase_Text_Trainer6Defeated::
	.string "Hmm… I still have lots to learn.\n"
	.string "Back to the books for me.$"

SecretBase_Text_Trainer6PostBattle:
	.string "Thanks for battling me.\n"
	.string "Please come back again tomorrow.$"

SecretBase_Text_Trainer6PreChampion:
	.string "Welcome to my POKéMON LAB.\p"
	.string "I carry out secret research on\n"
	.string "battling, like a CAPSULE CORP. genius.$"

SecretBase_Text_Trainer2Intro:
	.string "A big mansion is nice, but I like\n"
	.string "places like this more.\p"
	.string "All kinds of people come to visit me\n"
	.string "here, and I love that.\p"
	.string "So, how about a battle?$"

SecretBase_Text_Trainer2AcceptBattle:
	.string "That's the spirit!$"

SecretBase_Text_Trainer2DeclineBattle:
	.string "When you're ready, give me a shout!$"

SecretBase_Text_Trainer2Defeated::
	.string "Aww! I'm done in!\n"
	.string "But battling is still fun!$"

SecretBase_Text_Trainer2PostBattle:
	.string "Well, anyway, I should go buy some\n"
	.string "decorations and furniture.\p"
	.string "I want my SECRET BASE to be a place\n"
	.string "that other people can enjoy.$"

SecretBase_Text_Trainer2PreChampion:
	.string "A big mansion is nice, but I like\n"
	.string "places like this more.\p"
	.string "All kinds of people come to visit me\n"
	.string "here, and I love that.$"

SecretBase_Text_Trainer7Intro:
	.string "I simply adore shopping for\n"
	.string "decorations and furniture.\p"
	.string "I love raising POKéMON just as\n"
	.string "much.\p"
	.string "If you'd be so kind, will you battle\n"
	.string "my POKéMON?$"

SecretBase_Text_Trainer7AcceptBattle:
	.string "Thank you.\n"
	.string "Shall we begin?$"

SecretBase_Text_Trainer7DeclineBattle:
	.string "Oh.\n"
	.string "How disappointing…$"

SecretBase_Text_Trainer7Defeated::
	.string "I concede…$"

SecretBase_Text_Trainer7PostBattle:
	.string "That was all in good fun!\n"
	.string "Time for me to go shopping.$"

SecretBase_Text_Trainer7PreChampion:
	.string "I simply adore shopping for\n"
	.string "decorations and furniture.\p"
	.string "I love raising POKéMON just as\n"
	.string "much.$"

SecretBase_Text_Trainer3Intro:
	.string "Some people build SECRET BASES in\n"
	.string "hard-to-find places.\l"
	.string "Maybe they want to lie low?\p"
	.string "But since you found me, how about a\n"
	.string "battle?$"

SecretBase_Text_Trainer3AcceptBattle:
	.string "I won't go down easy!$"

SecretBase_Text_Trainer3DeclineBattle:
	.string "Oh… Are you worn out from searching\n"
	.string "for this place?$"

SecretBase_Text_Trainer3Defeated::
	.string "I went down…$"

SecretBase_Text_Trainer3PostBattle:
	.string "Where's your SECRET BASE?\n"
	.string "I should go visit you there.$"

SecretBase_Text_Trainer3PreChampion:
	.string "Some people build SECRET BASES in\n"
	.string "hard-to-find places.\l"
	.string "Maybe they want to lie low?$"

SecretBase_Text_Trainer8Intro:
	.string "I heard there are several ways to\n"
	.string "get decorations.\p"
	.string "Let's race to see who can collect\n"
	.string "nicer decorations and furniture!\p"
	.string "In the meantime, want to battle?$"

SecretBase_Text_Trainer8AcceptBattle:
	.string "This is my SECRET BASE.\n"
	.string "I can't lose!$"

SecretBase_Text_Trainer8DeclineBattle:
	.string "I'll battle you anytime.$"

SecretBase_Text_Trainer8Defeated::
	.string "Huh?\n"
	.string "Did I just lose?$"

SecretBase_Text_Trainer8PostBattle:
	.string "I won't lose at collecting decorations.\n"
	.string "Come visit again!$"

SecretBase_Text_Trainer8PreChampion:
	.string "I heard there are several ways to\n"
	.string "get decorations.\p"
	.string "Let's race to see who can collect\n"
	.string "nicer decorations and furniture!$"

SecretBase_Text_Trainer4Intro:
	.string "I found a spot I liked and fixed it\n"
	.string "up with my favorite decorations.\p"
	.string "I raise my favorite POKéMON and\n"
	.string "grow stronger alongside them.\p"
	.string "That's my training. Want to battle?$"

SecretBase_Text_Trainer4AcceptBattle:
	.string "Show me what you're made of!$"

SecretBase_Text_Trainer4DeclineBattle:
	.string "I guess there are days when you're not\n"
	.string "in the mood.$"

SecretBase_Text_Trainer4Defeated::
	.string "Now I know exactly what you're\n"
	.string "made of.$"

SecretBase_Text_Trainer4PostBattle:
	.string "We can both get stronger.\n"
	.string "Let's keep at it!$"

SecretBase_Text_Trainer4PreChampion:
	.string "I found a spot I liked and fixed it\n"
	.string "up with my favorite decorations.\p"
	.string "I raise my favorite POKéMON and\n"
	.string "grow stronger alongside them.\p"
	.string "Every day is a great day.$"

SecretBase_Text_Trainer9Intro:
	.string "You can learn a lot about a person's\n"
	.string "taste and sense from their\l"
	.string "decorations and how they display them.\p"
	.string "What do you think of my taste?\n"
	.string "Are you speechless?\p"
	.string "Want to see my taste in battling?$"

SecretBase_Text_Trainer9AcceptBattle:
	.string "No holding back!$"

SecretBase_Text_Trainer9DeclineBattle:
	.string "I'll gladly show off my style\n"
	.string "anytime.$"

SecretBase_Text_Trainer9Defeated::
	.string "You're supremely talented!\n"
	.string "Your power seems limitless…$"

SecretBase_Text_Trainer9PostBattle:
	.string "What did you think of my style?\n"
	.string "I'll keep on polishing it!$"

SecretBase_Text_Trainer9PreChampion:
	.string "You can learn a lot about a person's\n"
	.string "taste and sense from their\l"
	.string "decorations and how they display them.\p"
	.string "What do you think of my taste?\n"
	.string "Are you speechless?$"
