ShoalCave_LowTideEntranceRoom_Text_AreYouPlanningOnGoingInThere:
	.string "Are you planning on going deep in\n"
	.string "there?\p"
	.string "How about bringing me back some SHOAL\n"
	.string "SALT and SHOAL SHELLS?\p"
	.string "I can make you something good if you\n"
	.string "bring me the ingredients.$"

ShoalCave_LowTideEntranceRoom_Text_BringMe4ShoalSaltAndShells:
	.string "If you bring me four each of SHOAL SALT\n"
	.string "and SHOAL SHELLS, I can make you a\l"
	.string "SHELL BELL…\p"
	.string "You can find those ingredients every\n"
	.string "day.$"

ShoalCave_LowTideEntranceRoom_Text_WouldYouLikeShellBell:
	.string "Oh, hey! SHOAL SALT and SHOAL SHELLS!\p"
	.string "And enough of them, too!\p"
	.string "Would you like me to make you a SHELL\n"
	.string "BELL with them?$"

ShoalCave_LowTideEntranceRoom_Text_MakeShellBellRightAway:
	.string "All righty, then! I'll make you a SHELL\n"
	.string "BELL right away.\p"
	.string "… … … … … … … …\n"
	.string "… … … … … … … …\p"
	.string "There! Done!$"

ShoalCave_LowTideEntranceRoom_Text_ExplainShellBell:
	.string "Have a POKéMON hold on to that. It'll\n"
	.string "love it, that's for certain.\p"
	.string "Why, the SHELL BELL's chime… It's simply\n"
	.string "sublime!\p"
	.string "You can get its ingredients every day,\n"
	.string "so I can make you more.$"

ShoalCave_LowTideEntranceRoom_Text_WantedToMakeShellBell:
	.string "Oh… Is that so…\p"
	.string "I really wanted to make a SHELL BELL…$"

ShoalCave_LowTideEntranceRoom_Text_NoSpaceInYourBag:
	.string "You don't have space in your BAG for it.\p"
	.string "Make some room and come back for your\n"
	.string "SHELL BELL.$"

ShoalCave_Text_WasShoalSaltNowNothing:
	.string "There was some SHOAL SALT here.\p"
	.string "But there's nothing here now.$"

ShoalCave_Text_WasShoallShellNowNothing:
	.string "There was a SHOAL SHELL here.\p"
	.string "But there's nothing here now.$"
