Route102_Text_CalvinIntro:
	.string "You've got POKéMON? Then you're a real\n"
	.string "TRAINER, and my scouter says you're\l"
	.string "worth a fight! No saying no!$"

Route102_Text_CalvinDefeated:
	.string "Arrgh, I lost! I should've worn heavier\n"
	.string "training gear…$"

Route102_Text_CalvinPostBattle:
	.string "Listen up, you. If you're this strong,\n"
	.string "you should've warned me first!$"

Route102_Text_CalvinRegister:
	.string "I've been training like a madman since\n"
	.string "you beat me.\p"
	.string "I want to fight you again, so register\n"
	.string "me in your POKéNAV, okay?$"

Route102_Text_CalvinRegisterShort:
	.string "I want to fight you again, so register\n"
	.string "me in your POKéNAV, okay?$"

Route102_Text_CalvinRematchIntro:
	.string "Ever since you beat me, I've been\n"
	.string "training my POKéMON day and night. No\l"
	.string "saying no to a rematch!$"

Route102_Text_CalvinRematchDefeated:
	.string "Arrgh, lost again! Is my training\n"
	.string "routine wrong?$"

Route102_Text_CalvinRematchPostBattle:
	.string "If you keep getting stronger, then I'll\n"
	.string "keep getting stronger, too!$"

Route102_Text_AllenIntro:
	.string "Did you just start out as a TRAINER? Me\n"
	.string "too! We're both beginners, so let's spar!$"

Route102_Text_AllenDefeated:
	.string "I only called you out because I thought\n"
	.string "I could win…$"

Route102_Text_AllenPostBattle:
	.string "I haven't won a single fight yet… I wish\n"
	.string "I could win just once soon…$"

Route102_Text_RickIntro:
	.string "Hahah! Our eyes met! Prepare to face my\n"
	.string "BUG POKéMON!$"

Route102_Text_RickDefeated:
	.string "Owww! That knocked the stuffing out of\n"
	.string "me!$"

Route102_Text_RickPostBattle:
	.string "If you lock eyes with a TRAINER, you\n"
	.string "have to fight! That's the martial arts\l"
	.string "code!$"

Route102_Text_TianaIntro:
	.string "I'm going to keep winning until I'm the\n"
	.string "best TRAINER around. Help me climb the\l"
	.string "ranks!$"

Route102_Text_TianaDefeated:
	.string "Looks like I helped you climb the ranks\n"
	.string "instead…$"

Route102_Text_TianaPostBattle:
	.string "To keep winning, I've got to catch more\n"
	.string "POKéMON and build a bigger team.$"

Route103_Text_DaisyIntro:
	.string "Did you feel the pull of our soothing\n"
	.string "fragrance? Come, battle with a calm\l"
	.string "heart.$"

Route103_Text_DaisyDefeated:
	.string "You weren't swayed by our aroma…$"

Route103_Text_DaisyPostBattle:
	.string "Aromatherapy heals the mind with scent.\n"
	.string "A calm mind keeps your ki flowing\l"
	.string "smoothly.$"

Route103_Text_AmyIntro:
	.string "AMY: I'm AMY. This is my little sister\n"
	.string "LIV. We fight as a team!$"

Route103_Text_AmyDefeated:
	.string "AMY: Oh no, our teamwork wasn't enough\n"
	.string "this time.$"

Route103_Text_AmyPostBattle:
	.string "AMY: Fighting two TRAINERS at once\n"
	.string "means you have to watch everything at\l"
	.string "the same time.$"

Route103_Text_AmyNotEnoughPokemon:
	.string "AMY: Uh-oh, you only have one POKéMON\n"
	.string "with you. We can't fight you like that.$"

Route103_Text_LivIntro:
	.string "LIV: We fight together as one team.$"

Route103_Text_LivDefeated:
	.string "LIV: Oh no, we lost, big sister…$"

Route103_Text_LivPostBattle:
	.string "LIV: We move in perfect sync, me and my\n"
	.string "big sister…\p"
	.string "But we still lost…$"

Route103_Text_AmyLivRegister:
	.string "LIV: We're a lot better than that,\n"
	.string "really! It's true! We'll show you next\l"
	.string "time!$"

Route103_Text_LivNotEnoughPokemon:
	.string "LIV: If you want to fight us, you need\n"
	.string "two POKéMON! It's not fair if you don't!$"

Route103_Text_AmyRematchIntro:
	.string "AMY: I'm AMY. This is my little sister\n"
	.string "LIV. We fight as a team!$"

Route103_Text_AmyRematchDefeated:
	.string "AMY: Aww, we got beaten again…$"

Route103_Text_AmyRematchPostBattle:
	.string "AMY: Fighting two TRAINERS at once\n"
	.string "means you have to watch everything at\l"
	.string "the same time.$"

Route103_Text_AmyRematchNotEnoughPokemon:
	.string "AMY: Uh-oh, you only have one POKéMON\n"
	.string "with you. We can't fight you like that.$"

Route103_Text_LivRematchIntro:
	.string "LIV: We fight together as one team.$"

Route103_Text_LivRematchDefeated:
	.string "LIV: Not again… Sorry, big sister…$"

Route103_Text_LivRematchPostBattle:
	.string "LIV: We move in perfect sync, me and my\n"
	.string "big sister…\p"
	.string "So why did we lose again?$"

Route103_Text_LivRematchNotEnoughPokemon:
	.string "LIV: If you want to fight us, you need\n"
	.string "two POKéMON! It's not fair if you don't!$"

Route103_Text_AndrewIntro:
	.string "Gah! My fishing line is all tangled up!\n"
	.string "I'm so mad I could blow up a planet!\l"
	.string "That's it, battle me!$"

Route103_Text_AndrewDefeated:
	.string "Gah! I lost! Now I'm even angrier!$"

Route103_Text_AndrewPostBattle:
	.string "Gah, I'm still boiling mad… Grrrrr… I\n"
	.string "think I'm powering up!$"

Route103_Text_MiguelIntro:
	.string "My POKéMON is the most adorable thing\n"
	.string "in the world! Don't be shy, I'll show you!$"

Route103_Text_MiguelDefeated:
	.string "Oh my gosh, my precious darling fainted!$"

Route103_Text_MiguelPostBattle:
	.string "My lovely POKéMON looks darling even\n"
	.string "when it's fainted!$"

Route103_Text_MiguelRegister:
	.string "Come back and see my lovely POKéMON\n"
	.string "again, okay? I'll make you!$"

Route103_Text_MiguelRematchIntro:
	.string "Hi, you! My adorable POKéMON has become\n"
	.string "even more darling!$"

Route103_Text_MiguelRematchDefeated:
	.string "Oh no! My sweet little darling!$"

Route103_Text_MiguelRematchPostBattle:
	.string "The more time I spend with it, the more\n"
	.string "adorable my POKéMON gets.$"

Route103_Text_PeteIntro:
	.string "A little distance like this? You should\n"
	.string "just swim it!$"

Route103_Text_PeteDefeated:
	.string "Oh, that's some good going!$"

Route103_Text_PetePostBattle:
	.string "Oh, now I get where you're coming from.\p"
	.string "If I had a POKéMON that dependable, I'd\n"
	.string "want to SURF on it, too!$"

Route103_Text_IsabelleIntro:
	.string "Look out! Move it or we're going to\n"
	.string "collide!$"

Route103_Text_IsabelleDefeated:
	.string "Ugh, I'm dizzy…$"

Route103_Text_IsabellePostBattle:
	.string "I'm a poor swimmer, so I was practicing…\n"
	.string "Sorry for almost crashing into you.$"

Route103_Text_RhettIntro:
	.string "Whoa! How did you squeeze into a space\n"
	.string "this small?$"

Route103_Text_RhettDefeated:
	.string "Whoa! This kid can really fight!$"

Route103_Text_RhettPostBattle:
	.string "Do you like cramped quarters like this?\n"
	.string "Great for dodging practice!$"

Route103_Text_MarcosIntro:
	.string "Did my guitar's wailing pull you in? Then\n"
	.string "let's rock this fight!$"

Route103_Text_MarcosDefeated:
	.string "And just like that, the concert's over…$"

Route103_Text_MarcosPostBattle:
	.string "I was playing my guitar where nobody\n"
	.string "ever passes by, but a crowd has\l"
	.string "gathered.\p"
	.string "Heh, maybe I should go pro. Like the\n"
	.string "Great Saiyaman, but with a guitar.$"

Route104_Text_GinaIntro:
	.string "GINA: Okay, let's fight together with\n"
	.string "our POKéMON!$"

Route104_Text_GinaDefeat:
	.string "GINA: Losing makes me so mad!$"

Route104_Text_GinaPostBattle:
	.string "GINA: You're strong! We have to train a\n"
	.string "lot more!$"

Route104_Text_GinaNotEnoughMons:
	.string "GINA: Huh? Only one POKéMON? Then we\n"
	.string "won't fight you.\p"
	.string "A lone POKéMON gets lonely, and that's\n"
	.string "not nice.$"

Route104_Text_MiaIntro:
	.string "MIA: We're twins, so we fight together\n"
	.string "with our POKéMON.$"

Route104_Text_MiaDefeat:
	.string "MIA: We fought together, and we lost\n"
	.string "together…$"

Route104_Text_MiaPostBattle:
	.string "MIA: We'll train our POKéMON harder and\n"
	.string "get strong like you.$"

Route104_Text_MiaNotEnoughMons:
	.string "MIA: You want to fight us?\p"
	.string "You need two POKéMON or it's a big\n"
	.string "no-no. We're too strong for you anyway!$"

Route104_Text_IvanIntro:
	.string "Why hide it? I'm the number one WATER\n"
	.string "POKéMON expert around!\p"
	.string "Huh? You've never heard of me?$"

Route104_Text_IvanDefeat:
	.string "I thought I was pretty good, if I may\n"
	.string "say so, but I guess not… Bleah…$"

Route104_Text_IvanPostBattle:
	.string "I got so into fishing that I forgot to\n"
	.string "train my POKéMON…$"

Route104_Text_BillyIntro:
	.string "Leaving footprints in the sand is so\n"
	.string "much fun!$"

Route104_Text_BillyDefeat:
	.string "Waah! I got sand in my shoes! They're all\n"
	.string "gritty!$"

Route104_Text_BillyPostBattle:
	.string "I want to leave my footprints in the\n"
	.string "sand everywhere, but the waves wash\l"
	.string "them away so fast…$"

Route104_Text_HaleyIntro:
	.string "Should I… or shouldn't I?\p"
	.string "Okay, sure, I'll fight!$"

Route104_Text_HaleyDefeat:
	.string "I shouldn't have fought…$"

Route104_Text_HaleyPostBattle:
	.string "When you're facing a decision and you\n"
	.string "let someone else choose, you'll regret\l"
	.string "it however it turns out.$"

Route104_Text_HaleyRegister1:
	.string "You're strong, but should I register you\n"
	.string "in my POKéNAV? Maybe I shouldn't…\p"
	.string "Okay, sure, I'll register you!$"

Route104_Text_HaleyRegister2:
	.string "You're strong, but should I register you\n"
	.string "in my POKéNAV? Maybe I shouldn't…\p"
	.string "Okay, sure, I'll register you!$"

Route104_Text_HaleyRematchIntro:
	.string "Come on, fight me!$"

Route104_Text_HaleyRematchDefeat:
	.string "Ohh… I really thought I had it…$"

Route104_Text_HaleyPostRematch:
	.string "I chose to fight, so I can accept this\n"
	.string "loss with grace.\p"
	.string "I'm still upset about losing, though!$"

Route104_Text_WinstonIntro:
	.string "Oh, sure, I'll accept your challenge. My\n"
	.string "family owns a lot of Capsule Corp.\l"
	.string "stock.$"

Route104_Text_WinstonDefeat:
	.string "How can this be? I couldn't pull off a\n"
	.string "win!$"

Route104_Text_WinstonPostBattle:
	.string "There are some things even a fat wallet\n"
	.string "can't buy. Like POKéMON power…$"

Route104_Text_WinstonRegister1:
	.string "Hm? Ah, you've got a POKéNAV.\p"
	.string "I'll gladly register you. After all, I\n"
	.string "have plenty of zeni.$"

Route104_Text_WinstonRegister2:
	.string "Hm? Ah, you've got a POKéNAV.\p"
	.string "I'll gladly register you. After all, I\n"
	.string "have plenty of zeni.$"

Route104_Text_WinstonRematchIntro:
	.string "After I lost to you, I studied a bunch\n"
	.string "of things about POKéMON.$"

Route104_Text_WinstonRematchDefeat:
	.string "I lost again? Why can't I win?$"

Route104_Text_WinstonPostRematch:
	.string "I'm fabulously rich, but I can't seem to\n"
	.string "win at POKéMON…\p"
	.string "The world of POKéMON runs so deep…$"

Route104_Text_CindyIntro:
	.string "Surely fate brought us together. Would\n"
	.string "you honor me with a battle?$"

Route104_Text_CindyDefeat:
	.string "Oh, goodness me!$"

Route104_Text_CindyPostBattle:
	.string "“Hello” is the start of “good-bye.” I\n"
	.string "hope we meet again.$"

Route104_Text_CindyRegister1:
	.string "Hello again. It seems we're destined to\n"
	.string "keep crossing paths.\p"
	.string "Let's exchange numbers on our\n"
	.string "POKéNAVS.$"

Route104_Text_CindyRegister2:
	.string "We should mark how we keep being drawn\n"
	.string "together.\p"
	.string "Let's register each other in our\n"
	.string "POKéNAVS.$"

Route104_Text_CindyRematchIntro:
	.string "Hello again. Would you do me the honor\n"
	.string "of another battle?$"

Route104_Text_CindyRematchDefeat:
	.string "Oh dear… I gave it everything I had…$"

Route104_Text_CindyPostRematch:
	.string "“Hello” is the start of “good-bye.” I\n"
	.string "hope we meet again.$"

Route104_Text_DarianIntro:
	.string "I fished up a tough-looking POKéMON!\p"
	.string "It's got a mysterious aura! It\n"
	.string "definitely looks strong, yes it does!$"

Route104_Text_DarianDefeat:
	.string "Wh-what just happened…$"

Route104_Text_DarianPostBattle:
	.string "Oh, MAGIKARP… You were supposed to be\n"
	.string "my secret weapon!$"

Route105_Text_FosterIntro:
	.string "They say a mystical rock sits somewhere\n"
	.string "around here. Have you heard anything\l"
	.string "about it?$"

Route105_Text_FosterDefeated:
	.string "I was thinking about that rock so hard\n"
	.string "that my POKéMON stayed weak…$"

Route105_Text_FosterPostBattle:
	.string "I can stare at a good rock for hours\n"
	.string "and hours without getting bored.$"

Route105_Text_LuisIntro:
	.string "Whew! When I saw you, I was worried a kid\n"
	.string "was drowning.\p"
	.string "You look okay, so how about a battle?$"

Route105_Text_LuisDefeated:
	.string "Blub… blub blub…$"

Route105_Text_LuisPostBattle:
	.string "If you're drowning, the signal is to\n"
	.string "wave one arm toward the beach.$"

Route105_Text_DominikIntro:
	.string "Swimming the deep blue sea… It feels\n"
	.string "amazing!$"

Route105_Text_DominikDefeated:
	.string "Beaten… and now I'm blue as the sea…$"

Route105_Text_DominikPostBattle:
	.string "Why is the sea blue?\p"
	.string "I learned why at the MUSEUM in\n"
	.string "SLATEPORT, but I forgot.$"

Route105_Text_BeverlyIntro:
	.string "My body feels lighter in the water. It's\n"
	.string "like I'm training in low gravity!$"

Route105_Text_BeverlyDefeated:
	.string "I think I'm just going to float for a\n"
	.string "while…$"

Route105_Text_PostBattle:
	.string "In the water, your body weight drops to\n"
	.string "one tenth.\p"
	.string "That would make me… Whoops! I'm not\n"
	.string "telling you my weight!$"

Route105_Text_ImaniIntro:
	.string "Endless blue sky, endless blue sea… It's\n"
	.string "all so calm…$"

Route105_Text_ImaniDefeated:
	.string "I got beaten while I was daydreaming!$"

Route105_Text_ImaniPostBattle:
	.string "I want people to say I'm relaxing to be\n"
	.string "around. Giggle.$"

Route105_Text_AndresIntro:
	.string "I'm convinced the sea is keeping\n"
	.string "secrets from us.$"

Route105_Text_AndresDefeated:
	.string "Yes… I'm no good at battling…$"

Route105_Text_AndresPostBattle:
	.string "There must be so many secrets waiting\n"
	.string "to be found in the world's seas.\p"
	.string "I mean to find them all!$"

Route105_Text_AndresRegister:
	.string "Huh? I'm so weak, and you still want to\n"
	.string "register me in your POKéNAV?$"

Route105_Text_AndresRematchIntro:
	.string "I told you I'm weak… Are you sure you\n"
	.string "want to do this?$"

Route105_Text_AndresRematchDefeated:
	.string "Yes… I figured I'd lose.$"

Route105_Text_AndresRematchPostBattle:
	.string "I may be weak at fighting, but my urge\n"
	.string "to explore can't be beaten.\p"
	.string "I'll travel the seas all around the\n"
	.string "world!$"

Route105_Text_JosueIntro:
	.string "I'm worn out from swimming. I'm just not\n"
	.string "used to it.\p"
	.string "I need a battle for a change of pace!$"

Route105_Text_JosueDefeated:
	.string "I lost because I fought at sea.$"

Route105_Text_JosuePostBattle:
	.string "Yeah, the sky suits me a lot better than\n"
	.string "the sea. Flying is my kind of training.$"

Route106_Text_ElliotIntro:
	.string "Which do you prefer, fishing in the sea\n"
	.string "or in a stream?$"

Route106_Text_ElliotDefeated:
	.string "Just like deep-sea fishing, I lost\n"
	.string "spectacularly!$"

Route106_Text_ElliotPostBattle:
	.string "Fishing is the greatest, sea or stream.\n"
	.string "You agree with me, right?$"

Route106_Text_ElliotRegister:
	.string "Fishing's great, but so is fighting. If\n"
	.string "you don't mind, can we meet again?$"

Route106_Text_ElliotRematchIntro:
	.string "I've been reeling in new POKéMON. Get\n"
	.string "ready for a battle you won't forget!$"

Route106_Text_ElliotRematchDefeated:
	.string "I lost again, spectacularly!$"

Route106_Text_ElliotRematchPostBattle:
	.string "Win or lose, POKéMON are the best! Don't\n"
	.string "you think so, too?$"

Route106_Text_NedIntro:
	.string "What do people do when they need the\n"
	.string "bathroom?\p"
	.string "What if my ROD hooks a huge one while\n"
	.string "I'm in there? I just can't go…$"

Route106_Text_NedDefeated:
	.string "I lost because I'm trying so hard not to\n"
	.string "go to the bathroom…$"

Route106_Text_NedPostBattle:
	.string "Oh, no! I've got this feeling something\n"
	.string "big is about to bite!$"

Route106_Text_DouglasIntro:
	.string "Hahahah! I'm a lousy runner, but in the\n"
	.string "water nobody can catch me!$"

Route106_Text_DouglasDefeated:
	.string "Okay, okay, I yield!$"

Route106_Text_DouglasPostBattle:
	.string "I wouldn't lose a swimming race…$"

Route106_Text_KylaIntro:
	.string "The sea is my backyard. I won't go easy\n"
	.string "on you just because you're a kid!$"

Route106_Text_KylaDefeated:
	.string "Did you go easy on me, by any chance?$"

Route106_Text_KylaPostBattle:
	.string "Drifting along with the waves… I love\n"
	.string "it! Why not give it a try?$"

Route107_Text_DarrinIntro:
	.string "Yawn…\p"
	.string "I must have dozed off while I was\n"
	.string "drifting on the waves.$"

Route107_Text_DarrinDefeated:
	.string "Ahaha, I lost… I think I'll take a nap…$"

Route107_Text_DarrinPostBattle:
	.string "Floating and rocking with the waves is\n"
	.string "like sleeping in a plush, comfy bed.$"

Route107_Text_TonyIntro:
	.string "The sea is my backyard. Let's fight!$"

Route107_Text_TonyDefeated:
	.string "I lost on my home turf… I'm in shock!$"

Route107_Text_TonyPostBattle:
	.string "I swim the seas with a heart full of\n"
	.string "dreams…\p"
	.string "It's a song! Anyway, I'm going to keep\n"
	.string "swimming.$"

Route107_Text_TonyRegister:
	.string "You shocked me to the bone! Well, so you\n"
	.string "won't forget me…$"

Route107_Text_TonyRematchIntro:
	.string "Swimming in the big, wide sea has made\n"
	.string "my POKéMON stronger!$"

Route107_Text_TonyRematchDefeated:
	.string "What a shock!\p"
	.string "My POKéMON got stronger, but I stayed\n"
	.string "weak as a TRAINER!$"

Route107_Text_TonyRematchPostBattle:
	.string "Every fight teaches a TRAINER\n"
	.string "something new. The waves taught me\l"
	.string "that.$"

Route107_Text_DeniseIntro:
	.string "Say, have you ever heard of a little\n"
	.string "town called DEWFORD?$"

Route107_Text_DeniseDefeated:
	.string "Grrr, I can't stand this!$"

Route107_Text_DenisePostBattle:
	.string "A weird saying is getting really popular\n"
	.string "at DEWFORD HALL.$"

Route107_Text_BethIntro:
	.string "Looking for a fight? Sure, I'm in!$"

Route107_Text_BethDefeated:
	.string "I wasn't up to your level.$"

Route107_Text_BethPostBattle:
	.string "I think you'll keep getting better. I'll\n"
	.string "go for it, too!$"

Route107_Text_LisaIntro:
	.string "LISA: We're a sister-and-brother team,\n"
	.string "and we challenge you!$"

Route107_Text_LisaDefeated:
	.string "LISA: Awesome. You're in a whole\n"
	.string "different class of tough.$"

Route107_Text_LisaPostBattle:
	.string "LISA: Do you have any friends who'd go\n"
	.string "to the beach with you?$"

Route107_Text_LisaNotEnoughPokemon:
	.string "LISA: If you want to fight us, bring\n"
	.string "more POKéMON.$"

Route107_Text_RayIntro:
	.string "RAY: My sister and I always fight with\n"
	.string "POKéMON together.\p"
	.string "I always lose alone, but we can take you\n"
	.string "2-on-2!$"

Route107_Text_RayDefeated:
	.string "RAY: Wowee, your power level is way\n"
	.string "above ours!$"

Route107_Text_RayPostBattle:
	.string "RAY: My sister gave me my POKéMON. I\n"
	.string "raised it, and now it's my most\l"
	.string "important partner!$"

Route107_Text_RayNotEnoughPokemon:
	.string "RAY: If you want to fight us, go get\n"
	.string "some more POKéMON!$"

Route107_Text_CamronIntro:
	.string "I'm in the middle of a triathlon, and I'm\n"
	.string "nowhere near tired!$"

Route107_Text_CamronDefeated:
	.string "That wiped me out…$"

Route107_Text_CamronPostBattle:
	.string "I still have swimming and running left\n"
	.string "after this.\p"
	.string "Am I going to be okay?$"

Route108_Text_JeromeIntro:
	.string "My dream is to swim all seven seas of\n"
	.string "the world!$"

Route108_Text_JeromeDefeated:
	.string "I'll never swim the seven seas like\n"
	.string "this…$"

Route108_Text_JeromePostBattle:
	.string "Playing with marine POKéMON is one of\n"
	.string "the joys of swimming!$"

Route108_Text_MatthewIntro:
	.string "Ahoy, there! Are you headed out to the\n"
	.string "ABANDONED SHIP, too?$"

Route108_Text_MatthewDefeated:
	.string "I'm going under! Glub… glub…$"

Route108_Text_MatthewPostBattle:
	.string "Some brave souls even sneak inside the\n"
	.string "ABANDONED SHIP.$"

Route108_Text_TaraIntro:
	.string "My liar of a boyfriend told me I look\n"
	.string "great in a bikini…$"

Route108_Text_TaraDefeated:
	.string "Ugh, so unfair!$"

Route108_Text_TaraPostBattle:
	.string "Even if it's a lie, I love hearing I look\n"
	.string "great… Girls are so complicated…$"

Route108_Text_MissyIntro:
	.string "I adore the ocean! Once I'm swimming, all\n"
	.string "my worries float away!$"

Route108_Text_MissyDefeated:
	.string "Losing a fight just stresses me right\n"
	.string "out!$"

Route108_Text_MissyPostBattle:
	.string "Swim your stress away! It's great for\n"
	.string "your health!$"

Route108_Text_CoryIntro:
	.string "WATER-type POKéMON are my favorite!\n"
	.string "But I love all the others, too!$"

Route108_Text_CoryDefeated:
	.string "Waaaah! I lost! Waaaah!$"

Route108_Text_CoryPostBattle:
	.string "Shouting is good for me! It pumps me up!$"

Route108_Text_CoryRegister:
	.string "Strong TRAINERS are my favorite, too!\n"
	.string "Put me in your POKéNAV!$"

Route108_Text_CoryRematchIntro:
	.string "Win or lose, there's nothing like a fight\n"
	.string "out at sea!$"

Route108_Text_CoryRematchDefeated:
	.string "Waaaah! Lost again! Waaaah!$"

Route108_Text_CoryRematchPostBattle:
	.string "When you're facing a challenge, try\n"
	.string "shouting at the sea!$"

Route108_Text_CarolinaIntro:
	.string "I'm so proud of my POKéMON. Get ready\n"
	.string "for a lightning-fast battle!$"

Route108_Text_CarolinaDefeated:
	.string "Well, that was not cute at all.$"

Route108_Text_CarolinaPostBattle:
	.string "Since I'm out at sea like this, I\n"
	.string "wouldn't mind putting on a pink, frilly\l"
	.string "swimsuit…$"

Route109_Text_DavidIntro:
	.string "Hiyah! Behold my chiseled abs! This, my\n"
	.string "friend, is what “cut” looks like!$"

Route109_Text_DavidDefeated:
	.string "Aiyah! Flubbed it!$"

Route109_Text_DavidPostBattle:
	.string "Hiyah!\p"
	.string "These sculpted abs have nothing to do\n"
	.string "with how I fight!$"

Route109_Text_AliceIntro:
	.string "Did you put on enough sunscreen?$"

Route109_Text_AliceDefeated:
	.string "Owie, owie, owie!$"

Route109_Text_AlicePostBattle:
	.string "Your cheeks burn the fastest, so watch\n"
	.string "them!$"

Route109_Text_HueyIntro:
	.string "I've dropped anchor in ports around the\n"
	.string "world, but SLATEPORT is the best.$"

Route109_Text_HueyDefeated:
	.string "You're the champ!$"

Route109_Text_HueyPostBattle:
	.string "In the best port, I met the best\n"
	.string "TRAINER…$"

Route109_Text_EdmondIntro:
	.string "Urrrrppp… A fight? With me?$"

Route109_Text_EdmondDefeated:
	.string "Urp… Ooooohhh… Urrrppp…$"

Route109_Text_EdmondPostBattle:
	.string "I'm usually way stronger than this! I'm\n"
	.string "just seasick as a dog!\p"
	.string "I'm a SAILOR, but…$"

Route109_Text_RickyIntro:
	.string "So thirsty… I'd kill for a SODA POP from\n"
	.string "the SEASHORE HOUSE…$"

Route109_Text_RickyDefeated:
	.string "Ughh…$"

Route109_Text_RickyPostBattle:
	.string "I'm getting famished… My inner tube is\n"
	.string "starting to look like a giant doughnut…$"

Route109_Text_RickyRegister:
	.string "Will you fight me again when I'm not so\n"
	.string "thirsty?$"

Route109_Text_RickyRematchIntro:
	.string "I'm hungry, but I've got enough pep left\n"
	.string "for a battle!$"

Route109_Text_RickyRematchDefeated:
	.string "I lost… I blame my empty stomach…$"

Route109_Text_RickyRematchPostBattle:
	.string "Eating on a beach makes everything\n"
	.string "taste a little better. Goku would agree!$"

Route109_Text_LolaIntro:
	.string "Don't beach umbrellas look like giant\n"
	.string "flowers?$"

Route109_Text_LolaDefeated:
	.string "Mommyyy!$"

Route109_Text_LolaPostBattle:
	.string "From up in the sky, this beach must look\n"
	.string "like a giant flower garden!$"

Route109_Text_LolaRegister:
	.string "Me? I'm out here every single day!$"

Route109_Text_LolaRematchIntro:
	.string "I'm not losing to you again! That's why I\n"
	.string "brought my inner tube!$"

Route109_Text_LolaRematchDefeated:
	.string "Mommyyy!$"

Route109_Text_LolaRematchPostBattle:
	.string "With an inner tube, me and my POKéMON's\n"
	.string "cuteness goes way up!$"

Route109_Text_AustinaIntro:
	.string "I can't swim a stroke without my inner\n"
	.string "tube, but I never lose at POKéMON!$"

Route109_Text_AustinaDefeated:
	.string "Did I lose because of my inner tube?$"

Route109_Text_AustinaPostBattle:
	.string "My inner tube is a fashion statement. I\n"
	.string "wouldn't be caught dead without it.$"

Route109_Text_GwenIntro:
	.string "Hi, big TRAINER. Will you fight with me?$"

Route109_Text_GwenDefeated:
	.string "Wow, you're really strong.$"

Route109_Text_GwenPostBattle:
	.string "How did you get so strong?$"

Route109_Text_CarterIntro:
	.string "Wahahah! This dude's going to hook\n"
	.string "himself a big one!$"

Route109_Text_CarterDefeated:
	.string "This dude's catch just got away…$"

Route109_Text_CarterPostBattle:
	.string "This dude says you're the big one. Or\n"
	.string "the big-one-to-be, anyway!$"

Route109_Text_PaulIntro:
	.string "PAUL: Well, this is a mood-breaker.\p"
	.string "I wish you wouldn't interrupt our\n"
	.string "precious time together.$"

Route109_Text_PaulDefeated:
	.string "PAUL: Fine, you win. I give up.$"

Route109_Text_PaulPostBattle:
	.string "PAUL: Well, don't tell anyone we're here.\n"
	.string "This is our private world of two!$"

Route109_Text_PaulNotEnoughPokemon:
	.string "PAUL: We're totally, deeply in love.\n"
	.string "That's why we make our POKéMON fight\l"
	.string "together.$"

Route109_Text_MelIntro:
	.string "MEL: We're, like, SO in love. We're setting\n"
	.string "all of HOENN on fire!$"

Route109_Text_MelDefeated:
	.string "MEL: We lost and it's all my fault! PAUL\n"
	.string "is going to hate me!$"

Route109_Text_MelPostBattle:
	.string "MEL: Um, PAUL, are you mad at me? Please\n"
	.string "don't be mad.$"

Route109_Text_MelNotEnoughPokemon:
	.string "MEL: We're, like, deeply and truly in love.\n"
	.string "That's why we make our POKéMON fight\l"
	.string "together.$"

Route109_Text_ChandlerIntro:
	.string "Tadaah! See? My inner tube is round!$"

Route109_Text_ChandlerDefeated:
	.string "Aw, shucks! Too bad!$"

Route109_Text_ChandlerPostBattle:
	.string "And I even showed you my round inner\n"
	.string "tube, too…$"

Route109_Text_HaileyIntro:
	.string "I can't actually swim, so I just flail\n"
	.string "around and pretend.$"

Route109_Text_HaileyDefeated:
	.string "I knew it! I didn't think we could win.$"

Route109_Text_HaileyPostBattle:
	.string "Once I learn to swim, I think my POKéMON\n"
	.string "will get tougher, too.$"

Route109_Text_ElijahIntro:
	.string "A tough guy like me and a POKéMON like\n"
	.string "this? Perfect match!$"

Route109_Text_ElijahDefeated:
	.string "See? Even when I lose, I look cool.$"

Route109_Text_ElijahPostBattle:
	.string "A rugged guy like me belongs in a harbor\n"
	.string "town! Next stop, SLATEPORT.$"

Route110_Text_JacobIntro:
	.string "Whoa, watch out! Guess you're new to\n"
	.string "BIKE racing.$"

Route110_Text_JacobDefeated:
	.string "Whoa! I lost my brakes!$"

Route110_Text_JacobPostBattle:
	.string "Flat tires and bad brakes can cause\n"
	.string "serious injury! Inspect your BIKE for\l"
	.string "problems!$"

Route110_Text_AnthonyIntro:
	.string "Hey, you! Think you can keep up with me?$"

Route110_Text_AnthonyDefeated:
	.string "Wiped out!$"

Route110_Text_AnthonyPostBattle:
	.string "Speed alone won't win POKéMON battles.\n"
	.string "I need to rethink this…$"

Route110_Text_BenjaminIntro:
	.string "Don't panic just because your BIKE's\n"
	.string "going fast!$"

Route110_Text_BenjaminDefeated:
	.string "I should stay calm during POKéMON\n"
	.string "battles…$"

Route110_Text_BenjaminPostBattle:
	.string "No need to panic or stress. Take it\n"
	.string "easy. There's plenty of time.$"

Route110_Text_BenjaminRegister:
	.string "I'll keep chugging along without\n"
	.string "stressing. Give me a shout if you're up\l"
	.string "for it.$"

Route110_Text_BenjaminRematchIntro:
	.string "Aren't you in a bit of a rush? Slow down\n"
	.string "and fight me.$"

Route110_Text_BenjaminRematchDefeated:
	.string "I kept my cool, and I still lost…$"

Route110_Text_BenjaminRematchPostBattle:
	.string "No need to panic or stress. Take it\n"
	.string "easy. There's plenty of time.$"

Route110_Text_AbigailIntro:
	.string "The triathlon is brutally hard.\p"
	.string "You have to finish three events:\n"
	.string "swimming, cycling, and running.$"

Route110_Text_AbigailDefeated:
	.string "POKéMON battles are exhausting, too!$"

Route110_Text_AbigailPostBattle:
	.string "I'm exhausted, so I need a break. Proper\n"
	.string "rest is part of training.$"

Route110_Text_AbigailRegister:
	.string "You know, I really like you! Let's meet\n"
	.string "for a rematch on CYCLING ROAD.$"

Route110_Text_AbigailRematchIntro:
	.string "Isn't it neat to battle while cycling?$"

Route110_Text_AbigailRematchDefeated:
	.string "Wow… How can you be so strong?$"

Route110_Text_AbigailRematchPostBattle:
	.string "Were you going for a record?\p"
	.string "I'm sorry if I held you up!$"

Route110_Text_JasmineIntro:
	.string "I've been pedaling nonstop. My legs are\n"
	.string "solid rock!$"

Route110_Text_JasmineDefeated:
	.string "I hope I don't cramp up…$"

Route110_Text_JasminePostBattle:
	.string "You've got GYM BADGES? That explains\n"
	.string "how strong you are!$"

Route110_Text_EdwardIntro:
	.string "I foresaw your arrival! There's no way I\n"
	.string "can lose!$"

Route110_Text_EdwardDefeated:
	.string "I failed to foresee my own defeat! Baba\n"
	.string "would be ashamed!$"

Route110_Text_EdwardPostBattle:
	.string "I see your future…\p"
	.string "Hmm… I see a shining golden light…$"

Route110_Text_JaclynIntro:
	.string "Ahahahaha! Prepare to be dazzled by my\n"
	.string "wonders!$"

Route110_Text_JaclynDefeated:
	.string "I lost, but it was wondrous!$"

Route110_Text_JaclynPostBattle:
	.string "You only won because it was a wonder!\n"
	.string "Yes, a wonder! Don't think you can win\l"
	.string "every time!$"

Route110_Text_EdwinIntro:
	.string "Might I see your POKéMON? Just a peek,\n"
	.string "please?$"

Route110_Text_EdwinDefeated:
	.string "And I was so close to finishing my\n"
	.string "collection…$"

Route110_Text_EdwinPostBattle:
	.string "When I see a POKéMON I don't know, my\n"
	.string "collector's passion bursts into flames!$"

Route110_Text_EdwinRegister:
	.string "I like collecting POKéNAV\n"
	.string "registrations, too…$"

Route110_Text_EdwinRematchIntro:
	.string "Hello again! Have you caught any new\n"
	.string "POKéMON?\p"
	.string "May I see them? Just a peek, please?$"

Route110_Text_EdwinRematchDefeated:
	.string "Your POKéMON… I'm so jealous.$"

Route110_Text_EdwinRematchPostBattle:
	.string "Oh, I long to make every rare POKéMON\n"
	.string "mine, like collecting all seven Dragon\l"
	.string "Balls!$"

Route110_Text_DaleIntro:
	.string "Hey! Don't creep up on me like that!$"

Route110_Text_DaleDefeated:
	.string "Lost! Dang it!$"

Route110_Text_DalePostBattle:
	.string "Fishing is all about concentration.\n"
	.string "Keep your focus on the floater, like a\l"
	.string "martial artist.$"

Route110_Text_IsabelIntro:
	.string "Ahahaha! I'd go anywhere to show off my\n"
	.string "delightful POKéMON.$"

Route110_Text_IsabelDefeated:
	.string "Oh my, that didn't go well.$"

Route110_Text_IsabelPostBattle:
	.string "Instead of fighting, I should be\n"
	.string "showing off my POKéMON at the FAN CLUB.$"

Route110_Text_IsabelRegister:
	.string "That was nowhere near what I can do to\n"
	.string "show off my POKéMON.\p"
	.string "I'll have you as my captive audience as\n"
	.string "often as possible!$"

Route110_Text_IsabelRematchIntro:
	.string "Ahahahaha! I'd be happy to show off my\n"
	.string "POKéMON as often as you like!$"

Route110_Text_IsabelRematchDefeated:
	.string "Oh my, that didn't go well.$"

Route110_Text_IsabelRematchPostBattle:
	.string "I don't think I could ever stop showing\n"
	.string "off my POKéMON.\p"
	.string "But I like to battle, too!$"

Route110_Text_TimmyIntro:
	.string "I found some really cool POKéMON in the\n"
	.string "grass around here!$"

Route110_Text_TimmyDefeated:
	.string "Being cool wasn't enough to win…$"

Route110_Text_TimmyPostBattle:
	.string "It's hard to fight with POKéMON you\n"
	.string "just caught.$"

Route110_Text_AlyssaIntro:
	.string "I fell off CYCLING ROAD…\p"
	.string "I'll get over my embarrassment by\n"
	.string "battling you!$"

Route110_Text_AlyssaDefeated:
	.string "Oops, I lost again!$"

Route110_Text_AlyssaPostBattle:
	.string "Falling… Losing… This is so humiliating!$"

Route110_Text_JosephIntro:
	.string "Okay! Full-throttle time! If you can't\n"
	.string "keep the rhythm, you get left behind!$"

Route110_Text_JosephDefeated:
	.string "You kept the rhythm, all right…$"

Route110_Text_JosephPostBattle:
	.string "This won't bring me down! Losing makes\n"
	.string "me a better man!$"

Route110_Text_KalebIntro:
	.string "When cute POKéMON help each other…\n"
	.string "there's no more adorable sight!$"

Route110_Text_KalebDefeated:
	.string "Have you no mercy at all?$"

Route110_Text_KalebPostBattle:
	.string "Okay, okay, you did your best, my\n"
	.string "pretties.$"

Route111_Text_DrewIntro:
	.string "Oh, hey! Those GO-GOGGLES suit you. But\n"
	.string "I think they look better on me.\p"
	.string "Let's settle who wears them better with\n"
	.string "a battle!$"

Route111_Text_DrewDefeat:
	.string "The GO-GOGGLES made it impossible to\n"
	.string "see what was coming from my sides.$"

Route111_Text_DrewPostBattle:
	.string "GO-GOGGLES let you get through\n"
	.string "sandstorms. That makes me happy!$"

Route111_Text_HeidiIntro:
	.string "I'm having a picnic in the desert.\p"
	.string "There's always a TRAINER around, so I\n"
	.string "can enjoy a battle here, too!$"

Route111_Text_HeidiDefeat:
	.string "Ohhh! That was mean!$"

Route111_Text_HeidiPostBattle:
	.string "When you fight in a sandstorm, watch\n"
	.string "your POKéMON's HP.\p"
	.string "It can faint if you don't keep an eye on\n"
	.string "it!$"

Route111_Text_BeauIntro:
	.string "These GO-GOGGLES make me feel like a\n"
	.string "true hero. Right now, I'm unbeatable!$"

Route111_Text_BeauDefeat:
	.string "Spirit alone isn't enough to win…$"

Route111_Text_BeauPostBattle:
	.string "I'm going to be a real hero one day, like\n"
	.string "the Great Saiyaman. I'll work harder to\l"
	.string "make me and my POKéMON stronger.$"

Route111_Text_BeckyIntro:
	.string "I heard there are fossils in the desert.\n"
	.string "Where could they be?$"

Route111_Text_BeckyDefeat:
	.string "I fell short…$"

Route111_Text_BeckyPostBattle:
	.string "If fossils can be found in the desert,\n"
	.string "it must have been a sea once.$"

Route111_Text_DustyIntro:
	.string "For thirty years I have searched for\n"
	.string "ancient ruins! And now I am to be\l"
	.string "challenged?$"

Route111_Text_DustyDefeat:
	.string "While I searched for ruins, I never\n"
	.string "searched for strong POKéMON.$"

Route111_Text_DustyPostBattle:
	.string "For thirty years I've searched for\n"
	.string "ancient ruins!\p"
	.string "Wait, was it forty years? Which was it\n"
	.string "again?$"

Route111_Text_DustyRegister:
	.string "I've never searched for strong\n"
	.string "POKéMON.\p"
	.string "But, oddly enough, I do adore POKéNAVS.$"

Route111_Text_DustyRematchIntro:
	.string "For thirty years I've searched for\n"
	.string "ancient ruins!\p"
	.string "Wait, was it forty? Never mind. Are you\n"
	.string "challenging me?$"

Route111_Text_DustyRematchDefeat:
	.string "I've found no ruins, and I've found no\n"
	.string "strong POKéMON either…$"

Route111_Text_DustyPostRematch:
	.string "For thirty years I've searched for\n"
	.string "ancient ruins!\p"
	.string "Wait, or was it forty years?\p"
	.string "Hmm… Maybe even fifty… How long has it\n"
	.string "been?$"

Route111_Text_TravisIntro:
	.string "I'm bursting with pep! And so is my\n"
	.string "POKéMON!$"

Route111_Text_TravisDefeat:
	.string "My POKéMON ran out of pep…$"

Route111_Text_TravisPostBattle:
	.string "When I see a TRAINER with lots of pep, I\n"
	.string "can't help but stare.$"

Route111_Text_IreneIntro:
	.string "I don't know where you're headed, but\n"
	.string "would you like to battle?$"

Route111_Text_IreneDefeat:
	.string "Ugh, you're annoyingly good!$"

Route111_Text_IrenePostBattle:
	.string "I'm thinking I should go to MT. CHIMNEY,\n"
	.string "but the view around here is very nice,\l"
	.string "too.$"

Route111_Text_DaisukeIntro:
	.string "To train myself, I challenge everyone I\n"
	.string "meet!$"

Route111_Text_DaisukeDefeat:
	.string "Okay, okay, I give up!$"

Route111_Text_DaisukePostBattle:
	.string "All I can do is keep training until I can\n"
	.string "beat strong TRAINERS like you.$"

Route111_Text_WiltonIntro:
	.string "Show me how much stronger you've made\n"
	.string "your POKéMON.$"

Route111_Text_WiltonDefeat:
	.string "I see. You have toughened them greatly.$"

Route111_Text_WiltonPostBattle:
	.string "POKéMON and TRAINERS learn so much\n"
	.string "through battle.\p"
	.string "What matters is to never give up, even\n"
	.string "when you lose.$"

Route111_Text_WiltonRegister:
	.string "There is much to learn from your\n"
	.string "training style.\p"
	.string "I request a rematch, if it pleases you.$"

Route111_Text_WiltonRematchIntro:
	.string "We're training here to raise our game to\n"
	.string "the next level. Stay and train with us!$"

Route111_Text_WiltonRematchDefeat:
	.string "Ooh, not bad at all!$"

Route111_Text_WiltonPostRematch:
	.string "Strong as you are, you should set your\n"
	.string "sights on the POKéMON LEAGUE.$"

Route111_Text_BrookeIntro:
	.string "Your POKéMON look like seasoned\n"
	.string "performers. I must request a match.$"

Route111_Text_BrookeDefeat:
	.string "They didn't only look strong, they truly\n"
	.string "are strong!$"

Route111_Text_BrookePostBattle:
	.string "I thought I was raising my POKéMON\n"
	.string "diligently, but oh no, there's still much\l"
	.string "to be done.$"

Route111_Text_BrookeRegister:
	.string "I'd love to befriend more strong people\n"
	.string "like you!$"

Route111_Text_BrookeRematchIntro:
	.string "Teach your POKéMON different moves\n"
	.string "and they'll get stronger or weaker.\p"
	.string "What moves have you taught yours?$"

Route111_Text_BrookeRematchDefeat:
	.string "You've taught them well!$"

Route111_Text_BrookePostRematch:
	.string "Maybe I should have kept my POKéMON\n"
	.string "from evolving until they learned better\l"
	.string "moves…$"

Route111_Text_CeliaIntro:
	.string "I never should have picked a place like\n"
	.string "this for a picnic!$"

Route111_Text_CeliaDefeat:
	.string "Aww, I knew I shouldn't have come!$"

Route111_Text_CeliaPostBattle:
	.string "In a sandstorm like this, I can't even\n"
	.string "set up a picnic with my GO-GOGGLES on…$"

Route111_Text_BryanIntro:
	.string "Just how strong are you? We shall\n"
	.string "uncover that secret!$"

Route111_Text_BryanDefeat:
	.string "Oh! Your strength! It remains a\n"
	.string "mystery!$"

Route111_Text_BryanPostBattle:
	.string "This desert guards countless mysteries\n"
	.string "beneath its shifting sands!$"

Route111_Text_BrandenIntro:
	.string "Lose to me and I'll share my sandwich\n"
	.string "with you.$"

Route111_Text_BrandenDefeat:
	.string "Tch! I figured a sandwich would be a\n"
	.string "good enough bribe…$"

Route111_Text_BrandenPostBattle:
	.string "My SANDSHREW loves eating my\n"
	.string "sandwiches. It's got a Saiyan appetite.$"

Route111_Text_TyronIntro:
	.string "This is my favorite kind of POKéMON, bar\n"
	.string "none!$"

Route111_Text_TyronDefeat:
	.string "Wait! Did you at least get a good look\n"
	.string "at my POKéMON?$"

Route111_Text_TyronPostBattle:
	.string "In a battle, I get a kick out of showing\n"
	.string "off my POKéMON.\p"
	.string "I bet everyone feels that way when\n"
	.string "they step into a fight!$"

Route111_Text_CelinaIntro:
	.string "Come on, show me how to add a little\n"
	.string "thrill to my life.$"

Route111_Text_CelinaDefeat:
	.string "Oh my… That was almost too thrilling.$"

Route111_Text_CelinaPostBattle:
	.string "My heart is still pounding. What a\n"
	.string "fabulous TRAINER you are.$"

Route111_Text_HaydenIntro:
	.string "When you're as famished as I am, there's\n"
	.string "no room for pity!$"

Route111_Text_HaydenDefeat:
	.string "Ugh, my stomach…$"

Route111_Text_HaydenPostBattle:
	.string "My belly's growling! Maybe I'll grill up\n"
	.string "some BERRIES…$"

Route111_Text_BiancaIntro:
	.string "Did you come from MAUVILLE? Then you\n"
	.string "must be full of energy!$"

Route111_Text_BiancaDefeat:
	.string "Ooh lala! That's a lot to handle!$"

Route111_Text_BiancaPostBattle:
	.string "This road here… You've got quite a ways\n"
	.string "to travel.$"

Route112_Text_BriceIntro:
	.string "Hahahaha! How about a battle? You and\n"
	.string "me!\p"
	.string "Hahahaha!$"

Route112_Text_BriceDefeat:
	.string "I lost! Hahahaha, what a great fight!$"

Route112_Text_BricePostBattle:
	.string "Hahahahaha! A bug flew up my nose!\n"
	.string "Hahahaha-ah-choo!$"

Route112_Text_TrentIntro:
	.string "My legs are solid from pounding up and\n"
	.string "down the mountains.\p"
	.string "They won't buckle easily, friend!$"

Route112_Text_TrentDefeat:
	.string "Ow, ow! My legs seized up!$"

Route112_Text_TrentPostBattle:
	.string "Try hiking, and I mean really pounding,\n"
	.string "up these mountain trails with a pack\l"
	.string "weighing dozens of pounds.\p"
	.string "That, my friend, is how a martial artist\n"
	.string "builds a serious body.$"

Route112_Text_TrentRegister:
	.string "Ow, my legs cramped up. Can you grab\n"
	.string "some bandages from my backpack?\p"
	.string "No, that's my POKéNAV! Oh, fine, I'll\n"
	.string "register you.$"

Route112_Text_TrentRematchIntro:
	.string "I've stayed in shape by hiking. I've got\n"
	.string "power to spare!$"

Route112_Text_TrentRematchDefeat:
	.string "I got beaten in power?$"

Route112_Text_TrentRematchPostBattle:
	.string "I hear some seriously tough TRAINERS\n"
	.string "wait at the top of MT. CHIMNEY.\p"
	.string "I intend to get up there and challenge\n"
	.string "them!$"

Route112_Text_LarryIntro:
	.string "I'm tough. I won't cry if I lose.$"

Route112_Text_LarryDefeat:
	.string "Waaaaah!$"

Route112_Text_LarryPostBattle:
	.string "I'm not crying because I miss my mommy!\n"
	.string "Sniff…$"

Route112_Text_CarolIntro:
	.string "When you're out on a picnic, you simply\n"
	.string "must sing! Come on, sing along!$"

Route112_Text_CarolDefeat:
	.string "Oh, you're amazing!$"

Route112_Text_CarolPostBattle:
	.string "It doesn't matter how well you sing or\n"
	.string "fight with POKéMON.\p"
	.string "Whoever has the most fun wins!$"

Route112_Text_BryantIntro:
	.string "I caught some hot POKéMON at FIERY\n"
	.string "PATH! Take a look!$"

Route112_Text_BryantDefeat:
	.string "What a wild ride!$"

Route112_Text_BryantPostBattle:
	.string "I like the way you fight. It has a\n"
	.string "certain flair to it.$"

Route112_Text_ShaylaIntro:
	.string "Oh, what an adorable TRAINER! Please,\n"
	.string "I'm in the mood for a romantic battle!\l"
	.string "I'm fairly decent!$"

Route112_Text_ShaylaDefeat:
	.string "Oh my, you're so strong! That gave me\n"
	.string "quite a jolt!$"

Route112_Text_ShaylaPostBattle:
	.string "Are you busy right now? I was thinking\n"
	.string "we could have a rematch right now…\p"
	.string "But it's all right if you're busy.$"

Route113_Text_JaylenIntro:
	.string "Can you guess why it's so chilly around\n"
	.string "here?$"

Route113_Text_JaylenDefeat:
	.string "Pee-yew! What a stinker!$"

Route113_Text_JaylenPostBattle:
	.string "The volcanic ash blocks the sun, so it\n"
	.string "never gets very warm.\p"
	.string "That's good for me. I can't stand heat!$"

Route113_Text_DillonIntro:
	.string "That volcanic eruption proves the\n"
	.string "earth itself is alive.$"

Route113_Text_DillonDefeat:
	.string "Whoa, you're seriously strong!$"

Route113_Text_DillonPostBattle:
	.string "Ouch! Owww! I can't see a thing! Ashes\n"
	.string "in my eyelashes!\p"
	.string "Get it? Ashes and eyelashes?\p"
	.string "Okay, that was terrible, sorry…$"

Route113_Text_MadelineIntro:
	.string "I use this parasol to keep the filthy,\n"
	.string "yucky volcanic ash off my dear NUMEL.$"

Route113_Text_MadelineDefeat:
	.string "Huff, huff… I'm exhausted…$"

Route113_Text_MadelinePostBattle:
	.string "You're remarkably good. I'm truly\n"
	.string "impressed!$"

Route113_Text_MadelineRegister:
	.string "Come, step under my parasol. Let me\n"
	.string "register you in my POKéNAV.$"

Route113_Text_MadelineRematchIntro:
	.string "Oh, hello, it's been a while, hasn't it?\n"
	.string "May I invite you to battle?$"

Route113_Text_MadelineRematchDefeat:
	.string "Oh, how marvelous!$"

Route113_Text_MadelinePostRematch:
	.string "You've stayed very good at this. I must\n"
	.string "say I'm impressed!$"

Route113_Text_LaoIntro:
	.string "From the ashes I spring forth! Hiyah! I\n"
	.string "challenge thee!$"

Route113_Text_LaoDefeat:
	.string "With honor, I accept my defeat!$"

Route113_Text_LaoPostBattle:
	.string "I must sharpen my art of concealment.\n"
	.string "Farewell.$"

Route113_Text_LaoRegister:
	.string "Yiiyaah! Behold the ancient ninja art of\n"
	.string "POKéNAV registration!$"

Route113_Text_LaoRematchIntro:
	.string "From the ashes I spring forth! Hiyah! I\n"
	.string "challenge thee!$"

Route113_Text_LaoRematchDefeat:
	.string "With honor, I accept my defeat!$"

Route113_Text_LaoPostRematch:
	.string "My flawless concealment was undone by\n"
	.string "my immature fighting skills…\p"
	.string "I bid thee farewell.$"

Route113_Text_LungIntro:
	.string "Thanks for finding me! But we still have\n"
	.string "to fight!$"

Route113_Text_LungDefeat:
	.string "Behold my ninjutsu… “VOLCANIC ASH\n"
	.string "SWIRL CLOAK”!\p"
	.string "…Huh? It's over already?$"

Route113_Text_LungPostBattle:
	.string "You know what's lousy about hiding?\n"
	.string "It's lonely if no one comes looking.$"

Route113_Text_ToriIntro:
	.string "TORI: We both collect ashes. We battle\n"
	.string "POKéMON, too.$"

Route113_Text_ToriDefeat:
	.string "TORI: We lost… It's boring, so I'm going\n"
	.string "to go get more ashes.$"

Route113_Text_ToriPostBattle:
	.string "TORI: I wonder how much ash we've got.\n"
	.string "Enough for a WHITE FLUTE, I hope.$"

Route113_Text_ToriNotEnoughMons:
	.string "TORI: We want to battle 2-on-2. If we\n"
	.string "didn't, we'd lose!$"

Route113_Text_TiaIntro:
	.string "TIA: We both collect ashes. We battle\n"
	.string "POKéMON, too.$"

Route113_Text_TiaDefeat:
	.string "TIA: We lost… How boring. I'll go collect\n"
	.string "more ash.$"

Route113_Text_TiaPostBattle:
	.string "TIA: Look at all this ash! Surely it's\n"
	.string "enough for a WHITE FLUTE!$"

Route113_Text_TiaNotEnoughMons:
	.string "TIA: We only fight 2-on-2. Otherwise\n"
	.string "we'd lose for sure!$"

Route113_Text_CobyIntro:
	.string "Pfft, with these wings, I can swat you\n"
	.string "away!$"

Route113_Text_CobyDefeat:
	.string "Wh-what?$"

Route113_Text_CobyPostBattle:
	.string "I never know what to say when I lose\n"
	.string "this fast…$"

Route113_Text_SophieIntro:
	.string "The warmth here is making me drowsy.\n"
	.string "Fight me so I can stay awake.$"

Route113_Text_SophieDefeat:
	.string "This has to be a dream. It has to be…$"

Route113_Text_SophiePostBattle:
	.string "Losing makes me so mad… I'm just going\n"
	.string "to nap right here!\p"
	.string "Zzz!$"

Route113_Text_LawrenceIntro:
	.string "Were you maybe in the middle of\n"
	.string "gathering volcanic ash?$"

Route113_Text_LawrenceDefeat:
	.string "Ehehe. You beat us fair and square.$"

Route113_Text_LawrencePostBattle:
	.string "Maybe I should bury myself under the\n"
	.string "ash, too.$"

Route113_Text_WyattIntro:
	.string "Y-you want to fight me? Even though I\n"
	.string "just caught my POKéMON?$"

Route113_Text_WyattDefeat:
	.string "Y-you're happy to win? Even against\n"
	.string "someone like me?$"

Route113_Text_WyattPostBattle:
	.string "Oh, now you want to say something to\n"
	.string "the loser?\p"
	.string "Aren't you just the coolest? Hmph!$"

Route114_Text_LennyIntro:
	.string "Yodelayhihoo!\p"
	.string "… …\p"
	.string "You're supposed to shout\n"
	.string "“yodelayhihoo” back, since there's no\l"
	.string "echo here!$"

Route114_Text_LennyDefeat:
	.string "Yodelayhihoo!$"

Route114_Text_LennyPostBattle:
	.string "When I was a wee tyke, I believed\n"
	.string "someone was copying me and shouting\l"
	.string "back, “Yodelayhihoo.”$"

Route114_Text_LucasIntro:
	.string "Don't come into these mountains\n"
	.string "unprepared!$"

Route114_Text_LucasDefeat:
	.string "The mountains show no mercy…$"

Route114_Text_LucasPostBattle:
	.string "In winter, mountains turn deadly with\n"
	.string "blizzards and avalanches.$"

Route114_Text_ShaneIntro:
	.string "Camping's fun! You can fish, roast\n"
	.string "marshmallows, and tell spooky stories!\p"
	.string "But the best part is POKéMON battles!$"

Route114_Text_ShaneDefeat:
	.string "Way, way too strong!$"

Route114_Text_ShanePostBattle:
	.string "It's awesome that I get to go camping\n"
	.string "with my POKéMON.$"

Route114_Text_NancyIntro:
	.string "I should work off that big meal. Let's\n"
	.string "have a match!$"

Route114_Text_NancyDefeat:
	.string "Oh, no, no, no!$"

Route114_Text_NancyPostBattle:
	.string "That meal was delicious. Now I'm getting\n"
	.string "sleepy…$"

Route114_Text_SteveIntro:
	.string "Ufufufufufu… Want to battle my\n"
	.string "POKéMON?$"

Route114_Text_SteveDefeat:
	.string "M-my poor POKéMON…$"

Route114_Text_StevePostBattle:
	.string "A big body, all lumpy and hard, enormous\n"
	.string "horns, and vicious fangs…\p"
	.string "Ufufufufu… I wish I had a POKéMON like\n"
	.string "that…$"

Route114_Text_SteveRegister:
	.string "Don't forget what you've done to me!\n"
	.string "I'll make sure you can't forget!$"

Route114_Text_SteveRematchIntro:
	.string "Ufufufufufu… Come now, fight my\n"
	.string "POKéMON…$"

Route114_Text_SteveRematchDefeat:
	.string "I feel so lucky to see your POKéMON…$"

Route114_Text_StevePostRematch:
	.string "Ufufufufufu…\p"
	.string "When I watch POKéMON battle, I get all\n"
	.string "shivery and shaky…$"

Route114_Text_BernieIntro:
	.string "If you light a campfire, make sure you\n"
	.string "have water handy.$"

Route114_Text_BernieDefeat:
	.string "Thanks for putting out my fire!$"

Route114_Text_BerniePostBattle:
	.string "You really have to be careful with any\n"
	.string "kind of fire in a forest.\p"
	.string "Don't ever underestimate the power of\n"
	.string "fire.$"

Route114_Text_BernieRegister:
	.string "You lit a fire in my heart. Let's register\n"
	.string "each other!$"

Route114_Text_BernieRematchIntro:
	.string "Did you remember to keep water handy\n"
	.string "for your campfires?$"

Route114_Text_BernieRematchDefeat:
	.string "Looks like I got doused before I could\n"
	.string "blaze up.$"

Route114_Text_BerniePostRematch:
	.string "You really have to be careful with any\n"
	.string "kind of fire in a forest.\p"
	.string "Don't ever underestimate the power of\n"
	.string "fire.$"

Route114_Text_ClaudeIntro:
	.string "If this were a fishing contest, you\n"
	.string "wouldn't have a prayer. So, bring on your\l"
	.string "POKéMON!$"

Route114_Text_ClaudeDefeat:
	.string "If this were fishing, I would have won…$"

Route114_Text_ClaudePostBattle:
	.string "I think I'll try my luck landing a big one\n"
	.string "at METEOR FALLS.\p"
	.string "There has to be something in there. I\n"
	.string "just know it.$"

Route114_Text_NolanIntro:
	.string "I like to fish. But I also like to battle!\p"
	.string "If anyone challenges me, I'm there, even\n"
	.string "if I'm mid-cast.$"

Route114_Text_NolanDefeat:
	.string "I love to fight, but that doesn't mean\n"
	.string "I'm any good…$"

Route114_Text_NolanPostBattle:
	.string "Next time I'll win!\p"
	.string "I always say that, which is why I can't\n"
	.string "quit fishing or POKéMON.$"

Route114_Text_TyraIntro:
	.string "TYRA: Why not? I'm in the mood. Let me\n"
	.string "teach you a thing or two about POKéMON.$"

Route114_Text_TyraDefeat:
	.string "TYRA: What an amazing fighting style!$"

Route114_Text_TyraPostBattle:
	.string "TYRA: I've been teaching my junior IVY\n"
	.string "the ropes.$"

Route114_Text_TyraNotEnoughMons:
	.string "TYRA: Giggle… If you want to battle us,\n"
	.string "just one POKéMON isn't enough!$"

Route114_Text_IvyIntro:
	.string "IVY: So who was it that taught you\n"
	.string "about POKéMON?$"

Route114_Text_IvyDefeat:
	.string "IVY: What an amazing fighting style!$"

Route114_Text_IvyPostBattle:
	.string "IVY: I only started training POKéMON\n"
	.string "because TYRA, my mentor, showed me how!$"

Route114_Text_IvyNotEnoughMons:
	.string "IVY: You only have one POKéMON? It must\n"
	.string "get lonely.$"

Route114_Text_KaiIntro:
	.string "I just hooked a big one! A real whopper!$"

Route114_Text_KaiDefeat:
	.string "What's going on? Did mine shrink?$"

Route114_Text_KaiPostBattle:
	.string "Fine! I'll just catch a bigger one!$"

Route114_Text_CharlotteIntro:
	.string "Me? I'm much more than a pretty face!$"

Route114_Text_CharlotteDefeat:
	.string "Not cute at all!$"

Route114_Text_CharlottePostBattle:
	.string "I don't want a POKéMON that's only cute.\p"
	.string "I love cute ones with a quirk or two!$"

Route114_Text_AngelinaIntro:
	.string "Have you evolved many of your POKéMON?$"

Route114_Text_AngelinaDefeat:
	.string "Oh, I see. Good to know.$"

Route114_Text_AngelinaPostBattle:
	.string "Some POKéMON change so much when they\n"
	.string "evolve, it's startling! Like a Saiyan\l"
	.string "going Super!$"

Route115_Text_TimothyIntro:
	.string "Hm… You look quite capable… Allow me to\n"
	.string "keep you company!$"

Route115_Text_TimothyDefeat:
	.string "You're far stronger than I imagined!$"

Route115_Text_TimothyPostBattle:
	.string "There's no such thing as a born genius.\n"
	.string "It all depends on effort!\p"
	.string "That is what I believe…$"

Route115_Text_TimothyRegister:
	.string "Hmm… A loss this thorough is a distant\n"
	.string "memory.\p"
	.string "If you'd allow it, I wish for another\n"
	.string "chance to fight.$"

Route115_Text_TimothyRematchIntro:
	.string "Hm… Your agility speaks for itself, as\n"
	.string "always. Come, keep me company!$"

Route115_Text_TimothyRematchDefeat:
	.string "Still as strong as ever!$"

Route115_Text_TimothyPostRematch:
	.string "Effort is everything!\p"
	.string "I lost because I haven't put in enough\n"
	.string "effort!$"

Route115_Text_KoichiIntro:
	.string "You! Face my MACHOP! Battle now!$"

Route115_Text_KoichiDefeat:
	.string "Ow, ow, ow, ow!$"

Route115_Text_KoichiPostBattle:
	.string "My MACHOP crew!\p"
	.string "As long as they chase strength, I'll\n"
	.string "grow strong right alongside them!$"

Route115_Text_NobIntro:
	.string "My best skill is busting bricks with my\n"
	.string "forehead!$"

Route115_Text_NobDefeat:
	.string "Ugwaaaah! My head's cracked!$"

Route115_Text_NobPostBattle:
	.string "I've been teaching my POKéMON karate.\p"
	.string "Looks like they'll get a lot better than\n"
	.string "me. I'm excited about that.$"

Route115_Text_NobRegister:
	.string "I'm impressed! Give me a rematch once\n"
	.string "I've redone my training!$"

Route115_Text_NobRematchIntro:
	.string "After you beat me, we trained hard to\n"
	.string "sharpen our skills. Come on, give us a\l"
	.string "rematch!$"

Route115_Text_NobRematchDefeat:
	.string "Ugwaaah! Lost again!$"

Route115_Text_NobPostRematch:
	.string "My POKéMON will get stronger! I'm\n"
	.string "doubling my training!$"

Route115_Text_CyndyIntro:
	.string "This beach is my secret training spot!\n"
	.string "Don't barge in!$"

Route115_Text_CyndyDefeat:
	.string "I still haven't trained hard enough!$"

Route115_Text_CyndyPostBattle:
	.string "The sand cushions every impact and\n"
	.string "keeps you from getting hurt. This is the\l"
	.string "perfect place to train.$"

Route115_Text_CyndyRegister:
	.string "Okay, fine, you're free to come here. In\n"
	.string "return, I want to battle you again.$"

Route115_Text_CyndyRematchIntro:
	.string "All right, let's do this!$"

Route115_Text_CyndyRematchDefeat:
	.string "I can fight, but my POKéMON…$"

Route115_Text_CyndyPostRematch:
	.string "Even when I lose, I still enjoy it. It\n"
	.string "must be because I love POKéMON.$"

Route115_Text_HectorIntro:
	.string "I own a rare POKéMON! Want to see it?$"

Route115_Text_HectorDefeat:
	.string "You… you're after my POKéMON, aren't\n"
	.string "you?$"

Route115_Text_HectorPostBattle:
	.string "I own this rare POKéMON, and that's all I\n"
	.string "need to be happy.$"

Route115_Text_KyraIntro:
	.string "I fight while I run! See if you can keep\n"
	.string "pace!$"

Route115_Text_KyraDefeat:
	.string "Huff, huff…$"

Route115_Text_KyraPostBattle:
	.string "I made the mistake of trying to battle\n"
	.string "while running!\p"
	.string "I should go for a run to calm down…$"

Route115_Text_JaidenIntro:
	.string "Take this! Ultra POKéMON ninja strike!$"

Route115_Text_JaidenDefeat:
	.string "Waaah! Our plan fell apart!$"

Route115_Text_JaidenPostBattle:
	.string "But admit it, my POKéMON were ultra,\n"
	.string "right?$"

Route115_Text_HeleneIntro:
	.string "My POKéMON hit with the strength of a\n"
	.string "black belt!$"

Route115_Text_HeleneDefeat:
	.string "This is beyond humiliating!$"

Route115_Text_HelenePostBattle:
	.string "I rarely meet anyone better than me…\p"
	.string "I get it now! You're a GYM LEADER, aren't\n"
	.string "you?$"

Route115_Text_AlixIntro:
	.string "Our eyes met! Now there's no escape!$"

Route115_Text_AlixDefeat:
	.string "Gah! Impressive!$"

Route115_Text_AlixPostBattle:
	.string "Oh, well. I think I'll TELEPORT home.$"

Route115_Text_MarleneIntro:
	.string "You interrupted my meditation… and now\n"
	.string "you'll pay for it.$"

Route115_Text_MarleneDefeat:
	.string "You've shattered my focus!$"

Route115_Text_MarlenePostBattle:
	.string "I came here to meditate with my\n"
	.string "POKéMON, but it's far from peaceful…$"

Route116_Text_ClarkIntro:
	.string "If the tunnel doesn't go through, I'll\n"
	.string "just go over the top.$"

Route116_Text_ClarkDefeat:
	.string "Huff… huff… That wore me out…$"

Route116_Text_ClarkPostBattle:
	.string "No big deal if there's no tunnel. To a\n"
	.string "HIKER, mountains are roads!$"

Route116_Text_JoeyIntro:
	.string "My POKéMON are the best! Take a look!$"

Route116_Text_JoeyDefeat:
	.string "Ouch, a scrape! Time for a bandage!$"

Route116_Text_JoeyPostBattle:
	.string "Bandages are badges of toughness! And\n"
	.string "I've got a new one!$"

Route116_Text_JoseIntro:
	.string "My BUG POKéMON are no pushovers! Let's\n"
	.string "fight!$"

Route116_Text_JoseDefeat:
	.string "I lost! I was sure I had you!$"

Route116_Text_JosePostBattle:
	.string "BUG POKéMON evolve quickly, so they get\n"
	.string "strong quickly, too.$"

Route116_Text_JaniceIntro:
	.string "Let me show you how strong my adorable\n"
	.string "POKéMON is!$"

Route116_Text_JaniceDefeat:
	.string "You're a cut above me…$"

Route116_Text_JanicePostBattle:
	.string "POKéMON that have both cuteness and\n"
	.string "power, that's the ideal, I think.$"

Route116_Text_JerryIntro:
	.string "We learn all sorts of things at the\n"
	.string "TRAINER'S SCHOOL.\p"
	.string "I want to test them out for real!$"

Route116_Text_JerryDefeat:
	.string "I skipped too many classes… That's why\n"
	.string "I lost.$"

Route116_Text_JerryPostBattle:
	.string "I'll have to retake some classes at the\n"
	.string "TRAINER'S SCHOOL. If I don't, YAMCHA\l"
	.string "will be steamed.$"

Route116_Text_JerryRegister1:
	.string "They taught us at the TRAINER'S SCHOOL\n"
	.string "that a POKéNAV can register TRAINERS.\p"
	.string "I don't quite understand what that\n"
	.string "means, so mind if I try it out?$"

Route116_Text_JerryRegister2:
	.string "They taught us at the TRAINER'S SCHOOL\n"
	.string "that a POKéNAV can register TRAINERS.\p"
	.string "I don't quite understand what that\n"
	.string "means, so mind if I try it out?$"

Route116_Text_JerryRematchIntro:
	.string "I've been studying seriously at the\n"
	.string "TRAINER'S SCHOOL. I won't lose like last\l"
	.string "time.$"

Route116_Text_JerryRematchDefeat:
	.string "Huh? But I studied so hard.$"

Route116_Text_JerryPostRematch:
	.string "I'll have to retake some classes at the\n"
	.string "TRAINER'S SCHOOL. If I don't, YAMCHA\l"
	.string "will be steamed.$"

Route116_Text_KarenIntro:
	.string "I study at school, and I keep studying\n"
	.string "on the way home!$"

Route116_Text_KarenDefeat:
	.string "I'm in shock. I lost?$"

Route116_Text_KarenPostBattle:
	.string "Awww, at this rate I'll never become an\n"
	.string "elegant TRAINER like YAMCHA!$"

Route116_Text_KarenRegister1:
	.string "Oh, wow! Is that a POKéNAV? I have one,\n"
	.string "too! Please register me!$"

Route116_Text_KarenRegister2:
	.string "Oh, wow! Is that a POKéNAV? I have one,\n"
	.string "too! Please register me!$"

Route116_Text_KarenRematchIntro:
	.string "I've studied a whole lot since I saw you.\n"
	.string "You have to see my results!$"

Route116_Text_KarenRematchDefeat:
	.string "I'm stunned. Lost again?$"

Route116_Text_KarenPostRematch:
	.string "You beat YAMCHA? Then I can't beat you.\n"
	.string "Not yet.$"

Route116_Text_SarahIntro:
	.string "Just so you know, nobody has ever\n"
	.string "beaten me at anything.$"

Route116_Text_SarahDefeat:
	.string "Goodness me. This is a brand new\n"
	.string "feeling.$"

Route116_Text_SarahPostBattle:
	.string "My life of luxury gives me everything I\n"
	.string "could possibly desire.\p"
	.string "But when it comes to POKéMON, my wealth\n"
	.string "means nothing.$"

Route116_Text_DawsonIntro:
	.string "When you lay eyes on my POKéMON's\n"
	.string "gorgeous fur, its beauty will leave you\l"
	.string "helpless!$"

Route116_Text_DawsonDefeat:
	.string "Oh, baby, tell me this isn't happening!$"

Route116_Text_DawsonPostBattle:
	.string "Oh, no, no, no! You've messed up my\n"
	.string "POKéMON's fur!\p"
	.string "And my hair, too! I must call my stylist\n"
	.string "at once!$"

Route116_Text_DevanIntro:
	.string "Get ready, because we're going to rock\n"
	.string "you!$"

Route116_Text_DevanDefeat:
	.string "Aiyiyi! Wasn't even close!$"

Route116_Text_DevanPostBattle:
	.string "I should try different POKéMON types.\n"
	.string "That's what I ought to do.$"

Route116_Text_JohnsonIntro:
	.string "This path ends here, and I'm bored. Want\n"
	.string "to fight?$"

Route116_Text_JohnsonDefeat:
	.string "I lost, but that was a blast.$"

Route116_Text_JohnsonPostBattle:
	.string "Why don't you stick around and keep me\n"
	.string "company?$"

Route117_Text_IsaacIntro:
	.string "Listen, could I get you to fight the\n"
	.string "POKéMON I'm raising?$"

Route117_Text_IsaacDefeat:
	.string "You've raised yours beautifully…$"

Route117_Text_IsaacPostBattle:
	.string "POKéMON isn't all about power.\p"
	.string "Polishing a unique side of a POKéMON's\n"
	.string "character is another way to enjoy them.$"

Route117_Text_IsaacRegister:
	.string "I'll train twice as hard. Would you come\n"
	.string "check on us sometime?$"

Route117_Text_IsaacRematchIntro:
	.string "The POKéMON I'm raising look as healthy\n"
	.string "as ever.$"

Route117_Text_IsaacRematchDefeat:
	.string "You really know how to raise them. Maybe\n"
	.string "you've got a talent for the DAY CARE…$"

Route117_Text_IsaacPostRematch:
	.string "Your POKéMON are growing well! You\n"
	.string "should enter them in CONTESTS.$"

Route117_Text_LydiaIntro:
	.string "Please, allow me to judge whether you've\n"
	.string "raised your POKéMON properly.$"

Route117_Text_LydiaDefeat:
	.string "Yes, they're growing just as they\n"
	.string "should.$"

Route117_Text_LydiaPostBattle:
	.string "Try paying closer attention to your\n"
	.string "POKéMON's personalities as you raise\l"
	.string "them.$"

Route117_Text_LydiaRegister:
	.string "I'm delighted to have met such a superb\n"
	.string "TRAINER. I hope we meet again.$"

Route117_Text_LydiaRematchIntro:
	.string "Allow me to judge again whether you've\n"
	.string "raised your POKéMON properly.$"

Route117_Text_LydiaRematchDefeat:
	.string "Admirable growth indeed.$"

Route117_Text_LydiaPostRematch:
	.string "Each POKéMON enjoys different\n"
	.string "{POKEBLOCK}S, depending on its nature.$"

Route117_Text_DylanIntro:
	.string "I'm in the middle of a triathlon, but,\n"
	.string "whatever, let's battle!$"

Route117_Text_DylanDefeat:
	.string "Totally out of gas!$"

Route117_Text_DylanPostBattle:
	.string "I may have blown it…\p"
	.string "I might have dropped to last place\n"
	.string "during that battle…$"

Route117_Text_DylanRegister:
	.string "POKéMON need to be strong, too? Then\n"
	.string "please train me!$"

Route117_Text_DylanRematchIntro:
	.string "I'm right in the middle of a triathlon,\n"
	.string "and I'm way ahead. Let's keep this\l"
	.string "battle quick!$"

Route117_Text_DylanRematchDefeat:
	.string "Out of gas again!$"

Route117_Text_DylanPostRematch:
	.string "I was tops in swimming and cycling, but\n"
	.string "I'm not that confident with POKéMON\l"
	.string "yet.$"

Route117_Text_MariaIntro:
	.string "I train for triathlons with my POKéMON,\n"
	.string "so I'm confident in my speed.$"

Route117_Text_MariaDefeat:
	.string "I guess I need more practice.$"

Route117_Text_MariaPostBattle:
	.string "Training only means something if you\n"
	.string "keep it up regularly.\p"
	.string "Okay! I'll resume my training! Tomorrow!$"

Route117_Text_MariaRegister:
	.string "You look like you're training properly…\n"
	.string "If you like, I'll battle you later!$"

Route117_Text_MariaRematchIntro:
	.string "Are you keeping up with your training? I\n"
	.string "sure am! Let me show you the proof!$"

Route117_Text_MariaRematchDefeat:
	.string "I guess I need more practice.$"

Route117_Text_MariaPostRematch:
	.string "I'll start training again tomorrow. Let's\n"
	.string "fight again sometime!$"

Route117_Text_DerekIntro:
	.string "Once a BUG CATCHER! And now a BUG\n"
	.string "MANIAC!\p"
	.string "But my love for POKéMON hasn't changed!$"

Route117_Text_DerekDefeat:
	.string "My ineptitude hasn't changed either…$"

Route117_Text_DerekPostBattle:
	.string "All I did was follow my heart, and now\n"
	.string "they call me a BUG MANIAC…\p"
	.string "Still, I'm an expert on BUG POKéMON, so\n"
	.string "it's only natural they call me a BUG\l"
	.string "MANIAC.$"

Route117_Text_AnnaIntro:
	.string "ANNA: I'm with my pretty junior partner.\n"
	.string "I have to do well!$"

Route117_Text_AnnaDefeat:
	.string "ANNA: I'm with my pretty junior partner!\n"
	.string "Let me win!$"

Route117_Text_AnnaPostBattle:
	.string "ANNA: Your POKéMON work well together.\p"
	.string "I'd call you second best, right behind\n"
	.string "us!$"

Route117_Text_AnnaAndMegRegister:
	.string "ANNA: We can't take this lying down!\n"
	.string "You'll come back, won't you?$"

Route117_Text_AnnaNotEnoughMons:
	.string "ANNA: To fight us, you need to bring two\n"
	.string "POKéMON.$"

Route117_Text_MegIntro:
	.string "MEG: I'm going to team up with my super\n"
	.string "senior partner and beat you!$"

Route117_Text_MegDefeat:
	.string "MEG: Oh no! I'm so sorry, ANNA! I let you\n"
	.string "down…$"

Route117_Text_MegPostBattle:
	.string "MEG: I dragged ANNA down… If I hadn't,\n"
	.string "she would have won!$"

Route117_Text_MegNotEnoughMons:
	.string "MEG: Do you only have one POKéMON? Then\n"
	.string "we can't battle you.\p"
	.string "We want a 2-on-2 battle.$"

Route117_Text_AnnaRematchIntro:
	.string "ANNA: I can't keep losing in front of my\n"
	.string "junior, can I?$"

Route117_Text_AnnaRematchDefeat:
	.string "ANNA: I just couldn't find my rhythm.$"

Route117_Text_AnnaPostRematch:
	.string "ANNA: Your POKéMON work well together.\p"
	.string "I'd call you second best, right behind\n"
	.string "us!$"

Route117_Text_AnnaRematchNotEnoughMons:
	.string "ANNA: To fight us, you need to bring two\n"
	.string "POKéMON.$"

Route117_Text_MegRematchIntro:
	.string "MEG: I'm going to team up with my senior\n"
	.string "partner and win this time!$"

Route117_Text_MegRematchDefeat:
	.string "MEG: So strong!$"

Route117_Text_MegPostRematch:
	.string "MEG: I fought together with my senior\n"
	.string "partner, but we lost…\p"
	.string "That's so discouraging…$"

Route117_Text_MegRematchNotEnoughMons:
	.string "MEG: Do you only have one POKéMON? Then\n"
	.string "we can't battle you.\p"
	.string "We want a 2-on-2 battle.$"

Route117_Text_MelinaIntro:
	.string "Isn't it nice to battle while looking at\n"
	.string "pretty flowers?$"

Route117_Text_MelinaDefeat:
	.string "Oh, how very impressive!$"

Route117_Text_MelinaPostBattle:
	.string "It feels wonderful to jog while looking\n"
	.string "at flowers.$"

Route117_Text_BrandiIntro:
	.string "Let me show you the power hidden within\n"
	.string "a PSYCHIC POKéMON!$"

Route117_Text_BrandiDefeat:
	.string "Remarkable!$"

Route117_Text_BrandiPostBattle:
	.string "PSYCHIC POKéMON are a puzzle. You\n"
	.string "should try catching a few.$"

Route117_Text_AishaIntro:
	.string "Concentrate on the win. That's how I\n"
	.string "fight!$"

Route117_Text_AishaDefeat:
	.string "I don't waste time being angry about a\n"
	.string "loss. I'd rather train.$"

Route117_Text_AishaPostBattle:
	.string "I think if you worry about losing, you're\n"
	.string "more likely to lose.$"

Route118_Text_RoseIntro:
	.string "The aroma of flowers has a magical\n"
	.string "power. It cleanses body and soul.$"

Route118_Text_RoseDefeat:
	.string "Oh my, it seems I've been beaten.$"

Route118_Text_RosePostBattle:
	.string "Flowers, POKéMON… I love anything that\n"
	.string "smells lovely.\p"
	.string "Anything stinky… no thank you.$"

Route118_Text_RoseRegister:
	.string "Sniff… That scent, it's a POKéNAV! We\n"
	.string "must register each other!$"

Route118_Text_RoseRematchIntro:
	.string "Did the sweet scent draw you here?$"

Route118_Text_RoseRematchDefeat:
	.string "The power of fragrance… didn't help\n"
	.string "much.$"

Route118_Text_RosePostRematch:
	.string "Use a sweet aroma properly, and POKéMON\n"
	.string "will be drawn to it.$"

Route118_Text_PerryIntro:
	.string "BIRD POKéMON that FLY gracefully\n"
	.string "through the sky… They're the best!$"

Route118_Text_PerryDefeat:
	.string "Urgh… Crash landing…$"

Route118_Text_PerryPostBattle:
	.string "You've got great POKéMON. I'll have to\n"
	.string "train mine harder.$"

Route118_Text_ChesterIntro:
	.string "Spread your wings! Go, my BIRD POKéMON!$"

Route118_Text_ChesterDefeat:
	.string "They flew, all right. Straight down…$"

Route118_Text_ChesterPostBattle:
	.string "If they got stronger, they could fly\n"
	.string "more freely, like Goku on the Flying\l"
	.string "Nimbus…$"

Route118_Text_BarnyIntro:
	.string "I'm a FISHERMAN, but I'm a TRAINER, too.\n"
	.string "I'm raising the POKéMON I've caught.$"

Route118_Text_BarnyDefeat:
	.string "I thought my training was going okay…$"

Route118_Text_BarnyPostBattle:
	.string "I couldn't win by training POKéMON while\n"
	.string "I fished…\p"
	.string "Was I doing things by halves?$"

Route118_Text_WadeIntro:
	.string "For FISHERMEN, gear is the key.\p"
	.string "But for TRAINERS, the key ingredients\n"
	.string "are POKéMON and heart, of course!$"

Route118_Text_WadeDefeat:
	.string "You beat me in heart?$"

Route118_Text_WadePostBattle:
	.string "Now that I think about it, fishing is a\n"
	.string "fight between a FISHERMAN and a\l"
	.string "POKéMON.$"

Route118_Text_DaltonIntro:
	.string "Let my music shake your soul!$"

Route118_Text_DaltonDefeat:
	.string "La-la-la…$"

Route118_Text_DaltonPostBattle:
	.string "An electric guitar doesn't always have\n"
	.string "to be noisy…\p"
	.string "Strum it right and it squeezes out a\n"
	.string "heart-stirring melody…$"

Route118_Text_DaltonRegister:
	.string "Once I write better songs, you have to\n"
	.string "come listen, okay?$"

Route118_Text_DaltonRematchIntro:
	.string "A song from my POKéMON and me… May it\n"
	.string "reach your soul.$"

Route118_Text_DaltonRematchDefeat:
	.string "La-la-la…$"

Route118_Text_DaltonPostRematch:
	.string "When I play, my feelings should reach\n"
	.string "you through my electric guitar…$"

Route118_Text_DeandreIntro:
	.string "Go, go, go! POKéMON number 1, 2, and 3!$"

Route118_Text_DeandreDefeat:
	.string "Hang in there, POKéMON! Are you all\n"
	.string "right? POKéMON 1, 2, and 3?!$"

Route118_Text_DeandrePostBattle:
	.string "Isn't it cool that I have a whole\n"
	.string "POKéMON battle team?\p"
	.string "You can copy me. I don't mind!$"

Route119_Text_BrentIntro:
	.string "We're the MIMIC CIRCLE! We MIMIC\n"
	.string "whatever you do!$"

Route119_Text_BrentDefeat:
	.string "Whoopsie! I lost!$"

Route119_Text_BrentPostBattle:
	.string "What's so great about mimicry?\p"
	.string "Fufufu… you'll never understand…$"

Route119_Text_DonaldIntro:
	.string "At last, we meet! My BUG POKéMON will\n"
	.string "keep you company!$"

Route119_Text_DonaldDefeat:
	.string "I wish we'd never crossed paths…$"

Route119_Text_DonaldPostBattle:
	.string "I want to MIMIC you some more. Would\n"
	.string "you hurry up and move?$"

Route119_Text_TaylorIntro:
	.string "If you step forward, we step forward.\p"
	.string "If you turn right, we turn right, too…$"

Route119_Text_TaylorDefeat:
	.string "But if you win, then I lose…$"

Route119_Text_TaylorPostBattle:
	.string "There's no way to MIMIC you winning.\n"
	.string "It's impossible… I'm so frustrated…$"

Route119_Text_DougIntro:
	.string "Yep, you finally caught me! Or were you\n"
	.string "trying to avoid me?$"

Route119_Text_DougDefeat:
	.string "Whoop, what a great match!$"

Route119_Text_DougPostBattle:
	.string "We're the MIMIC CIRCLE! I hope you\n"
	.string "liked our act.$"

Route119_Text_GregIntro:
	.string "You don't know who I am, do you?\p"
	.string "But I don't know you either. So, we'll\n"
	.string "battle!$"

Route119_Text_GregDefeat:
	.string "You're quite strong!$"

Route119_Text_GregPostBattle:
	.string "Until you go away somewhere, we'll keep\n"
	.string "mimicking your every move.$"

Route119_Text_KentIntro:
	.string "The MIMIC CIRCLE was formed by people\n"
	.string "who love to MIMIC.\p"
	.string "A battle starts the instant we meet!$"

Route119_Text_KentDefeat:
	.string "I surrender!$"

Route119_Text_KentPostBattle:
	.string "Why not join our MIMIC CIRCLE?$"

Route119_Text_JacksonIntro:
	.string "Who knows the techniques for survival?\p"
	.string "POKéMON RANGERS, of course!$"

Route119_Text_JacksonDefeat:
	.string "I didn't know enough about POKéMON…$"

Route119_Text_JacksonPostBattle:
	.string "Leave civilization behind and awaken\n"
	.string "the wild spirit within!\p"
	.string "That's our vision.$"

Route119_Text_JacksonRegister:
	.string "Please give me a rematch, and don't\n"
	.string "laugh at how little I know.$"

Route119_Text_JacksonRematchIntro:
	.string "I'm going to regain my wild spirit by\n"
	.string "living together with POKéMON.$"

Route119_Text_JacksonRematchDefeat:
	.string "You've stayed strong!$"

Route119_Text_JacksonPostRematch:
	.string "Believe in your POKéMON. Believe in\n"
	.string "yourself.\p"
	.string "The path will show itself.$"

Route119_Text_CatherineIntro:
	.string "Oh? Look at you.\p"
	.string "For an adventurer, you're traveling\n"
	.string "very light.$"

Route119_Text_CatherineDefeat:
	.string "Accidents happen when you come\n"
	.string "unprepared!$"

Route119_Text_CatherinePostBattle:
	.string "You're traveling light, but you have\n"
	.string "everything you need.\p"
	.string "You're on top of things, mentally and\n"
	.string "physically.$"

Route119_Text_CatherineRegister:
	.string "Do you have a POKéNAV? Every TRAINER\n"
	.string "needs one.\p"
	.string "Oh, you do! Then let's register each\n"
	.string "other!$"

Route119_Text_CatherineRematchIntro:
	.string "How is your journey with POKéMON going?$"

Route119_Text_CatherineRematchDefeat:
	.string "There's still something I'm missing…$"

Route119_Text_CatherinePostRematch:
	.string "Just as you rely on your POKéMON as a\n"
	.string "TRAINER, your POKéMON rely on you.$"

Route119_Text_HughIntro:
	.string "The vast sky holds untold promise!\p"
	.string "Nothing compares to the sheer thrill of\n"
	.string "flight!$"

Route119_Text_HughDefeat:
	.string "Shot down!$"

Route119_Text_HughPostBattle:
	.string "My BIRD POKéMON made my dream of flying\n"
	.string "come true!$"

Route119_Text_PhilIntro:
	.string "I'll show you what my BIRD POKéMON and\n"
	.string "I are truly capable of!$"

Route119_Text_PhilDefeat:
	.string "We didn't have what it takes…$"

Route119_Text_PhilPostBattle:
	.string "Ever since I was a little kid, I've\n"
	.string "admired BIRD POKéMON…$"

Route119_Text_YasuIntro:
	.string "To lurk in shadows and live in darkness…\n"
	.string "That is my destiny.\p"
	.string "I emerge to challenge you!$"

Route119_Text_YasuDefeat:
	.string "I accept my defeat!$"

Route119_Text_YasuPostBattle:
	.string "The defeated slip quietly back into the\n"
	.string "shadows.\p"
	.string "That too is destiny…$"

Route119_Text_TakashiIntro:
	.string "Let your guard down, and you'll pay for\n"
	.string "it!$"

Route119_Text_TakashiDefeat:
	.string "Hm, you're better than you look!$"

Route119_Text_TakashiPostBattle:
	.string "My sneak attack failed…$"

Route119_Text_HideoIntro:
	.string "When you need to hide a tree, use a\n"
	.string "forest!$"

Route119_Text_HideoDefeat:
	.string "I bow before your superior skill.$"

Route119_Text_HideoPostBattle:
	.string "To hide a tree, use a forest! To hide a\n"
	.string "POKéMON, use a POKéMON!\p"
	.string "There's no deep, hidden meaning to that.$"

Route119_Text_ChrisIntro:
	.string "You spoke to me… so you want a fight!\p"
	.string "All right! I'll test the POKéMON I\n"
	.string "caught while SURFING!$"

Route119_Text_ChrisDefeat:
	.string "I don't have a clue what it takes to win.$"

Route119_Text_ChrisPostBattle:
	.string "Go for a SURF on my POKéMON…\p"
	.string "Then fish off its back…\p"
	.string "It's an indescribably luxurious moment!$"

Route119_Text_FabianIntro:
	.string "Hit me with a power chord! Victory's\n"
	.string "mine!\p"
	.string "It's our time to shine, whoa, yeah!$"

Route119_Text_FabianDefeat:
	.string "You showed me who's boss! We take the\n"
	.string "loss, oh, no!$"

Route119_Text_FabianPostBattle:
	.string "Hit me with one more power chord! Leave\n"
	.string "me alone!\p"
	.string "Your win you have to atone!$"

Route119_Text_DaytonIntro:
	.string "Hohoho! I love kid TRAINERS! Let's have\n"
	.string "a great match!$"

Route119_Text_DaytonDefeat:
	.string "You're quite something! Hohoho!$"

Route119_Text_DaytonPostBattle:
	.string "Hohoho! I'll try to copy the pep of kid\n"
	.string "TRAINERS like you!$"

Route119_Text_RachelIntro:
	.string "Wherever I go, whenever I go, my parasol\n"
	.string "goes with me.$"

Route119_Text_RachelDefeat:
	.string "Oh, but… that's unfair.$"

Route119_Text_RachelPostBattle:
	.string "You're asking if my parasol is heavy?\n"
	.string "Your BAG is stuffed with more junk than\l"
	.string "I ever carry.$"

Route120_Text_ColinIntro:
	.string "Do you know any moves that can hit a\n"
	.string "flying POKéMON?$"

Route120_Text_ColinDefeat:
	.string "You flew right past me!$"

Route120_Text_ColinPostBattle:
	.string "The move FLY is convenient, don't you\n"
	.string "think?\p"
	.string "While the POKéMON is in the air, almost\n"
	.string "no moves can hit it.$"

Route120_Text_RobertIntro:
	.string "My POKéMON is strong! What about\n"
	.string "yours?$"

Route120_Text_RobertDefeat:
	.string "Your POKéMON were the stronger ones…$"

Route120_Text_RobertPostBattle:
	.string "A POKéMON that gets stronger bit by bit\n"
	.string "is one you can rely on.$"

Route120_Text_RobertRegister:
	.string "You'll only get better. I'd like to put\n"
	.string "you in my POKéNAV!$"

Route120_Text_RobertRematchIntro:
	.string "A POKéMON that gets stronger bit by bit\n"
	.string "is one you can rely on.$"

Route120_Text_RobertRematchDefeat:
	.string "Your POKéMON are seriously powerful.$"

Route120_Text_RobertPostRematch:
	.string "My POKéMON keep getting stronger. I\n"
	.string "need to keep up.$"

Route120_Text_LorenzoIntro:
	.string "Let me test your POKéMON and see\n"
	.string "whether they're ready for the\l"
	.string "wilderness.$"

Route120_Text_LorenzoDefeat:
	.string "POKéMON that strong will never need a\n"
	.string "rescue!$"

Route120_Text_LorenzoPostBattle:
	.string "Traveling wherever your heart desires\n"
	.string "with your POKéMON… That's the joy of\l"
	.string "being a TRAINER.$"

Route120_Text_JennaIntro:
	.string "How's your physical fitness? If you're\n"
	.string "not fit, you could have a rough time\l"
	.string "when it counts.$"

Route120_Text_JennaDefeat:
	.string "I'm in top shape, but…$"

Route120_Text_JennaPostBattle:
	.string "Fitness training is part of my routine.\n"
	.string "I always run with my POKéMON.$"

Route120_Text_JeffreyIntro:
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "Shall we fight?$"

Route120_Text_JeffreyDefeat:
	.string "Beaten…$"

Route120_Text_JeffreyPostBattle:
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "I'll do better…$"

Route120_Text_JeffreyRegister:
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "Got a POKéNAV…?$"

Route120_Text_JeffreyRematchIntro:
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "Fight again?$"

Route120_Text_JeffreyRematchDefeat:
	.string "… … … … … …\n"
	.string "Beaten again…$"

Route120_Text_JeffreyPostRematch:
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "I'll do better…\l"
	.string "For my precious BUG POKéMON…$"

Route120_Text_JenniferIntro:
	.string "POKéMON have all sorts of special\n"
	.string "abilities. To be a first-class TRAINER,\l"
	.string "you have to study them.$"

Route120_Text_JenniferDefeat:
	.string "You're clearly thinking.$"

Route120_Text_JenniferPostBattle:
	.string "A POKéMON's special ability can\n"
	.string "completely change your fighting style.$"

Route120_Text_ChipIntro:
	.string "Who might you be?\p"
	.string "Are you perhaps searching for the\n"
	.string "ancient ruins that legend says may\l"
	.string "possibly exist?$"

Route120_Text_ChipDefeat:
	.string "What a shameful setback…$"

Route120_Text_ChipPostBattle:
	.string "That giant rock… I'd like to believe it\n"
	.string "may indeed hold ancient ruins. But I see\l"
	.string "no entrance.$"

Route120_Text_ClarissaIntro:
	.string "Why am I carrying this parasol?\p"
	.string "I'll tell you if you can beat me.$"

Route120_Text_ClarissaDefeat:
	.string "A parasol can't block a POKéMON's\n"
	.string "attack…$"

Route120_Text_ClarissaPostBattle:
	.string "Strong sunlight isn't good for my\n"
	.string "POKéMON, I think. So I keep them in my\l"
	.string "parasol's shade.$"

Route120_Text_AngelicaIntro:
	.string "Me, my POKéMON, and my parasol…\p"
	.string "If any one of them is missing, the\n"
	.string "picture of beauty is ruined.$"

Route120_Text_AngelicaDefeat:
	.string "You've shattered my beauty completely…$"

Route120_Text_AngelicaPostBattle:
	.string "A parasol would look terrible on you.\p"
	.string "It would only get in your way.$"

Route120_Text_KeigoIntro:
	.string "I'll copy the movements of POKéMON and\n"
	.string "invent new ninja techniques.$"

Route120_Text_KeigoDefeat:
	.string "Creating new ninja techniques is but a\n"
	.string "distant dream…$"

Route120_Text_KeigoPostBattle:
	.string "Perhaps I ought to apprentice under a\n"
	.string "ninja sensei. Or even a Turtle Hermit.$"

Route120_Text_RileyIntro:
	.string "We ninja conceal ourselves under\n"
	.string "camouflage cloaks. I bet you didn't\l"
	.string "know where I was!$"

Route120_Text_RileyDefeat:
	.string "I lost! I need to camouflage my\n"
	.string "embarrassment!$"

Route120_Text_RileyPostBattle:
	.string "Every one of our camouflage cloaks is\n"
	.string "handmade.$"

Route120_Text_CallieIntro:
	.string "Stay alert, or you're going to get hurt!$"

Route120_Text_CallieDefeat:
	.string "Ouch! I was the one who got hurt.$"

Route120_Text_CalliePostBattle:
	.string "Hmm… should I evolve my POKéMON?\n"
	.string "They're so cute as they are, though.$"

Route120_Text_LeonelIntro:
	.string "Your party POKéMON… are they different\n"
	.string "types?$"

Route120_Text_LeonelDefeat:
	.string "Now I've seen your strategy in action!$"

Route120_Text_LeonelPostBattle:
	.string "I think it's awesome that you fight so\n"
	.string "strongly with your favorite POKéMON.$"

Route121_Text_VanessaIntro:
	.string "Won't you play with my lovely, pretty\n"
	.string "POKéMON?$"

Route121_Text_VanessaDefeat:
	.string "That's not what I meant at all!$"

Route121_Text_VanessaPostBattle:
	.string "I'm headed to a CONTEST in LILYCOVE.\p"
	.string "My POKéMON will surely sweep the MASTER\n"
	.string "CLASS.$"

Route121_Text_WalterIntro:
	.string "With my POKéMON, I've traveled to the\n"
	.string "four corners of the world.\p"
	.string "You might say I have some confidence in\n"
	.string "my abilities.$"

Route121_Text_WalterDefeat:
	.string "Ah, nicely done.$"

Route121_Text_WalterPostBattle:
	.string "I'd like to circle the globe once again\n"
	.string "with my POKéMON.$"

Route121_Text_WalterRegister:
	.string "Your skill with POKéMON is remarkable.\n"
	.string "Let me register you as a keepsake.$"

Route121_Text_WalterRematchIntro:
	.string "With my POKéMON, I've traveled to the\n"
	.string "four corners of the world.\p"
	.string "You might say I have some confidence in\n"
	.string "my abilities.$"

Route121_Text_WalterRematchDefeat:
	.string "Ah, nicely done.$"

Route121_Text_WalterPostRematch:
	.string "You and your POKéMON…\p"
	.string "Your combined strength would be called\n"
	.string "formidable even overseas.$"

Route121_Text_TammyIntro:
	.string "There are powers in this world beyond\n"
	.string "our understanding…$"

Route121_Text_TammyDefeat:
	.string "I have been defeated…$"

Route121_Text_TammyPostBattle:
	.string "MT. PYRE…\p"
	.string "There is a mysterious power at work\n"
	.string "there… Perhaps the Other World is\l"
	.string "close.$"

Route121_Text_KateIntro:
	.string "KATE: Together, we're fearless! We'll\n"
	.string "show you how tough we are!$"

Route121_Text_KateDefeat:
	.string "KATE: I blew it in front of my junior\n"
	.string "partner…$"

Route121_Text_KatePostBattle:
	.string "KATE: When someone looks up to me, I\n"
	.string "just have to look cool in front of them…$"

Route121_Text_KateNotEnoughMons:
	.string "KATE: If you've only got one POKéMON, we\n"
	.string "can't battle you.\p"
	.string "That would be bullying.$"

Route121_Text_JoyIntro:
	.string "JOY: Together, we're fearless! We'll show\n"
	.string "you how tough we are!$"

Route121_Text_JoyDefeat:
	.string "JOY: I'm so sorry, KATE!$"

Route121_Text_JoyPostBattle:
	.string "JOY: Ehehe, I'll have to train with KATE,\n"
	.string "my senior partner, again.$"

Route121_Text_JoyNotEnoughMons:
	.string "JOY: To take us on, you need at least\n"
	.string "two POKéMON!$"

Route121_Text_JessicaIntro:
	.string "Stop! Take a good look at my precious\n"
	.string "POKéMON!$"

Route121_Text_JessicaDefeat:
	.string "Oh, how dare you! There's no need to be\n"
	.string "so serious!$"

Route121_Text_JessicaPostBattle:
	.string "Perhaps I'll catch some more POKéMON at\n"
	.string "the SAFARI.$"

Route121_Text_JessicaRegister:
	.string "I took it easy on you this time! It won't\n"
	.string "be that way next time!$"

Route121_Text_JessicaRematchIntro:
	.string "My precious POKéMON grew! Take a good\n"
	.string "look!$"

Route121_Text_JessicaRematchDefeat:
	.string "Oh, how dare you! You still won't go\n"
	.string "easy!$"

Route121_Text_JessicaPostRematch:
	.string "Perhaps I'll catch some more POKéMON at\n"
	.string "the SAFARI.$"

Route121_Text_CristinIntro:
	.string "I have a routine. Defeat five TRAINERS\n"
	.string "a day.\p"
	.string "Guess what? You're number five!$"

Route121_Text_CristinDefeat:
	.string "No fair! You're awful!$"

Route121_Text_CristinPostBattle:
	.string "I never thought I'd lose this easily…\n"
	.string "Next time, I win!$"

Route121_Text_CristinRegister:
	.string "That was pure humiliation! I'll never\n"
	.string "forget you…\p"
	.string "Hand over your POKéNAV!$"

Route121_Text_CristinRematchIntro:
	.string "I have a new routine. Defeat ten\n"
	.string "TRAINERS a day.\p"
	.string "Guess what? You're number ten!$"

Route121_Text_CristinRematchDefeat:
	.string "Hey, that's cheating! I demand a\n"
	.string "rematch!$"

Route121_Text_CristinPostRematch:
	.string "An opponent I just can't beat… Sniff…\p"
	.string "I can't believe this is happening…$"

Route121_Text_CaleIntro:
	.string "Can't you see I'm carrying all this\n"
	.string "stuff?\p"
	.string "And you still insist on a battle?$"

Route121_Text_CaleDefeat:
	.string "Of course I lost! Both my hands are\n"
	.string "full!$"

Route121_Text_CalePostBattle:
	.string "I bought way too much at the LILYCOVE\n"
	.string "DEPT. STORE.\p"
	.string "It's up the road from here. I wish I had\n"
	.string "a BAG like yours.$"

Route121_Text_MylesIntro:
	.string "I love nothing more than seeing other\n"
	.string "people's POKéMON!$"

Route121_Text_MylesDefeat:
	.string "Totally awesome!$"

Route121_Text_MylesPostBattle:
	.string "Your POKéMON are fantastic! How do you\n"
	.string "raise them?$"

Route121_Text_PatIntro:
	.string "I want the whole world to see the\n"
	.string "POKéMON I've raised!$"

Route121_Text_PatDefeat:
	.string "Wow, that was spectacular!$"

Route121_Text_PatPostBattle:
	.string "I raise every POKéMON with the same\n"
	.string "love and care. I don't pick favorites.$"

Route121_Text_MarcelIntro:
	.string "My POKéMON have never tasted defeat!\n"
	.string "After their next win, I'm entering them\l"
	.string "in CONTESTS.$"

Route121_Text_MarcelDefeat:
	.string "Huh? What happened there?$"

Route121_Text_MarcelPostBattle:
	.string "I should train my team harder before I\n"
	.string "enter any CONTEST.$"

Route123_Text_WendyIntro:
	.string "Want to find out how strong you are?\n"
	.string "I'll be the test!$"

Route123_Text_WendyDefeat:
	.string "You passed the test with flying colors!$"

Route123_Text_WendyPostBattle:
	.string "To beat even me… Your strength is\n"
	.string "marvelous!$"

Route123_Text_BraxtonIntro:
	.string "That's quite a stack of GYM BADGES you\n"
	.string "have.\p"
	.string "Let me find out if you truly deserve\n"
	.string "them!$"

Route123_Text_BraxtonDefeat:
	.string "Oh, you deserve them, all right!$"

Route123_Text_BraxtonPostBattle:
	.string "You made those BADGES proud in that\n"
	.string "fight!$"

Route123_Text_VioletIntro:
	.string "They say good times are filled with good\n"
	.string "aromas.$"

Route123_Text_VioletDefeat:
	.string "Oh… I smell the bitter scent of defeat…$"

Route123_Text_VioletPostBattle:
	.string "The BERRY MASTER's garden is full of\n"
	.string "uplifting fragrances.$"

Route123_Text_CameronIntro:
	.string "Being a psychic is about willpower.\p"
	.string "I've willed myself never to lose to\n"
	.string "anyone. That's what makes me strong!$"

Route123_Text_CameronDefeat:
	.string "I'm so sad…$"

Route123_Text_CameronPostBattle:
	.string "A psychic runs on willpower. I thought\n"
	.string "I'd never lose to you…$"

Route123_Text_CameronRegister:
	.string "I sense it! You and I will fight again!\p"
	.string "Whether I'll win, I can't say…\p"
	.string "Let me see your POKéNAV.$"

Route123_Text_CameronRematchIntro:
	.string "I've convinced myself I won't lose\n"
	.string "anymore. That's what makes me strong!$"

Route123_Text_CameronRematchDefeat:
	.string "I'm so sad…$"

Route123_Text_CameronPostRematch:
	.string "I should train at MT. PYRE… At this rate\n"
	.string "I'll never beat you…$"

Route123_Text_JackiIntro:
	.string "Don't be too happy if your POKéMON\n"
	.string "develop psychic powers.\p"
	.string "You need to refine those powers to\n"
	.string "make them truly useful.$"

Route123_Text_JackiDefeat:
	.string "Overpowered!$"

Route123_Text_JackiPostBattle:
	.string "Everyone has psychic powers. We've\n"
	.string "simply forgotten how to use them.$"

Route123_Text_JackiRegister:
	.string "I'd like to face you again. Would that be\n"
	.string "all right?$"

Route123_Text_JackiRematchIntro:
	.string "Have you awakened the psychic powers\n"
	.string "within you?$"

Route123_Text_JackiRematchDefeat:
	.string "Truly astounding!$"

Route123_Text_JackiPostRematch:
	.string "Your bond with POKéMON… that might be a\n"
	.string "psychic power, too.$"

Route123_Text_MiuIntro:
	.string "MIU: Hello, TRAINER. I hope your POKéMON\n"
	.string "don't cry when they lose.$"

Route123_Text_MiuDefeat:
	.string "MIU: Oh no, we lost.$"

Route123_Text_MiuPostBattle:
	.string "MIU: TRAINER, your POKéMON are strong\n"
	.string "because you're friends.$"

Route123_Text_MiuNotEnoughMons:
	.string "MIU: Battling isn't fun unless you have\n"
	.string "two POKéMON.$"

Route123_Text_YukiIntro:
	.string "YUKI: Okay! We're going to beat the\n"
	.string "TRAINER's POKéMON!$"

Route123_Text_YukiDefeat:
	.string "YUKI: Oh no, we lost.$"

Route123_Text_YukiPostBattle:
	.string "YUKI: How are you so strong? We've\n"
	.string "never been beaten before.$"

Route123_Text_YukiNotEnoughMons:
	.string "YUKI: Battling isn't fun unless you have\n"
	.string "two POKéMON.$"

Route123_Text_KindraIntro:
	.string "MT. PYRE… where the spirits of POKéMON\n"
	.string "rest…\p"
	.string "Will your POKéMON rest, too?$"

Route123_Text_KindraDefeat:
	.string "Brimming with vitality…$"

Route123_Text_KindraPostBattle:
	.string "MT. PYRE… where the spirits of POKéMON\n"
	.string "rest…\p"
	.string "It must brim with a power that soothes\n"
	.string "the spirits…$"

Route123_Text_FernandoIntro:
	.string "I'll knock you out while I rip through\n"
	.string "this tune!$"

Route123_Text_FernandoDefeat:
	.string "Hey, wait! I was still on the intro!$"

Route123_Text_FernandoPostBattle:
	.string "You're solid as a rock. I'd like to write\n"
	.string "a song about you.$"

Route123_Text_FernandoRegister:
	.string "Next time, lend your ears to the full\n"
	.string "tune, will you?$"

Route123_Text_FernandoRematchIntro:
	.string "Today's the day I do it! I'll knock you\n"
	.string "out before I finish singing my song!$"

Route123_Text_FernandoRematchDefeat:
	.string "Hey, wait! I hadn't even reached the\n"
	.string "chorus!$"

Route123_Text_FernandoPostRematch:
	.string "I thought you'd be so enthralled by my\n"
	.string "tune that you'd lose.$"

Route123_Text_DavisIntro:
	.string "Check out my awesome BUG POKéMON! My\n"
	.string "big brother gave it to me.$"

Route123_Text_DavisDefeat:
	.string "Waaaah! You big meanie!$"

Route123_Text_DavisPostBattle:
	.string "Don't tell my brother I lost. Promise\n"
	.string "you'll keep it a secret!$"

Route123_Text_JazmynIntro:
	.string "My confidence will get a boost if I beat\n"
	.string "someone who's obviously strong!$"

Route123_Text_JazmynDefeat:
	.string "And there goes my confidence…$"

Route123_Text_JazmynPostBattle:
	.string "They say you can't judge a person by\n"
	.string "appearance.\p"
	.string "But often, looks don't lie…$"

Route123_Text_FrederickIntro:
	.string "Well, hello, child! Could you spare a\n"
	.string "moment?$"

Route123_Text_FrederickDefeat:
	.string "Ah, a mighty capable child! Let me add\n"
	.string "to your allowance.$"

Route123_Text_FrederickPostBattle:
	.string "Add to your allowance? Wasn't the prize\n"
	.string "money enough?$"

Route123_Text_AlbertoIntro:
	.string "I'll be honest with you, BIRD POKéMON\n"
	.string "are my obsession!\p"
	.string "Birds are cool! Birds are the best!$"

Route123_Text_AlbertoDefeat:
	.string "Even when they lose, BIRD POKéMON are\n"
	.string "cool!$"

Route123_Text_AlbertoPostBattle:
	.string "I collect the feathers that scatter\n"
	.string "during battles.\p"
	.string "I'm going to make a hat out of BIRD\n"
	.string "POKéMON feathers.$"

Route123_Text_EdIntro:
	.string "When no TRAINERS are around, I make my\n"
	.string "POKéMON fight each other and just\l"
	.string "watch.$"

Route123_Text_EdDefeat:
	.string "I sort of like your POKéMON.$"

Route123_Text_EdPostBattle:
	.string "Hehe, I'm stealing your fighting ideas!\n"
	.string "They're going to make me better.$"

Route123_Text_JonasIntro:
	.string "I was hiding in ambush, and a TRAINER\n"
	.string "walked right into my trap!$"

Route123_Text_JonasDefeat:
	.string "If you won't lose, how am I supposed to\n"
	.string "enjoy playing ninja?$"

Route123_Text_JonasPostBattle:
	.string "Next time, I'll ambush a TRAINER who\n"
	.string "looks weaker.$"

Route123_Text_KayleyIntro:
	.string "I just bought this parasol, so my\n"
	.string "cuteness has to be up by a third!$"

Route123_Text_KayleyDefeat:
	.string "You're about five times better than me!$"

Route123_Text_KayleyPostBattle:
	.string "Using accessories well is the secret to\n"
	.string "fashion appeal.$"

Route124_Text_SpencerIntro:
	.string "Hey, are you lost at sea?\p"
	.string "If you can beat my POKéMON, I'll serve\n"
	.string "as your pilot.$"

Route124_Text_SpencerDefeat:
	.string "I lost my bearings in the middle of the\n"
	.string "fight!$"

Route124_Text_SpencerPostBattle:
	.string "Plenty of people lose their bearings at\n"
	.string "sea.\p"
	.string "If you're that type, check the\n"
	.string "POKéNAV's MAP.$"

Route124_Text_RolandIntro:
	.string "Hm! You're riding a POKéMON instead of\n"
	.string "swimming yourself…\p"
	.string "I'm envious!$"

Route124_Text_RolandDefeat:
	.string "Oh! I just can't…$"

Route124_Text_RolandPostBattle:
	.string "I'm getting cold… I've been in the water\n"
	.string "way too long…\p"
	.string "I wish I could ride a POKéMON like you\n"
	.string "do…$"

Route124_Text_JennyIntro:
	.string "Float out here long enough, and POKéMON\n"
	.string "drift over to play.$"

Route124_Text_JennyDefeat:
	.string "Oh, darn. I lost.$"

Route124_Text_JennyPostBattle:
	.string "While swimming, I noticed some POKéMON\n"
	.string "attack and some just watch.\p"
	.string "I guess POKéMON have personalities of\n"
	.string "their own.$"

Route124_Text_JennyRegister:
	.string "It's only on a whim, but maybe I'll have\n"
	.string "you register me in your POKéNAV.$"

Route124_Text_JennyRematchIntro:
	.string "Float out here long enough, and\n"
	.string "TRAINERS come to challenge you!$"

Route124_Text_JennyRematchDefeat:
	.string "How strange… I lost again…$"

Route124_Text_JennyPostRematch:
	.string "This has nothing to do with anything,\n"
	.string "but I might visit the TRICK HOUSE.$"

Route124_Text_GraceIntro:
	.string "I'm getting bored of swimming… How\n"
	.string "about a battle?$"

Route124_Text_GraceDefeat:
	.string "I had no idea you were this strong!$"

Route124_Text_GracePostBattle:
	.string "All the hard work you've put in is what\n"
	.string "made you this strong.$"

Route124_Text_ChadIntro:
	.string "Fufufufu… I dive deep underwater so I\n"
	.string "can go deep undercover.\p"
	.string "The depths are where I shine!$"

Route124_Text_ChadDefeat:
	.string "Glub, glub, glub… Going under…$"

Route124_Text_ChadPostBattle:
	.string "I hear there's a DIVE spot around here.\p"
	.string "Now I want to go deep again…$"

Route124_Text_LilaIntro:
	.string "LILA: Sigh…\p"
	.string "Here I am in the sea, and who's with me?\n"
	.string "My little brother!\p"
	.string "Let's battle so I don't have to dwell on\n"
	.string "that!$"

Route124_Text_LilaDefeat:
	.string "LILA: ROY! We lost because of you!\n"
	.string "You're in big trouble later!$"

Route124_Text_LilaPostBattle:
	.string "LILA: Sigh…\p"
	.string "If only the guy next to me were a nice\n"
	.string "boyfriend instead of my little brother…$"

Route124_Text_LilaNotEnoughMons:
	.string "LILA: You want to fight us? Not unless\n"
	.string "you bring two POKéMON.$"

Route124_Text_RoyIntro:
	.string "ROY: My big sister is a beast at\n"
	.string "POKéMON!\p"
	.string "Don't you cry when you lose!$"

Route124_Text_RoyDefeat:
	.string "ROY: Uh-oh… My big sister is going to\n"
	.string "chew me out…$"

Route124_Text_RoyPostBattle:
	.string "ROY: My big sister is really scary when\n"
	.string "she's angry.\p"
	.string "That's why she doesn't have a\n"
	.string "boyfriend.$"

Route124_Text_LilaRoyRegister:
	.string "ROY: Will you battle us again? But go\n"
	.string "easy next time, okay?$"

Route124_Text_RoyNotEnoughMons:
	.string "ROY: Did you want to battle us? Then\n"
	.string "bring two POKéMON.$"

Route124_Text_LilaRematchIntro:
	.string "LILA: Sigh…\p"
	.string "Here I am in the sea, and who's with me?\n"
	.string "My little brother!\p"
	.string "Oh, hi, it's been a while. Let's battle so\n"
	.string "I don't have to dwell on things!$"

Route124_Text_LilaRematchDefeat:
	.string "LILA: ROY! We lost again because of you!\p"
	.string "We're having a training session later!$"

Route124_Text_LilaPostRematch:
	.string "LILA: Sigh…\p"
	.string "With a nice boyfriend, we'd beat anyone\n"
	.string "with our lovely combinations…$"

Route124_Text_LilaRematchNotEnoughMons:
	.string "LILA: You want to fight us? Not unless\n"
	.string "you bring two POKéMON.$"

Route124_Text_RoyRematchIntro:
	.string "ROY: If we lose, I'll catch heck. I'm\n"
	.string "going all out!$"

Route124_Text_RoyRematchDefeat:
	.string "ROY: Uh-oh… My big sister is going to\n"
	.string "chew me out again.$"

Route124_Text_RoyPostRematch:
	.string "ROY: My big sister is really scary when\n"
	.string "she's angry.\p"
	.string "She's going to make me train really hard\n"
	.string "with POKéMON later…$"

Route124_Text_RoyRematchNotEnoughMons:
	.string "ROY: Did you want to battle us? Then\n"
	.string "bring two POKéMON.$"

Route124_Text_DeclanIntro:
	.string "Here I am swimming all alone on this\n"
	.string "wide, beautiful sea.\p"
	.string "There's no other word for it. This is\n"
	.string "pathetic!$"

Route124_Text_DeclanDefeat:
	.string "I'm so blue. Blue as the sky…$"

Route124_Text_DeclanPostBattle:
	.string "I ought to go flirt with the lady\n"
	.string "SWIMMERS and invite them on a long swim.$"

Route124_Text_IsabellaIntro:
	.string "There's no way I'll lose to a surfing\n"
	.string "TRAINER.$"

Route124_Text_IsabellaDefeat:
	.string "I've just got sweat in my eyes! I am not\n"
	.string "crying!$"

Route124_Text_IsabellaPostBattle:
	.string "Pretty, colorful shards turn up all over\n"
	.string "this area.$"

Route125_Text_NolenIntro:
	.string "I heard you coming, so I hung around for\n"
	.string "you!$"

Route125_Text_NolenDefeat:
	.string "I give up!$"

Route125_Text_NolenPostBattle:
	.string "Did you know sound travels faster\n"
	.string "through water than through air?$"

Route125_Text_StanIntro:
	.string "Hey, there! Come take a look at my sweet\n"
	.string "POKéMON!$"

Route125_Text_StanDefeat:
	.string "I flopped…$"

Route125_Text_StanPostBattle:
	.string "HORSEA's charm knocked me off my feet,\n"
	.string "so I started swimming, too.$"

Route125_Text_TanyaIntro:
	.string "I'm sick of swimming. Want to fight me\n"
	.string "for a change?$"

Route125_Text_TanyaDefeat:
	.string "That was way too much!$"

Route125_Text_TanyaPostBattle:
	.string "Whew… Which way to MOSSDEEP CITY\n"
	.string "again?$"

Route125_Text_SharonIntro:
	.string "Care to take on the WATER-type\n"
	.string "POKéMON I've raised?$"

Route125_Text_SharonDefeat:
	.string "Beaten…$"

Route125_Text_SharonPostBattle:
	.string "Your power… you're the genuine article.\n"
	.string "I'm amazed!$"

Route125_Text_ErnestIntro:
	.string "Ahoy! I'm a big, burly SAILOR! I've\n"
	.string "sailed every sea in the world!$"

Route125_Text_ErnestDefeat:
	.string "Gwrroooar! I lost!$"

Route125_Text_ErnestPostBattle:
	.string "The tide rises and falls inside the\n"
	.string "SHOAL CAVE.\p"
	.string "By the way, high tide to low tide takes\n"
	.string "about six hours. Did you know that?$"

Route125_Text_ErnestRegister:
	.string "Register me in your POKéNAV, and I'll let\n"
	.string "you in on something good.$"

Route125_Text_ErnestRematchIntro:
	.string "It's high time I got my payback! Come\n"
	.string "on, we're battling!$"

Route125_Text_ErnestRematchDefeat:
	.string "I lost! I flat-out lost!$"

Route125_Text_ErnestRematchPostBattle:
	.string "The SHOAL CAVE…\p"
	.string "There are places you can and can't\n"
	.string "reach depending on the rise and fall of\l"
	.string "the tide.\p"
	.string "By the way, it's about six hours from\n"
	.string "high tide to low tide. Don't forget!$"

Route125_Text_KimIntro:
	.string "KIM: Someone told me a funny old man\n"
	.string "lives in the SHOAL CAVE. Are you going\l"
	.string "to see him, too?$"

Route125_Text_KimDefeat:
	.string "KIM: I thought we'd win.$"

Route125_Text_KimPostBattle:
	.string "KIM: A funny old man lives in the SHOAL\n"
	.string "CAVE, right?\p"
	.string "Let's go see him, IRIS!$"

Route125_Text_KimNotEnoughMons:
	.string "KIM: No, no, no! You need two POKéMON, or\n"
	.string "it doesn't count!$"

Route125_Text_IrisIntro:
	.string "IRIS: KIM, what exactly are we looking\n"
	.string "for out here?$"

Route125_Text_IrisDefeat:
	.string "IRIS: Oh, we almost had it.$"

Route125_Text_IrisPostBattle:
	.string "IRIS: KIM, are we really going into the\n"
	.string "SHOAL CAVE? We'll get soaked.$"

Route125_Text_IrisNotEnoughMons:
	.string "IRIS: Oh, we could never, ever do\n"
	.string "something like a 2-on-1 battle.$"

Route125_Text_PresleyIntro:
	.string "Why would a BIRDKEEPER like me come out\n"
	.string "to sea?$"

Route125_Text_PresleyDefeat:
	.string "Fine. I'll tell you why I'm here.$"

Route125_Text_PresleyPostBattle:
	.string "I put a message in a bottle and set it\n"
	.string "adrift.\p"
	.string "I'm sure a girl SWIMMER will find it!$"

Route125_Text_AuronIntro:
	.string "Hey! Are you the one dumping garbage in\n"
	.string "the sea?$"

Route125_Text_AuronDefeat:
	.string "Oh, so you weren't the one dumping\n"
	.string "trash in the sea.$"

Route125_Text_AuronPostBattle:
	.string "I found an ugly bottle bobbing in the\n"
	.string "waves earlier.\p"
	.string "It makes me furious that someone would\n"
	.string "pollute the sea!$"

Route126_Text_BarryIntro:
	.string "Swimming is a full-body workout! You'll\n"
	.string "get fit!$"

Route126_Text_BarryDefeat:
	.string "I admit it, you win!$"

Route126_Text_BarryPostBattle:
	.string "Thanks to my daily swim… Look! Feast\n"
	.string "your eyes on this physique!$"

Route126_Text_DeanIntro:
	.string "That towering white mountain of rock is\n"
	.string "SOOTOPOLIS CITY.$"

Route126_Text_DeanDefeat:
	.string "I got beaten?$"

Route126_Text_DeanPostBattle:
	.string "I can't find the way into SOOTOPOLIS.\n"
	.string "Where could the entrance be?$"

Route126_Text_NikkiIntro:
	.string "Ufufufufu! I'm a mermaid!$"

Route126_Text_NikkiDefeat:
	.string "My fantasy burst like a bubble! Blub,\n"
	.string "blub, blub…$"

Route126_Text_NikkiPostBattle:
	.string "You thrashed me… I want to vanish in a\n"
	.string "wave of despair…$"

Route126_Text_BrendaIntro:
	.string "Hello there, kiddo! Want to fight me?$"

Route126_Text_BrendaDefeat:
	.string "Oh, noooo!$"

Route126_Text_BrendaPostBattle:
	.string "I just love splashing around with\n"
	.string "POKéMON in the sea!$"

Route126_Text_PabloIntro:
	.string "Take a look at this sculpted body! I'm\n"
	.string "more ripped than a BLACK BELT!$"

Route126_Text_PabloDefeat:
	.string "Whoops! Way too strong! Not bad, not\n"
	.string "bad at all!$"

Route126_Text_PabloPostBattle:
	.string "Losing to you stimulated my senses! I'll\n"
	.string "train myself and my POKéMON harder!$"

Route126_Text_PabloRegister:
	.string "Yep, you're not bad at all! I'd like to\n"
	.string "get to know you better!$"

Route126_Text_PabloRematchIntro:
	.string "Take a look at this beautiful body! I'm\n"
	.string "more shapely than any SWIMMER!$"

Route126_Text_PabloRematchDefeat:
	.string "Whoops! Way too strong! Not bad! Not\n"
	.string "bad at all!$"

Route126_Text_PabloPostRematch:
	.string "I'll train even harder! You really\n"
	.string "motivate me!\p"
	.string "Come back anytime!$"

Route126_Text_LeonardoIntro:
	.string "Last year I couldn't swim at all, and now\n"
	.string "I'm a decent SWIMMER.\p"
	.string "I feel like I can do anything now.$"

Route126_Text_LeonardoDefeat:
	.string "Geez, getting cocky didn't help me one\n"
	.string "bit.$"

Route126_Text_LeonardoPostBattle:
	.string "If you practice at something, you get\n"
	.string "better at it.\p"
	.string "You're young. Don't be afraid to try all\n"
	.string "sorts of things!$"

Route126_Text_IsobelIntro:
	.string "When seawater goes up your nose,\n"
	.string "doesn't it feel awful?$"

Route126_Text_IsobelDefeat:
	.string "Ack! You… Glub!$"

Route126_Text_IsobelPostBattle:
	.string "Ooh, I swallowed some water! It's\n"
	.string "bitter! It's salty!!$"

Route126_Text_SiennaIntro:
	.string "I'm putting my whole heart into this!$"

Route126_Text_SiennaDefeat:
	.string "Your heart was bigger!$"

Route126_Text_SiennaPostBattle:
	.string "Time to cool off… I think I'll take a\n"
	.string "dive.$"

Route127_Text_CamdenIntro:
	.string "It's written all over your face. You\n"
	.string "want to challenge me.$"

Route127_Text_CamdenDefeat:
	.string "Awawawawawa…$"

Route127_Text_CamdenPostBattle:
	.string "A well-fought match leaves me feeling\n"
	.string "refreshed and serene.$"

Route127_Text_DonnyIntro:
	.string "Do you have a rival you just hate to\n"
	.string "lose to?$"

Route127_Text_DonnyDefeat:
	.string "Arrrgh! I can't stand losing!$"

Route127_Text_DonnyPostBattle:
	.string "When you have a rival, don't you feel\n"
	.string "like you have to keep getting better?$"

Route127_Text_JonahIntro:
	.string "Fishing has brought me a state of\n"
	.string "perfect serenity…\p"
	.string "Please, allow me to demonstrate…$"

Route127_Text_JonahDefeat:
	.string "I may have lost, but my heart stays\n"
	.string "calm…$"

Route127_Text_JonahPostBattle:
	.string "It doesn't matter that I catch nothing.\n"
	.string "The line stays in the water…$"

Route127_Text_HenryIntro:
	.string "Whoops! Don't tell me I hooked a\n"
	.string "SURFING POKéMON?$"

Route127_Text_HenryDefeat:
	.string "Too fast for me to keep up!$"

Route127_Text_HenryPostBattle:
	.string "Hooking a tough POKéMON like yours\n"
	.string "would be a real handful!$"

Route127_Text_RogerIntro:
	.string "Well, well! A POKéMON fan versus a\n"
	.string "fishing fanatic!$"

Route127_Text_RogerDefeat:
	.string "No! My line's all knotted up! The party's\n"
	.string "over!$"

Route127_Text_RogerPostBattle:
	.string "My fishing line is dancing! The tangle\n"
	.string "tango! Hahaha, snarl!$"

Route127_Text_AidanIntro:
	.string "BIRD POKéMON have incredible eyesight.\n"
	.string "They can spot prey from way up high.$"

Route127_Text_AidanDefeat:
	.string "Whew… I yield.$"

Route127_Text_AidanPostBattle:
	.string "There are lots of diving spots in the\n"
	.string "sea around here.\p"
	.string "You can spot them easily from the sky\n"
	.string "by their darker color.$"

Route127_Text_KojiIntro:
	.string "Run in your bare feet. That'll toughen\n"
	.string "up your soles!$"

Route127_Text_KojiDefeat:
	.string "Yowch! I've got a pebble stuck under my\n"
	.string "toenail!$"

Route127_Text_KojiPostBattle:
	.string "Going barefoot feels great. But your\n"
	.string "RUNNING SHOES look cool, too.$"

Route127_Text_KojiRegister:
	.string "That's my way of dealing with anyone\n"
	.string "who beats me! I hope we can do this\l"
	.string "again.$"

Route127_Text_KojiRematchIntro:
	.string "I still run barefoot every day. My soles\n"
	.string "are like iron!$"

Route127_Text_KojiRematchDefeat:
	.string "Yowch! Pebbles stabbed my arches!$"

Route127_Text_KojiPostRematch:
	.string "Want to go barefoot for a while, so I\n"
	.string "can try your RUNNING SHOES?$"

Route127_Text_AthenaIntro:
	.string "Let's have a slow and methodical match.$"

Route127_Text_AthenaDefeat:
	.string "You didn't give me any chance to\n"
	.string "strategize.$"

Route127_Text_AthenaPostBattle:
	.string "When I'm surrounded by the blue sea and\n"
	.string "sky, it feels like time slows down.$"

Route128_Text_IsaiahIntro:
	.string "EVER GRANDE CITY is still a long way\n"
	.string "off…$"

Route128_Text_IsaiahDefeat:
	.string "My first victory seems far away, too…$"

Route128_Text_IsaiahPostBattle:
	.string "I've lost all my life, but I'll never give\n"
	.string "up!$"

Route128_Text_IsaiahRegister:
	.string "I know I'm not good yet, but I think I'll\n"
	.string "win someday.\p"
	.string "Please register me in your POKéNAV.$"

Route128_Text_IsaiahRematchIntro:
	.string "I'm still feeling good. I'll keep swimming\n"
	.string "to EVER GRANDE CITY.$"

Route128_Text_IsaiahRematchDefeat:
	.string "My first victory still hasn't come…$"

Route128_Text_IsaiahPostRematch:
	.string "I'll eventually reach EVER GRANDE CITY,\n"
	.string "where I can eventually win…$"

Route128_Text_KatelynIntro:
	.string "In a triathlon you swim, cycle, and then\n"
	.string "run a marathon.\p"
	.string "It's a grueling race of three events.$"

Route128_Text_KatelynDefeat:
	.string "POKéMON battles are grueling, too…$"

Route128_Text_KatelynPostBattle:
	.string "Next up is the BIKE leg, but… I'm ready\n"
	.string "to throw in the towel…$"

Route128_Text_KatelynRegister:
	.string "Well, I might as well make the most of\n"
	.string "this. I'd love a rematch sometime.$"

Route128_Text_KatelynRematchIntro:
	.string "A triathlon is long. But I guess the\n"
	.string "road to becoming POKéMON CHAMPION is\l"
	.string "also long and grueling.$"

Route128_Text_KatelynRematchDefeat:
	.string "POKéMON battles really are harsh and\n"
	.string "unforgiving…$"

Route128_Text_KatelynPostRematch:
	.string "You should give serious thought to the\n"
	.string "challenges on VICTORY ROAD.$"

Route128_Text_AlexaIntro:
	.string "We've been working so hard for a\n"
	.string "POKéMON LEAGUE challenge…\p"
	.string "We can't afford to lose now!$"

Route128_Text_AlexaDefeat:
	.string "What?! How could this happen?!$"

Route128_Text_AlexaPostBattle:
	.string "After everything I did to get here, one\n"
	.string "setback won't make me quit.$"

Route128_Text_RubenIntro:
	.string "No TRAINER is stronger than I am!$"

Route128_Text_RubenDefeat:
	.string "This can't be happening!$"

Route128_Text_RubenPostBattle:
	.string "It looks like no TRAINER is stronger\n"
	.string "than you!$"

Route128_Text_WayneIntro:
	.string "I want to visit EVER GRANDE, so I\n"
	.string "caught a POKéMON that knows WATERFALL\l"
	.string "to climb the falls.$"

Route128_Text_WayneDefeat:
	.string "I'm devastated!$"

Route128_Text_WaynePostBattle:
	.string "Awww, phooey!\p"
	.string "My POKéMON can use WATERFALL, but I\n"
	.string "don't have the SOOTOPOLIS GYM BADGE to\l"
	.string "command it!$"

Route128_Text_HarrisonIntro:
	.string "You look awfully tough. I wonder if I\n"
	.string "can win?$"

Route128_Text_HarrisonDefeat:
	.string "Ouch! I guess winning was never going\n"
	.string "to happen.$"

Route128_Text_HarrisonPostBattle:
	.string "There are tough TRAINERS galore around\n"
	.string "EVER GRANDE.\p"
	.string "Do you think I'm out of my league?$"

Route128_Text_CarleeIntro:
	.string "The sunlight seems harsher in this area.$"

Route128_Text_CarleeDefeat:
	.string "The glare from the sun kept me from\n"
	.string "seeing clearly.$"

Route128_Text_CarleePostBattle:
	.string "I should head back soon. I need to\n"
	.string "reapply my sunscreen.$"

Route129_Text_ChaseIntro:
	.string "This is my first triathlon. I'm so tense\n"
	.string "and nervous!$"

Route129_Text_ChaseDefeat:
	.string "Wroooaaar! I couldn't pull off the win!$"

Route129_Text_ChasePostBattle:
	.string "If I'm all tensed up, I can't give it my\n"
	.string "all.$"

Route129_Text_AllisonIntro:
	.string "I'm in the middle of a triathlon, but\n"
	.string "sure, why not have a battle?$"

Route129_Text_AllisonDefeat:
	.string "I was positive I'd win!$"

Route129_Text_AllisonPostBattle:
	.string "Do you know the greatest thing about\n"
	.string "triathlons?\p"
	.string "Testing the limits of your own strength\n"
	.string "and endurance against Mother Nature!$"

Route129_Text_ReedIntro:
	.string "Say hey, hey! Let's go!$"

Route129_Text_ReedDefeat:
	.string "Beaten, I'm beaten. That's all, folks!$"

Route129_Text_ReedPostBattle:
	.string "There's nothing for a loser here. Time\n"
	.string "for me to beat it home.$"

Route129_Text_TishaIntro:
	.string "What's the rush? Let's take it nice and\n"
	.string "easy.$"

Route129_Text_TishaDefeat:
	.string "Oh, my. I wanted to relax a little\n"
	.string "longer…$"

Route129_Text_TishaPostBattle:
	.string "Don't you hate making mistakes when\n"
	.string "you're in a rush?\p"
	.string "That's why I take things slowly.$"

Route129_Text_ClarenceIntro:
	.string "Surfing isn't as easy as it looks, is it?$"

Route129_Text_ClarenceDefeat:
	.string "Winning really isn't easy.$"

Route129_Text_ClarencePostBattle:
	.string "You've got your sights on the POKéMON\n"
	.string "LEAGUE? Keep at it!$"

Route130_Text_RodneyIntro:
	.string "What a surprise! I didn't expect to see\n"
	.string "a TRAINER out at sea.\p"
	.string "I think we should battle!$"

Route130_Text_RodneyDefeat:
	.string "This kid is awfully tough…$"

Route130_Text_RodneyPostBattle:
	.string "Your eyes have the look of someone\n"
	.string "who's faced harsh challenges and won.\l"
	.string "It suits you well!$"

Route130_Text_KatieIntro:
	.string "In the deep blue sea, my shattered blue\n"
	.string "heart finds comfort among the waves.$"

Route130_Text_KatieDefeat:
	.string "Like the vast blue sea, the world of\n"
	.string "POKéMON runs deeper than anyone can\l"
	.string "believe.$"

Route130_Text_KatiePostBattle:
	.string "The children of the world dream of one\n"
	.string "day becoming the POKéMON CHAMPION.$"

Route130_Text_SantiagoIntro:
	.string "Floating on the open sea like this… so\n"
	.string "peaceful.$"

Route130_Text_SantiagoDefeat:
	.string "I should've been a little less relaxed!$"

Route130_Text_SantiagoPostBattle:
	.string "Swimming and fighting like this… I'm a\n"
	.string "happy guy…$"

Route131_Text_RichardIntro:
	.string "The sea is crawling with POKéMON.\n"
	.string "Swimming here is no picnic, I tell you.$"

Route131_Text_RichardDefeat:
	.string "POKéMON raised by TRAINERS are no\n"
	.string "joke…$"

Route131_Text_RichardPostBattle:
	.string "Gasp… Gasp… I'm wiped out…\p"
	.string "The going's easy. It's the leaving\n"
	.string "that's hard.\p"
	.string "Will I have any energy left for the trip\n"
	.string "back?$"

Route131_Text_HermanIntro:
	.string "The sea… the sea… the sea… nothing but\n"
	.string "sea as far as I can see!\p"
	.string "I'm sick and tired of the sea!$"

Route131_Text_HermanDefeat:
	.string "Bleaaah!$"

Route131_Text_HermanPostBattle:
	.string "The sea bores me, but swim I must.\p"
	.string "I'm a born swimmer! That's just who I am.$"

Route131_Text_SusieIntro:
	.string "Hi, sweetie, hold on! You and I should\n"
	.string "fight!$"

Route131_Text_SusieDefeat:
	.string "You're tough in spite of how you look!$"

Route131_Text_SusiePostBattle:
	.string "Did you see a guy over there whining\n"
	.string "that he's bored of the sea?\p"
	.string "That's all talk. He's hopelessly in love\n"
	.string "with the sea!$"

Route131_Text_KaraIntro:
	.string "Why do men love bathing suits so much?\p"
	.string "They all ogle me! Even Master Roshi\n"
	.string "would!$"

Route131_Text_KaraDefeat:
	.string "I'm in over my head!$"

Route131_Text_KaraPostBattle:
	.string "Maybe it isn't my bathing suit that gets\n"
	.string "them looking. It must be my beauty!$"

Route131_Text_ReliIntro:
	.string "RELI: As brother and sister, we'll take\n"
	.string "you on together!$"

Route131_Text_ReliDefeat:
	.string "RELI: We worked together and still\n"
	.string "couldn't win…$"

Route131_Text_ReliPostBattle:
	.string "RELI: The people of PACIFIDLOG live\n"
	.string "with the sea and POKéMON from the day\l"
	.string "they're born.$"

Route131_Text_ReliNotEnoughMons:
	.string "RELI: You don't have two POKéMON? Then\n"
	.string "we can't enjoy a battle.$"

Route131_Text_IanIntro:
	.string "IAN: I'm giving it my all with my sis!$"

Route131_Text_IanDefeat:
	.string "IAN: I gave it my all with my sis, and we\n"
	.string "still lost…$"

Route131_Text_IanPostBattle:
	.string "IAN: You know how PACIFIDLOG is a\n"
	.string "floating town?\p"
	.string "So wherever there's sea, that's a part\n"
	.string "of PACIFIDLOG!$"

Route131_Text_IanNotEnoughMons:
	.string "IAN: Bring two POKéMON and we'll take\n"
	.string "you on!$"

Route131_Text_TaliaIntro:
	.string "Beat me, and I'll tell you something\n"
	.string "useful!$"

Route131_Text_TaliaDefeat:
	.string "Oh? I lost?$"

Route131_Text_TaliaPostBattle:
	.string "There's an odd place nearby. A huge\n"
	.string "tower stands there.\p"
	.string "Why don't you go take a look?$"

Route131_Text_KevinIntro:
	.string "The people of PACIFIDLOG are very\n"
	.string "peaceful.\p"
	.string "We never get angry. That includes me.$"

Route131_Text_KevinDefeat:
	.string "Oops!$"

Route131_Text_KevinPostBattle:
	.string "Tch! …Oh, wait. I'm not angry. Really!\p"
	.string "But, wow, you're strong! Hahaha!$"

Route132_Text_GilbertIntro:
	.string "I caught colds all the time as a kid, but\n"
	.string "I got totally fit after I started\l"
	.string "swimming.$"

Route132_Text_GilbertDefeat:
	.string "I need more power…$"

Route132_Text_GilbertPostBattle:
	.string "TRAINERS travel the fields and\n"
	.string "mountains, so they have to be fit, too.$"

Route132_Text_DanaIntro:
	.string "I avoid swimming where the currents run\n"
	.string "too strong.$"

Route132_Text_DanaDefeat:
	.string "Oh, no, please!$"

Route132_Text_DanaPostBattle:
	.string "If I get swept away, I'll lose all sense\n"
	.string "of where I am…$"

Route132_Text_RonaldIntro:
	.string "Win or lose, you can't know until you\n"
	.string "try!$"

Route132_Text_RonaldDefeat:
	.string "Waah! I went down with the ship!$"

Route132_Text_RonaldPostBattle:
	.string "I never fight when I know I'll win. I like\n"
	.string "to battle at the razor's edge of\l"
	.string "victory and defeat!$"

Route132_Text_KiyoIntro:
	.string "I think about POKéMON 24 hours a day.\n"
	.string "How could you possibly beat me?$"

Route132_Text_KiyoDefeat:
	.string "I lose. I concede defeat.$"

Route132_Text_KiyoPostBattle:
	.string "Urggh… You're a POKéMON fanatic, aren't\n"
	.string "you?\p"
	.string "You must think about POKéMON 24 hours\n"
	.string "a day, too!$"

Route132_Text_MakaylaIntro:
	.string "I'm always with my husband, but I can\n"
	.string "win without him, too.$"

Route132_Text_MakaylaDefeat:
	.string "Oh, I suppose I wasn't good enough.$"

Route132_Text_MakaylaPostBattle:
	.string "That young man over there looks just\n"
	.string "like my husband did when he was young.\p"
	.string "He's making me blush!$"

Route132_Text_JonathanIntro:
	.string "Someone's been staring at me. Was it\n"
	.string "you?$"

Route132_Text_JonathanDefeat:
	.string "Wow! You're strong, all right!$"

Route132_Text_JonathanPostBattle:
	.string "I can't shake the feeling that\n"
	.string "someone's watching me.\p"
	.string "I can't concentrate!$"

Route132_Text_PaxtonIntro:
	.string "Where could my wife have gone? I'm\n"
	.string "always with her.\p"
	.string "I wonder if I can win on my own.$"

Route132_Text_PaxtonDefeat:
	.string "Ah, I see I couldn't manage to win on my\n"
	.string "own after all.$"

Route132_Text_PaxtonPostBattle:
	.string "My wife must be searching for me. I'd\n"
	.string "better find her right away.$"

Route132_Text_DarcyIntro:
	.string "I enjoyed training here alone. How awful\n"
	.string "that all these people showed up!$"

Route132_Text_DarcyDefeat:
	.string "Fine! I won't complain about everyone\n"
	.string "else being here.$"

Route132_Text_DarcyPostBattle:
	.string "Maybe I'll team up with that old man and\n"
	.string "challenge that other pair.$"

Route133_Text_FranklinIntro:
	.string "Did the currents carry you here, too?\n"
	.string "This must be fate. Let's battle!$"

Route133_Text_FranklinDefeat:
	.string "So strong! Way too strong!$"

Route133_Text_FranklinPostBattle:
	.string "Just my luck that a tough TRAINER like\n"
	.string "you would drift here… I must be cursed…$"

Route133_Text_DebraIntro:
	.string "I've led a life of woe and misery… I was\n"
	.string "cast away, and this is where I drifted…$"

Route133_Text_DebraDefeat:
	.string "Another loss…$"

Route133_Text_DebraPostBattle:
	.string "A life adrift… I'm done with it!$"

Route133_Text_LindaIntro:
	.string "Welcome! I've been waiting for you!$"

Route133_Text_LindaDefeat:
	.string "No! Please!$"

Route133_Text_LindaPostBattle:
	.string "A strong child TRAINER… How irritating!$"

Route133_Text_WarrenIntro:
	.string "I want to win like everyone else, but I\n"
	.string "won't raise my POKéMON like everyone\l"
	.string "else.$"

Route133_Text_WarrenDefeat:
	.string "Darn! My way is still too sloppy!$"

Route133_Text_WarrenPostBattle:
	.string "It's way more fun to do things my own\n"
	.string "way than to be like everybody else.\p"
	.string "I mean, that's obvious!$"

Route133_Text_BeckIntro:
	.string "I flew all the way out here with my BIRD\n"
	.string "POKéMON.$"

Route133_Text_BeckDefeat:
	.string "You… you're stunningly cool!$"

Route133_Text_BeckPostBattle:
	.string "I'd like to go back to FORTREE, but I've\n"
	.string "started to like it here, too.$"

Route133_Text_MollieIntro:
	.string "I've battled thousands of times. I've\n"
	.string "lost count.$"

Route133_Text_MollieDefeat:
	.string "I may have lost thousands of times, but\n"
	.string "losing still stings.$"

Route133_Text_MolliePostBattle:
	.string "Keep at it, youngster, so you can\n"
	.string "become like my husband and me.$"

Route133_Text_ConorIntro:
	.string "Young people are too happy to go with\n"
	.string "the flow. They have no direction.$"

Route133_Text_ConorDefeat:
	.string "You have a strong sense of purpose.$"

Route133_Text_ConorPostBattle:
	.string "Don't let others lead you astray. Don't\n"
	.string "lose your direction as you grow older.$"

Route134_Text_JackIntro:
	.string "Even POKéMON that can swim get carried\n"
	.string "along by the rapid currents.$"

Route134_Text_JackDefeat:
	.string "Aiyeeeeee!$"

Route134_Text_JackPostBattle:
	.string "I think POKéMON love the fast currents\n"
	.string "around here.$"

Route134_Text_LaurelIntro:
	.string "My LUVDISC want a fun match. Will you\n"
	.string "join us?$"

Route134_Text_LaurelDefeat:
	.string "Oopsie-daisy!$"

Route134_Text_LaurelPostBattle:
	.string "There's a collector after the SCALES of\n"
	.string "LUVDISC.$"

Route134_Text_AlexIntro:
	.string "Okeydokey! Rest time's over, gang! Time\n"
	.string "for a match!$"

Route134_Text_AlexDefeat:
	.string "Wiped out again…$"

Route134_Text_AlexPostBattle:
	.string "My BIRD POKéMON tire out fast after a\n"
	.string "long flight…$"

Route134_Text_HitoshiIntro:
	.string "You're a POKéMON TRAINER. No need for\n"
	.string "words. We fight now.$"

Route134_Text_HitoshiDefeat:
	.string "… … … … … …\n"
	.string "… … … … … …$"

Route134_Text_HitoshiPostBattle:
	.string "I was the one who challenged you, and I\n"
	.string "lost. I am deeply ashamed…$"

Route134_Text_AaronIntro:
	.string "The savage tide in this area makes us\n"
	.string "stronger than ever.$"

Route134_Text_AaronDefeat:
	.string "I concede defeat without complaint.$"

Route134_Text_AaronPostBattle:
	.string "We will return to METEOR FALLS for more\n"
	.string "training.\p"
	.string "If you like, you should go, too. It will\n"
	.string "definitely toughen you up!$"

Route134_Text_KelvinIntro:
	.string "O-our boat! The tide swept it away!$"

Route134_Text_KelvinDefeat:
	.string "Awawawawah! Stop, please! Please!$"

Route134_Text_KelvinPostBattle:
	.string "If we can't SURF, how will we ever get\n"
	.string "home?\p"
	.string "Actually, I know a fainted POKéMON can\n"
	.string "still SURF, but it feels wrong.$"

Route134_Text_MarleyIntro:
	.string "Can your POKéMON dodge our\n"
	.string "lightning-fast attacks?$"

Route134_Text_MarleyDefeat:
	.string "I never knew such a technique existed!\n"
	.string "You've beaten us thoroughly.$"

Route134_Text_MarleyPostBattle:
	.string "My passion for speed hasn't faded. I'll\n"
	.string "try even harder.$"

Route134_Text_ReynaIntro:
	.string "My POKéMON aren't easy to take down!$"

Route134_Text_ReynaDefeat:
	.string "You've got to be kidding! How did I\n"
	.string "lose?!$"

Route134_Text_ReynaPostBattle:
	.string "Haha! You won, all right!\p"
	.string "I'll work my way back up by challenging\n"
	.string "TRAINERS I happen to meet!$"

Route134_Text_HudsonIntro:
	.string "Excuse me, have you seen another\n"
	.string "SAILOR around here?$"

Route134_Text_HudsonDefeat:
	.string "Now that's impressive!$"

Route134_Text_HudsonPostBattle:
	.string "Our boat drifted out to sea.\p"
	.string "My buddy is the timid type, so I'm\n"
	.string "worried sick about him.$"
