VerdanturfTown_House_MapScripts::
	.byte 0

VerdanturfTown_House_EventScript_Woman1::
	msgbox VerdanturfTown_House_Text_TrainersGatherAtPokemonLeague, MSGBOX_NPC
	end

VerdanturfTown_House_EventScript_Woman2::
	msgbox VerdanturfTown_House_Text_DefeatEliteFourInARow, MSGBOX_NPC
	end

VerdanturfTown_House_Text_TrainersGatherAtPokemonLeague:
	.string "Far away, in EVER GRANDE CITY, stands\n"
	.string "the POKéMON LEAGUE.\p"
	.string "Every TRAINER who gathers there has a\n"
	.string "terrifying power level.$"

VerdanturfTown_House_Text_DefeatEliteFourInARow:
	.string "From what I hear, you have to fight the\n"
	.string "ELITE FOUR back to back at the POKéMON\l"
	.string "LEAGUE.\p"
	.string "Lose to any one of them and you start\n"
	.string "over from the first.$"

