#!/usr/bin/env python3
"""Battle backgrounds that show the actual overworld spot.
For each outdoor/cave tileset pair, every metatile used by those maps is composited (both layers),
lightly graded for battle, and quantised into 6 shared 16-colour palettes (BG palettes 2-4, 10-12 in
battle). At battle start the game copies the 16x7 metatiles around Goku into BG3 (src/dbz_battle_bg.c)."""
import json, os, re, struct
import numpy as np
from PIL import Image
from sklearn.cluster import KMeans

PE = '/home/claude/pokeemerald'
OUT_H = f'{PE}/src/data/dbz_battle_views.h'
OUT_DIR = f'{PE}/graphics/dbz/battle_views'
os.makedirs(OUT_DIR, exist_ok=True)
NPAL, NCOL = 6, 15

PAIRS_SKIP = {'gTileset_NavelRock', 'gTileset_InsideShip', 'gTileset_Facility', 'gTileset_BikeShop', 'gTileset_MirageTower'}
TYPES = ('MAP_TYPE_ROUTE', 'MAP_TYPE_TOWN', 'MAP_TYPE_CITY', 'MAP_TYPE_OCEAN_ROUTE', 'MAP_TYPE_UNDERGROUND')

def load_pal(path):
    L = open(path).read().split('\n')[3:19]
    return np.array([[int(v) for v in l.split()] for l in L], np.float32)

def load_tiles(path):
    a = np.array(Image.open(path))
    h, w = a.shape
    return [a[ty * 8:ty * 8 + 8, tx * 8:tx * 8 + 8] & 15 for ty in range(h // 8) for tx in range(w // 8)]

hdr = open(f'{PE}/src/data/tilesets/headers.h').read()
gfx = open(f'{PE}/src/data/tilesets/graphics.h').read() + open(f'{PE}/src/graphics.c').read()
t2d = {m.group(1): m.group(2) for m in re.finditer(r'const u32 (gTilesetTiles_\w+)\[\] = INCGFX_U32\("(data/tilesets/[^"]+)/tiles\.png"', gfx)}
sym2dir = {m.group(1): f'{PE}/' + t2d[m.group(2)] for m in re.finditer(r'const struct Tileset (gTileset_\w+) =\s*\{.*?\.tiles = (gTilesetTiles_\w+)', hdr, re.S) if m.group(2) in t2d}

layouts = {L['id']: L for L in json.load(open(f'{PE}/data/layouts/layouts.json'))['layouts'] if 'id' in L}
pairs = {}
for m in sorted(os.listdir(f'{PE}/data/maps')):
    p = f'{PE}/data/maps/{m}/map.json'
    if not os.path.exists(p): continue
    M = json.load(open(p))
    if M.get('map_type') not in TYPES: continue
    L = layouts[M['layout']]
    key = (L['primary_tileset'], L['secondary_tileset'])
    if key[1] in PAIRS_SKIP: continue
    pairs.setdefault(key, []).append(L)

def used_metatiles(lays):
    s = set()
    for L in lays:
        blk = open(f'{PE}/{L["blockdata_filepath"]}', 'rb').read()
        for i in range(0, len(blk), 2):
            s.add(struct.unpack_from('<H', blk, i)[0] & 0x3FF)
        bd = open(f'{PE}/{L["border_filepath"]}', 'rb').read()
        for i in range(0, len(bd), 2):
            s.add(struct.unpack_from('<H', bd, i)[0] & 0x3FF)
    return sorted(s)

def grade_for_battle(rgb):
    # soften a touch so the Pokemon pop in front: lower contrast + slight haze
    return rgb * 0.82 + 255 * 0.08

c_out = ['// generated by tools/gen_battle_views.py', '']
table = []
total = 0
for (psym, ssym), lays in sorted(pairs.items(), key=lambda kv: kv[0][1]):
    pd, sd = sym2dir[psym], sym2dir[ssym]
    ptiles = load_tiles(f'{pd}/tiles.png'); stiles = load_tiles(f'{sd}/tiles.png')
    tiles = ptiles + [np.zeros((8, 8), np.uint8)] * (512 - len(ptiles)) + stiles
    pals = [load_pal(f'{pd}/palettes/{i:02d}.pal') for i in range(6)] + [load_pal(f'{sd}/palettes/{i:02d}.pal') for i in range(6, 13)]
    pmt = open(f'{pd}/metatiles.bin', 'rb').read(); smt = open(f'{sd}/metatiles.bin', 'rb').read()
    used = used_metatiles(lays)
    # composite each used metatile into 4 RGB 8x8 tiles
    qtiles = []      # (metatile, quadrant) -> rgb 8x8
    for mid in used:
        mt, local = (pmt, mid) if mid < 512 else (smt, mid - 512)
        if local * 16 + 16 > len(mt):
            ents = [0] * 8
        else:
            ents = struct.unpack_from('<8H', mt, local * 16)
        for q in range(4):
            out = np.zeros((8, 8, 3), np.float32)
            for layer in range(2):
                e = ents[layer * 4 + q]
                t = e & 0x3FF; p = e >> 12
                if t >= len(tiles) or p >= 13: continue
                a = tiles[t]
                if e >> 10 & 1: a = a[:, ::-1]
                if e >> 11 & 1: a = a[::-1]
                col = pals[p][a]
                if layer == 0:
                    out = col.copy()
                else:
                    m = a != 0
                    out[m] = col[m]
            qtiles.append(grade_for_battle(out))
    T = np.array(qtiles).reshape(len(qtiles), 64, 3)
    T5 = np.round(T / 255 * 31)
    # palette clustering (same approach as the title screen)
    feat = np.concatenate([T5.mean(1), T5.std(1)], 1)
    assign = KMeans(NPAL, n_init=3, random_state=2).fit_predict(feat)
    for it in range(5):
        palsq = []
        for p in range(NPAL):
            pts = T5[assign == p].reshape(-1, 3)
            if len(pts) == 0: pts = T5[0]
            u = np.unique(pts, axis=0)
            if len(u) <= NCOL:
                pal = np.zeros((NCOL, 3)); pal[:len(u)] = u; pal[len(u):] = u[0]
            else:
                pal = np.round(KMeans(NCOL, n_init=1, random_state=1).fit(pts[::max(1, len(pts) // 20000)]).cluster_centers_)
            palsq.append(np.clip(pal, 0, 31))
        palsq = np.array(palsq)
        # error per tile per palette, chunked to save memory
        errs = np.zeros((len(T5), NPAL)); idxs = np.zeros((len(T5), NPAL, 64), np.uint8)
        for s0 in range(0, len(T5), 512):
            d = ((T5[s0:s0 + 512, None, :, None, :] - palsq[None, :, None, :, :]) ** 2).sum(-1)
            errs[s0:s0 + 512] = d.min(-1).sum(-1); idxs[s0:s0 + 512] = d.argmin(-1)
        new = errs.argmin(1)
        if (new == assign).all(): break
        assign = new
    tidx = idxs[np.arange(len(T5)), assign] + 1
    # dedupe (no flips: the game copies tiles straight into VRAM)
    pool, lookup, entries = [], {}, []
    for k in range(len(T5)):
        a = tidx[k].reshape(8, 8).astype(np.uint8)
        key = (int(assign[k]), a.tobytes())
        if key not in lookup:
            lookup[key] = len(pool); pool.append(a)
        entries.append(lookup[key] | (int(assign[k]) << 12))
    # metatile -> entries (full 1024 table, unused = 0xFFFF)
    mtab = [0xFFFF] * (1024 * 4)
    for n, mid in enumerate(used):
        for q in range(4):
            mtab[mid * 4 + q] = entries[n * 4 + q]
    name = ssym.replace('gTileset_', '')
    with open(f'{OUT_DIR}/{name}.4bpp', 'wb') as f:
        for a in pool:
            for row in a:
                for x in range(0, 8, 2):
                    f.write(bytes([int(row[x]) | (int(row[x + 1]) << 4)]))
    with open(f'{OUT_DIR}/{name}.gbapal', 'wb') as f:
        for p in palsq:
            for c in [(0, 0, 0)] + [tuple(int(v) for v in c) for c in p]:
                v = c[0] | (c[1] << 5) | (c[2] << 10); f.write(struct.pack('<H', v))
    # darker / lighter colour LUTs per palette for the battle platforms
    dark, light = [], []
    for p in palsq:
        full = np.concatenate([[[0, 0, 0]], p])
        for ci in range(16):
            c = full[ci]
            dt = c * 0.62; lt = np.minimum(31, c * 1.25 + 3)
            dark.append(0 if ci == 0 else 1 + int(((p - dt) ** 2).sum(1).argmin()))
            light.append(0 if ci == 0 else 1 + int(((p - lt) ** 2).sum(1).argmin()))
    c_out.append(f'static const u32 sBV_Tiles_{name}[] = INCBIN_U32("graphics/dbz/battle_views/{name}.4bpp");')
    c_out.append(f'static const u16 sBV_Pal_{name}[] = INCBIN_U16("graphics/dbz/battle_views/{name}.gbapal");')
    c_out.append(f'static const u16 sBV_Meta_{name}[] = {{' + ','.join(str(v) for v in mtab) + '};')
    c_out.append(f'static const u8 sBV_Dark_{name}[] = {{' + ','.join(map(str, dark)) + '};')
    c_out.append(f'static const u8 sBV_Light_{name}[] = {{' + ','.join(map(str, light)) + '};')
    table.append(f'    {{&{psym}, &{ssym}, sBV_Tiles_{name}, sBV_Pal_{name}, sBV_Meta_{name}, sBV_Dark_{name}, sBV_Light_{name}}},')
    size = len(pool) * 32 + 8192 + 192 + 192
    total += size
    print(f'{name}: {len(used)} metatiles, {len(pool)} tiles, {size // 1024} KB')

c_out.append('')
c_out.append('static const struct DbzBattleView sBattleViews[] = {')
c_out += table
c_out.append('};')
open(OUT_H, 'w').write('\n'.join(c_out) + '\n')
print('total', total // 1024, 'KB')
