#!/usr/bin/env python3
"""Generate C glue for PokeBall Orange overworld graphics and patch pokeemerald sources (idempotent)."""
import re, os
PE = '/home/claude/pokeemerald'
D = f'{PE}/src/data/object_events'

def camel(n): return ''.join(p.capitalize() for p in n.split('_'))

# name -> kind
NPC16 = ['chichi', 'roshi', 'krillin', 'yamcha', 'tien', 'bulma', 'videl', 'android18', 'supreme_kai', 'piccolo',
         'mr_satan', 'great_saiyaman', 'uub', 'trunks', 'baba', 'goten', 'dende', 'announcer', 'fat_buu', 'broly',
         'yamu', 'majin_soldier', 'saiyan_soldier', 'lime', 'dr_brief', 'oolong', 'gohan_kid']
FORMS = ['goku_ssj', 'goku_ssj2', 'goku_ssj3']

# graphics id -> graphics info symbol
REPOINT = {
    'MOM': 'chichi', 'PROF_BIRCH': 'roshi', 'NORMAN': 'krillin', 'WALLY': 'uub',
    'ROXANNE': 'yamcha', 'BRAWLY': 'tien', 'WATTSON': 'bulma', 'FLANNERY': 'videl', 'WINONA': 'great_saiyaman',
    'TATE': 'goten', 'LIZA': 'trunks', 'JUAN': 'piccolo', 'PHOEBE': 'baba', 'GLACIA': 'android18', 'DRAKE': 'dende',
    'WALLACE': 'mr_satan', 'STEVEN': 'supreme_kai', 'SCOTT': 'announcer', 'MAXIE': 'fat_buu', 'ARCHIE': 'broly',
    'MAGMA_MEMBER_M': 'yamu', 'MAGMA_MEMBER_F': 'lime', 'AQUA_MEMBER_M': 'saiyan_soldier', 'AQUA_MEMBER_F': 'majin_soldier',
    'UNUSED_NATU_DOLL': 'goku_ssj', 'UNUSED_MAGNEMITE_DOLL': 'goku_ssj2', 'UNUSED_SQUIRTLE_DOLL': 'goku_ssj3',
    'RIVAL_MAY_NORMAL': 'vegeta', 'RIVAL_MAY_MACH_BIKE': 'vegeta_mach_bike', 'RIVAL_MAY_ACRO_BIKE': 'vegeta_acro_bike',
    'RIVAL_MAY_SURFING': 'vegeta_surfing', 'RIVAL_MAY_FIELD_MOVE': 'vegeta_field_move',
    'RIVAL_BRENDAN_NORMAL': 'vegeta', 'RIVAL_BRENDAN_MACH_BIKE': 'vegeta_mach_bike', 'RIVAL_BRENDAN_ACRO_BIKE': 'vegeta_acro_bike',
    'RIVAL_BRENDAN_SURFING': 'vegeta_surfing', 'RIVAL_BRENDAN_FIELD_MOVE': 'vegeta_field_move',
}

pal_names = NPC16 + FORMS + [f + '_reflection' for f in FORMS] + ['vegeta', 'dragon_ball']
tags = {n: 0x1130 + i for i, n in enumerate(pal_names)}

out_gfx, out_tags, out_info, out_paltab = [], [], [], []
out_tags.append('// generated by tools/gen_c.py')
for n in pal_names:
    out_tags.append(f'#define OBJ_EVENT_PAL_TAG_DBZ_{n.upper()} 0x{tags[n]:04X}')
    out_gfx.append(f'const u16 gObjectEventPal_DBZ_{camel(n)}[] = INCGFX_U16("graphics/object_events/palettes/dbz/{n}.pal", ".gbapal");')
    out_paltab.append(f'    {{gObjectEventPal_DBZ_{camel(n)}, OBJ_EVENT_PAL_TAG_DBZ_{n.upper()}}},')

def pic(name, w, h):
    return f'const u32 gObjectEventPic_DBZ_{camel(name)}[] = INCGFX_U32("graphics/object_events/pics/dbz/{name}.png", ".4bpp", "-mwidth {w // 8} -mheight {h // 8}");'

def info(sym, paltag, slot, size, w, h, oam, sub, anims, images, tracks='TRACKS_FOOT', refl='OBJ_EVENT_PAL_TAG_NONE'):
    return f'''const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_DBZ_{sym} = {{
    .tileTag = TAG_NONE,
    .paletteTag = {paltag},
    .reflectionPaletteTag = {refl},
    .size = {size},
    .width = {w},
    .height = {h},
    .paletteSlot = {slot},
    .shadowSize = SHADOW_SIZE_M,
    .inanimate = FALSE,
    .disableReflectionPaletteLoad = FALSE,
    .tracks = {tracks},
    .oam = &gObjectEventBaseOam_{w}x{h},
    .subspriteTables = sOamTables_{w}x{h},
    .anims = {anims},
    .images = {images},
    .affineAnims = gDummySpriteAffineAnimTable,
}};
'''

def pictable(sym, picname, n, w, h, frames=None):
    frames = frames if frames is not None else list(range(n))
    lines = [f'static const struct SpriteFrameImage sPicTable_DBZ_{sym}[] = {{']
    for f in frames:
        if isinstance(f, tuple):
            lines.append(f'    overworld_frame(gObjectEventPic_DBZ_{camel(f[0])}, {w // 8}, {h // 8}, {f[1]}),')
        else:
            lines.append(f'    overworld_frame(gObjectEventPic_DBZ_{camel(picname)}, {w // 8}, {h // 8}, {f}),')
    lines.append('};\n')
    return '\n'.join(lines)

for n in NPC16:
    out_gfx.append(pic(n, 16, 32))
    out_info.append(pictable(camel(n), n, 9, 16, 32))
    out_info.append(info(camel(n), f'OBJ_EVENT_PAL_TAG_DBZ_{n.upper()}', 'PALSLOT_NPC_1', 256, 16, 32, None, None,
                         'sAnimTable_Standard', f'sPicTable_DBZ_{camel(n)}'))
for f in FORMS:
    out_gfx.append(pic(f, 16, 32)); out_gfx.append(pic(f + '_running', 16, 32))
    frames = [(f, i) for i in range(9)] + [(f + '_running', i) for i in range(9)]
    out_info.append(pictable(camel(f), f, 18, 16, 32, frames))
    out_info.append(info(camel(f), f'OBJ_EVENT_PAL_TAG_DBZ_{f.upper()}', 'PALSLOT_PLAYER', 256, 16, 32, None, None,
                         'sAnimTable_BrendanMayNormal', f'sPicTable_DBZ_{camel(f)}', refl='OBJ_EVENT_PAL_TAG_BRIDGE_REFLECTION'))
# Vegeta
out_gfx.append(pic('vegeta', 16, 32)); out_gfx.append(pic('vegeta_running', 16, 32))
for nm, n in [('vegeta_mach_bike', 9), ('vegeta_acro_bike', 27), ('vegeta_surfing', 6), ('vegeta_field_move', 5)]:
    out_gfx.append(pic(nm, 32, 32))
vt = 'OBJ_EVENT_PAL_TAG_DBZ_VEGETA'
out_info.append(pictable('Vegeta', 'vegeta', 18, 16, 32, [('vegeta', i) for i in range(9)] + [('vegeta_running', i) for i in range(9)]))
out_info.append(info('Vegeta', vt, 'PALSLOT_NPC_1', 256, 16, 32, None, None, 'sAnimTable_BrendanMayNormal', 'sPicTable_DBZ_Vegeta'))
out_info.append(pictable('VegetaMachBike', 'vegeta_mach_bike', 9, 32, 32))
out_info.append(info('VegetaMachBike', vt, 'PALSLOT_NPC_1', 512, 32, 32, None, None, 'sAnimTable_Standard', 'sPicTable_DBZ_VegetaMachBike', 'TRACKS_NONE'))
out_info.append(pictable('VegetaAcroBike', 'vegeta_acro_bike', 27, 32, 32))
out_info.append(info('VegetaAcroBike', vt, 'PALSLOT_NPC_1', 512, 32, 32, None, None, 'sAnimTable_AcroBike', 'sPicTable_DBZ_VegetaAcroBike', 'TRACKS_NONE'))
out_info.append(pictable('VegetaSurfing', 'vegeta_surfing', 12, 32, 32, [0, 2, 4, 0, 0, 2, 2, 4, 4, 1, 3, 5]))
out_info.append(info('VegetaSurfing', vt, 'PALSLOT_NPC_1', 512, 32, 32, None, None, 'sAnimTable_Surfing', 'sPicTable_DBZ_VegetaSurfing'))
out_info.append(pictable('VegetaFieldMove', 'vegeta_field_move', 5, 32, 32))
out_info.append(info('VegetaFieldMove', vt, 'PALSLOT_NPC_1', 512, 32, 32, None, None, 'sAnimTable_FieldMove', 'sPicTable_DBZ_VegetaFieldMove'))

# Dragon Ball (inanimate 16x16 pickup)
out_gfx.append(pic('dragon_ball', 16, 16))
out_info.append(pictable('DragonBall', 'dragon_ball', 1, 16, 16))
out_info.append(info('DragonBall', 'OBJ_EVENT_PAL_TAG_DBZ_DRAGON_BALL', 'PALSLOT_NPC_1', 128, 16, 16, None, None,
                     'sAnimTable_Inanimate', 'sPicTable_DBZ_DragonBall', 'TRACKS_NONE')
                .replace('.inanimate = FALSE', '.inanimate = TRUE').replace('SHADOW_SIZE_M', 'SHADOW_SIZE_S'))
REPOINT['UNUSED_WOOPER_DOLL'] = 'dragon_ball'

sym_of = {n: camel(n) for n in NPC16 + FORMS}
sym_of['dragon_ball'] = 'DragonBall'
sym_of.update({'vegeta': 'Vegeta', 'vegeta_mach_bike': 'VegetaMachBike', 'vegeta_acro_bike': 'VegetaAcroBike',
               'vegeta_surfing': 'VegetaSurfing', 'vegeta_field_move': 'VegetaFieldMove'})
externs = [f'extern const struct ObjectEventGraphicsInfo gObjectEventGraphicsInfo_DBZ_{s};' for s in sorted(set(sym_of.values()))]

open(f'{D}/dbz_graphics.h', 'w').write('// generated by tools/gen_c.py\n' + '\n'.join(out_gfx) + '\n')
open(f'{D}/dbz_pal_tags.h', 'w').write('\n'.join(out_tags) + '\n' + '\n'.join(externs) + '\n')
open(f'{D}/dbz_graphics_info.h', 'w').write('// generated by tools/gen_c.py\n' + '\n'.join(out_info))
open(f'{D}/dbz_palettes_table.h', 'w').write('// generated by tools/gen_c.py\n' + '\n'.join(out_paltab) + '\n')

# player reflection pairs for the SSJ forms
refl = []
for f in FORMS:
    U = f.upper()
    refl.append(f'static const u16 sReflectionPaletteTags_DBZ_{camel(f)}[] = {{ OBJ_EVENT_PAL_TAG_DBZ_{U}_REFLECTION, OBJ_EVENT_PAL_TAG_DBZ_{U}_REFLECTION, OBJ_EVENT_PAL_TAG_DBZ_{U}_REFLECTION, OBJ_EVENT_PAL_TAG_DBZ_{U}_REFLECTION }};')
open(f'{D}/dbz_reflection_tags.h', 'w').write('\n'.join(refl) + '\n')
open(f'{D}/dbz_reflection_sets.h', 'w').write('\n'.join(
    f'    {{OBJ_EVENT_PAL_TAG_DBZ_{f.upper()}, sReflectionPaletteTags_DBZ_{camel(f)}}},' for f in FORMS) + '\n')

# ---- patch event_object_movement.c
p = f'{PE}/src/event_object_movement.c'; s = open(p).read()
if 'dbz_graphics.h' not in s:
    s = s.replace('#include "data/object_events/object_event_graphics.h"\n',
                  '#include "data/object_events/object_event_graphics.h"\n#include "data/object_events/dbz_graphics.h"\n')
    s = s.replace('#define OBJ_EVENT_PAL_TAG_NONE                    0x11FF\n',
                  '#define OBJ_EVENT_PAL_TAG_NONE                    0x11FF\n#include "data/object_events/dbz_pal_tags.h"\n')
    s = s.replace('#include "data/object_events/object_event_graphics_info.h"\n',
                  '#include "data/object_events/object_event_graphics_info.h"\n#include "data/object_events/dbz_graphics_info.h"\n')
    s = s.replace('''    {gObjectEventPal_RubySapphireMay,       OBJ_EVENT_PAL_TAG_RS_MAY},
#ifdef BUGFIX
    {NULL,                                  OBJ_EVENT_PAL_TAG_NONE},
#else
    {}, // BUG: FindObjectEventPaletteIndexByTag looks for OBJ_EVENT_PAL_TAG_NONE and not 0x0.
        // If it's looking for a tag that isn't in this table, the game locks in an infinite loop.
#endif''', '''    {gObjectEventPal_RubySapphireMay,       OBJ_EVENT_PAL_TAG_RS_MAY},
#include "data/object_events/dbz_palettes_table.h"
    {NULL,                                  OBJ_EVENT_PAL_TAG_NONE},''')
    s = s.replace('static const struct PairedPalettes sPlayerReflectionPaletteSets[] = {\n',
                  '#include "data/object_events/dbz_reflection_tags.h"\nstatic const struct PairedPalettes sPlayerReflectionPaletteSets[] = {\n#include "data/object_events/dbz_reflection_sets.h"\n')
    open(p, 'w').write(s)

# ---- repoint graphics ids
p = f'{D}/object_event_graphics_info_pointers.h'; s = open(p).read()
for gid, n in REPOINT.items():
    s = re.sub(r'(\[OBJ_EVENT_GFX_' + gid + r'\]\s*=\s*)&gObjectEventGraphicsInfo_\w+', r'\1&gObjectEventGraphicsInfo_DBZ_' + sym_of[n], s)
open(p, 'w').write(s)
print('generated', len(NPC16), 'npcs')
