#!/usr/bin/env python3
"""Overworld HUD assets: 64x32 panel, 16x16 Goku head icons per form, a 3x5 pixel font, shared palette.
Writes src/data/dbz_hud.h (the HUD is composed at runtime in src/dbz_hud.c)."""
import numpy as np
from PIL import Image

PE = '/home/claude/pokeemerald'
PAL = [
    (255, 0, 255),   # 0 transparent
    (16, 16, 24),    # 1 panel / drop shadows (shared with the shadow sprites)
    (248, 144, 0),   # 2 orange border
    (248, 248, 248), # 3 text
    (48, 48, 80),    # 4 text shadow / outline
    (56, 56, 72),    # 5 empty bar
    (64, 224, 72),   # 6 HP green
    (248, 208, 32),  # 7 HP yellow
    (248, 56, 32),   # 8 HP red
    (96, 208, 248),  # 9 charge
    (248, 248, 160), # 10 charge full
    (8, 8, 8),       # 11 hair black
    (248, 240, 88),  # 12 gold light
    (232, 176, 40),  # 13 gold mid
    (168, 104, 16),  # 14 gold dark
    (240, 192, 128), # 15 skin
]

FONT = {
    'A': ['.#.', '#.#', '###', '#.#', '#.#'], 'B': ['##.', '#.#', '##.', '#.#', '##.'],
    'C': ['.##', '#..', '#..', '#..', '.##'], 'D': ['##.', '#.#', '#.#', '#.#', '##.'],
    'E': ['###', '#..', '##.', '#..', '###'], 'F': ['###', '#..', '##.', '#..', '#..'],
    'G': ['.##', '#..', '#.#', '#.#', '.##'], 'H': ['#.#', '#.#', '###', '#.#', '#.#'],
    'I': ['###', '.#.', '.#.', '.#.', '###'], 'J': ['..#', '..#', '..#', '#.#', '.#.'],
    'K': ['#.#', '#.#', '##.', '#.#', '#.#'], 'L': ['#..', '#..', '#..', '#..', '###'],
    'M': ['#.#', '###', '###', '#.#', '#.#'], 'N': ['##.', '#.#', '#.#', '#.#', '#.#'],
    'O': ['.#.', '#.#', '#.#', '#.#', '.#.'], 'P': ['##.', '#.#', '##.', '#..', '#..'],
    'Q': ['.#.', '#.#', '#.#', '##.', '.##'], 'R': ['##.', '#.#', '##.', '#.#', '#.#'],
    'S': ['.##', '#..', '.#.', '..#', '##.'], 'T': ['###', '.#.', '.#.', '.#.', '.#.'],
    'U': ['#.#', '#.#', '#.#', '#.#', '###'], 'V': ['#.#', '#.#', '#.#', '#.#', '.#.'],
    'W': ['#.#', '#.#', '###', '###', '#.#'], 'X': ['#.#', '#.#', '.#.', '#.#', '#.#'],
    'Y': ['#.#', '#.#', '.#.', '.#.', '.#.'], 'Z': ['###', '..#', '.#.', '#..', '###'],
    '0': ['###', '#.#', '#.#', '#.#', '###'], '1': ['.#.', '##.', '.#.', '.#.', '###'],
    '2': ['##.', '..#', '.#.', '#..', '###'], '3': ['##.', '..#', '.#.', '..#', '##.'],
    '4': ['#.#', '#.#', '###', '..#', '..#'], '5': ['###', '#..', '##.', '..#', '##.'],
    '6': ['.##', '#..', '###', '#.#', '###'], '7': ['###', '..#', '.#.', '.#.', '.#.'],
    '8': ['###', '#.#', '###', '#.#', '###'], '9': ['###', '#.#', '###', '..#', '##.'],
    '/': ['..#', '..#', '.#.', '#..', '#..'], ' ': ['...'] * 5,
}
ORDER = ' ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789/'

def nearest(rgb):
    best, bi = 1e9, 1
    for i, c in enumerate(PAL[1:], 1):
        d = sum((a - b) ** 2 for a, b in zip(rgb, c))
        if d < best:
            best, bi = d, i
    return bi

def icon(path):
    im = Image.open(path).convert('RGBA')
    full = np.array(im)[:, :16]
    opaque = (full[..., 3] > 0) & ~((full[..., 0] == 115) & (full[..., 1] == 197) & (full[..., 2] == 164))
    top = int(np.argmax(opaque.any(1)))
    a = full[top + 2:top + 18]
    out = np.zeros((16, 16), np.uint8)
    for y in range(16):
        for x in range(16):
            r, g, b, al = a[y, x]
            if al == 0 or (r, g, b) == (115, 197, 164):
                continue
            if int(r) + int(g) + int(b) < 150:
                out[y, x] = 11   # hair black / outline
            else:
                out[y, x] = nearest((int(r), int(g), int(b)))
    return out

icons = [icon(f'{PE}/graphics/object_events/pics/people/brendan/walking.png'),
         icon(f'{PE}/graphics/object_events/pics/dbz/goku_ssj.png'),
         icon(f'{PE}/graphics/object_events/pics/dbz/goku_ssj2.png'),
         icon(f'{PE}/graphics/object_events/pics/dbz/goku_ssj3.png'),
         icon(f'{PE}/graphics/object_events/pics/dbz/goku_vegito.png')]

# panel: rounded box, orange rim
W, H = 64, 32
panel = np.zeros((H, W), np.uint8)
panel[:, :] = 1
panel[0, :] = 2; panel[H - 1, :] = 2; panel[:, 0] = 2; panel[:, W - 1] = 2
for (y, x) in [(0, 0), (0, W - 1), (H - 1, 0), (H - 1, W - 1)]:
    panel[y, x] = 0

out = ['// generated by tools/gen_hud.py', '']
out.append('const u16 gDBZHudPalette[16] = {' + ','.join(
    str((r >> 3) | ((g >> 3) << 5) | ((b >> 3) << 10)) for r, g, b in PAL) + '};')
out.append('static const u8 sHudPanel[32][64] = {' + ','.join(
    '{' + ','.join(map(str, row)) + '}' for row in panel) + '};')
out.append('static const u8 sHudIcons[5][16][16] = {' + ','.join(
    '{' + ','.join('{' + ','.join(map(str, row)) + '}' for row in ic) + '}' for ic in icons) + '};')
glyphs = []
for ch in ORDER:
    rows = FONT[ch]
    glyphs.append('{' + ','.join(str(sum(1 << (2 - i) for i, c in enumerate(r) if c == '#')) for r in rows) + '}')
out.append(f'static const u8 sHudFont[{len(ORDER)}][5] = {{' + ','.join(glyphs) + '};')
out.append(f'static const u8 sHudFontOrder[] = "{ORDER}";')
open(f'{PE}/src/data/dbz_hud.h', 'w').write('\n'.join(out) + '\n')
# preview
prev = np.zeros((32, 64 + 5 * 18, 3), np.uint8)
P = np.array(PAL, np.uint8)
prev[:, :64] = P[panel]
for i, ic in enumerate(icons):
    prev[:16, 66 + i * 18:82 + i * 18] = P[ic]
Image.fromarray(prev).resize(((64 + 90) * 4, 128), 0).save('/tmp/claude-0/hud_assets.png')
print('ok')
