#!/usr/bin/env python3
"""Dialogue portraits for PokeBall Orange: Buu's Fury 64x64 portraits (with their gold frames), 16 colors each."""
import sys
sys.path.insert(0, '/home/claude/tools')
import numpy as np
from PIL import Image
import gen_trainers as g

PE = '/home/claude/pokeemerald'
# name -> Buu's Fury portrait index
PORTRAITS = [
    ('goku', 47), ('vegeta', 136), ('vegito', 142), ('chichi', 12), ('bulma', 9), ('roshi', 89),
    ('krillin', 82), ('kid_buu', 119), ('gero', 112), ('ox_king', 102), ('brief', 18), ('announcer', 2),
    ('super_buu', 122), ('uub', 134), ('kai', 76), ('satan', 68), ('yamcha', 151), ('tien', 127),
    ('videl', 144), ('saiyaman', 39), ('goten', 54), ('trunks', 128), ('piccolo', 104), ('baba', 3),
    ('android18', 1), ('dende', 17),
]

def build(name, idx):
    a = g.portrait(idx)
    rgb = g.PRGB[a].astype(np.uint8)
    im = Image.fromarray(rgb).quantize(colors=15, method=Image.MEDIANCUT, dither=Image.NONE)
    pal = im.getpalette()[:45]
    px = np.array(im) + 1                      # index 0 stays transparent (unused)
    out = Image.fromarray(px.astype(np.uint8), 'P')
    out.putpalette([255, 0, 255] + pal + [0] * (768 - 48))
    out.save(f'{PE}/graphics/dbz/portraits/{name}.png', bits=4)

lines = ['// generated by tools/gen_portraits.py: Buu\'s Fury dialogue portraits', '']
for name, idx in PORTRAITS:
    build(name, idx)
    cname = ''.join(p.capitalize() for p in name.split('_'))
    lines.append(f'static const u32 sPortraitGfx_{cname}[] = INCGFX_U32("graphics/dbz/portraits/{name}.png", ".4bpp");')
    lines.append(f'static const u16 sPortraitPal_{cname}[] = INCGFX_U16("graphics/dbz/portraits/{name}.png", ".gbapal");')
lines.append('')
lines.append('enum {')
for name, _ in PORTRAITS:
    lines.append(f'    PORTRAIT_{name.upper()},')
lines.append('    PORTRAIT_COUNT,')
lines.append('    PORTRAIT_NONE = 0xFF,')
lines.append('};')
lines.append('')
lines.append('static const struct { const u32 *gfx; const u16 *pal; } sPortraits[PORTRAIT_COUNT] = {')
for name, _ in PORTRAITS:
    cname = ''.join(p.capitalize() for p in name.split('_'))
    lines.append(f'    [PORTRAIT_{name.upper()}] = {{ sPortraitGfx_{cname}, sPortraitPal_{cname} }},')
lines.append('};')
open(f'{PE}/src/data/dbz_portraits.h', 'w').write('\n'.join(lines) + '\n')
print('ok', len(PORTRAITS))
