// generated by tools/pbo/build_cove.py: tile slots animated in gTileset_PboCove
#define PBO_COVE_NUM_TILES 391
#define PBO_COVE_FIRE_TILE 324
#define PBO_COVE_WATER_TILE_0 171
#define PBO_COVE_WATER_TILE_1 168
#define PBO_COVE_WATER_TILE_2 172
#define PBO_COVE_WATER_TILE_3 170
