PetalburgCity_House2_MapScripts::
	.byte 0

PetalburgCity_House2_EventScript_Woman::
	msgbox PetalburgCity_House2_Text_NormanBecameGymLeader, MSGBOX_NPC
	end

PetalburgCity_House2_EventScript_SchoolKid::
	msgbox PetalburgCity_House2_Text_BattledNormanOnce, MSGBOX_NPC
	end

PetalburgCity_House2_Text_NormanBecameGymLeader:
	.string "KRILLIN is our town's new GYM LEADER.\p"
	.string "I hear he brought his family over from\n"
	.string "somewhere far away.$"

PetalburgCity_House2_Text_BattledNormanOnce:
	.string "I challenged KRILLIN once, and whew,\n"
	.string "he was way too strong for me.\p"
	.string "How can I put it?\p"
	.string "He just seems like a man who lives\n"
	.string "and breathes POKéMON.$"

