OldaleTown_House1_MapScripts::
	.byte 0

OldaleTown_House1_EventScript_Woman::
	msgbox OldaleTown_House1_Text_LeftPokemonGoesOutFirst, MSGBOX_NPC
	end

OldaleTown_House1_Text_LeftPokemonGoesOutFirst:
	.string "When a POKéMON battle starts, the one\n"
	.string "at the top of your party list goes out\l"
	.string "first.\p"
	.string "So once you have more POKéMON, try\n"
	.string "shuffling their order around.\p"
	.string "Picking who fights first can give you\n"
	.string "an edge.$"

