PetalburgCity_House1_MapScripts::
	.byte 0

PetalburgCity_House1_EventScript_Man::
	msgbox PetalburgCity_House1_Text_TravelingIsWonderful, MSGBOX_NPC
	end

PetalburgCity_House1_EventScript_Woman::
	msgbox PetalburgCity_House1_Text_GoOnAdventure, MSGBOX_NPC
	end

PetalburgCity_House1_Text_TravelingIsWonderful:
	.string "Traveling is wonderful!\p"
	.string "When I was young, I trained my way\n"
	.string "across the seas and mountains!$"

PetalburgCity_House1_Text_GoOnAdventure:
	.string "Sigh…\p"
	.string "I wish I could set off on an adventure\n"
	.string "with a few POKéMON…\p"
	.string "Push through wet grass…\n"
	.string "Climb steep, rocky mountains…\p"
	.string "Cross the raging seas…\n"
	.string "Explore dark caves…\p"
	.string "And now and then, feel a little\n"
	.string "homesick…\p"
	.string "Traveling must be wonderful!$"

