FortreeCity_House3_MapScripts::
	.byte 0

FortreeCity_House3_EventScript_Maniac::
	msgbox FortreeCity_House3_Text_MetStevenHadAmazingPokemon, MSGBOX_NPC
	end

FortreeCity_House3_EventScript_SchoolKidM::
	msgbox FortreeCity_House3_Text_OhYouHavePokedex, MSGBOX_NPC
	end

FortreeCity_House3_Text_MetStevenHadAmazingPokemon:
	.string "Speaking of POKéDEXES, that reminds me\n"
	.string "of something.\p"
	.string "I once met a TRAINER named SUPREME KAI\n"
	.string "while I was hunting for rare stones.\p"
	.string "Hoo, boy! His POKéMON were incredible.\n"
	.string "They weren't just rare, they were\l"
	.string "trained to terrifying heights!\p"
	.string "He may even be stronger than the GYM\n"
	.string "LEADER of this town…$"

FortreeCity_House3_Text_OhYouHavePokedex:
	.string "What's that gadget you have there?\p"
	.string "… … … … … …\p"
	.string "A POKéDEX, you say? Amazing! It's like a\n"
	.string "SCOUTER for POKéMON!$"

