// generated by tools/gen_portraits.py: Buu's Fury dialogue portraits

static const u32 sPortraitGfx_Goku[] = INCGFX_U32("graphics/dbz/portraits/goku.png", ".4bpp");
static const u16 sPortraitPal_Goku[] = INCGFX_U16("graphics/dbz/portraits/goku.png", ".gbapal");
static const u32 sPortraitGfx_Vegeta[] = INCGFX_U32("graphics/dbz/portraits/vegeta.png", ".4bpp");
static const u16 sPortraitPal_Vegeta[] = INCGFX_U16("graphics/dbz/portraits/vegeta.png", ".gbapal");
static const u32 sPortraitGfx_Vegito[] = INCGFX_U32("graphics/dbz/portraits/vegito.png", ".4bpp");
static const u16 sPortraitPal_Vegito[] = INCGFX_U16("graphics/dbz/portraits/vegito.png", ".gbapal");
static const u32 sPortraitGfx_Chichi[] = INCGFX_U32("graphics/dbz/portraits/chichi.png", ".4bpp");
static const u16 sPortraitPal_Chichi[] = INCGFX_U16("graphics/dbz/portraits/chichi.png", ".gbapal");
static const u32 sPortraitGfx_Bulma[] = INCGFX_U32("graphics/dbz/portraits/bulma.png", ".4bpp");
static const u16 sPortraitPal_Bulma[] = INCGFX_U16("graphics/dbz/portraits/bulma.png", ".gbapal");
static const u32 sPortraitGfx_Roshi[] = INCGFX_U32("graphics/dbz/portraits/roshi.png", ".4bpp");
static const u16 sPortraitPal_Roshi[] = INCGFX_U16("graphics/dbz/portraits/roshi.png", ".gbapal");
static const u32 sPortraitGfx_Krillin[] = INCGFX_U32("graphics/dbz/portraits/krillin.png", ".4bpp");
static const u16 sPortraitPal_Krillin[] = INCGFX_U16("graphics/dbz/portraits/krillin.png", ".gbapal");
static const u32 sPortraitGfx_KidBuu[] = INCGFX_U32("graphics/dbz/portraits/kid_buu.png", ".4bpp");
static const u16 sPortraitPal_KidBuu[] = INCGFX_U16("graphics/dbz/portraits/kid_buu.png", ".gbapal");
static const u32 sPortraitGfx_Gero[] = INCGFX_U32("graphics/dbz/portraits/gero.png", ".4bpp");
static const u16 sPortraitPal_Gero[] = INCGFX_U16("graphics/dbz/portraits/gero.png", ".gbapal");
static const u32 sPortraitGfx_OxKing[] = INCGFX_U32("graphics/dbz/portraits/ox_king.png", ".4bpp");
static const u16 sPortraitPal_OxKing[] = INCGFX_U16("graphics/dbz/portraits/ox_king.png", ".gbapal");
static const u32 sPortraitGfx_Brief[] = INCGFX_U32("graphics/dbz/portraits/brief.png", ".4bpp");
static const u16 sPortraitPal_Brief[] = INCGFX_U16("graphics/dbz/portraits/brief.png", ".gbapal");
static const u32 sPortraitGfx_Announcer[] = INCGFX_U32("graphics/dbz/portraits/announcer.png", ".4bpp");
static const u16 sPortraitPal_Announcer[] = INCGFX_U16("graphics/dbz/portraits/announcer.png", ".gbapal");
static const u32 sPortraitGfx_SuperBuu[] = INCGFX_U32("graphics/dbz/portraits/super_buu.png", ".4bpp");
static const u16 sPortraitPal_SuperBuu[] = INCGFX_U16("graphics/dbz/portraits/super_buu.png", ".gbapal");
static const u32 sPortraitGfx_Uub[] = INCGFX_U32("graphics/dbz/portraits/uub.png", ".4bpp");
static const u16 sPortraitPal_Uub[] = INCGFX_U16("graphics/dbz/portraits/uub.png", ".gbapal");
static const u32 sPortraitGfx_Kai[] = INCGFX_U32("graphics/dbz/portraits/kai.png", ".4bpp");
static const u16 sPortraitPal_Kai[] = INCGFX_U16("graphics/dbz/portraits/kai.png", ".gbapal");
static const u32 sPortraitGfx_Satan[] = INCGFX_U32("graphics/dbz/portraits/satan.png", ".4bpp");
static const u16 sPortraitPal_Satan[] = INCGFX_U16("graphics/dbz/portraits/satan.png", ".gbapal");
static const u32 sPortraitGfx_Yamcha[] = INCGFX_U32("graphics/dbz/portraits/yamcha.png", ".4bpp");
static const u16 sPortraitPal_Yamcha[] = INCGFX_U16("graphics/dbz/portraits/yamcha.png", ".gbapal");
static const u32 sPortraitGfx_Tien[] = INCGFX_U32("graphics/dbz/portraits/tien.png", ".4bpp");
static const u16 sPortraitPal_Tien[] = INCGFX_U16("graphics/dbz/portraits/tien.png", ".gbapal");
static const u32 sPortraitGfx_Videl[] = INCGFX_U32("graphics/dbz/portraits/videl.png", ".4bpp");
static const u16 sPortraitPal_Videl[] = INCGFX_U16("graphics/dbz/portraits/videl.png", ".gbapal");
static const u32 sPortraitGfx_Saiyaman[] = INCGFX_U32("graphics/dbz/portraits/saiyaman.png", ".4bpp");
static const u16 sPortraitPal_Saiyaman[] = INCGFX_U16("graphics/dbz/portraits/saiyaman.png", ".gbapal");
static const u32 sPortraitGfx_Goten[] = INCGFX_U32("graphics/dbz/portraits/goten.png", ".4bpp");
static const u16 sPortraitPal_Goten[] = INCGFX_U16("graphics/dbz/portraits/goten.png", ".gbapal");
static const u32 sPortraitGfx_Trunks[] = INCGFX_U32("graphics/dbz/portraits/trunks.png", ".4bpp");
static const u16 sPortraitPal_Trunks[] = INCGFX_U16("graphics/dbz/portraits/trunks.png", ".gbapal");
static const u32 sPortraitGfx_Piccolo[] = INCGFX_U32("graphics/dbz/portraits/piccolo.png", ".4bpp");
static const u16 sPortraitPal_Piccolo[] = INCGFX_U16("graphics/dbz/portraits/piccolo.png", ".gbapal");
static const u32 sPortraitGfx_Baba[] = INCGFX_U32("graphics/dbz/portraits/baba.png", ".4bpp");
static const u16 sPortraitPal_Baba[] = INCGFX_U16("graphics/dbz/portraits/baba.png", ".gbapal");
static const u32 sPortraitGfx_Android18[] = INCGFX_U32("graphics/dbz/portraits/android18.png", ".4bpp");
static const u16 sPortraitPal_Android18[] = INCGFX_U16("graphics/dbz/portraits/android18.png", ".gbapal");
static const u32 sPortraitGfx_Dende[] = INCGFX_U32("graphics/dbz/portraits/dende.png", ".4bpp");
static const u16 sPortraitPal_Dende[] = INCGFX_U16("graphics/dbz/portraits/dende.png", ".gbapal");

enum {
    PORTRAIT_GOKU,
    PORTRAIT_VEGETA,
    PORTRAIT_VEGITO,
    PORTRAIT_CHICHI,
    PORTRAIT_BULMA,
    PORTRAIT_ROSHI,
    PORTRAIT_KRILLIN,
    PORTRAIT_KID_BUU,
    PORTRAIT_GERO,
    PORTRAIT_OX_KING,
    PORTRAIT_BRIEF,
    PORTRAIT_ANNOUNCER,
    PORTRAIT_SUPER_BUU,
    PORTRAIT_UUB,
    PORTRAIT_KAI,
    PORTRAIT_SATAN,
    PORTRAIT_YAMCHA,
    PORTRAIT_TIEN,
    PORTRAIT_VIDEL,
    PORTRAIT_SAIYAMAN,
    PORTRAIT_GOTEN,
    PORTRAIT_TRUNKS,
    PORTRAIT_PICCOLO,
    PORTRAIT_BABA,
    PORTRAIT_ANDROID18,
    PORTRAIT_DENDE,
    PORTRAIT_COUNT,
    PORTRAIT_NONE = 0xFF,
};

static const struct { const u32 *gfx; const u16 *pal; } sPortraits[PORTRAIT_COUNT] = {
    [PORTRAIT_GOKU] = { sPortraitGfx_Goku, sPortraitPal_Goku },
    [PORTRAIT_VEGETA] = { sPortraitGfx_Vegeta, sPortraitPal_Vegeta },
    [PORTRAIT_VEGITO] = { sPortraitGfx_Vegito, sPortraitPal_Vegito },
    [PORTRAIT_CHICHI] = { sPortraitGfx_Chichi, sPortraitPal_Chichi },
    [PORTRAIT_BULMA] = { sPortraitGfx_Bulma, sPortraitPal_Bulma },
    [PORTRAIT_ROSHI] = { sPortraitGfx_Roshi, sPortraitPal_Roshi },
    [PORTRAIT_KRILLIN] = { sPortraitGfx_Krillin, sPortraitPal_Krillin },
    [PORTRAIT_KID_BUU] = { sPortraitGfx_KidBuu, sPortraitPal_KidBuu },
    [PORTRAIT_GERO] = { sPortraitGfx_Gero, sPortraitPal_Gero },
    [PORTRAIT_OX_KING] = { sPortraitGfx_OxKing, sPortraitPal_OxKing },
    [PORTRAIT_BRIEF] = { sPortraitGfx_Brief, sPortraitPal_Brief },
    [PORTRAIT_ANNOUNCER] = { sPortraitGfx_Announcer, sPortraitPal_Announcer },
    [PORTRAIT_SUPER_BUU] = { sPortraitGfx_SuperBuu, sPortraitPal_SuperBuu },
    [PORTRAIT_UUB] = { sPortraitGfx_Uub, sPortraitPal_Uub },
    [PORTRAIT_KAI] = { sPortraitGfx_Kai, sPortraitPal_Kai },
    [PORTRAIT_SATAN] = { sPortraitGfx_Satan, sPortraitPal_Satan },
    [PORTRAIT_YAMCHA] = { sPortraitGfx_Yamcha, sPortraitPal_Yamcha },
    [PORTRAIT_TIEN] = { sPortraitGfx_Tien, sPortraitPal_Tien },
    [PORTRAIT_VIDEL] = { sPortraitGfx_Videl, sPortraitPal_Videl },
    [PORTRAIT_SAIYAMAN] = { sPortraitGfx_Saiyaman, sPortraitPal_Saiyaman },
    [PORTRAIT_GOTEN] = { sPortraitGfx_Goten, sPortraitPal_Goten },
    [PORTRAIT_TRUNKS] = { sPortraitGfx_Trunks, sPortraitPal_Trunks },
    [PORTRAIT_PICCOLO] = { sPortraitGfx_Piccolo, sPortraitPal_Piccolo },
    [PORTRAIT_BABA] = { sPortraitGfx_Baba, sPortraitPal_Baba },
    [PORTRAIT_ANDROID18] = { sPortraitGfx_Android18, sPortraitPal_Android18 },
    [PORTRAIT_DENDE] = { sPortraitGfx_Dende, sPortraitPal_Dende },
};
